stage1_fly/run/main.go

We were assuming that there's always an app in the Image Manifest when
evaluating the mounts, but the spec doesn't require an app to be
present.
Check for nil when merging Mounts/Volumes with MountPoints.
Fixes #2254

stage1_fly: check for nil in imApp

---

store/tree.go

If the "image" file is not present in the tree store directory, that
tree store can't be removed. Don't error out if that happens, just print
a warning so it is removed.
This means that the image size will be overestimated because we can't
know which image the tree store refers to, but at least we can remove
the tree store.
Fixes #2180 (for real)
```
$ sudo rkt run docker://busybox --insecure-options=image
image: using image from local store for image name coreos.com/rkt/stage1-coreos:1.1.0+git4f50d4e
image: using image from local store for url docker://busybox
networking: loading networks from /etc/rkt/net.d
networking: loading network default with type ptp 
$ sudo rm /var/lib/rkt/cas/tree/deps-sha512-630c391429eff28aa9a18da5445848a9ad055d15b2979127f168abd7a52cd24b/{image,rendered} …
```

store: force removal of the tree store even if it's in a bad state

---

rkt/image/io.go
rkt/image/resumablesession.go

Whenever we create a Store temporary file, we lock it so concurrent
downloads don't corrupt it.
Fixes #2165

rkt/image: lock temp files to avoid problems with concurrent fetches

---

Documentation/devel/release.md

The ACI discovery mechanism can download individual files but not locate
a file inside a tarball.
This will help for https://github.com/coreos/rkt/issues/2241
-----
/cc @n0rad

release guide: attach stage1 ACIs individually

---

rkt/pods.go
rkt/run.go

We need to setup the containers runtime environment to match the label
of the container image.  The goal is to get any files that need to be
written by the container process to be the container label.
Not sure if the Relabel is the best way to handle this.  But it works
pretty well.  BTW The label/selinux code in opencontainers has been
updated with newer API then you have in RKT.  It should be updated.
Signed-off-by: Dan Walsh <dwalsh@redhat.com>

selinux: relabel content under pods/run to match container image

---

tests/inspect/inspect.go

One test in TestVolumes attempts to write on a read-only volume and
checks that the error message passed by the "inspect" app is as follows:
> Cannot write to file "/dir1/file": open /dir1/file: read-only file
> system
The "inspect" app returned the return code 1 in that case.
With new versions of systemd, the app return code is propagated to
systemd-nspawn and the rkt command returns that return code. See
https://github.com/coreos/rkt/issues/1460
But TestVolumes was expecting the return code 0. In order to make the
test work both on old systemd versions and newer systemd versions, this
patch changes the "inspect" app return code to 0. TestVolumes checks the
error message anyway.
Fixes https://github.com/coreos/rkt/issues/2219

tests: fix TestVolumes on systemd-git-master

---

Documentation/dependencies.md
README.md

Linux 3.18 introduced the fix for unlinking files and directories that
are mount points in another mount namespace. Before Linux 3.18,
unlinking could return EBUSY:
https://github.com/torvalds/linux/commit/8ed936b
With the introduction of rkt-fly, this becomes a visible issue with rkt
gc, see discussion on:
https://github.com/coreos/rkt/issues/1922#issuecomment-196914006
This patch bumps the run-time dependency to Linux 3.18
-----
/cc @jellonek @BrianHicks @jcollie

doc: dependencies: linux 3.18

---

README.md

* Correct missing period with a minor rephrase
* Remove misplaced title case
* Correct italics markdown to preferred symbol
supersedes #2291 (little git loop oops)

README: Add missed punctuation in sec disclosure

---

Documentation/subcommands/prepare.md
rkt/prepare.go

It is rather expected to be able to pass a custom signature to prepare
command too, as it may fetch the image from the network.

docs, rkt: Add missing --signature parameter

---

Documentation/devel/stage1-implementors-guide.md
stage0/interface.go
stage1/aci/aci-manifest.in

So stage0 can check which features stage1 supports and pass flags
accordingly.
cc @krnowak

stage0,stage1: add interface-version annotation

---

Documentation/app-environment.md
stage1/prepare-app/prepare-app.c

rkt starts systemd-journald in the pod and creates the symlink in the
stage1 rootfs:
/dev/log -> /run/systemd/journal/dev-log (socket file)
But unfortunately it isn't directly available for the app because the
app is chrooted.
systemd-journald listens on the following sockets and other paths:
- /dev/kmsg,
- /dev/log,
- /run/systemd/journal/dev-log,
- /run/systemd/journal/socket,
- /run/systemd/journal/stdout
This patch prepares /dev/log in stage2 as a symlink to
/run/systemd/journal/dev-log and bind mounts the directory
/run/systemd/journal from stage1 to stage2, so both /dev/log and
journald's native logging will work for the application
This will help haproxy and nginx.
See https://groups.google.com/forum/#!topic/rkt-dev/P6HEylgrv8U

prepare-app: create /dev/log for stage2

---

Documentation/devel/stage1-implementors-guide.md
Documentation/subcommands/run-prepared.md
Documentation/subcommands/run.md
rkt/run.go
rkt/run_prepared.go
stage0/interface.go
stage0/run.go
stage1/aci/aci-manifest.in
stage1/init/init.go
tests/inspect/inspect.go
tests/rkt_hostname_test.go

It allows the user to specify a host name for the pod. If not specified, it will be "rkt-$PODUUID".
This approach might not be OK if we want to use systemd-resolved, apparently it expects container's machine name to match the hostname.
cc @steveeJ @yifan-gu @sjpotter 
Fixes #2245

rkt: add --hostname option

---

stage1/init/common/pod.go
tests/functional.mk
tests/rkt_mount_test.go

nspawn doesn't handle a mount operation correctly if the container path contains a symlink.
This tries to fix the problem in rkt by evaluating the mount path and resolve any symlinks before passing the mount path to nspawn.
cc @alban @iaguis @jonboulle @sjpotter

stage1: Temporary fix for symlink mount issue.

---

Documentation/app-environment.md
stage1/prepare-app/prepare-app.c

If /dev/ptmx or /dev/log already exists in the image,
leave it as is instead of overriding it.
Fix #2301

stage1/prepare-app: Do not error out if symlinks exits.

---

stage1/init/init.go

Since v222, systemd-shutdown follows `--log-target` so we don't need to
pass `--log-level=warning` anymore.

stage1/init: remove unnecessary arg to systemd

---

tests/aws.sh
tests/cloudinit/fedora.cloudinit

Fedora images get published on AWS again. It broke in February, and was
repaired yesterday. We can now test on more recent images.

tests: aws: update Fedora images

---

stage1/init/kvm/resources.go

When lkvm is using more vcpus than platform has got, then VMs
spinning up is very slow. This patch blocks this behavior and
when user choose more vcpus then platform has cores, then
number of cpus is set to number of cores

kvm: Improving lkvm performance

---

Documentation/dependencies.md
configure.ac
stage1/usr_from_coreos/build-usr.mk
stage1/usr_from_kvm/manifest.d/ip.manifest

Since unsquashfs does not have a flag for ensuring that all the files from manifest were extracted, we have to do it on our own. We do this by making sure that the complete manifest is a subset of a list of the files in the squashfs file (acquired by the "unsquashfs -ls <file>" command). This requires doing some set operations, so we got a dependency on comm from coreutils.
This also fixes one manifest file. All other manifest files do not add the root slash to the path.
Fixes #2337.

build, stage1: Check squashfs manifest

---

rkt/pods.go

If 'getChildPID()' returns an 'ErrChildNotReady' error,
then the variable 'err' will be set to nil, which causes the last
If statement's condition to be true, and returns '-1, nil'.
cc @alban @iaguis @sjpotter

rkt/pods.go: Fix a bug in getContainerPID1().

---

Documentation/hacking.md
Documentation/running-fly-stage1.md
Documentation/running-lkvm-stage1.md
Documentation/subcommands/enter.md
Documentation/subcommands/run.md
rkt/stage1hash.go

We were not checking signatures when the uses passes `--stage1-*`
options.
The new behavior is like so:
- If the user doesn't pass any flag, stage1 images will be taken from the default stage1 directory or from the directory where the rkt binary is. In that case, we don't check any signatures.
- If the user passes any `--stage1-*` flag, we always check the signature unless the resulting path is the one configured at build time.
- If the user uses rkt's configuration to configure a different stage1 we assume they know what they're doing and we'll check the signature.
Does this make sense? // @krnowak

rkt: check signatures on --stage1-* options

---

Documentation/distributions.md

rkt on Fedora is still limited because of SELinux and FirewallD but the
situation improved recently. Update the caveats.
-----
/cc @philips

doc: distributions: update caveats

---

Documentation/commands.md
Documentation/subcommands/api-service.md
Documentation/subcommands/cat-manifest.md
Documentation/subcommands/enter.md
Documentation/subcommands/fetch.md
Documentation/subcommands/gc.md
Documentation/subcommands/image.md
Documentation/subcommands/list.md
Documentation/subcommands/metadata-service.md
Documentation/subcommands/prepare.md
Documentation/subcommands/rm.md
Documentation/subcommands/run-prepared.md
Documentation/subcommands/run.md
Documentation/subcommands/status.md
Documentation/subcommands/trust.md
rkt/flag/secflags.go
rkt/image/namefetcher.go
rkt/pubkey/pubkey.go

This adds a new, "pubkey" insecure option, so we can temporarily (by creating a second keystore in /tmp) trust keys from HTTP(S). We need this for testing, because local ACI server uses an invalid certificate (apparently for example.com, not for localhost), so to be able to download anything from it, we need to pass a "tls" insecure option. But then, the keys from discovery weren't downloaded at all.
It also deduplicates global flags documentation.

Add "pubkey" insecure flag.

---

Documentation/subcommands/run.md

The syntax description for the --volume option uses lowercase for the uid and gid parameters; whereas the example uses uppercase. Change the example to conform to the implemented behaviour.

Use lowercase for UID & GID options in run example

---

stage1/init/common/kvm_mount.go
stage1/init/common/mount.go
stage1/init/common/pod.go
tests/image/manifest
tests/rkt_volume_test.go

Docker volumes are initialized with the files in the image if they
exist, unless a host directory is mounted there (see
https://docs.docker.com/engine/userguide/containers/dockervolumes/#data-volumes).
However, when we convert docker images with docker2aci, we convert
docker volumes to mount points, and if the user doesn't specify a host
path for mounting, we mount an empty volume, effectively masking the
files in the image.
To fix this, we create a special case for the case when application uses
an image converted from docker and we mount an implicit empty volume.
In that case, we copy the files from the image to the volume, so docker
images work correctly.
Note that we won't do this if the user explicitly specifies an empty
volume or if they mount a host directory.
TODO:
- ~~What if the …

stage1: implement docker volume semantics

---

tests/rkt_api_service_test.go

A timeout of 10 seconds is not enough for slow machines.
https://github.com/coreos/rkt/issues/2357
-----
/cc @yifan-gu

test: TestAPIServiceCgroup: increase timeout

---

Documentation/subcommands/run.md

Add docker port name convention.
Update link to contained network doc#heading.
<strike>Be explicit about false, at least in this row for now</strike> D'oh. :blush:
Ref #2113.

Doc/subcmd/run: Add docker port name convention

---

rkt/prepare.go

Prior to this commit, `rkt prepare` would check the ondisk image even if
the `--insecure-options=ondisk` flag was provided.
This commit corrects that.
I wasn't sure if there was an appropriate way to unit/functional test this. It didn't seem that there was a good framework inplace for unit testing run/prepare commands, and a functional test would be nontrivial (probably corrupt the ondisk data to see that it doesn't verify?).
I'd be happy to look into this a bit more if you feel it's prudent.

prepare: Support 'ondisk' verification skip

---

Documentation/subcommands/prepare.md
Documentation/subcommands/run.md

This diff turned out nastier than expected even though the changes aren't that crazy.
This fixes a few problems:
1. items with no default are specified with empty backticks instead of none
2. A few of the long code strings were causing some layout issues because they couldn't be wrapped.
3. In several places the options columns was being used for the description
4. Inconsistent use of columns led to ambiguity around the format of some stage1 options. For example, is this a name or a path? Is this an absolute or relative url?
Note that due to the wide nature of this table, it will overflow the bounds of the page on coreos.com on smaller screens. This is not ideal, but at known issue that is ok for now.
cc: @kbrwn

docs: make options table more consistent

---

Documentation/subcommands/gc.md
rkt/gc.go
tests/rkt_gc_test.go
tests/rkt_tests.go

If this flag is set to true, then we move the exited/aborted pods
to exited-garbage/garbage directory, but do not deleting them.
For prepared pods, if the flag is true, we don't move them to garbage
even the pods are expired.
A third party application can use 'rkt gc --mark-only=true' to
marks the time when the pods is not running.
Follows https://github.com/coreos/rkt/issues/1789#issuecomment-207111814
Next, will need `rkt list/status` and `rkt api-service` to return the timestamp.
cc @alban @jonboulle @iaguis @sjpotter @euank

gc: Add flag 'mark-only' to mark garbage pods without deleting them.

---

store/db.go
store/db_test.go

When there are multiple OS processes concurrently accessing the ql
db and at least one of them has multiple goroutines using a shared store
instance the internal ql (camlistore based) locking error: `cannot
acquire lock: resource temporarily unavailable` can be triggered.
For example:
Process A, goroutine 1: takes the the flock, then takes the lock on the mutex, and does db.Open
Process A, goroutine 2: takes the flock, blocks on the lock on the mutex
Process A, goroutine 1: does something on db, calls db.Close, unlocks the flock, release the lock on the mutex
Process A, goroutine 2: takes the lock on the mutex, but now it has the flock UNLOCKED
Process B, goroutine 1: take the lock on the flock and then takes lock on the mutex (since it's another process): the ql internal camlistore lock …

store: fix multi process with multi goroutines race on db.

---

CHANGELOG.md
rkt/image/namefetcher.go
rkt/image/validator.go
tests/rkt_fetch_test.go

The spec in the discovery part says: "Implementations MUST ensure
that the initial name and labels used for discovery matches the name and
labels in the Image Manifest."
Actually rkt just checks that the names matches but ignore the labels.
This patch also check the labels. Like the other validation parts the
check is executed only if the user doesn't pass `--insecure-options=image`
A functional test is added.
With this patch users calling `rkt fetch example.com/aci:latest` but
receiving an aci with a different version (like v2.0) will receive a
validation error.
This will fix a part of #2305 (since it will error on users running `rkt fetch example.com/aci:latest` to get the latest image if they don't have image verification disabled)

rkt/image: check that discovery labels match manifest labels

---

Documentation/using-rkt-with-systemd.md
tests/rkt_socket_proxyd_test.go

Setting `ptp` template network and IP address in systemd unit during
test. Updated also docs with example.

functional tests: Add new test with systemd-proxyd

---

stage1/init/common/mount.go
stage1/init/common/pod.go
stage1/init/kvm.go
tests/rkt_run_pod_manifest_test.go
tests/rkt_tests.go
tests/rkt_volume_test.go

To detect if we're running an image that was converted from docker, we
were getting annotations from the RuntimeApp. This doesn't work for the
case where the user runs rkt directly with a pod manifest, since they
can omit the annotations there.
Instead, use the ImageManifest, which is the right place to look for
annotations.
Also, fix a bug in the tests introduced by https://github.com/coreos/rkt/pull/2394 and another bug when the image is converted from docker, has a mountpoint, but the mountpoint directory is not actually included in the image.

stage1/init: fix docker volume semantics

---

rkt/pods.go

rkt status needs `ppid` file, which was removed in #2396

kvm: fix rkt status

---

CHANGELOG.md
Documentation/subcommands/prepare.md
Documentation/subcommands/run.md
common/apps/apps.go
rkt/cli_apps.go
rkt/prepare.go
rkt/run.go
stage0/run.go
tests/rkt_run_user_group_test.go

This adds --user and --group app flags to override the user and/or the
group for the run subcommand.
Fixes #1920

run: add user/group app flags

---

tools/actool.mk

actool is used during the build to generate stage1 images, etc.  Without
this patch, actool is mistakenly compiled for the *target* architecture.

Build actool for the *build* architecture

---

Documentation/commands.md
Documentation/subcommands/config.md
rkt/config.go
rkt/config/auth.go
rkt/config/config.go
rkt/config/config_test.go

This command adds the config subcommand.
TODOs:
Fixes #2368

config: add config subcommand

---

pkg/sys/sys_linux_ppc64.go
pkg/sys/sys_linux_ppc64le.go

Added missing SYS_SYNCFS definition for ppc64 and ppc64le,
fixing build failures on those architectures.
Closes: coreos/rkt#2441
Signed-off-by: Luca Bruno <lucab@debian.org>

pkg/sys: add SYS_SYNCFS definition for ppc64/ppc64le

---

Documentation/subcommands/config.md

Add a newline on either side of code blocks, and a concluding set of backticks to the last one.
(Fixed in-place downstream in the docs sync coreos-inc/coreos-pages#631)

Doc/subcmd/config: Fix formatting of code blocks - newline.

---

stage1/init/common/pod.go
tests/rkt_run_pod_manifest_test.go
tests/rkt_run_user_group_test.go

This is a special case and it should work even if the image doesn't have
/etc/passwd or /etc/group.
Fixes #2411

stage1/init: interpret "root" as UID/GID 0

---

tests/build-and-run-tests.sh

When we did the refactoring of the CI build script, we inverted the
condition that checks if we're in origin/master to always run the tests
in that case. That caused tests not running on the master branch
anymore.

functional tests: fix detectChanges function

---

stage1/prepare-app/prepare-app.c

Starting a pod with 100 apps is really slow. This patch fixes the
slowness.
prepare-app recursively bind-mounts /sys from stage1 to the stage2
(apps' rootfs). "Recursive" means it includes all the cgroup mounts
because they are in /sys/fs/cgroup. Moreover, rkt bind mounts some
cgroup knob files in the cgroup filesystem for enabling the memory and
cpu isolator.
The number of cgroup bind mounts in stage1 is linear with the number of
apps: O(n)
The number of cgroup bind mounts in stage2 is quadratic with the number
of apps: O(n^2)
With one app, I have 17 bind mounts related to cgroups. With 100 apps,
17 * 100 * 100 = 170.000 bind mounts.
For each change in the mount table, systemd is notified via inotify on
/proc/self/mountinfo and it checks the configuration of that mount in …

stage1/prepare-app: avoid recursive bind-mounts on /sys

---

rkt/image/fetcher.go
tests/rkt_image_dependencies_test.go

rkt was delaying rendering images to the tree store until they were
about to run for the first time which caused that first run to be slow
for big images.
This commit renders the image to the tree store at fetch time.
If the system doesn't support overlayfs, we don't render it because we
don't use the tree store when overlayfs is not used.
Startup time benchmark:
rkt run a Docker nginx image, pre-fetched. Size = 188MiB when unextracted
The insecure option `ondisk` was used.
command | time (rkt master) | time (rkt master + https://github.com/coreos/rkt/pull/2398)
--------|-------------------|---------------------------
1st time run | real 0m4.964s, user 0m3.570s, sys 0m0.813s | real 0m0.333s, user 0m0.097s, sys 0m0.050s
2nd time run | real 0m0.350s, user 0m0.063s, sys 0m0.077s | real …

rkt/image: render images on fetch

---

stage1/prepare-app/prepare-app.c

Fixes a regression if a container is started in a user namespaced environment.
Fixes #2490

stage1/prepare-app: check for user namespace env

---

stage1/usr_from_src/usr_from_src.mk

Symptoms:
configure: WARNING: unrecognized options: --disable-python-devel,
--disable-chkconfig, --disable-bootchart, --disable-gudev,
--disable-terminal

stage1: src: remove obsolete systemd configure flags

---

tests/rkt_userns_test.go

It's needed to read /proc/1/root

functional tests: add CAP_SYS_PTRACE to TestUserns

---

Documentation/networking/overriding-defaults.md
tests/rkt_socket_proxyd_test.go

Fixes #2432. Command is not sent to a shell, and not remove double
quotes by systemd on some old distros (fedora22).

tests: removing double quotes from rkt cmd

---

rkt/image/dockerfetcher.go
rkt/image/downloader.go
rkt/image/fetcher.go
rkt/image/filefetcher.go
rkt/image/httpfetcher.go
rkt/image/httpops.go
rkt/image/namefetcher.go
rkt/image/resumablesession.go
rkt/image/validator.go

Refactors 'rkt/image' to remove 'Get' from the method names.
Related to #2450

Remove 'get' from method names in 'rkt/image' pkg

---

rkt/image/fetcher.go

To render images, we need access to the tree store directories and
capabilities to do a chroot.
We could allow the rkt group to access the tree store directories and
not do a chroot when rendering but since this rendering-on-fetch is just
an optimization, it's simpler to just skip the rendering if we fetch as
non-root.
Fixes https://github.com/coreos/rkt/issues/2521

rkt/image: render images only if we're root

---

Documentation/configuration.md
Documentation/running-docker-images.md

The Docker Hub index URL is not index.docker.io anymore, it is
registry-1.docker.io.
Also, fix the Docker Hub link so it goes to the user-facing page.
Fixes #2526

Documentation: update references to the Docker Hub

---

tests/rkt_net_test.go

Closes #2314.
It should work by now (fixed in CNI) so adding a test case.

tests/net: cover too long net names

---

Documentation/rkt-build-rkt.md
scripts/acbuild-rkt-builder.sh

Instead of getting the Debian Sid image from the Docker hub (we don't
check its signature) we generate a Debian Sid ACI using debootstrap.
This is an intermediate step to having the rkt builder hosted by CoreOS
with a proper official signature.

scripts: generate a Debian Sid ACI instead of using the Docker hub

---

Documentation/devel/stage1-implementors-guide.md
rkt/pods.go

Clarify that only one file must be written among pid / ppid.
Reword the description. With the kvm flavor, the pid 1 of the container
was not visible on the host. The new wording does not make that
assumption.
/cc @jellonek @jonboulle @s-urbaniak PTAL
Related to: https://github.com/coreos/rkt/issues/2389

doc: stage1-implementors-guide.md: clarify pid vs ppid

---

tests/inspect/inspect.go
tests/rkt_service_file_test.go

In TestService, we start a systemd service running a rkt image that
prints a message every second. Then we stop the unit and check it's not
in the service list.
This was working before because we weren't propagating the exit status
of apps in the pod to the outside.
Now that we do it, stopping the unit file means that SIGTERM will be
sent to nspawn, which will trigger a shutdown of systemd inside the pod,
which means SIGTERM will be sent to all the apps and that makes the
inspect binary exit with a non-zero status. Transient units that exit
with a failed status remain on the services list, so our test fails.
Capture SIGTERM in inspect and return 0 in that case, so the test
passes.
Fixes https://github.com/coreos/rkt/issues/2323

functional tests: capture SIGTERM in inspect

---

stage1/init/kvm.go

Cause - AppRootfsPath called with local "root" value was adding
stage1/rootfs twice. After this change this is made properly.
Fixes regression made in df53308, closes #2469

kvm: fix mounts regression

---

tests/install-deps.sh

The kvm flavor needs 'bc' to build and 'bc' is not installed by default
on Semaphore. This was introduced by https://github.com/coreos/rkt/pull/2007

tests: install bc on Semaphore for kvm

---

Documentation/benchmarks/README.md
Documentation/benchmarks/rkt-1-4-0-benchmarks.md

Added the `Documentation/benchmarks` folder which includes a README that
describes how rkt-monitor works and how to use it, and a file detailing
the results of running rkt-monitor on each current workload with rkt
v1.4.0.
Fixes https://github.com/coreos/rkt/issues/1788

docs: added benchmarks folder, benchmarks for v1.4.0

---

tests/rkt_net_test.go
tests/rkt_volume_test.go

We just enabled functional testing for the KVM flavor but there're two
tests that currently don't pass: TestDockerVolumeSemantics and
TestNetLongName.
Disable building the files where those tests are included on the KVM
flavor for now.

functional tests: disable problematic tests

---

stage1/prepare-app/prepare-app.c

https://github.com/coreos/rkt/pull/2386 introduced an optimization to prepare-app: we don't do a recursive bind-mount from stage1 to stage2. This was made to avoid systemd going crazy about new mounts and causing huge delays when starting pods with many apps (more details in the issue).
Later, #2499 fixed a regression with user namespaces (reasoning [here](https://github.com/coreos/rkt/blob/8a76e2ddd3eb6650d8ca52278b93dc0af3abc73f/stage1/prepare-app/prepare-app.c#L163).
It turns out SELinux doesn't allow doing this, and to make rkt work, you need to mount `/sys` recursively. This is not investigated yet but since it's just an optimization for an extreme case, let's revert the two patches for now.
Fixes https://github.com/coreos/rkt/issues/2539

stage1/prepare-app: revert /sys optimization

---

networking/kvm.go
tests/rkt_net_nspawn_test.go
tests/rkt_net_test.go

Update kvm flavor networking code with bits added in CNI.
Resolves #2533
Reverts #2538

kvm: fix net long names

---

rkt/rkt.go
rkt/rkt_test.go

Adds tests for `calculateDataDir`
Fixes #2422 
Fixes #2550 
Fixes #2552

Test calculateDataDir

---

Documentation/subcommands/enter.md

Remove irrelevant section from the enter subcommand documentation.
Background doesn't make sense here. Probably an oversight from here: a63e496e647

docs: remove leftover enter subcmd section

---

README.md

that link will probably break with every release, why not just keep the link to the files and skip the specifics.

remove specific version from coreos-overlay repo

---

stage1/init/common/pod.go
tests/rkt_run_user_group_test.go

To make sure sysusers entries are generated correctly.
Fixes #2505

functional tests: run TestAppUserGroup with --private-users

---

pkg/aci/render.go
pkg/fileutil/fileutil.go
pkg/fileutil/fileutil_test.go
pkg/tar/chroot.go
pkg/tar/tar.go
pkg/tar/tar_test.go
pkg/user/doc.go
pkg/user/resolver.go
pkg/user/resolver_test.go
pkg/user/uid_range.go
rkt/image_extract.go
rkt/image_render.go
rkt/prepare.go
rkt/run.go
stage0/run.go
stage1/init/common/mount.go
stage1/init/common/pod.go
stage1_fly/run/main.go
store/backup.go
store/tree.go

This cleans up the code a bit and provides the necessary uid/gid functionality for implementing user/groups for rkt fly, see #2439

Implement composable uid/gid generators

---

Documentation/devel/update-coreos-stage1.md
Documentation/hacking.md

This adds instructions to update the CoreOS image use to build the
coreos flavor stage1.
We usually want to do this to get a newer version of systemd.

Documentation: how to update coreos flavor stage1

---

stage1/usr_from_coreos/coreos-common.mk
stage1/usr_from_coreos/manifest.d/systemd.manifest

Now that [systemd v229 is in CoreOS](https://github.com/coreos/coreos-overlay/pull/1833) we can bump it in stage1.
Fixes https://github.com/coreos/rkt/issues/1759

stage1/usr_from_coreos: use CoreOS 1032.0.0 with systemd v229

---

Documentation/distributions.md
README.md

Improve documentation on the Fedora caveat with FirewallD. Add a link from README.md.
Addresses a part of https://github.com/coreos/rkt/issues/2202
@joshix PTAL

docs: distributions: Fedora

---

stage0/run.go

Checks '/etc' before writing to '/etc/rkt-resolv.conf' and creates it with default permissions if it doesn't exist.

stage0: check and create /etc

---

Documentation/networking/overview.md
networking/kvm.go
networking/networking.go
networking/portfwd.go
stage1/init/init.go
tests/rkt_net_kvm_test.go
tests/rkt_net_nspawn_test.go
tests/rkt_net_test.go

This PR fixes port forwarding functionality when a pod is run with custom ipMasq'ed CNI networks.
It also fixes #2283: port forwarding where hostPort and podPort are different
---
Post-Merge Checklist

net: fix port forwarding behavior with custom CNI ipMasq'ed networks different and allow different hostPort:podPort combinations

---

Documentation/getting-started-guide.md

Current build command would not work after #2506
Fixes #2584
@alban Can you please take a look at my PR. I am not sure if this is what you wanted, but i tried to build `hello` with the new build command an it worked for me. Please let me know if there is something wrong with my PR. Thanks!

docs: Change getting started guide to build a static binary

---

Documentation/dependencies.md
Documentation/hacking.md
configure.ac

To use kernel sources during kvm flavor build, openssl headers
are needed.
Signed-off-by: Michal Rostecki <michal.rostecki@gmail.com>

Check for openssl headers availability in kvm flavor

---

stage1/enterexec/enterexec.c

Prior to this commit, if `rkt enter` was executed without the `TERM`
environment variable set, a segfault could occur.
This commit treats an unset TERM environment variable as meaning 'xterm'
and avoids the segfault.
This is more noticeable in environments where rkt is the child of some non-terminal process (e.g. the kubelet).
Related to https://github.com/kubernetes/kubernetes/issues/25430
I reproduced this via `sudo sh -c 'unset TERM && rkt enter $uid ls'` on my machine, though I'm not certain that it reproduces consistently on all machines. I could not reproduce it after this change.
I wasn't sure if it was preferable to leave `TERM` blank when it is unset for the caller and I'm open for any discussion / arguments there.
cc @dgonyeo

stage1: Fix segfault in enterexec

---

Documentation/hacking.md
scripts/install-deps-debian-sid.sh

This pull request adds the dependency `libtspi-dev` to `scripts/install-deps-debian-sid.sh` to reuse this install script for the [Building rkt with Docker](https://github.com/coreos/rkt/blob/master/Documentation/hacking.md#building-rkt-with-docker) section. Also i changed the image of this part to `debian:sid`. Now it uses the same image and dependencies like the [Building rkt in rkt](https://github.com/coreos/rkt/blob/master/Documentation/rkt-build-rkt.md#debian-sid) section.
@alban @iaguis @jellonek Can somebody please take a look? Thanks!

Add libtspi dev to install script update docker build cmd

---

stage1/init/common/pod.go
tests/inspect/inspect.go
tests/rkt_mountns_test.go
tests/rkt_volume_test.go

Up to this point, you could escape the app's chroot easily by using a
simple program downloaded from the internet [[1]][1]. To avoid this, we now
create a new mount namespace per each app.
You can still escape the chroot if you have CAP_SYS_PTRACE and access
`/proc/1/root` but this fixes the issue for images that don't need this
capability.
[1]: http://www.unixwiz.net/techtips/chroot-practices.html

stage1/init: create a new mount ns for each app

---

dist/init/systemd/tmpfiles.d/rkt.conf

By creating this directory, users can run `rkt trust` without being
root, if the user is in the rkt group.
If we want to treat `rkt trust` as a more privileged operation, than we could go one step further and create `/etc/rkt/trustedkeys` with a different set of permissions/groups.

dist: Update tmpfiles to create /etc/rkt

---

tests/rkt_ace_validator_test.go

This allows to debug https://github.com/coreos/rkt/issues/2171 properly.

tests: print proper output for TestAceValidator

---

rkt/prepare.go
rkt/run.go
rkt/run_prepared.go
rkt/stage1hash.go

This removes some unnecessary indefinite articles from the start of argument doc strings and fixes the arg doc string for run-prepared's --interactive flag.

Some simple arg doc string fixes

---

stage1/prepare-app/prepare-app.c

stag1/prepare-app/prepare-app.c:get_machine_name()
CHANGE:
- stag1/prepare-app/prepare-app.c:get_machine_name() Now parses the expected
format of UUIDs in the format of 8-4-4-4-12. This is done becaues the
package which generates UUIDs generates 32-character long UUIDs instead of
the expected 28-character long UUIDs.
Fixes #2573

Parse 32 character auto-generated UUIDs correctly.

---

stage1/init/common/pod.go
tests/inspect/inspect.go
tests/rkt_caps_test.go

It follows the [Linux Isolators semantics from the App Container Executor spec](https://github.com/appc/spec/blob/master/spec/ace.md#linux-isolators), as modified by https://github.com/appc/spec/pull/600.
The new functional test TestCapsSeveralApp runs a pod with 12 apps with various capability definitions and tests that each app is executed with the correct caps. The 12 images are generated by `actool patch-manifest --capability=|--revoke-capability=` implemented by https://github.com/appc/spec/pull/601.
This PR depends on https://github.com/appc/spec/pull/601.
Fixes https://github.com/coreos/rkt/issues/2348

stage1: capabilities: implement both remain set and remove set

---

Documentation/subcommands/run.md
stage1/init/common/pod.go
tests/rkt_run_pod_manifest_test.go

Using the Pod manifest readOnlyRootFS option mounts the rootfs of the app
as read-only using systemd-exec unit option ReadOnlyDirectories.
Fixes #2487 
Supersedes #2612

stage1: implement read-only rootfs

---

rkt/rkt_test.go

@tmrts PTAL
Fixes TestCalculateDataDir failure triggered when /var/lib/rkt is a symlink.

rkt: handle symlink in calculateDataDir test

---

Documentation/subcommands/run.md

Fixes the word "network" appearing twice instead of once when explaining the default contained network argument.

docs: fix duplicate word

---

Documentation/getting-started-ubuntu.md

Updates the Ubuntu Vivid Vagrant broken link to a working Ubuntu Wily link.
Related to #2243, #2259

docs: updated Ubuntu link

---

.gitignore
rkt/rkt.mk

Pass expected variables to build commands and prefer them over hardcoded ones. Also, git ignore `dist` directory with build artifacts.

build: fix build failures on manpages/bash-completion target due to missing GOPATH

---

tests/build-and-run-tests.sh

This commit adds more patterns to DOC_CHANGE_PATTERN, skipping
testing on image changes and more top-level files.
Closes #2642
Signed-off-by: Luca Bruno <lucab@debian.org>

tests: update pattern to skip more doc/img files

---

tools/depsgen/globcmd.go

`depsgen` works on file lists and globs, consuming `stat` output
to calculate dependencies. This commit adds an explicit C locale
setting to avoid build failures on non-English locales.

build: fix building on non-English locales

---

.gitignore

Refine `.gitignore` to only ignore bash_completion and manpages
artifacts. Reinstate the toplevel `dist` directory, as it contains
some other tracked data.

build: only ignore specific sub-directories in `dist`

---

rkt/api_service.go
tests/rkt_image_list_test.go

We need to take into account the treestore size too.
cc @yifan-gu

api: fix image size reporting

---

networking/kvm.go

Fixes https://github.com/coreos/rkt/issues/2636

kvm: transform flannel network to allow teardown

---

tests/rkt_service_file_test.go

TestServiceFile was previously waiting 10 seconds. In our test on Fedora
23, it was taking 11 seconds. This made the test fail. This patch
increases the delay to 15 seconds. It should be enough.
/cc @iaguis

tests: TestServiceFile: increase timeout to 15s

---

store/tree.go

1. fix slice make, capacity instead of length
2. preallocate slice with capacity to avoid slice growth with append
3. simplify return type

store/tree.go: fix multiple things

---

rkt/prepare.go
rkt/run.go
tests/rkt_prepare_test.go
tests/rkt_run_test.go

When a pod manifest is passed to rkt-prepare other conflicting
CLI flags are discarded, so far in a silent way.
This commit makes the issue explicit and abort when conflicting
flags are specified together with `--pod-manifest`.
Fixes #2418

stage0: complain and abort on conflicting CLI flags

---

Documentation/commands.md

Documentation: document per-app logs

---

tests/inspect/inspect.go
tests/rkt_run_pod_manifest_test.go

Add a new test to check that the WorkingDirectory specified in the ACI
manifest is used.

tests: check current working directory

---

stage1/prepare-app/prepare-app.c

The previous two patches make rkt not do a recursive bind-mount on `/sys`
unless we use user namespaces (the kernel doesn't allow that). However,
SELinux doesn't allow mounting `/sys/fs/cgroup` manually in that case.
Since the spec doesn't say apps should have a view of /sys/fs/cgroup,
let's not mount it in stage2.
Fixes https://github.com/coreos/rkt/issues/2351

stage1/prepare-app: don't mount /sys/fs/cgroup in stage2

---

common/cgroup/cgroup.go
stage1/gc/gc.go
stage1/init/init.go
tests/rkt_gc_nspawn_test.go
tests/rkt_rm_nspawn_test.go
tests/rkt_rm_test.go

After a pod exits, there'll be some leftover directories in
/sys/fs/cgroup.
This commit cleans them up on GC.
Fixes (partially) #2504

stage1: clean up pod cgroups on GC

---

Documentation/commands.md

Docs only showed a way to access logs from running container
Fixes #1528 
@alban Can you please take a look?

Add way to access logs from stopped container to docs

---

.travis.yml

Complains when the commit is a merge commit, it shouldn't!
Discovered in  #2684

git-validation: disable short-subject validation

---

rkt/rm.go
rkt/uuid.go
tests/rkt_rm_test.go

We were trusting that the value in the uuid file referred to an existing
pod, which caused a panic if that wasn't the case.
In this commit we resolve the UUID to check if the pod actually exists.
Also, make rm's behavior consistent between caling it with a pod UUID
and with `--uuid-file`:
* Print a similar error message
* Set the exit status to 1 if we fail to remove any pod
There's no tests for `rkt rm`. I add some in https://github.com/coreos/rkt/pull/2655. I can add a test-case for this there.
Fixes https://github.com/coreos/rkt/issues/2678

rkt: fix panic on rm a non-existing pod with uuid-file

---

.travis.yml

Travis fails because git-validation also checks Godeps changes.
Let's check only HEAD until
https://github.com/coreos/git-validation/issues/4 is solved.

git-validation: check only the HEAD commit

---

makelib/misc.mk
tests/tests.mk

We were only checking the packages that had non-empty TestGoFiles
field returned by "go list". But the TestGoFiles contains only files
that have the same package as the non-test files in the same
directory. The test files with the different package name are in the
XTestGoFiles field, which we did not handle before.
This makes go test to run the test for pkg/selinux and pkg/user
packages too.
Should help with #2496.

build: Find also blackbox tests for unit-check

---

stage1/init/common/pod.go
tests/rkt_mount_test.go

Many procfs and sysfs endpoints are currently not namespace-aware
and can be used by malicious pods to manipulate host state
and escape the sandboxing.
This commit introduces an initial mitigation, by marking those
paths as read-only or inaccessible to containers.
(Partially) Fixes #2484

stage1: restrict access to procfs and sysfs paths

---

tests/README.md
tests/build-and-run-tests.sh

This patch enables running builds w/o testing and using not commited changes for builds

Add additional options for developers in build-and-run-tests.sh script

---

tests/rkt_api_service_test.go

This fixes the flaky test where pod is RUNNING but pid file and
network info files are not ready.
After this, the tests passed stably.
Ref https://github.com/coreos/rkt/issues/2638
cc @jonboulle @iaguis @matthaias

tests/rkt_api_service_test.go: Also check PID when polling the pod.

---

Documentation/distributions.md
Documentation/install-rkt-in-coreos.md

Added Documentation/install-rkt-in-coreos.md, which details a systemd
oneshot unit file that downloads and extracts rkt to /opt. Added a
reference to this file in Documentation/distributions.md.
Fixes https://github.com/coreos/rkt/issues/2601#issuecomment-218463662.

docs: added instructions for installing a newer rkt in coreos

---

common/common.go
rkt/prepare.go
rkt/run.go

OverlayFS doesn't work on top of ZFS, thus using ZFS under `/var/lib/rkt` requires passing `--no-overlay` flag every time. This code detects ZFS and disables overlay automatically.

disable OverlayFS by default when working on ZFS

---

Documentation/benchmarks/README.md
Documentation/benchmarks/rkt-1-4-0-benchmarks.md
Godeps/Godeps.json
Godeps/_workspace/src/github.com/shirou/gopsutil/load/load.go
Godeps/_workspace/src/github.com/shirou/gopsutil/load/load_darwin.go
Godeps/_workspace/src/github.com/shirou/gopsutil/load/load_freebsd.go
Godeps/_workspace/src/github.com/shirou/gopsutil/load/load_linux.go
Godeps/_workspace/src/github.com/shirou/gopsutil/load/load_windows.go
tests/rkt-monitor/README.md
tests/rkt-monitor/main.go

New statistics for load average and boot/stop time measure of container.
Differences are measured in a nanoseconds. Godeps updated as well.

tests: rkt-monitor add new statistics

---

CHANGELOG.md
Documentation/devel/architecture.md
Documentation/devel/pod-lifecycle.md
Documentation/devel/stage1-implementors-guide.md
Documentation/subcommands/run.md
stage0/run.go
stage1/README.md
tests/rkt_caps_test.go

Fixes #2610 
@jonboulle @blixtra PTAL

docs: use stageX consistently

---

stage1/init/common/pod.go
tests/inspect/inspect.go
tests/rkt_no_new_privs_test.go

stage1: implement no-new-privs linux isolator

---

Documentation/capabilities-guide.md

This commit introduces a walk-through guide for capabilities usage.
It is targeted to users, introducing them to Linux capabilities in
general, documenting the differences between the two available
isolators, and showing how to use them for building sandboxed images.
Fixes #2648

docs: document capabilities usage

---

rkt/gc.go
stage0/gc.go
tests/rkt_gc_nspawn_test.go
tests/rkt_gc_test.go
tests/rkt_rm_nspawn_test.go
tests/rkt_rm_test.go
tests/rkt_tests.go

It might happen that stage1 is unmounted between the time where the pod
was stopped and it is GCd. This causes the stage1 GC or the CNI
plugins not to be accessible.
To fix it, we mount stage1 from the treestore at GC time.

rkt/gc: mount stage1 on GC

---

.travis.yml
Documentation/dependencies.md
Godeps/Godeps.json
Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/dbus.go
Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/methods.go
Godeps/_workspace/src/github.com/coreos/go-systemd/sdjournal/journal.go
Godeps/_workspace/src/github.com/coreos/go-systemd/sdjournal/read.go
Godeps/_workspace/src/github.com/coreos/go-systemd/util/util.go
Godeps/_workspace/src/github.com/coreos/pkg/dlopen/dlopen.go
Godeps/_workspace/src/github.com/coreos/pkg/dlopen/dlopen_example.go
api/v1alpha/client_example.go
configure.ac
rkt/api_service.go
scripts/acbuild-rkt-builder.sh
scripts/install-common.sh
scripts/install-deps-debian-sid.sh
scripts/install-deps-fedora-22.sh
stage1/init/init.go
tests/cloudinit/centos.cloudinit
tests/cloudinit/fedora.cloudinit
tests/cloudinit/ubuntu.cloudinit
tests/install-deps.sh

Allows being able to get the logs of a pod with the API service without forking off journalctl.
Fixes #1970 
Depends on https://github.com/coreos/go-systemd/pull/160

api_service: Implement GetLogs RPC request

---

Godeps/Godeps.json

Per OOB, thanks to the calamity that is GitHub,
this inconsistency slipped in as a mix of
https://github.com/coreos/rkt/pull/2587/files#diff-681659ab9abb4b4883e78e8aaa980dbaR510
and https://github.com/coreos/rkt/pull/2705/files

Godeps: fix gopsutil/load reference

---

MAINTAINERS

Piotr has provided invaluable contributions to the project, mostly
around the KVM stage1 but also more generally. This proposes adding him
as a maintainer of all KVM-related areas.
This format is taken straight from
https://github.com/coreos/etcd/blob/master/MAINTAINERS but open to
better suggestions. I don't think it's necessary yet to go to a fully
structured approach (i.e. human parseable is fine for now).

MAINTAINERS: add Piotr Skamruk (@jellonek)

---

tests/inspect/inspect.go

We're not mounting `/sys/fs/cgroup` on stage2 anymore so this check
doesn't make sense. Let's just check on
`/proc/1/root/sys/fs/cgroup/...`.

functional tests: fix check-cgroup on inspect

---

Documentation/capabilities-guide.md
Documentation/subcommands/run.md

- Fix formatting of code blocks and lists in capabilities-guide doc
- Fix broken link to networking/overview in Docs/subcmd/run.

Documentation: Fix issues from downstream: fmt and link

---

Documentation/devel/stage1-implementors-guide.md

Switch to all atx-style markdown for headings and sort the hierarchy.
Ref https://github.com/coreos/rkt/issues/2707

Doc/devel/stage1-implementors-guide: Fix heading fmt

---

pkg/label/label_selinux.go
pkg/selinux/selinux.go
pkg/selinux/selinux_test.go

TestSELinux was not setting the MCS dir which caused the paths of every
MCS to be in the root of the file system (the path is calculated as
`fmt.Sprintf("%s/%s", mcsdir, mcs)` and `mcsdir` was the empty string by
default). This was making the test to fail when it runs as non-root.
The test failure was non-obvious because of the way the algorithm to get
a unique MCS is implemented. We first try to create the MCS file with a
random category pair and, if it doesn't work, we continue with a
different random category pair. Since we can't write to the MCS
directory, we'll continue doing this until the test times out and we
don't print any errors when we can't create the MCS file.
Let's clean this package a bit.

pkg/selinux: various fixes

---

pkg/fileutil/fileutil.go

This fixes the issue where when cleanSrc equals '.', copied files are missing the first character from their names.
Note: I had issues getting the functional and unit tests working on my machine.
Fixes appc/acbuild#211

Don't remove the cleanSrc if it equals '.'

---

Documentation/subcommands/rm.md

Documentation/subcmd/rm: Correct --uuid-file-save typo

---

Documentation/devel/release.md

This tries to document current release model, tentatively
introducing a buffer day to stabilize the release and better
plan next ones.

docs: document rkt release cycle

---

rkt/api_service.go

Symptoms:
> panic: interface conversion: []uint8 is not proto.Message: missing
> method ProtoMessage
This patch fixes the panic, but there are other crashes that are not
related to LogsStreamWriter. I'll file a separate PR.
Helps with https://github.com/coreos/rkt/issues/2740

api: GetLogs: use the correct type in LogsStreamWriter

---

stage1/init/common/pod.go

This removes write access to /proc/bus/, stopping malicious apps
from directly accessing devices through procfs.
For reference, see Appendix IV of
https://www.nccgroup.trust/globalassets/our-research/us/whitepapers/2016/june/abusing-privileged-and-unprivileged-linux-containerspdf
(This also helps toward reducing `apptToSystemd()` size as per #2616)

stage1: make /proc/bus/ read-only

---

rkt/config.go

Pretty printing makes it easier to read for humans. Since it is still
json, it's still easy to automate. A script still has the option to
enable or disable pretty printing.

stage0/config: add a CLI flag to pretty print json

---

api/v1alpha/client_example.go
rkt/api_service.go

With this PR, the api client_example gets a new flag `-follow` to use the 'Follow' feature of GetLogs.
To test this, start with running a container:
```
sudo rkt run docker://busybox --exec sh -- -c 'while sleep 1 ; do date ; done'
```
In another terminal, start rkt's API service:
```
rkt api-service
```
In another terminal, start client_example with different options:
```
cd api/v1alpha
go build  client_example.go
./client_example
./client_example -follow
```
See also https://github.com/coreos/rkt/issues/2740
/cc @yifan-gu @euank @pskrzyns

api: GetLogs: improve client example with 'Follow'

---

Documentation/signing-and-verification-guide.md

This is a small clarification, but I think the guidelines can be extended further with the following information:
For demo purposes using a CoreOS instance the assets created in the tutorial can be put in the following directory structure:
```
./hello
./images
./images/example.com
./images/example.com/hello-0.0.1-linux-amd64.aci.asc
./images/example.com/hello-0.0.1-linux-amd64.aci
./pubkeys.gpg
```
`/etc/hosts` can be modified as follows:
```
core@core-01 ~ $ cat /etc/hosts
127.0.0.1 core-01
127.0.0.1 example.com
```
If Docker is available, we can easily host the discovery page:
```
docker run -d --name nginx -v $(pwd):/usr/share/nginx/html:ro -p 80:80 nginx:mainline-alpine
```
Effectively seeing rkt discovering & verifying the image:
```
sudo rkt run --insecure-options=http,pubkey …
```

docs: clarify the URL for the discovery example

---

networking/networking.go
stage0/run.go

stage0:  remove superfluous %v Printf verb from logged message when tree cache is bad
Fixes #2749

stage0:  remove superfluous error verbs

---

api/v1alpha/client_example.go
rkt/api_service.go

When appname is given, we should set SYSLOG_IDENTIFIER=appname instead of the service name.
cc @alban @iaguis

api_service: Fix the GetLogs() when appname is given.

---

api/v1alpha/client_example.go

Fixes the concern expressed in https://github.com/coreos/rkt/pull/2763#discussion_r66409260

api/client_example: fix panic if pod has no apps

---

rkt/rkt.mk

manpages_gen and bash_completion_gen are compiled and run at build time,
so need to be built for the build platform, not the target platform.
This change overrides GOARCH/CC appropriately for these two targets.
Note building these tools requires that the systemd and acl C headers
are also available for the build architecture.

build: compile generators for build platform

---

Documentation/subcommands/trust.md
rkt/trust.go

Error message is not helpful at the moment for the user
Fixes #480 
@jonboulle can you please take a look at this. I am not sure if this is ok so, this is my first code change in a golang project and rkt :)
The result is:
````
$ ./build-rkt-1.6.0+git/bin/rkt trust coreos.com
trust: Prevented potentially dangerous unbounded trust of all containers signed by keys from coreos.com
To continue trusting this root domain:
rkt trust --root PUBKEY (local key file, no discovery)
Or, establish a smaller scope with a prefix:
rkt trust --prefix "example.com/hello"
rkt trust --prefix "example.com/foo/*"
````

stage0/trust: change error message if prefix/root flag missing

---

stage1/init/init.go
stage1/init/kvm/log.go
stage1/init/kvm/network.go

This switches the kvm package to using a diagnostic logger whose
messages are only sent to stderr when debugging is switched on.
Otherwise messages are discarded.

kvm: use diagnostic messages for diagnostics

---

store/main_test.go

The code this check was based on changed lately and we've been getting
some occurrences of a goroutine leak when running unit tests.
Update the code to match golang upstream [1][1], which waits a bit for
goroutines to finish, in the hope of getting rid of those issues.
[1]: https://github.com/golang/go/blob/release-branch.go1.6/src/net/http/main_test.go#L21

store: update goroutine leak check

---

stage1/prepare-app/prepare-app.c
tests/rkt_etc_hosts_test.go

This commit lets prepare-app bind mount /proc/sys/kernel/hostname
over /etc/hostname, so that applications have a consistent hostname
view.
Fixes #2657

stage1/prepare-app: always adjust /etc/hostname

---

common/common.go

The size of Statfs_t.Type varies by platform.  Use untyped constants to
avoid a compile error on non-64bit platforms.

common: Use untyped FsMagic constants

---

tests/rkt_exit_test.go

Sometimes, the first app (hello0) didn't have time to print its message
before the pod exits. Sleep on every app so all of them have time to
print it.
Fixes #2779

functional tests: sleep on every app when testing exit code

---

Documentation/subcommands/prepare.md
Documentation/subcommands/run.md

Fix broken links to k8s/design/resources.
Restore docker port name convention doc from
https://github.com/coreos/rkt/commit/443073354c7d2bb40a3f69d520f4f45f69f2f31d
(eaten in https://github.com/coreos/rkt/commit/96f65b362258cef064ab3a660faa891bc7366cba)

Doc/subcmd: Fix options table in prepare and run

---

stage1/usr_from_kvm/lkvm/patches/do_synchronous_writes.patch

It is minimal cache that is only used for read-write mmap.
Nothing else is cached, like cache=none, but it allows to read logs from rkt+kvm.
9p doc: https://www.kernel.org/doc/Documentation/filesystems/9p.txt
/cc @pskrzyns @iaguis @jellonek

KVM: Update LKVM patch to mount with mmap mode.

---

tests/rkt_caps_kvm_test.go
tests/rkt_caps_nspawn_test.go
tests/rkt_caps_test.go

tests: enable all cases in capabilities test for rkt-kvm

---

api/v1alpha/client_example.go
rkt/api_service.go
stage1_fly/run/main.go

rkt fly currently is stuck in an endless loop when `GetLogs()` is invoked in the api service. This PR fixes it by returning an empty log for fly pods.
Fixes #2792

rkt/api_service: fix fly pods

---

common/apps/apps.go
rkt/cli_apps.go
rkt/run.go
stage0/run.go
tests/rkt_caps_test.go

This adds the isolators os/linux/capabilities-retain-set or
os/linux/capabilities-remove-set respectively.
Examples of usage:
```
sudo rkt run docker://ubuntu --cap-retain=CAP_KILL,CAP_NET_ADMIN --exec sh  -- -c 'capsh --print'
sudo rkt run docker://ubuntu --cap-remove=CAP_MKNOD,CAP_SYS_CHROOT --exec sh  -- -c 'capsh --print'
```
It is not allowed to specify both --cap-retain and --cap-remove on the
same image.
Both flags will override any existing capability isolator from the ACI.
The override also happens on a capability isolator of a different type.
For example, if the image had os/linux/capabilities-retain-set, using
cap-remove will remove it even if --cap-remove refers to
os/linux/capabilities-remove-set.
-----
@lucab  PTAL
TODO:

run: add --cap-retain and --cap-remove

---

tests/rkt_fetch_test.go

Our test server sends half of the file and then tells TestResumedFetch
via a channel that it should kill rkt and start another rkt process
to check if it resumes the download.
However, it may happen that rkt doesn't have time to write everything to
disk before it gets killed, in some cases it doesn't even have time to
write anything and the test fails.
To fix it, we sleep a bit before telling TestResumedFetch that it should
kill rkt.
Also, in https://github.com/coreos/rkt/pull/2762 we skip TestFetch if remote fetching fails, but that was actually not working because we called `t.Errorf` before skipping. Fix that too.
Fixes #2668

functional tests: sleep before killing rkt on TestResumedFetch

---

Documentation/packaging.md
Documentation/subcommands/api-service.md
dist/init/systemd/rkt-api.service

This commit adds a sample service file for a rkt api-service listening
on localhost.
The existing documentation around the`init` scripts is sparse and it links to the entire directory already, but I'm happy to also make improvements there.

dist: Add rkt-api systemd unit

---

pkg/multicall/multicall.go

This commit strips base path from command name before trying multicall
matching. It allows for file binaries to be properly run with entrypoint
hijacking via multicall.

pkg/multicall: strip path from command before matching

---

rkt/uuid.go
tests/rkt_rm_test.go

After the patch, if the uuid is an empty string then matchUUID(uuid string)
returns no matches instead of all the pods.
This is done to avoid `rkt rm` or `rkt enter` to delete or enter pods
without intending to.
Fixes https://github.com/coreos/rkt/issues/2806

rkt/uuid: fix match when uuid is an empty string

---

stage1/usr_from_coreos/coreos-common.mk

This introduces support for arm64 and aligns to the current base of
beta channel.

stage1: update coreos image to 1068.0.0

---

Documentation/subcommands/prepare.md
Documentation/subcommands/run.md
rkt/prepare.go
rkt/run.go
stage0/run.go
tests/env_file_test.conf
tests/rkt_env_test.go

--set-env-file gets an environment variables file path in the format "VAR=VALUE\n...".
This switch may be used multiple times on the command line to provide multiple
environment files. When it used multiple times, it merges each environment file
in a single environment and it returns an error if the same variable is set multiple
times (either in different files or in the same file).
This patch implements priorities among the various way to specify
environment variables, from highest to least priority:
1. Command line (--set-env)
2. From files (--set-env-file)
3. Image Manifest
4. Inherit (--inherit-env)
A variable in a group with an higher priority will override the value
of a variable with the same name in groups with lower priority without
producing any error. Variables with unique …

rkt/run: added --set-env-file switch and priorities for environments

---

rkt/image/common.go

At some point rkt will fall back to using heuristics to determine if the
provided image name is referring to an ACI on disk or if it's an image
name to perform discovery on / look in the store for. This commit
modifies the function that determines this to begin by stat'ing the
provided image name. If a file to that exact path exists on disk, that's
probably what the user wished to run.
This commit was prompted by me attempting to run a filename that docker2aci had decided to put a colon in (docker2aci docker://localhost:5000/thing)

rkt/image: when using heuristics to determine app type, stat first

---

Documentation/subcommands/prepare.md
Documentation/subcommands/run.md

https://github.com/coreos/rkt/pull/2771 previously added --cap-retain and --cap-remove in the "rkt run" command but they were not added in the documentation. This patch adds them.
Also, the flags --user and --group were only partially documented. This patch also completes that.

Doc/subcmd: add missing flags

---

pkg/tar/tar_test.go

TestExtractTarOverwrite was failing due to attempting to test the tar
package's ability to overwrite files during extraction, but called
ExtractTar with the overwrite argument set to false. This went unnoticed
since the test is skipped when not run as root, which is the case in our
CI.
Fixes #1923.

pkg/tar: overwrite tests was failing due to not using overwrite flag

---

stage1_fly/run/main.go

This will allow any user to list the content directories. It does not
have any effect on the permissions on the mounted files itself.
Quick fix for #2831.

stage1/fly: use 0755 to create mountpaths

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/coreos/go-systemd/sdjournal/read.go

go-systemd v10 fixes a panic-inducing bug due to returning incorrect
Read() length values.
Fixes #2835

Godeps: update go-systemd

---

common/cgroup/cgroup.go

There are some places in the common/cgroup/cgroup.go which contain the same
code which collects flags to mount a filesystem in read-only mode and calls
mount system call with the given flags and a filesystem source/target.
This patch adds mountFsRO() helper function to prevent code duplication.
Signed-off-by: Alexander Kuleshov <kuleshovmail@gmail.com>

common/cgroup: add mountFsRO() helper function

---

common/apps/apps.go

This patch removes apps.GetImageIds() method as it has no callers anymore.
This helper was added to pass list of image ids to the state0, but now we
pass list of apps in a pod instead.
Last user of the GetImageIDs() was removed in the 227fe3cc2 commit
(  Move pod registration from stage1 to stage0. by @eyakubovich ) and it is
not used anywhere anymore.
So we can remove it.

common: remove unused GetImageIDs()

---

tests/rkt_run_pod_manifest_test.go

appc 0.8.5 performs stricter validation on types.Isolator instances,
and some rkt tests would fail due to misuses.
This commit switches to proper unmarshaling to construct those
instances.
Context at https://github.com/appc/spec/pull/633

tests: fix abuses of appc types.Isolator

---

pkg/tar/tar.go

Since this package can be used outside of rkt, there is no need to
obscure the return values by using errwrap. All of the internal
consumers of these functions already wrap the output anyway, so this is
actually redundant. For example, `extractTarCommand()` may return:
```
error extracting tarball
error extracting tarball
no such file or directory
```
This change removes the outermost wrap:
```
error extracting tarball
no such file or directory
```

pkg/tar: remove errwrap

---

Documentation/trying-out-rkt.md

Addressing https://github.com/coreos/rkt/pull/2808#discussion-diff-67933880
Update to clarify the 3 use cases (actually 4, since we describe Vagrant
on linux as well).
Update for styleguide stuff - ref links, sentence case, fmt.
Update etcd ACI version and hashes to v2.3.7.

Documentation/trying-out-rkt: Update for clarity and style

---

stage1/enterexec/enterexec.c
stage1/init/common/path.go
stage1/init/common/pod.go

This patch modifies enterexec to get environment files with variables
separated by the new line character (like the systemd ones).
This patch works also with environment files in the old format (separator '\0').
Fixes https://github.com/coreos/rkt/issues/2507

stage1/enterexec: environment file with '\n' as separator (systemd style)

---

stage1/enterexec/enterexec.c

`}` on a new line
Fix formatting typo of https://github.com/coreos/rkt/pull/2839

stage1/enterexec: fix formatting

---

rkt/stage1hash.go

Make comments consistent to the implementation as currently the 'location' field only supports URL and file path.
cc @krnowak @iaguis @alban @s-urbaniak @lucab 
@s-urbaniak Feel free to reassign :)

stage1hash.go: Fix the documentation for getStage1Hash().

---

rkt/metadata_service.go
tests/rkt_ace_validator_test.go
tests/rkt_metadata_service_test.go

This fixes coreos/rkt#2621 by bringing the metadata service in compliance with the Appc spec v0.8.1.
It also fixes a few small encoding issues in the sandbox-side service.

run: fix sandbox-side metadata service to comply to appc v0.8.1

---

stage1_fly/run/main.go
tests/rkt_fly_test.go

Fixes #2846.
I'm not positive that all the implementation of the different App types and MountPoints really reflect the specs, but this change reproduces what stage1-coreos does.
/cc @iaguis

stage1/fly: respect runtimeApp App's MountPoints

---

tests/rkt_stop_test.go

On the fly flavor, rkt stop just sends SIGTERM to the process, since we
don't do anything special, inspect returns a non-zero exit status which
makes the test fail because we expect 0.
Add `--silent-sigterm` so the test works on fly too.

functional tests: add --silent-sigterm on rkt stop test

---

scripts/glide-update.sh

glide is confused when it's not running the rkt repository inside $GOPATH.
The new check implies to be in the root directory of the repo.

scripts/glide-update: ensure running from $GOPATH

---

stage1/usr_from_coreos/coreos-common.mk
stage1/usr_from_coreos/manifest-amd64-usr.d/systemd.manifest
stage1/usr_from_coreos/manifest-arm64-usr.d/systemd.manifest

This is needed for a recent enough version of libseccomp (2.3.0), with support for
new syscalls (eg. getrandom).

stage1: update coreos image to 1097.0.0

---

rkt/pods.go
store/db.go
store/store.go

Close db lock on store close. If we don't do it, there's a fd leak everytime we open a new Store, even
if it was closed.
Also, close `overlay-prepared` when checking if a pod uses overlay.
cc @sgotti 
Fixes https://github.com/coreos/rkt/issues/2899

store,rkt: fix fd leaks

---

rkt/run.go
stage1/enterexec/enterexec.c
tests/env_file_test.conf

Loading environment retained the new line character (`\n`),
this produced an incorrect evaluation of the environment variables.
Fixes: https://github.com/coreos/rkt/issues/2893
Related to: https://github.com/coreos/rkt/pull/2839

stage1/enterexec: remove trailing `\n` in environment variables.

---

rkt/rm.go
rkt/stop.go
tests/rkt_stop_test.go

So the user can use the value saved on rkt run with --uuid-file-save.
Fixes #2892

rkt/stop: implement --uuid-file

---

Makefile.in
configure.ac
rkt/api_service.go
rkt/api_service_sdjournal.go
rkt/api_service_stub.go
rkt/rkt.mk

This introduces a 'sdjournal' tag and corresponding stubs in api_service,
turning libsystemd headers into a soft-dependency.
If systemd-journal support is enabled and `sd-journal.h` found at build
time, api_service will use it for logs retrieval.
This is enabled by default, but downstream can turn it off via
`--enable-sdjournal=no`.
Fixes #2866
Ref #2797

api_service: optionally build systemd-journal support

---

store/db.go
store/db_test.go
store/store.go

Instead of having a file lock to handle inter process locking and a sync.Mutex
to handle locking between multiple goroutines, just create, lock and close a
new file lock at every db.Do function.
Additionally, saving a sqldb instance in the db struct between open and close
doesn't make great sense (and will create data races accessing sqldb, and that
was one of the reasons for the added sync.Mutex) since sqldb will be opened and
closed for every db.Do.
This is a followup of #2391 
/cc @yifan-gu @euank

store: simplify db locking and functions

---

rkt/api_service_sdjournal.go

Hit this when stressing the api service..
cc @lucab @s-urbaniak

api_service/log: Fix file descriptor leak in GetLogs().

---

glide.lock
glide.yaml
vendor/github.com/appc/docker2aci/lib/internal/backend/repository/repository.go
vendor/github.com/appc/docker2aci/lib/internal/backend/repository/repository2.go
vendor/github.com/appc/docker2aci/lib/internal/internal.go
vendor/github.com/appc/docker2aci/lib/internal/typesV2/docker_types.go
vendor/github.com/appc/docker2aci/lib/version.go

It includes support for the docker image format v2.2 and OCI image
format and allows fetching via digest.
Ref: https://github.com/coreos/rkt/issues/2188
To fully fix #2188 it we need to verify signatures (https://github.com/appc/docker2aci/issues/156)

glide: update docker2aci to v0.12.1

---

stage1/init/common/path.go
stage1/prepare-app/prepare-app.c
tests/rkt_volume_test.go

When users mount /sys or a sub-directory of /sys as a volume,
prepare-app should not mount /sys: that would mask the volume provided
by users. This patch detects if there is a volume mounted in /sys or a
subdirectory and skips the mount.
Fixes https://github.com/coreos/rkt/issues/2874
-----
/cc @tjdett
TODO:

stage1: prepare-app: don't mount /sys if path already used

---

Documentation/using-rkt-with-kubernetes.md

Doc: Update rktnetes docs.

---

makelib/misc.mk
stage1/net-plugins/net-plugins.mk

This should fix the `expr: syntax error` and useless rebuilds of network plugins.

build: Build system fixes

---

Documentation/commands.md
Documentation/subcommands/export.md
common/common.go
common/overlay/overlay.go
rkt/export.go
rkt/pods.go
stage0/run.go
tests/rkt_export_container_test.go
tests/rkt_export_fly_test.go
tests/rkt_export_test.go
tests/rkt_gc_test.go
tests/rkt_tests.go

Adds a new `export` command to rkt which generates an aci from a
pod; saving any changes made to the pod.
Usage is `rkt export POD_UUID my.aci`
This is currently restricted to only working with exited pods with a
single app.
Fixes #1197

rkt: add command to export a pod to an aci

---

Makefile.in
configure.ac
stage1/init/init.go
stage1/init/init.mk
stage1/init/kvm/hypervisor/hypervisor.go
stage1/init/kvm/hypervisor/lkvm_driver.go
stage1/init/kvm/hypervisor/none_driver.go
stage1/init/kvm/network.go
stage1/init/kvm/network_test.go

Here's the first PR in our plan to put some focus on qemu as a KVM hypervisor. Whole code is based on Michał Stachowski's (@mstachowski) work in https://github.com/coreos/rkt/pull/2592 ,and it's taken by me, due to the other activities inside our company that Michał must handle. We're also closing #2592.
This code provides a generic mechanism to use different kvm hypervisors (such as lkvm, qemu-kvm), to set it by passing proper option to ./configure (New configure option --with-stage1-kvm-hypervisor). This PR covers only implementation of KvmHypervisor type and a small refactor of kvm's part of init.go to match the new KvmHypervisor interface (lkvm is the only option that could be passed to --with-stage1-kvm-hypervisor and it's also default)
I fixed most of the review suggestions from …

KVM: Hypervisor support for KVM flavor

---

stage1/init/init.go
stage1/init/kvm.go
stage1/init/kvm/hypervisor/hypervisor.go
stage1/init/kvm/hypervisor/lkvm_driver.go
tests/rkt_journal_test.go

In nspawn flavors, nspawn creates a symlink from `/var/log/journal/${machine-id}`
to the pod's journal directory. In kvm we need to do the link ourselves.
Logs can be inspected like this:
```
$ journalctl -m _MACHINE_ID=${MACHINE_ID}
```
where MACHINE_ID is the pod UUID without the dashes.
Fixes #2798

stage1/init: link pod's journal in kvm flavor

---

configure.ac

This PR fixes a minor issue which leads to x86 builds failing.
The GOARCH environment variable should be `386` instead of `i386`.

build: fix x86 builds

---

tests/inspect/inspect.go
tests/rkt_env_test.go

This patch implements the test for https://github.com/coreos/rkt/pull/2901,
it tests that `$PATH` does not end with `\n\0` but with `\0`.
This fixes https://github.com/coreos/rkt/issues/2905
Related to https://github.com/coreos/rkt/issues/2893
This patch also introduces the `--check-path` flag in `inspect.go` to carry out the test.

functional test: check PATH variable for trailer `\n` character

---

Documentation/commands.md
Documentation/performance/README.md
Documentation/performance/rkt-1-4-0-benchmarks.md
rkt/rkt.go

Add two hidden global flags to enable profiling rkt.
Also add documentation about how to build and use the flags.

rkt: Add `--cpuprofile` `--memprofile` for profiling the rkt 

---

tests/aws.sh
tests/cloudinit/centos.cloudinit
tests/cloudinit/debian.cloudinit
tests/cloudinit/fedora-24.cloudinit
tests/cloudinit/fedora.cloudinit
tests/cloudinit/ubuntu.cloudinit
tests/test-on-several-distro.md

This changes the aws.sh script to generate AMIs with the rkt
dependencies installed so they can be used in Jenkins.
cc @albanc

functional tests: re-purpose aws.sh for generating AMIs

---

rkt/fetch.go
rkt/help.go

The 'fetch' option belongs under 'image'. I left a hidden option 'rkt fetch' to make this a non-breaking change. Note: I had trouble getting all tests to run.
Fixes #2701

Move 'fetch' option to 'image fetch'

---

stage1/init/init.go

According to machine-id(5):
machine ID is a single newline-terminated, hexadecimal, 32-character,
lowercase machine ID string.
Let's finish the file with a new line. Otherwise, systemd ~v231 will
fail.

stage1/init: fix writing of /etc/machine-id

---

rkt/cli_apps.go

We don't print them with the rkt log package, it's cobra/pflag who does
it, so the concrete error messages were missing.

rkt: don't errwrap cli_apps errors

---

tests/rkt_run_pod_manifest_test.go

The ACE spec defines limit as:
*limit*: cores that can be consumed before the kernel temporarily throttles
the process
and core as:
*core*: seconds/second that the app/pod will be able to run. e.g. 1 (or
1000m for 1000 milli-seconds) would represent full use of a single CPU
core every second.
So setting 100 would mean 100 seconds/second which doesn't make sense.
Somehow this wasn't failing until now but testing the flavor src with
the (yet to be released) systemd v231 makes it fail.

functional tests: set cpu isolator correctly

---

tests/rkt-monitor/README.md
tests/rkt-monitor/build-stresser.sh
tests/rkt-monitor/main.go
tools/cpu-stresser.mk
tools/log-stresser.mk
tools/mem-stresser.mk
tools/rkt-monitor.mk
tools/sleeper.mk

* Fix to build issue introduced with glide? (BINDIR -> TARGET_BINDIR)
* Fix to build issue with rkt v1.10
* New flag: output-dir, output CSV files will be placed there
* New flag: rkt-dir: directory with rkt binary
* New flag: stage1-path: which flavor use in tests
* CSV output filename now contains date, time and flavor
* Output file flag don't prevents printing result summary to stdout

rkt-monitor: misc fixes

---

stage1_fly/run/main.go
tests/rkt_dns_test.go

If the user specified the --dns option, a file named rkt-resolv.conf
will be created in /etc in the stage1 rootfs.
If this file is present, copy it in the app so the --dns option works
in rkt fly.
Fixes #2928

fly: copy rkt-resolv.conf in the app

---

stage1/init/init.go

If the kernel has the cgroup namespace enabled, systemd v232 will use it
by default. This was introduced by systemd/systemd#3809
and it will cause problems in rkt when cgns is enabled and cgroup-v1 is used.
For more information see systemd/systemd#3589 (comment).
This patch tells systemd-nspawn not to use cgroup namespace using
the environment variable introduced by systemd/systemd#3809.

stage1: disabling cgroup namespace in systemd-nspawn

---

store/imagestore/store.go

If the CAS database is updated and the user runs a command that opens
the store as non-root, the DB backup will fail because it requires
privileges to copy the old DB.
Moreover, this leads to a state where manual intervention is required:
```
$ sudo rkt image list
list: cannot open store: mkdir /var/lib/rkt/cas/db-backups/tmp: file
exists
```
To avoid these issues, let's give a friendly error message asking the
user to run the command as root.

store: tell the user to run as root on db update

---

glide.lock
glide.yaml
rkt/api_service.go
vendor/github.com/hashicorp/golang-lru/2q.go
vendor/github.com/hashicorp/golang-lru/LICENSE
vendor/github.com/hashicorp/golang-lru/arc.go
vendor/github.com/hashicorp/golang-lru/lru.go
vendor/github.com/hashicorp/golang-lru/simplelru/lru.go

This PR enables rkt api service to cache pod manifest so that it will not read the disk unless:
- There is a cache miss.
- The pod manifest is modified on disk.
Ref #2877

api_service: Cache pod manifest

---

glide.lock
glide.yaml
vendor/github.com/appc/docker2aci/lib/internal/backend/repository/repository2.go
vendor/github.com/appc/docker2aci/lib/version.go

Fixes a bug where the converted Image Manifest had the wrong fields.

glide: bump docker2aci to v0.12.2

---

pkg/tar/chroot.go
pkg/tar/tar.go

When a function is called by multicall, it is not possible to use errwrap
because the log pkg is not initialized yet. Also initialize the log pkg will
not show the correct indentation in the log because the new process will
start printing from the most left.
Fixes https://github.com/coreos/rkt/issues/2984

pkg/tar/chroot: avoid errwrap in function called by multicall

---

tests/rkt_api_service_bench_test.go
tests/rkt_api_service_test.go
tests/rkt_fetch_test.go
tests/rkt_fly_test.go
tests/rkt_gc_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_image_dependencies_test.go
tests/rkt_image_export_test.go
tests/rkt_image_extract_test.go
tests/rkt_image_render_test.go
tests/rkt_non_root_test.go
tests/rkt_os_arch_test.go
tests/rkt_run_pod_manifest_test.go
tests/rkt_stage1_loading_test.go
tests/rkt_tests.go
tests/rkt_volume_test.go

On eed65378a we started skipping tests that fail on remote fetch when
calling rkt run or prepare. However, we didn't do the same with the
fetching functions we run before those.
Modify those functions to return an error if the exit status is not 0
and skip the test when this happens.
On the other tests, we always fetch from local files so treat errors as
Failures.

functional tests: skip test if remote fetch fails

---

.github/ISSUE_TEMPLATE.md

Hello All,
It will be much convenient to copy output of the script
without touching of bash prompt at the last line of the
output.
Here is little example of last part of the script from the ` .github/ISSUE_TEMPLATE.md`
Before:
```
~/dev/rkt (master) $ printf "$(systemctl --version)"
systemd 229
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN~/dev/rkt (master) $ 
```
After:
```
~/dev/rkt (master) $ printf "$(systemctl --version)\n"
systemd 229
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
~/dev/rkt (master) $ 
```

issue template: Add '\n' to the end of environment output

---

Documentation/subcommands/prepare.md
rkt/prepare.go

"rkt run" supports these overrides and it is convenient
for "rkt prepare" to do the same.
Fixes #3006

rkt: add --cap-retain and --cap-remove to prepare

---

common/common.go
rkt/api_service.go
rkt/api_service_sdjournal.go

Couple of places uses the same functionality which removes empty lines from
a multiline string. This patch introduces RemoveEmptyLines() function to
achive this functionality in one place and get rid from code duplication.
Not sure that `common/common.go` is the best place for this although.

common: introduce RemoveEmptyLines()

---

rkt/image/common.go
rkt/image/fetcher.go
rkt/image/httpfetcher.go
rkt/image/namefetcher.go
tests/rkt_auth_test.go
tests/rkt_fetch_test.go

The fetchers refactor in #1763 changed some logic in handling http Cache-Control max-age. The two commits fixes some issues for httpfetcher and namefetcher and adds related functional tests.
As you can see there's a lot of duplicated code between namefetcher and httpfetcher since namefetcher once discovered the ACI URL needs to fetch them via http (at the moment the unique supported transport). The proposals in #2953 and #2964 will avoid this code duplication. 
The namefetcher commit will probably fix the problem reported in https://github.com/coreos/rkt/issues/2276#issuecomment-232428086
/cc @dgonyeo It might interest you

fetcher: httpcaching fixes

---

dist/scripts/setup-data-dir.sh

Fixes the immediate problem with `scripts/setup-data-dir.sh` being out of sync with `init/systemd/tmpfiles.d/rkt.conf`(#2862).
This doesn't include the tips mentioned by @lucab in the issue. I'm working on it. Just wanted to take a first stab to fix the problem for now while I work on the rest of the points mentioned in #2862 to make the script better and avoid duplicating the directories.

scripts: add /etc/rkt owned by group rkt-admin in setup-data-dir.sh

---

tests/rkt_fetch_test.go
tests/rkt_tests.go

Another stab at skipping remote fetches that fail.
Previously we were failing before we could check the exit status when we
expected a regexp, so we missed the chance to skip the test.
Fix that and refactor the code to a checkExitStatus() function so we
don't repeat ourselves.

functional tests: really skip failed remote fetches

---

rkt/trust.go

We should be able to pass --insecure-options=tls option to the `rkt trust`
command. But now we can't because we test insecure tls value not from
global options but from already initialized public key manager in the
metaDiscoverPubKeyLocations():
if m.InsecureSkipTLSCheck {
insecure = insecure | discovery.InsecureTLS
}
This patch adds InsecureSkipTLSCheck to the initialization of a public
key manager structure during `rkt trust` command execution. So, the
value of the `--insecure-option=tls` will be matched and used as we
suppose.

trust: provide InsecureSkipTLSCheck to pubkey manager

---

networking/podenv.go
tests/rkt_net_nspawn_test.go
tests/rkt_net_test.go

networking: apply CNI args to the default networks as well

---

Documentation/capabilities-guide.md
Documentation/subcommands/run.md
rkt/cli_apps.go
rkt/run.go
stage0/run.go
tests/rkt_caps_test.go

The error messages are user visible and a bit confusing

cli: Rename `cap-retain` and `cap-remove` to `caps-*`

---

glide.lock
glide.yaml
vendor/github.com/appc/docker2aci/lib/internal/backend/repository/repository.go
vendor/github.com/appc/docker2aci/lib/internal/backend/repository/repository2.go
vendor/github.com/appc/docker2aci/lib/version.go

Fixes bugs in layer ordering for Docker API v2.1 and v2.2.
Fixes #3025 
Fixes #3003 
Fixes #3018

glide: bump docker2aci to v0.12.3

---

rkt/image/dockerfetcher.go
rkt/image/filefetcher.go
rkt/image/httpfetcher.go
rkt/image/namefetcher.go
rkt/image_list.go
store/imagestore/aciinfo.go
store/imagestore/migrate.go
store/imagestore/migrate_test.go
store/imagestore/schema.go
store/imagestore/store.go
tests/rkt_tests.go

There're some design issues around these fields (see
https://github.com/coreos/rkt/issues/3012 for details) so let's remove
them for now.
Supersedes #3017

store/*: remove insecureoptions, and aci and sig urls

---

CHANGELOG.md
Documentation/running-fly-stage1.md
Documentation/running-lkvm-stage1.md
Documentation/subcommands/prepare.md
Documentation/subcommands/version.md
Documentation/trying-out-rkt.md
configure.ac
scripts/install-rkt.sh
tests/empty-image/manifest
tests/image/manifest
tests/rkt-monitor/build-stresser.sh
tests/rkt_exec_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go

This release introduces support for seccomp filtering via two new seccomp isolators. It also gives a boost to api-service performance by introducing manifest caching. Finally it fixes several regressions related to Docker images handling.
Closes #2981

Release 1.12.0

---

common/common.go

instead of direct coding of it.

common: use fileutil.IsExecutable()

---

Documentation/devel/stage1-implementors-guide.md
rkt/flag/secflags.go
rkt/run.go
stage0/interface.go
stage0/run.go
stage1/aci/aci-manifest.in
stage1/init/common/pod.go
stage1/init/common/pod_test.go
stage1/init/init.go
tests/rkt_caps_test.go
tests/rkt_mount_test.go
tests/rkt_paths_test.go
tests/rkt_seccomp_test.go

Add the following options: `--insecure-options={capabilities,paths,seccomp}`
* capabilities:
* remove the `CapabilityBoundingSet` option from the .service file
* call nspawn `--capability=all` so the pod will have all caps
* paths: skip options like `ReadOnlyDirectories` and InaccessibleDirectories
* seccomp: does not do anything. It will be up to @lucab's https://github.com/coreos/rkt/pull/2753 to do something with that
This also includes:
- all-fetch: for the fetch related insecure options
- all-run: for the run related insecure options
- all: for all insecure options
This is implemented using a new option `--disable-{paths,seccomp,capabilities}` in the stage1's run entrypoint.
This feature will be useful for:
- rkt in rkt https://github.com/coreos/rkt/issues/2158 (for getting access to …

rkt: implements --insecure-options={capabilities,paths,seccomp}

---

Documentation/devel/architecture.md

Document the image lifecycle phases, their logic and explain the rkt implementations.

Documentation: document image lifecycle and implementation.

---

rkt/pods.go

as Documentation/container-lifecycle.md does not exist anymore.

docs/pods: fix path of documentation in a comment

---

rkt/api_service.go
store/imagestore/store.go

Ref #2877 
Depends on #2909 and #2891 
The last 3 commits are new. Basically it adds an in-memory cache to cache image object, and reads the disk when there is a cache miss.
If the image is removed (by stating the image manifest path), return nil.

api_service: Add lru cache to cache image info

---

networking/kvm.go

We were using the chain name as comment. This can lead to confusion
and does not add much value since the chain name is partly random.

kvm: use a properly formatted comment

---

stage1/usr_from_src/usr_from_src.mk

Apparently systemd got some tools written in python, which is executed
at the build time. And python being python likes to put the compiled
bytecode of the script next to the script itself, which violates my
assumption that the srcdir should not change when we perform the build
in a different directory.
To fix this, we generate the second filelist of the srcdir after the
building of systemd finishes and generate a clean file based on the
generated filelist.

build: Fix make clean for recent systemd version in src flavor

---

configure.ac

The functional tests rely on the propagation of exit status, which was
adde on systemd v227.
cc @krnowak

configure: disable tests on host flavor with systemd <227

---

tests/rkt_socket_proxyd_test.go

This test is currently racy. The socket-activated proxyd service depends
on a rkt service being ready. However, the application that runs inside
rkt doesn't have a way to signal when it's ready because of
https://github.com/coreos/rkt/issues/1464. Instead, systemd assumes it's
ready when the container starts, which is wrong, because the application
inside might not be listening on the port yet. This makes the test fail.
It fails a lot particularly in Fedora Rawhide with the flavor host:
https://jenkins-rkt-public.prod.coreos.systems/job/rkt-master-periodic/os_type=fedora-rawhide,stage1_flavor=host/
We can re-enable it when we fix https://github.com/coreos/rkt/issues/1464.
cc @woodbor

functional tests: skip TestSocketProxyd

---

tools/depsgen/mkfile.go

The invalidation messages were printed when Makefile was parsed and we
may be interested in them only when we actually want to build the
invalidated target.

build: Stop printing irrelevant invalidation messages

---

rkt/export.go
tests/rkt_export_container_test.go
tests/rkt_export_test.go

Names are specified in a similar manner to `rkt enter`:
```
$ rkt export --help
NAME:
export - Export an app from an exited pod to an ACI file
USAGE:
rkt export [--app=APPNAME] UUID OUTPUT_ACI_FILE
DESCRIPTION:
UUID should be the uuid of an exited pod.
OPTIONS:
--app=""                  name of the app to export within the specified pod
--overwrite[=false]       overwrite output ACI
```
As with `rkt enter`, previous behaviour for single app pods is preserved. A name only needs to be specified for multi-app pods.

export: name flag for exporting multi-app pods

---

Documentation/proposals/app-level-api.md

To facilitate [kubernetes#25899](https://github.com/kubernetes/kubernetes/pull/25899), new API extensions are proposed after taking the feedback in #2867 into account.
cc @euank @yifan-gu @philips @jonboulle  @coreos/rkt-maintainers

*: expose application-level operations

---

pkg/fileutil/fileutil.go
stage1/init/common/pod.go

This is a followup to https://github.com/coreos/rkt/pull/3027 fixing some issues raised by a post-merge review.
cc @alban

stage1: followup to limit device node creation/reading/writing

---

rkt/api_service.go

The previous log information wasn't very helpful when something actually did go wrong there.
cc @yifan-gu

api_service: Improve machined call error output

---

makelib/misc.mk
stage1/find-so-deps.mk
stage1/usr_from_coreos/build-usr.mk
stage1/usr_from_kvm/kernel.mk
stage1/usr_from_kvm/lkvm.mk
stage1/usr_from_src/usr_from_src.mk

This adds two simpler-to-use functions to generate clean files, so we don't have to deal with additional stamps and cleanmk files openly.

build: Make generating clean files simpler to do

---

Documentation/app-container.md
Documentation/devel/stage1-implementors-guide.md
Documentation/subcommands/cat-manifest.md
Documentation/subcommands/image.md
Documentation/subcommands/version.md
pkg/aci/aci.go
scripts/bump-appc-spec-version
scripts/bump-release
stage1_fly/aci/aci-manifest.in
store/imagestore/store_test.go
store/treestore/tree_test.go
tests/empty-image/manifest
tests/image/manifest
tests/rkt-monitor/build-too-many-apps.sh
tests/rkt_exec_test.go
tests/rkt_fetch_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_image_dependencies_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go
tests/stub-stage1/manifest

~~It is outdated compared to the acVersion in the ACI manifest of the coreos flavor.~~
There are more places where outdated appc/spec version is used. This PR replaced all of them and adds a new script for automating it. It could be used right after vendoring in the new version of appc/spec.

*: Fix old appc/spec version in various files

---

scripts/install-rkt.sh

Ubuntu doesn't install curl by default, so this adds support for Ubuntu.

scripts: add curl as build dependency

---

Documentation/seccomp-guide.md

This commit introduces a walk-through guide for seccomp usage.
It is targeted to users, introducing them to Linux seccomp in
general, documenting the differences between the two available
isolators, and how to use them when building images, patching
images and running them.

docs: document seccomp usage

---

Documentation/trying-out-rkt.md

The tutorial doesn't make it obvious why the started pod is available
under http://172.16.28.2. This fixes it by improving the documentation.
Supersedes #3080

Documentation/trying-out-rkt: document the assigned pod IP address

---

tests/rkt_export_container_test.go
tests/rkt_export_test.go

test uses app name specification and a patched test ACI which writes a
file with different content
Fixes #3054

export: test export for multi-app pods

---

Documentation/trying-out-rkt.md

The "http://172.28.128.3" should be shown as a link, and so does
the "http://172.28.128.2".

docs: remove hyperlink from URL

---

scripts/build-rir.sh

This bumps rkt-builder version to 1.0.2, in order to work with
seccomp filtering.
For reference https://github.com/coreos/rkt-builder/commit/8af31a2a2cfc51e1f36fdae328ced035f8f84b62

scripts: bump coreos.com/rkt/builder image version

---

Documentation/devel/stage1-implementors-guide.md

This patch :
- Remove duplicate words
- Keep the format of "Entrypoints(run,enter,gc,stop)" consistent
- Fix typo

Docs: some review on stage1-implementors-guide.md

---

Documentation/subcommands/run.md

I originally just wanted to fix the `caps-retain` example typo, but there were also a few inconsistencies and Markdown formatting errors that got fixed in the process.

Clean up rkt run documentation formatting

---

stage0/arch.go
stage0/gc.go
stage0/gc_test.go
stage0/registration.go
stage0/run.go
stage0/stop.go

stage0: fix golint warnings

---

scripts/install-rkt.sh

wget is not available in minimal debian installations (e.g. docker image debian:jessie)

scripts/install-rkt: add wget as dependency

---

Documentation/devel/distribution_point.md

A Distribution Point represents the method to fetch an image starting from an
input string.
Before this concept was introduced, rkt used the ImageType concept, the
ImageType was mapped to the input image string format and internally
covered multiple concepts like distribution, transport and image type
(hidden since all are now appc ACIs).
The distribution point concept will be used as the primary information in the
different layers of rkt (fetching but also for references in a CAS/ref store).
This patch introduces the distribution point concept. See
Documentation/devel/distribution_point.md for a detailed description.

docs/dev: introduce "Distribution Point" concept

---

tests/rkt_caps_test.go
tests/rkt_paths_test.go

This is a follow-up PR with tests covering #3138. It is rebased on top of that in order to check that patch on CI. I will rebase against master once all tests are green and the other PR is merged.

tests: check for run-prepared with insecure options

---

Documentation/subcommands/prepare.md
Documentation/subcommands/run.md
common/common.go
rkt/image/fetcher.go
rkt/pods.go
rkt/prepare.go
rkt/run.go
rkt/run_prepared.go
stage0/run.go
tests/rkt_export_container_test.go
tests/rkt_export_fly_test.go
tests/rkt_gc_test.go
tests/rkt_image_dependencies_test.go
tests/rkt_image_gc_test.go
tests/rkt_image_list_test.go

Previously FSSupportsOverlay only supported detection of filesystems
(aufs, zfs).
This adds support for detection of unknown file types which prevents
overlay to function properly.
Fixes #3040
Supersedes #3052

common: fall back to non-overlay with ftype=0

---

Documentation/devel/stage1-implementors-guide.md
stage1/init/init.go

Ref #2664
This also documents the existing behavior as an optional stage1 feature/contract. Ref #3072.
The `init.go` code does not run nspawn with --register=true for kvm, but
does write a subcgroup file of that form.
This makes it a little saner, and also simplifies it down to only one
dbus call rather than calling it several times in different places.

stage1/kvm: Avoid writing misleading subcgroup

---

rkt/api_service.go
tests/rkt_api_service_test.go

Use the `subcgroup` file hint provided by some stage1s rather than
machined registration.
Fixes #3060
TODO still:
cc @yifan-gu @alban @iaguis for opinions on if this implementaiton makes sense

api_service: Rework cgroup detection

---

scripts/install-rkt.sh

When install-pak (called from install-rkt.sh) fails at some point
abort packaging.
This is based on a discussion in
https://github.com/coreos/rkt/pull/3127#discussion-diff-76763179 where
it was agreed upon that aborting on unexpected failures would be
desirable.

scripts: install-rkt.sh: fail install-pak on errors

---

stage1/init/common/pod.go

The default stdout for shutdown.service is /dev/console (the tty created
by nspawn). But that tty might be destroyed if rkt is executed via ssh
and the user terminates the ssh session. We still want shutdown.service
to succeed in that case, so don't use /dev/console.
Fixes https://github.com/coreos/rkt/issues/2232
-----
@lucab PTAL

stage1: shutdown.service: don't use /dev/console

---

stage0/run.go

This PR requires appc/spec#649 to pass TestAceValidator.
When generating the pod manifest, RuntimeApp annotations shouldn't be copied
from the image annotations but, as explained in the appc spec, they should be
merged only when required by the metadata service.

stage0: don't copy image annotations to pod manifest RuntimeApp annotations.

---

tests/rkt-monitor/README.md
tests/rkt-monitor/build-stresser.sh
tests/rkt-monitor/cpu-stresser/main.go
tests/rkt-monitor/log-stresser/main.go
tests/rkt-monitor/main.go
tests/rkt-monitor/mem-stresser/main.go
tests/rkt-monitor/sleeper/main.go

* Container start time is measured by reading output from app
* Using rkt stop instead of killing all processes
* Using rkt gc when container is in exit state
* Using milliseconds instead of nanoseconds
* Added test image name to output csv filename
* Option for build all test images by one command
* Readme updated
* Minior fixes
In the context of #3019

rkt-monitor: bunch of improvements

---

Documentation/proposals/app-level-api.md

This adds a new subcommand `app init` to create an initial empty pod.
Follows #2932

proposals/app-level-api: add rkt app sandbox subcommand

---

stage1/init/common/pod.go

... since it has no sense.
See https://github.com/coreos/rkt/issues/3106#issuecomment-244081673
Solves #3106 
cc @pskrzyns @alban @iaguis

kvm/pod: disable insecure-options=paths for kvm flavor

---

tests/rkt_volume_mount_fly_test.go
tests/rkt_volume_mount_generic_test.go
tests/rkt_volume_mount_test.go

The test `volumeMountTestCasesNonRecursive` was defined but never executed. Add it in the list of tests to execute.
Also, rename variable names: camelCase.
This is a cleanup before #3154.
-----
/cc @steveeJ @iaguis

tests: volumes: add missing test

---

common/common.go
lib/app.go
rkt/app_list.go
stage0/app.go

An ${app}-created file will be created under /rkt/status/ when the app is added.
An ${app}-started file will be created under /rkt/status/ when the app is started.
Also a little bit refactoring.
cc @iaguis @s-urbaniak

CRI: Created ${app}-created, ${app-started} file for recording timestamps

---

Documentation/devel/architecture.md
stage1/init/common/units.go
tests/rkt_volume_mount_fly_test.go
tests/rkt_volume_mount_generic_test.go
tests/rkt_volume_mount_test.go

The conflict in the cri branch was caused by:
- master: changes in appToSystemd() via https://github.com/coreos/rkt/pull/3155
- cri: moving appToSystemd() to stage1/init/common/units.go: UnitWriter.AppUnit()
I resolved it by applying the change in the UnitWriter.AppUnit() and getting the 'flavor' again.
-----
/cc @jjlakis @yifan-gu @s-urbaniak @iaguis

Merge new master into cri

---

Documentation/devel/stage1-implementors-guide.md
stage1/app-rm/app-rm.go
stage1/app-stop/app-stop.go

While starting to document the stage1 new entrypoints "stop" and "rm", I noticed they don't use the pod uuid. We still pass the uuid as parameter for consistency and to allow future extension. However, I removed the dead code.
---
/cc @iaguis @s-urbaniak

cri: add stage API documentation

---

rkt/app_exec.go

This is essentially same as `rkt enter`. This is proposed in the original proposal https://github.com/coreos/rkt/blob/master/Documentation/proposals/app-level-api.md#rkt-app-exec , but I am ok either way whether we want this or not.
cc @iaguis @s-urbaniak

CRI: Add 'rkt app exec', which calls 'rkt enter'.

---

rkt/list.go

Since the pod manifest variable is changed to a pointer, it is possible that it can be nil.
Ref https://github.com/coreos/rkt/pull/3164

cri: Fix a nil pointer dereference in list.go

---

stage1/stdlibdirs.mk

In the src flavor, we have some code to copy missing libraries from the
host to stage1 if they're not already present after building systemd.
In systemd v231, libshared was converted into a private shared library
living in `/usr/lib/systemd` (systemd/systemd#3516).
However, the logic that detects if a library is present or not was not
taking into account `$ROOTFS/usr/lib/systemd`, only `$ROOTFS/usr/lib`.
So the host's library overwrote the `libsystemd-shared-231.so` generated
by the systemd build, causing general madness.
Add the systemd directory to the list of paths to check.

build,stage1: include systemd dir when checking libs

---

Documentation/subcommands/api-service.md

This is breaking links on the website, and this way every time we sync we won't have to remember to fix this for the latest version. We only sync the Documentation folder, so linking to things outside of it breaks.

docs: use absolute url in api-service doc

---

Documentation/capabilities-guide.md
Documentation/subcommands/prepare.md

Partially fixes #3179 (the documentation part)

Documentation/capabilities-guide: remove --cap-retain/remove mentions

---

Documentation/devel/release.md
scripts/build-rir.sh
scripts/pkg/after-install
scripts/pkg/after-remove
scripts/pkg/before-install
scripts/pkg/before-remove
scripts/pkg/build-pkgs.sh

Add a simple script to build .deb and .rpm packages. This is not a substitute for a proper distro-maintained package.
This depends on coreos/rkt-builder#3

build: build simple .deb and .rpm packages

---

rkt/fetch_test.go
rkt/image/common.go
store/imagestore/remote.go
store/imagestore/remote_test.go
store/imagestore/store.go
store/imagestore/store_test.go

Removes the 2nd argument signalling whether the remote is found or not
and returns a distinct error instead.
cc @lucab @sgotti

store: refactor GetRemote

---

lib/app.go

This makes the convertion to the container status defined in CRI
easier.

CRI: Change exit code's type to int32.

---

Documentation/distributions.md

The documentation was unclear as to where to get the `install-rkt.sh`
script. This makes it clear, and also describes how to install without
having to clone the entire rkt repo

Documentation: update Ubuntu installation

---

stage1/stage1.mk

Fixing problem with dependencies for parallel making two kvm images, found by @mzylowski on 40 cores environment.
ACTOOL was called before before all common files was copied to hypervisor-specific directories. So, it's simply adding STAGE1_COPY_IMAGE_FILES dependency for STAGE1_ACI_IMAGE rule if STAGE1_COPY_IMAGE_FILES exists. + removing redundant new-line signs.
cc @coreos/rkt-kvm-maintainers

makefile/kvm: add dependency for copied files

---

Documentation/using-rkt-with-systemd.md
stage1/init/common/pod.go
stage1/init/init.go
stage1/prepare-app/prepare-app.c
tests/image/manifest

After this patch, systemd on the host marks the container as "active"
when the init systemd in the container sends the ready message
instead of doing it after the container is created.
After this patch rkt sets --notify-ready=yes on systemd-nspawn.
Also appc/spec in godeps is patched to expose `SupportsNotify`.
Fixes: https://github.com/coreos/rkt/issues/1464
Warning:
If the application launched by rkt does not notify (with sd_notify())
that it is ready, then the application may be killed after a timeout.
Note: Requires systemd v231 in stage1, so this commit must not be merged before.

stage1: Implemented notifications from the app in the container to the host

---

rkt/stop.go

The loop should continue if there's an error in retrieving the pod.
The bug also appears in master, however it's slightly different, because in master, the uuid is tested before passing it to getPod(). but still, there could be race that causes getPod() to fail.
This fixes a panic caused by this when removing a non-existed pod.
```
$ sudo rkt stop dc688be9-7c79-11e6-97ff-28d244b00276
stop: cannot get pod: no matches found for "dc688be9-7c79-11e6-97ff-28d244b00276"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x49 pc=0x5b36f7]
goroutine 1 [running, locked to thread]:
panic(0xe2db40, 0xc820010120)
/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/coreos/rkt/pkg/pod.(*Pod).State(0x0, 0xf71ae0, 0xe) …
```

stop.go: Should continue when it fails to read the pod.

---

lib/app.go
lib/types.go
rkt/list.go

With json format, the parsing on the result is much easier and
consitent.
The json format is defined in coreos/rkt/lib/types.go.

CRI: Add json, json-pretty format to the output of 'rkt list'.

---

Documentation/using-rkt-with-systemd.md

`daemon.SdNotify` returns 2 variables.

doc/using-rkt-with-systemd: fix the go app example

---

rkt/app_stop.go
rkt/stop.go

Since 'rkt stop' is idempotent, 'rkt stop' on an already stopped
pod should not return error.
cc @s-urbaniak @lucab @iaguis @alban

stop: Don't treat 'rkt stop already-stopped-pods' as errors.

---

rkt/app_rm.go
stage0/app.go

When the pod is stopped, don't call app-add/app-rm entrypoint
because there is not much we can/need to do when the whole pod
is stopped.
Fix #3221 .
This is one approach of fixing it , the other way is to pass the -1 pid to the entrypoints, and make a contract saying `if the pid is negative, then it means the pod is not running`.
I am ok with both. cc @iaguis @lucab @s-urbaniak

Allow `rkt app rm` on a stopped pod.

---

common/cgroup/cgroup.go
common/cgroup/cgroup_test.go
rkt/api_service.go
stage1/gc/gc.go
stage1/init/init.go
tests/inspect/inspect.go
tests/rkt_app_isolator_test.go
tests/rkt_run_pod_manifest_test.go

This implements support for cgroups v2 along support for legacy version.
I took #2785 and fixed the conflicts.
Half of #1757
Based on work from: Michał Świętek <michalswietek88@gmail.com>
------
/cc @mike1729 @lucab

rkt: support for unified cgroups (cgroup2)

---

common/cgroup/cgroup.go
rkt/app_add.go
stage0/app.go
stage1/app-start/app-start.go
stage1/init/init.go
stage1/usr_from_coreos/manifest-amd64-usr.d/systemd.manifest
stage1/usr_from_coreos/manifest-arm64-usr.d/systemd.manifest
stage1/usr_from_src/mount.mk
stage1/usr_from_src/usr_from_src.mk

Adding the following flags in `rkt app add`: `--memory`, `--cpu`, `--caps-retain`, `--caps-remove`, `--seccomp`. Instead of adding the flags manually, the code for `rkt app add` and `rkt run` is factorised. Thanks to @krnowak for the patches. See also https://github.com/coreos/rkt/pull/3205#issuecomment-247551585
`--memory` and `--cpu` successfully update the manifest with the isolator. However, they are not enforced yet. I will need further work in another PR. The reason for that is that the cgroup filesystem for the memory & cpu controller are generally mounted read-only and rkt mount some files specific to the application in read-write mode. But at the time the pod is created (`rkt app sandbox`), the list of  applications is not known yet, so the mounts in read-write mode for the …

CRI: Add app params to "rkt app add"

---

common/networking/doc.go
common/networking/ports.go
networking/kvm.go
networking/networking.go
networking/portfwd.go
rkt/app_sandbox.go
rkt/run.go
stage0/run.go
stage1/init/init.go
tests/rkt_net_nspawn_test.go
tests/rkt_net_test.go

Allow the app sandbox to set up port forwarding without actually having any apps.
This also adds the ability to forward from a specific IP in `rkt run`, since we had to implement this anyway.

app sandbox port forwarding

---

stage1/init/init.go

As agreed on Rkt sync. All implemented cri features works well for kvm, and we plan to be on track with cri for kvm.

kvm/init: remove condition for kvm mutable pods

---

common/common.go
stage0/app.go
stage1/app-stop/app-stop.go
tests/rkt_tests.go

If we try to stop an app that doesn't have a service file (either
because it was not started or because the starting failed) we should
give an appropriate error message.
Also, since `app rm` calls the stop entrypoint, we should identify this
error and continue removing the app.

stage0,stage1: handle exit status from stop entrypoint

---

Documentation/subcommands/prepare.md
Documentation/subcommands/run.md
common/apps/apps.go
lib/app.go
lib/pod.go
lib/types.go
rkt/app_add.go
rkt/app_sandbox.go
rkt/app_status.go
rkt/cli_apps.go
rkt/prepare.go
rkt/run.go
stage0/app.go
stage0/run.go

Also removed unneccessary flag conflict checks for --pod-manifest
v.s. other flags (--name, --environment, etc) because they are already
taken care of since they all need to follow an image.
Address https://github.com/coreos/rkt/pull/3205#issuecomment-248854097
So after this gets merged, we can do:
```shell
$ sudo rkt run sha512-70971ee35fce --name=nginx1 --exec=/bin/sleep -- 1000 --- sha512-70971ee35fce --name=nginx2 --exec=/bin/sleep -- 1000 ---
image: using image from file /home/yifan/gopher/src/github.com/coreos/rkt/build-rkt-1.15.0+git/target/bin/stage1-coreos.aci
image: using image from the store with hash sha512-70971ee35fcea3b260eed30840b6d4cf3e589f21c8eaaa52dfe672724a784eb9
image: using image from the store with hash sha512-70971ee35fcea3b260eed30840b6d4cf3e589f21c8eaaa52dfe672724 …
```

run/prepare: Support mutating the app for 'rkt run/prepare' as well.

---

Documentation/devel/stage1-implementors-guide.md
rkt/app_add.go
rkt/app_start.go
stage0/app.go
stage0/manifest.go
stage0/run.go
stage1/aci/aci-manifest.in
stage1/app-add/app-add.go
stage1/app-add/app-add.mk
stage1/app-start/app-start.go
stage1/secondary-stuff.mk

Currently we set up the app's service during app-start which is not the
right place.
This implements the proper logic to set up systemd service files, as
well as any remounts of cgroups during app-add.

app-start: set up unit files/cgroups during app-add

---

CHANGELOG.md
Documentation/running-fly-stage1.md
Documentation/running-kvm-stage1.md
Documentation/subcommands/prepare.md
Documentation/subcommands/version.md
Documentation/trying-out-rkt.md
ROADMAP.md
configure.ac
scripts/install-rkt.sh
tests/empty-image/manifest
tests/image/manifest
tests/rkt-monitor/build-stresser.sh
tests/rkt_exec_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go

Release PR for rkt 1.16.0. This also re-introduces a minimal `ROADMAP.md`, just pointing to projects and milestones in GH and providing a month-scoped timeline.
Closes https://github.com/coreos/rkt/issues/3152
Closes https://github.com/coreos/rkt/issues/3206
Closes https://github.com/coreos/rkt/issues/3246

rkt 1.16.0

---

MAINTAINERS

Tamer is no longer with CoreOS or actively working on the project; fix
Alban/Iago's emails to refer to their Kinvolk addresses.

MAINTAINERS: update emails, remove Tamer, add Casey

---

Documentation/distributions.md

The CentOS community build for rkt is not ready due to pending systemd
upgrade issues. The docs should reflect this.

Docs: edited Documentation/distributions.md#centos

---

stage0/run.go
tests/inspect/inspect.go
tests/rkt_mtab_test.go

Several Linux tools expect this to exist, but several images do not
include it. This creates it when it does not exist.
Fixes #3264

stage0: Create an mtab symlink if not present

---

common/apps/apps.go
glide.lock
glide.yaml
rkt/app_add.go
rkt/cli_apps.go
stage0/app.go
stage1/app-add/app-add.go
stage1/init/common/mount.go
stage1/init/common/mount_test.go
stage1/init/common/pod.go
stage1/init/common/units.go
stage1/init/init.go
stage1/init/kvm.go
tests/rkt_volume_mount_test.go
tests/rkt_volume_test.go
vendor/github.com/kr/pretty/License
vendor/github.com/kr/pretty/diff.go
vendor/github.com/kr/pretty/formatter.go
vendor/github.com/kr/pretty/pretty.go
vendor/github.com/kr/pretty/zero.go
vendor/github.com/kr/text/License
vendor/github.com/kr/text/doc.go
vendor/github.com/kr/text/indent.go
vendor/github.com/kr/text/wrap.go

This subsumes #3239, adding the ability to add a per-app mount + volume at `app add` time. It also cleans up and centralizes the MountPoint -> Mount -> Volume matching logic, including some unit tests, yay.
Fortunately, the required systemd changes are in the current CoreOS alpha build.
Fixes #3195.

CRI: Support volume creation at app add time

---

stage1/init/common/pod.go
stage1/init/common/units.go
tests/rkt_paths_test.go

systemd recently introduced additional protections for procfs and sysfs paths,
available via `InacessiblePaths=` (in v231) and `ProtectKernelTunables=` (in v232)
properties.
This align rkt on it for improved procfs/sysfs limits.
Closes #2484

stage1: use systemd protection for kernel tunables

---

stage1/init/common/seccomp.go
stage1/init/common/units.go

This commit workarounds a systemd bug, which causes unit file
to be incorrectly parsed.
This is triggered by property lines longer than `LINE_MAX` (2048),
which frequently occur when passing a large set of values (eg. seccomp
and paths).
In this case, we will now split such values across multiple lines.
Reference https://github.com/systemd/systemd/issues/3302
Closes https://github.com/coreos/rkt/issues/3159

stage1: break down overlong property lines

---

common/cgroup/cgroup.go
common/cgroup/v1/cgroup.go
common/cgroup/v1/cgroup_test.go
common/cgroup/v2/cgroup.go
rkt/api_service.go
stage1/gc/gc.go
stage1/init/common/units.go
stage1/init/init.go
tests/inspect/inspect.go

Currently we have func .*V[1|2].* named function names in the cgroup
package.
This factors those functions into two separate packages cgroup/v1, and
cgroup/v2.
This is a prerequisite for #3242

cgroup: introduce proper cgroup/v1, cgroup/v2 packages

---

rkt/image/resumablesession.go

If InsecureSkipVerify is set to true, we skip setting the Proxy argument
in http.Transport. This fixes it.
Fixes #2590

stage0/image: set proxy if InsecureSkipVerify is set

---

MAINTAINERS

As you can see on issue tracker - I have too little time to maintain kvm component and even recently in review (https://github.com/coreos/rkt/pull/3304#discussion_r84576995) I missed quite important thing.
This is why I think that I should be no longer maintainer or this component.
I wanted to suggest someone from my old Intel team, but IMO this could be at first discussed on syncup, so I'm leaving that part without any suggestion.

MAINTAINERS: remove @jellonek

---

networking/networking.go
networking/podenv.go
rkt/image/common.go
rkt/image/dockerfetcher.go
rkt/image/fetcher.go
rkt/image/finder.go
rkt/image/httpfetcher.go
rkt/image/httpops.go
rkt/image/namefetcher.go
rkt/stage1hash.go
stage1_fly/run/main.go
tests/rkt_fetch_test.go
tests/rkt_gc_test.go
tests/rkt_tests.go

This PR turns off by default all image and networking diagnostic output, moving it behind explicit `--debug` flag. This turns an error-free rkt execution from this:
```
$ sudo rkt run quay.io/coreos/alpine-sh --exec echo -- "hello world!"
image: using image from local store for image name coreos.com/rkt/stage1-coreos:1.17.0
image: using image from local store for image name quay.io/coreos/alpine-sh
networking: loading networks from /etc/rkt/net.d
networking: loading network default with type ptp
[18489.453547] alpine-sh[5]: hello world!
```
into this:
```
$ sudo ./rkt run  quay.io/coreos/alpine-sh --exec echo -- "hello world!"
[18521.078185] alpine-sh[5]: hello world!
```
This makes rkt strictly following the UNIX rule of silence, but in the long term we need a better way of handling …

rkt: gate diagnostic output behind `--debug`

---

scripts/glide-update.sh
vendor/github.com/cznic/ql/vendored/github.com/camlistore/LICENSE

With the latest version of `glide` and `glide-vc`, running the `glide-update` script resulted in an unbuildable tree because `glide-vc` deleted too much stuff (such as actool).
Adding the `--use-lock-file` flag made it work correctly on my machine (only picking up one new file, included as well).
cc @sgotti

scripts: update glide vendor script

---

Documentation/running-docker-images.md

docker2aci is not critical to this user facing doc, just remove it.

Documentation: remove docker2aci mention

---

stage0/arch.go

After rkt's dependencies implementing ppc64le code, it is now time
to enable it on rkt.
With this patch, and upgrading rkt's dependencies (gopsutils, appc),
I am able to run a container image on rkt on Power processors.

stage0/arch: initial support for ppc64le platform

---

Documentation/networking/overview.md

Make it explicit that the DHCP daemon being referred to is the one
that's part of the special CNI DHCP plugin.

docs/networking: minor clarification to DHCP type

---

dist/scripts/setup-data-dir.sh

This is a follow-up for 65fc1fb935acda
Fixes:
```
$ sudo bash -x rkt-v1.18.0/scripts/setup-data-dir.sh
...
+ systemd-tmpfiles --create /usr/lib/tmpfiles.d/rkt.conf
Failed to open '/usr/lib/tmpfiles.d/rkt.conf', ignoring: No such file or directory
$ echo $?
1
```

setup-data-dir.sh: fallback to the `mkdir/chmod`s if the rkt.conf doesn't exist

---

scripts/install-deps-debian-sid.sh

This is required for the default build and is
included in the Fedora ones.

scripts: add gpg to Debian dependencies

---

tests/rkt_paths_test.go

All other tests use `--debug`
And this is very helpful: https://github.com/systemd/systemd/pull/4533#issuecomment-258327773
This is a follow-up for 102e05de679f10

tests: add the --debug option

---

networking/networking.go
networking/podenv.go
stage1/gc/gc.go

- Don't fail to gc if subcgroup doesn't exist (fixes #2804)
- Don't leak network namespaces (fixes #3114)
The biggest change is a minor cleanup of the netns creation code. Previously, we checkpointed its name only after successful network creation. Now we write as soon as the NS is generated.

gc: Clean up some GC leaks

---

common/cgroup/v1/cgroup.go

Currently mount flags are lost when remounting a mountpoint read-only.
This changes it such that mountFsRO takes a flags parameter, and adds
MS_BIND, MS_REMOUNT, MS_RDONLY.
Fixes #3286

cgroup/v1: introduce mount flags to mountFsRO

---

rkt/app_add.go
rkt/app_rm.go
rkt/app_start.go
rkt/app_stop.go

Minor rewording after CRI merge, cleaning up "appz" occurrences.

stage0: minor wording fixes

---

stage1/init/common/seccomp.go
stage1/init/common/units.go
tests/rkt_ace_validator_test.go

This PR removes `MountFlags` property from stage2 apps in pods
running with `--insecure-options=paths`.
This will leave the service without any properties with a mount-ns
requirement, so that stage2 rootfs can be nicely degraded to a chroot
with full mount propagation.
Fixes: https://github.com/coreos/rkt/issues/3272

stage1/init: leave privileged pods without stage2 mount-ns

---

stage1/usr_from_kvm/kernel/patches/0002-for-debian-gcc.patch
stage1/usr_from_kvm/lkvm.mk

With change introduced to Debian Sid default gcc flags: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841368 both lkvm and linux kernel wouldn't compile, here is fix for this.
Fixes #3343

kvm: fix for breaking change in Debian Sid GCC default options

---

Documentation/devel/stage1-implementors-guide.md
networking/net_plugin.go
networking/networking.go
rkt/gc.go
stage0/gc.go
stage0/manifest.go
stage1/aci/aci-manifest.in
stage1/gc/gc.go
stage1/net/rootfs/etc/rkt/net.d/99-default-restricted.conf
stage1/net/rootfs/etc/rkt/net.d/99-default.conf
stage1_fly/aci/aci-manifest.in
stage1_fly/gc/main.go
tests/rkt_net_test.go

We were not passing the --local-config flag through during gc.
Also passes the right CNI_VERSION environment variable.
Fixes #3133

gc: make sure CNI_PATH is same for gc and init

---

rkt/image_list.go
tests/rkt_image_list_test.go

This fixes a regression introduced in https://github.com/coreos/rkt/pull/3334,
where the `--field` flag is not anymore working for plaintext output.
Tests around image listing are also introduced here to catch future regressions.
Fixes https://github.com/coreos/rkt/issues/3359

image/list: bring back field filtering in plaintext mode

---

Documentation/subcommands/image.md
rkt/image.go
rkt/image_cat_manifest.go
rkt/image_export.go
rkt/image_extract.go
rkt/image_render.go
rkt/image_rm.go
tests/rkt_image_rm_test.go

Currently the `rkt image rm` subcommand has a custom logic for selecting
images to be deleted.
This aligns the behavior of the `rm` subcommand with the other `rkt
image` subcommands, and updates the documentation.
Fixes #3329

rkt/image*: align image selection behavior for the rm subcommand

---

CHANGELOG.md
Documentation/distributions.md
Documentation/running-fly-stage1.md
Documentation/running-kvm-stage1.md
Documentation/subcommands/prepare.md
Documentation/subcommands/version.md
Documentation/trying-out-rkt.md
ROADMAP.md
configure.ac
scripts/install-rkt.sh
tests/empty-image/manifest
tests/image/manifest
tests/rkt-monitor/build-stresser.sh
tests/rkt_exec_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go

This release contains multiple changes to rkt core, bringing it more in line with the new Container Runtime Interface (CRI) from Kubernetes.
A new experimental `app` subcommand has been introduced, which allows creating a "pod sandbox" and dynamically mutating it at runtime. This feature is not yet completely stabilized, and is currently gated behind an experimental flag.

release: rkt 1.19.0

---

rkt/run.go
tests/rkt_run_pod_manifest_test.go

@s-urbaniak PTAL
When using --pod-manifest we need to make sure that the pod manifest
contains at least one defined app.
Fixes: #3338

rkt/run: validates pod manifest to make sure it contains at least one app.

---

Documentation/devel/release.md

This covers copying package files where signing and uploading steps expect them to be.
/cc @squeed

docs: fix release steps

---

glide.lock
glide.yaml
stage1/init/common/units.go

the `third_party/reflect` package is gone from upstream, and it should be gone from our codebase too.
Alternately, we can copy over one const and not have to depend on K8s at all, which seems pretty sane to me, and I'd be happy to PR that instead.

vendor: Update k8s dependency

---

Documentation/distributions.md

As the systemd-sysuser bug[1] is now solved i removed the lines that referenced it from the documentation 
[1] https://github.com/coreos/rkt/issues/2571#issuecomment-260627481

docs: removed a passage from Debian section about a bug now solved

---

ROADMAP.md

This commit updates the roadmap with more references and details related
to current appc->oci projects.

docs: update roadmap with appc->oci projects

---

rkt/image/asc.go
rkt/image/common.go
rkt/image/common_test.go
rkt/image/downloader.go
rkt/image/filefetcher.go
rkt/image/httpfetcher.go
rkt/image/httpops.go
rkt/image/io.go
rkt/image/namefetcher.go

This PR implements the NopCloser()-like function NopReadSeekCloser() and some other cleanups related to the removing of isReallyNil().
Fixes #2922
Supersedes #3120

remove isReallyNil()

---

tests/build-and-run-tests.sh

This script had the parameter handling in the case statement, but not in
usage, and getopts.

tests/build-and-run-test.sh: fix systemd revision parameter

---

stage1/usr_from_coreos/coreos-common.mk
stage1/usr_from_coreos/manifest-amd64-usr.d/systemd.manifest
stage1/usr_from_coreos/manifest-arm64-usr.d/systemd.manifest

Update stage1 base image to coreos-alpha 1235.0.0. This is a pre-requisite for https://github.com/coreos/rkt/issues/1799 and supersedes https://github.com/coreos/rkt/pull/3219.

stage1: update coreos base to alpha 1235.0.0

---

lib/types.go
rkt/image_list.go

This allows external consumers to just directly unmarshal json into this
exported type.
I modified the types of some of its values for consistency with other
exported types as well. This is unfortunately backwards incompatible.

image: export `ImageListEntry` type for image list

---

tests/rkt_no_new_privs_test.go
tests/rkt_paths_test.go

systemd v232 gained some protection features both at nspawn and exec level, changing some behavior used while testing rkt insecure mode.
This PR adjusts the NoNewPrivileges check and temporarily disable the sysrq-trigger one.
Closes https://github.com/coreos/rkt/issues/3367

tests: adjust security tests for systemd v232

---

pkg/pod/pods.go
pkg/pod/pods_test.go

I think this is more readable.
This is just a refactor, as well as adding a few tests so the refactor was more likely to be correct.

pkg/pod: flatten the pod state if-ladders

---

lib/pod.go
pkg/pod/pods.go
rkt/app_status.go
rkt/list.go
rkt/status.go

This change reuses the `image list` flag parsing for `list`.
It also makes `list` and `list --format=json` have more similar behavior
in when the pod manifest is skipped.
Fixes #3402 
I'd also like to add more tests since I wouldn't be surprised if the coverage is a bit low here.

stage0: improve list --format behavior and flags

---

pkg/mountinfo/mountinfo.go
pkg/mountinfo/mountinfo_test.go
pkg/mountinfo/types.go
rkt/export.go
stage0/gc.go
stage1/init/kvm.go
stage1_fly/gc/main.go
stage1_fly/run/main.go

This PR deduplicates and moves all our `/proc/<pid>/mountinfo` parsing logic to its own package.
It will be later needed for https://github.com/coreos/rkt/issues/3411.

pkg/mountinfo: move mountinfo parser to its own package

---

makelib/git.mk
stage1/init/common/pod.go
tests/image/manifest

This PR fixes several systemd-related issues:
* Fix v232 breakage, deferring `ProtectKernelTunables` after https://github.com/systemd/systemd/issues/4567 (ie. post v233)
* Print out which commit is being used for src flavor, as requested at https://github.com/systemd/systemd/issues/4752#issuecomment-263160490
* Adjust rkt-inspect manifest to not lie about supports-systemd-notify status, as it causes some regressions in master, as reported at https://github.com/systemd/systemd/issues/4752#issuecomment-263179016
/cc @evverx @s-urbaniak

rkt: misc systemd-related fixes

---

stage1/app-rm/app-rm.go
tests/rkt_app_sandbox_test.go

Part of https://github.com/coreos/rkt/issues/3349

tests: add smoke test for app sandbox

---

tests/rkt_net_test.go
tests/rkt_stop_test.go
tests/rkt_tests.go

This PR tentatively fixes the following flakes:
* multiple jenkins-master failures, possibly due to debug output leading to a children blocked on write()
* kvm stop failures, possibly due to a too short timeout (or https://github.com/coreos/rkt/issues/3382, to be determined)

tests: tentative fixes for sporadic host and kvm failures

---

common/common.go
lib/app.go
pkg/pod/pods.go
stage0/run.go
tests/rkt_api_service_test.go

Prior to this change, the mtime of the 'pod' file is used for the created
timestamp.
This is inaccurate in the case of CRI where the pod manifest is changed
with each app added.
To resolve that problem, a new file is introduced which is not touched
by the app add codepath.

cri: correct 'created' timestamp

---

stage1_fly/stage1_fly.mk

We got this failure randomly, and the lack of an explicit dependency on the directory is suspect.
[amd64-usr] build: Unable to open target /build/amd64-usr/var/tmp/portage/app-emulation/rkt-1.20.0/work/rkt-1.20.0/build-rkt-1.20.0/target/bin/stage1-fly.aci: open /build/amd64-usr/var/tmp/portage/app-emulation/rkt-1.20.0/work/rkt-1.20.0/build-rkt-1.20.0/target/bin/stage1-fly.aci: no such file or directory
I built the package a few dozen times with varying parallel jobs and with this change applied, and there were no failues.

fly: ensure the target bin directory exists before building

---

Documentation/proposals/oci.md
README.md

This adds an OCI roadmap document to outline a general plan towards OCI referencing existing work.

Documentation/proposals: add OCI Image Format roadmap

---

stage1/net/rootfs/etc/rkt/net.d/99-default-restricted.conf
tests/rkt_net_test.go

There was a collision between `default` and `default-restricted`.
Also fixes some silly issues with the network test that led to IP leaks.
Fixes #3438 
Fixes #2943

Change the subnet for the default-restricted network 

---

stage1/init/init.go
stage1/usr_from_host/usr_from_host.mk
stage1/usr_from_src/usr_from_src.mk

`TestAppSandboxSmoke` is currently failing on host and src flavors because:
* stage1-host is missing a `/bin` directory
* stage1-host doesn't install systemd-tmpfiles from host
* stage1-src is built without systemd-tmpfiles
This should fix testsuite failures on those flavors.

stage1: ensure systemd-tmpfiles is available in pod

---

tests/rkt_app_sandbox_test.go
tests/rkt_etc_hosts_test.go
tests/rkt_fetch_test.go
tests/rkt_image_gc_test.go
tests/rkt_stop_test.go
tests/rkt_userns_test.go

gexpect `Wait()` may let the child deadlock, blocked on a write. This replace some potentially dangerous occurrences with a `waitOrFail()` which drains child output.
Reference https://github.com/coreos/rkt/pull/3434
Fixes https://github.com/coreos/rkt/pull/3439#issuecomment-264538581

tests: fix some potential gexpect hangs

---

stage0/app.go
stage1/app-add/app-add.go
stage1/common/types/pod.go
stage1/init/common/pod.go
stage1/init/common/pod_test.go
stage1/init/common/units.go
stage1/init/init.go
stage1/init/kvm.go
stage1_fly/run/main.go

This stores runtime parameters such as insecure options and the MDS
token to disk in the stage1. These are provided during init, but are
necessary during app add. This also simplifies the signature of some of
the stage1 methods.

stage1: persist runtime parameters

---

Documentation/distributions.md

Fedora's SELinux policies currently are broken. I currently don't have the time to look in to why. I'm just correcting the documentation.

docs: update SELinux info for Fedora

---

tests/rkt_export_container_test.go
tests/rkt_export_fly_test.go
tests/rkt_export_test.go
tests/rkt_flavor_coreos.go
tests/rkt_flavor_fly.go
tests/rkt_flavor_host.go
tests/rkt_flavor_kvm.go
tests/rkt_flavor_src.go
tests/rkt_tests.go

This testcase didn't work for kvm with kernels with overlayfs.

tests: fix TestExport for the KVM+overlay case

---

stage1/common/types/pod.go
stage1/init/init.go
stage1_fly/run/main.go

This adds the debug mode to the persisted runtime-pod, in order to be later re-used when setting debug mode for pod sidecars (eg. iottymux).

stage1: persist debug mode to runtime-pod

---

lib/app.go
stage1/init/common/mount.go
stage1/init/common/pod.go
stage1/init/kvm.go

stage1: app add, status didn't work with empty vols

---

tests/inspect/inspect.go

This commit reorders blocking operations, so that sleeps are performed
as first/last operations and reading stdin will block before performing
any other task.
It makes multi-step tests easier to write and without races.

tests/inspect: reorder blocking operations

---

stage1/net/rootfs/etc/rkt/net.d/99-default-restricted.conf
tests/rkt_net_test.go

Because the default-restricted network is almost always created, this limits the number of pods per machine to 253 right now. This should be made much larger.

net: increase the default-restricted subnet to a /16

---

glide.lock
glide.yaml
vendor/github.com/coreos/gexpect/gexpect.go

This changes Expect() to not return early errors
on final reads (EOF but n != 0) in order to avoid discarding
the last bytes from the source buffer. According to Reader interface
next loop iteration will get a (0, EOF) causing this method to
return.
Supersedes https://github.com/coreos/rkt/pull/3442

vendor: bump gexpect to 0.1.1

---

common/common.go
stage1/app-add/app-add.go
stage1/init/common/mount.go
stage1/init/common/pod.go
stage1/init/kvm.go

Before this change, the `copy-up` operation could fail with:
`stage1: could not prepare mountpoint: mkdir sharedVolumes/foo: no such file or directory`
This would occur because `CopyTree` does not implicitly create the
target directory, so we must create it prior to calling.
cc @squeed 
TODO:

mount: ensure empty volume paths exist for copy-up

---

stage1/usr_from_kvm/qemu.mk

QEMU would always be configured and built for every make. Fix this to reduce the development cycle.
This fix is also desirable for a follow on patchset that adds the ability in the QEMU Makefile to apply patches to QEMU before building.

stage1/kvm: Improve QEMU Makefile rules

---

Documentation/subcommands/status.md
lib/app.go
pkg/pod/pods.go
pkg/pod/sandbox.go
pkg/pod/wait.go
pkg/pod/wait_test.go
rkt/api_service.go
rkt/app_stop.go
rkt/status.go
rkt/stop.go
stage0/app.go
tests/rkt_app_sandbox_test.go
tests/rkt_tests.go

This adds a WaitReady method to be able to wait for pod readiness on the
command line.
It also reduces reduntant implementations in stage1 for checking mutable pods
and pod manifest update logic.
Fixes #3461

pkg/pod: add WaitReady, dry Sandbox methods

---

Documentation/commands.md

Since release 3.1.0-rc1, etcd can be forced to print logs to stdout
even if journals is available. This updates the workaround in our docs.
Reference https://github.com/coreos/etcd/pull/6799
Fixes https://github.com/coreos/rkt/issues/3394

docs: update etcd logging details

---

README.md

Emphasise pod-native, remove some older and less relevant material.

README: wording updates

---

Documentation/hacking.md

Hello!
As mentioned in #3499 `go get` is not required anymore.

docs: delete unnecessary go get

---

rkt/cat_manifest.go
tests/rkt_cat_manifest_test.go

So we will be able to use the value saved on rkt run with --uuid-file-save.

rkt/cat-manifest: add support for --uuid-file

---

stage1/init/init.go

When starting the container, we try and determine our subcgroup. On systems without systemd, this didn't work. So, fall back to the cpu cgroup as needed.
Fixes #3502

stage1: don't crash when systemd cgroup doesn't exist

---

pkg/pod/uuid.go

Functionality didn't change, just cleanup

pkg/pod: use IncludeMostDirs bitmask instead of constructing it

---

common/mount.go
rkt/gc.go
rkt/rm.go
stage0/gc.go
tests/rkt_gc_test.go

This fixes multiple issues in pods GC. In particular, rkt now tries
harder to clean its environment by:
* looping over all pods, even if one of them is faulty (eg. some files are busy or missing)
* leaving manifest removal as last step, so next GC run may succeed
* chroot-ing to pod before cleaning, to avoid chasing wrong symlinks (eg. ending outside of pod)
* chdir-ing to (host) root, to avoid keeping directories busy
* loop-unmounting all mountpoints, as single unmount operations may fail (eg. busy mountpoint)
* detecting busy mounts, and marking them as detached for lazy unmount (ie. `MNT_DETACH`)

gc: fix cleaning mounts and files

---

CHANGELOG.md
Documentation/distributions.md
Documentation/proposals/oci.md
Documentation/running-fly-stage1.md
Documentation/running-kvm-stage1.md
Documentation/subcommands/prepare.md
Documentation/subcommands/version.md
Documentation/trying-out-rkt.md
configure.ac
scripts/install-rkt.sh
tests/empty-image/manifest
tests/image/manifest
tests/rkt-monitor/build-stresser.sh
tests/rkt_exec_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go

This is a stabilization release which includes better support for environments without systemd, improvements to GC behavior in complex scenarios, and several additional fixes.
- rkt/cat-manifest: add support for --uuid-file ([#3498](https://github.com/coreos/rkt/pull/3498)).
- stage1: fallback if systemd cgroup doesn't exist ([#3507](https://github.com/coreos/rkt/pull/3507)).
- vendor: bump gocapability ([#3493](https://github.com/coreos/rkt/pull/3493)). This change renames `sys_psacct` to `sys_pacct`.
- stage0/app: pass debug flag to entrypoints ([#3469](https://github.com/coreos/rkt/pull/3469)).
- gc: fix cleaning mounts and files ([#3486](https://github.com/coreos/rkt/pull/3486)). This improves GC behavior in case of busy mounts and other complex scenarios.
- mount: ensure empty volume …

rkt 1.22.0

---

pkg/pod/pods.go

If `getPod` was called for a pod that no longer existed, a panic could
occur when trying to lock it.
This regression was introduced in #3404
Fixes #3513

pkg/pod: avoid nil panic for missing pods

---

tests/rkt_stop_test.go

Wait for the 'stop' command to complete before checking run status.
AFAICT,
Fixes #3091 
Signed-off-by: Graham Whaley <graham.whaley@intel.com>

tests/rkt_stop: Wait for 'stop' command to complete

---

rkt/gc.go

Running `rkt gc --grace-period=0 & rkt gc --grace-period=0` reproduces the error pretty reliably for this one. It helps to have a lot of dead pods present when doing so.

gc: avoid erroring in race to deletion

---

pkg/log/log.go
pkg/log/log_test.go

I deleted `Panicf` too because there were no callers and I really don't think there should be any ever again 😄

pkg/log: correctly handle var-arg printf params

---

stage1/init/common/dns_config.go
stage1/init/common/dns_config_test.go
stage1/init/init.go
tests/rkt_etc_hosts_test.go

This fixes a regression where the pod's hostname was missing from /etc/hosts
Fixes #3422

stage1: Add hostname to /etc/hosts

---

stage1_fly/run/main.go

stage1-fly was previously toggling `FD_CLOEXEC` on `RKT_LOCK_FD` multiple
times:
1. setting it at first
2. clearing it before exec()
3. setting it again after exec()
This commit just clears it once, as exec() is the very last stage1 step
and we either exit-fail or never return after that.

stage1/fly: clear FD_CLOEXEC only once

---

rkt/api_service.go

Fixes #3504 
This silences this silly error message. This logic isn't exactly correct, but I've filed another issue to fix that.

api-service: stop erroring when a pod is running

---

common/overlay/overlay.go
common/overlay/overlay_test.go
tests/rkt_mount_overlay_test.go
tests/rkt_tests.go

This patch provides an sanitizing function used to escape the colon characters in the directory names of the ```mount``` command.
According to the Linux documentation https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt it
is used as a separator symbol in case of multi lower-layer mount.
It also provides the unit tests for common/overlay package, that is possible to execute only with superuser privileges.
Fixes #3448

common/overlay: allow data directory name with colon character

---

stage1_fly/run/main.go
stage1_fly/stop/stop.go

This introduces an additional "pgid" file, specific to stage1-fly
implementation, to record the process group of the pod.
It is used by stop as a fallback mechanism if the pod-leader process
is gone but some daemonized children still exist, leaving the pod
in an unkillable status.
Fixes #3295

stage1/fly: record pgid and let stop fallback to it

---

stage1/usr_from_kvm/lkvm/patches/p9-chown-files-and-dirs-upon-creation.patch

Honor the uid/gid values when creating files and directories
Fixes #2576
As a side effect, it also seems to solve the remaining problems with
'apt-get update' in lkvm, so also:
Fixes #1917

stage1/kvm/lkvm: chown files and dirs on creation

---

Documentation/devel/cgroups.md
common/cgroup/cgroup.go
common/cgroup/v1/cgroup.go
stage1/app_add/app_add.go
stage1/init/init.go

This remounts the entire subcgroup (machine slice) read-write, instead of only the exact knobs per-app we need.
This is needed for runc (since it wants to manage cgroups for itself). It also simplifies `app add`, since we no longer need to manipulate cgroups after pod start time. It also reduces the number of bind mounts to one per controller, making various operations more efficient. (Before, we had one bind mount per controller knob per app).

stage1: remount entire subcgroup r/w, instead of each knob

---

pkg/aci/aci.go
pkg/aci/acitest/manifest.go
rkt/fetch_test.go
store/imagestore/store_test.go
store/treestore/tree_test.go
tests/rkt_exec_test.go
tests/rkt_fetch_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_image_dependencies_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go

This patch introduces a new package "pkg/aci/acitest" used to set the
default parameters to the application container image manifest
(precisely: name, version, kind).
It replaces the strings templates used to mock the manifest's JSON to
the types from "github.com/appc/schema" go-package.
Fixes #714

tests: use appc schema instead of string templates

---

stage1/init/common/units.go
stage1/init/init.go

This commit adjusts some systemd-related files in stage1
which were not properly uid-shifted for in case of user-ns.
Fixes https://github.com/coreos/rkt/issues/3528

stage1: uid shift systemd files

---

glide.lock
glide.yaml
vendor/github.com/appc/docker2aci/lib/internal/backend/file/file.go
vendor/github.com/appc/docker2aci/lib/internal/internal.go
vendor/github.com/appc/docker2aci/lib/version.go
vendor/github.com/appc/docker2aci/main.go
vendor/k8s.io/kubernetes/pkg/api/resource/generated.pb.go

This patch bumps the version of the appc/docker2aci library to 0.15.0
in order to support the conversion of the images with various os/arch.
fixes #3526

Bump appc/docker2aci library version to 0.15.0

---

rkt/image/namefetcher.go

Currently (rkt v1.22.0) e.g.
rkt fetch --no-store coreos.com/etcd:v3.0.15
(run twice to trigger) fails when using cached data due to
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x56200f0b6be5]
goroutine 1 [running, locked to thread]:
panic(0x56200f6f7c40, 0xc4200120d0)
/usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
github.com/coreos/rkt/rkt/image.(*nameFetcher).fetchImageFromSingleEndpoint(0xc4205338b0, 0xc42022ab00, 0xc420498cc0, 0x3f, 0xc420533a38, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/src/github.com/coreos/rkt/build-rkt-1.22.0/gopath/src/github.com/coreos/rkt/rkt/image/namefetcher.go:124 +0x245
github.com/coreos/rkt/rkt/image.(*nameFetcher).fetchImageFromEndpoints(0xc4205338b0, 0xc42022ab00, …
```

namefetcher: fix nil pointer dereference

---

common/cgroup/v1/cgroup.go

My previous PR used the wrong splitting function 🙇

stage1: fix incorrect splitting function

---

rkt/image_gc.go

This commit changes the behavior of `rkt image gc` to pass over any
images from which currently running pods were created from, regardless
of how long ago the image was last used.
Fixes https://github.com/coreos/rkt/issues/3385

image gc: don't remove images that currently running pods were made from

---

tests/rkt_run_user_group_test.go

TestAppUserGroup currently uses gexpect but does not need any
interactivity. This commit switches it away to use golang process
spawning and regexp matching.
Fixes https://github.com/coreos/rkt/issues/3560

tests: remove gexpect from TestAppUserGroup

---

tests/rkt_api_service_test.go
tests/rkt_config_test.go
tests/rkt_non_root_test.go
tests/rkt_root_commands_test.go
tests/rkt_tests.go
tests/testutils/ctx.go
tests/testutils/utils.go

Previously CommandsNeedRoot tested by executing rkt binary with user
"nobody". This fails when the ~/ folder of the user is only accessible
by the user itself. Now the test first chooses the owner of the rkt
binary file and if that is root it uses the "nobody" user as a fallback.
Fixes #1737

tests: fix when $HOME is only accessible by current user

---

stage1/usr_from_kvm/lkvm.mk

Update the LKVM git tag to the latest upstream.
This fetches in a number of 9pfs fixes.
Signed-off-by: Graham Whaley <graham.whaley@intel.com>

kvm/lkvm: update lkvm version to HEAD

---

Documentation/image-fetching-behavior.md
Documentation/subcommands/fetch.md
Documentation/subcommands/prepare.md
Documentation/subcommands/run.md
rkt/app_add.go
rkt/fetch.go
rkt/fetch_test.go
rkt/image/common.go
rkt/image/fetcher.go
rkt/prepare.go
rkt/run.go
rkt/stage1hash.go
tests/rkt_fetch_test.go
tests/rkt_image_dependencies_test.go
tests/rkt_tests.go

This replaces the `--no-store` and `--store-only` flags with a singular
flag `--pull-policy` that can accept one of three things, `never`,
`new`, and `update`. This is purely a cli change, there are no under the
hood impacts. `--no-store` has been aliased to `--pull-policy=update`
and `--store-only` has been aliased to `--pull-policy=never` for
compatibility reasons.
These changes come from a discussion in https://github.com/coreos/rkt/issues/2937.

run/prepare/fetch: replace --no-store and --store-only with --pull-policy

---

lib/app.go

Currently we use (mostly unpopulated) mountpoint metadata for returning
sandbox mounts. The appc added specific appVolume mounts though. This
fixes it by using the latter.

lib/app: use runtime app mounts and appVolumes rather than mountpoints

---

stage1_fly/run/main.go
tests/rkt_mount_test.go

This PR fixes stage1-fly logic when performing bind-mounts. It was previously following symlinks outside of application rootfs, resulting in wrong mounts being performed.
It now uses the same logic introduced in https://github.com/coreos/rkt/pull/3490 for resolving symlinks inside chroot.
Fixes https://github.com/coreos/rkt/issues/3228

stage1/fly: evaluate symlinks in mount targets

---

stage0/app_add.go

This commit uniforms app args and exec command, so that in both cases
CLI parameters always override image ones.

stage0/app-add: CLI args should override image ones

---

stage1/usr_from_kvm/qemu.mk

Update the QEMU pull tag to v2.8.0.
Disabling of VHDX is deprecated on the command line, so remove it from our option list.
Signed-off-by: Graham Whaley <graham.whaley@intel.com>

kvm/qemu: Update QEMU to v2.8.0

---

tests/rkt_non_root_test.go

This is a follow-up for 60dfa77a52e8040ec

tests: fix TestNonRootReadInfo when $HOME is only accessible by current user

---

stage1/init/common/units.go
stage1/prepare-app/prepare-app.c
tests/rkt_non_root_test.go
tests/rkt_paths_test.go
tests/rkt_root_commands_test.go
tests/rkt_tests.go

kvm-based stage1 flavours previously used a sym-link from /dev/ptmx to
/dev/pts/ptmx. However, the /dev/pts/ptmx device has perms 000 meaning
that non-root users could not access the device. Creating /dev/ptmx
unconditionally works with all flavours and matches behaviour on current
distributions.
Fixes #3252.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

stage1: Ensure ptmx device usable by non-root for all flavours.

---

stage1/init/kvm/resources.go
stage1/init/kvm/resources_test.go

Improve the memory allocation calculation for kvm.
And bump up the minimum.
I'm going to say:
Fixes: #3382 
And if we need then lets open a new ticket to cover any future more dynamic solutions.
Signed-off-by: Graham Whaley <graham.whaley@intel.com>

stage1/kvm: Change RAM calculation, and increase minimum

---

Documentation/build-configure.md
Documentation/dependencies.md
Documentation/subcommands/stop.md
configure.ac

A private semaphoreCI run on this branch shows:
- No test failures (same as `lkvm`)
- The same number of test passes

Switch default kvm flavour from lkvm to qemu

---

glide.lock
glide.yaml
vendor/github.com/appc/docker2aci/lib/common/common.go
vendor/github.com/appc/docker2aci/lib/docker2aci.go
vendor/github.com/appc/docker2aci/lib/internal/backend/file/file.go
vendor/github.com/appc/docker2aci/lib/internal/backend/repository/repository.go
vendor/github.com/appc/docker2aci/lib/internal/backend/repository/repository1.go
vendor/github.com/appc/docker2aci/lib/internal/backend/repository/repository2.go
vendor/github.com/appc/docker2aci/lib/internal/internal.go
vendor/github.com/appc/docker2aci/lib/internal/typesV2/docker_types.go
vendor/github.com/appc/docker2aci/lib/version.go
vendor/github.com/opencontainers/go-digest/LICENSE.code
vendor/github.com/opencontainers/go-digest/LICENSE.docs
vendor/github.com/opencontainers/go-digest/algorithm.go
vendor/github.com/opencontainers/go-digest/digest.go
vendor/github.com/opencontainers/go-digest/digester.go
vendor/github.com/opencontainers/go-digest/doc.go
vendor/github.com/opencontainers/go-digest/verifiers.go
vendor/golang.org/x/text/gen.go
vendor/golang.org/x/text/transform/transform.go
vendor/golang.org/x/text/unicode/norm/forminfo.go
vendor/golang.org/x/text/unicode/norm/normalize.go
vendor/golang.org/x/text/unicode/norm/readwriter.go
vendor/golang.org/x/text/width/transform.go
vendor/golang.org/x/text/width/width.go

This release adds a manifest hash annotation on converted images and introduces some API changes to allow for more granular control on registries and media types.
- Annotate manifest hash ([#237](https://github.com/appc/docker2aci/pull/237)).
- Allow selective disabling of registries and media types ([#239](https://github.com/appc/docker2aci/pull/239)).
- Update appc/spec to 0.8.10 ([#242](https://github.com/appc/docker2aci/pull/242)).

vendor: bump docker2aci to 0.16.0

---

CHANGELOG.md
Documentation/distributions.md
Documentation/proposals/oci.md
Documentation/running-fly-stage1.md
Documentation/running-kvm-stage1.md
Documentation/subcommands/prepare.md
Documentation/subcommands/version.md
Documentation/trying-out-rkt.md
ROADMAP.md
configure.ac
scripts/install-rkt.sh
tests/empty-image/manifest
tests/image/manifest
tests/rkt-monitor/build-stresser.sh
tests/rkt_exec_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go

This minor release contains bugfixes and other improvements related to the KVM flavour, which is now using qemu-kvm by default.
- Switch default kvm flavour from lkvm to qemu ([#3562](https://github.com/coreos/rkt/pull/3562)).
- stage1/kvm: Change RAM calculation, and increase minimum ([#3572](https://github.com/coreos/rkt/pull/3572)).
- stage1: Ensure ptmx device usable by non-root for all flavours ([#3484](https://github.com/coreos/rkt/pull/3484)).
- tests: fix TestNonRootReadInfo when $HOME is only accessible by current user ([#3580](https://github.com/coreos/rkt/pull/3580)).
- glide: bump grpc to 1.0.4 ([#3584](https://github.com/coreos/rkt/pull/3584)).
- vendor: bump docker2aci to 0.16.0 ([#3591](https://github.com/coreos/rkt/pull/3591)).

rkt 1.25.0

---

Documentation/integrations.md
Documentation/production-users.md
README.md

Production-users and Integrations pages, per the request from @philips

added production-users and integrations pages

---

Documentation/distributions.md

We renamed the project from CoreOS Linux to Container Linux. Fix rkt's
docs.

Documentation: CoreOS -> Container Linux

---

dist/init/systemd/rkt-gc.timer

The behavior of the default.target alias can be inconsistent and change
between systemd releases. Also it is customary to use multi-user.target
anyway. Switch to avoid potential surprise breakage.
Note: Container Linux isn't impacted since when this unit is enabled by
the ebuild it explicitly uses multi-user.target.
See https://github.com/coreos/coreos-overlay/pull/2484 for an example of default.target breaking.

dist: use multi-user.target instead of default.target

---

stage1/prepare-app/prepare-app.c

In glibc, inclusion of <sys/sysmacros.h> by <sys/types.h> has
been deprecated, so files that use makedev need to explicitly
include <sys/sysmacros.h>.
See:
https://sourceware.org/git/?p=glibc.git;a=commit;h=dbab6577c6684c62bd2521c1c29dc25c3cac966f

stage1: include <sys/sysmacros.h> for makedev function

---

common/common.go
rkt/fetch.go
rkt/image/fetcher.go

added function GetArch() to common/common.go which replaces runtime.GOARCH-calls in fetch related code. GetArch() returns the architecture of the current system, and especially returns either armv6l, armv7l or aarch64 if on arm devices (GOARCH is always arm). This leads to working rkt fetch on arm devices.

fetch: use proper appc os/arch labels

---

Documentation/commands.md
Documentation/subcommands/image.md
rkt/app_sandbox.go
rkt/flag/secflags.go
rkt/flag/secflags_test.go
rkt/image_verify.go
rkt/prepare.go
rkt/run.go
stage0/run.go
store/treestore/tree.go
tests/rkt_image_verify_test.go

For backwards compatibility, specifying 'insecure-options=ondisk' will
still run without error, however it will also not do anything.
Implements #3481 
This also implements an `image verify` subcommand that provides the original ondisk verification functionality.
This makes things much faster 💨 🚀.

stage0/{run,prepare}: remove ondisk verification

---

Documentation/integrations.md

Change "open an extensible" (a typo/incorrect) to "open and extensible".

Documentation/integrations.md: typo fix

---

api/v1/json.go
lib/app.go
lib/pod.go
lib/types.go
pkg/pod/pods.go
rkt/app_status.go
rkt/image_list.go
rkt/list.go

Make `rkt list|status --format=json` compatible with the default `k=v` format and include state info (exit codes in particular).
Also deprecate `App.AppNames` in the json output, but keep it there for backwards compatibility.
Before the change:
```sh-session
$ rkt status --format=json f4ef2301-511f-4ab0-9ce9-fdd02a76798e | jq "."
{
"name": "f4ef2301-511f-4ab0-9ce9-fdd02a76798e",
"state": "exited",
"app_names": [
"busybox"
],
"started_at": 1491855899
}
```
After the change:
```sh-session
$ rkt status --format=json f4ef2301-511f-4ab0-9ce9-fdd02a76798e | jq "."
{
"name": "f4ef2301-511f-4ab0-9ce9-fdd02a76798e",
"state": "exited",
"app_names": [
"busybox"
],
"apps": [
{
"name": "busybox",
"state": "exited",
"created_at": 1491855899323730200,
"exit_code": 12,
"image_id": …
```

rkt list|status: app state info (i.e. exit codes) in --format=json

---

tests/rkt_image_verify_test.go

Don't merge yet, I'm kicking semaphore to try and figure out why this test was failing there on the golint pr.

tests: fix image verify on semaphore

---

stage0/run.go
stage1/common/types/pod.go
stage1_fly/run/main.go
tests/rkt_volume_mount_fly_test.go
tests/rkt_volume_mount_generic_test.go
tests/rkt_volume_mount_test.go

Breaking change: volumes with duplicate names are now rejected.
This PR adds error-checking for duplicate volume names. Also, it adds path cleaning when de-duplicating mounts targets. Tests are slightly adjusted to check both cases.
Fixes https://github.com/rkt/rkt/issues/3663

stage1: improve duplicate mount-volume detection

---

stage1/usr_from_coreos/build-usr.mk

Currently there is a combination where both xattr data cannot be
transferred from a squashfs image to the filesystem combined with the
fact that it's not there.  This at least enables the transfer in the
future, and silences some of the warnings in the build process.
If it is decided that xattrs should not be explicitly transferred in the
future this should be changed to -no-xattrs.

build/stage1: transfer user xattr data

---

tests/rkt_caps_test.go

Capabilities tests produce a very large combination of images and
unpacked pods, which can easily fill all disk space on systems without
overlayfs support.
As we are currently hitting such limit on SemaphoreCI, this commit
makes caps tests optional by skipping them if overlayfs can't be used.

tests/caps: skip if overlayfs support is missing

---

Documentation/running-kvm-stage1.md
stage1/init/kvm/hypervisor/hypervisor.go

Supersedes #3622: I am doing a new PR because the CI seems broken.
-----
For testing purpose, I need to add extra kernel parameters in the VM.
Implemented in this way:
sudo RKT_HYPERVISOR_EXTRA_KERNEL_PARAMS="foo1=bar foo2=bar" \
./build-rkt-1.21.0+git/target/bin/rkt run \
--stage1-path=$PWD/build-rkt-1.21.0+git/target/bin/stage1-kvm.aci \
--insecure-options=image --interactive \
docker://busybox --cpu 1 --exec sh -- -c \
'cat /proc/cmdline'
noapic noacpi pci=conf1 reboot=k panic=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 console=ttyS0 i8042.noaux=1 rw rootflags=trans=virtio,version=9p2000.L,cache=mmap rootfstype=9p systemd.default_standard_error=journal+console systemd.default_standard_output=journal+console systemd.machine_id=3a2af63d415946778491bda1cb828c57 console=hvc0 …

kvm/qemu: add extra kernel parameters

---

stage1/init/common/seccomp_wildcards.go

This enables us to run binaries which use these syscalls when systemd has seccomp enforcing enabled.
Like reported this should affect at least all gcc compiled binaries.
This PR needs more testing, I just want to see what CI says. I'll setup at least one testbed with seccomp-enabled systemd. Perhaps @Xenopathic could test on aarch64 devices, I could test for armv6l and armv7l devices.
Fixes #3629.

seccomp: add arch-specific syscalls on ARM

---

Documentation/trying-out-rkt.md

Tested and edited the doc to reflect the latest etcd version: etcd:v3.2.0-rc.0

Documentation/trying-out-rkt.md: Reflect the latest ETCD version in rkt documentation

---

tests/functional.mk

The manifest contains values for the ACI arch and OS, not the go
language values.
Fixes 'make check' errors like these when run an ARM64 machines:
build: Layout failed validation: image manifest validation failed: bad arch "arm64" for linux (must be one of: [amd64 i386 aarch64 aarch64_be armv6l armv7l armv7b ppc64 ppc64le s390x])

functional test: Fix manifest arch error

---

store/imagestore/aciinfo.go
store/imagestore/migrate_test.go
store/imagestore/remote.go
store/imagestore/schema.go

When using sql queries the rows iterator needs to be closed if the entire query
result is not iterated over.  Failure to close the iterator results in resource
leakage.
Fixes errors like these seen with go1.8.1:
Too many goroutines running after integration test(s).
database/sql.(*Rows).awaitDone(0xc4201d9200, 0xd64000, 0xc4201e9b40)
database/sql/sql.go:2121
created by database/sql.(*Rows).initContextClose
database/sql/sql.go:2116
See: https://golang.org/pkg/database/sql/#Rows

imagestore: Fix sql resource leaks

---

tests/tests.mk

Fixes build errors like these when run on non amd64 machines:
go test: -race and -msan are only supported on linux/amd64, freebsd/amd64, darwin/amd64 and windows/amd64
A few other ways we can do this are to put the `GO_RACE` variable into variables.mk, or put a test into configure.ac.  Just let me know if you have a preference.

tests: Only run race test on supported arch

---

scripts/pkg/build-pkgs.sh

Not all builds will generate all stage1 images. It depends on what `./configure` flags (`--with-stage1-flavors`) were used.
When generating deb and rpm packages, only install what is available.
Signed-off-by: Fabio Kung <fabio.kung@gmail.com>

scripts: skip nonexistent stage1 images when packaging

---

Documentation/trying-out-rkt.md

Mac OS 10.12.3
Vagrant 1.9.4
VirtualBox 5.0.8
After following instructions to set up a Vagrant machine to try `rkt` (`git clone`, `vagrant up`), I could not login in the machine via `vagrant ssh` since it asked me for a password.
It was a bit painful to find so I added instructions in the documentation on how to get it.

fix(doc): how to get password for the ubuntu user

---

Documentation/commands.md

This fixes some rendering issues on https://coreos.com/rkt/docs/latest/commands.html#logging.

docs: fix code block syntax

---

scripts/pkg/after-remove
scripts/pkg/before-remove

On systems which have /var/lib/rkt as a separate partition, the active
mount detection in before-remove needs to not get confused by the
presence of /var/lib/rkt itself as a mount.  Therefore a longer path
is used for active mount detection.
Fixes #3706

scripts/pkg: improved detection of active mounts

---

stage1/net/rootfs/etc/rkt/net.d/99-default-restricted.conf
tests/rkt_net_test.go

Previously, we were using 172.17/16, which conflicts with the default
Docker networking. Change it to 172.31/16.

networking: change the default-restricted subnet

---

README.md

`rkt` has an icon of a rocket but previously the official pronunciation was "rock-it" which is incompatible with the logo. This change fixes that.
Fixes #3673

docs: correct rkt pronunciation

---

rkt/pubkey/pubkey.go

This reorders log-printing and error-returning when pubkeys discovery
fails, in order to print useful debugging information on error.

rkt/pubkeys: print debug logs on discovery errors

---

stage1/init/common/units.go

This prevents a race when apps are writing to their stdout/err (and
output is being sent to stage1's journal) while shutting down. If
journald terminates before the apps finish shutting down, their output
will be lost.
Signed-off-by: Fabio Kung <fabio.kung@gmail.com>

stage1/init/units: keep journald running while apps are shutting down

---

networking/podenv.go
tests/rkt_net_test.go

BREAKING: do not automatically add `default*` networks when custom ones are specified
Currently, a network named `"default"` (or `"default-restricted"`) is always added to Pods, even when `--net=custom1,custom2,...` was passed in. E.g.:
```
$ rkt --insecure-options=image run docker://alpine --net=custom1 --exec /bin/sh -- -c "ip link show"
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
3: eth0@if91: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc tbf state UP
link/ether 0a:58:c0:a8:02:03 brd ff:ff:ff:ff:ff:ff
5: eth1@if92: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
link/ether e2:a1:b3:c1:e7:24 brd ff:ff:ff:ff:ff:ff
```
The container in that case should only have `lo` and …

network: do not automatically add `default*` networks when custom ones are specified

---

tests/rkt_net_nspawn_test.go

Reference https://github.com/rkt/rkt/issues/3739

tests/net: skip TestNetCustomBridge on semaphore

---

Documentation/subcommands/status.md
rkt/status.go

A pid file never gets written if systemd never gets to run in stage1. This can happen if the image had a bad command, i.e.: not in $PATH.
Steps to reproduce:
```
$ sudo rkt --insecure-options=image run --uuid-file-save=/tmp/id docker://alpine --exec=bad
stage1: cannot initialize immutable environment: unable to find "bad" in "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
$ sudo rkt status $(cat /tmp/id)
state=exited
created=2017-06-16 16:34:27.38 -0700 PDT
status: unable to print status: unable to get PID for pod "e6ccefea-1cdf-459a-b98d-7da95373a7d2": <nil>
```
Signed-off-by: Fabio Kung <fabio.kung@gmail.com>

stage0/status: fix failure when systemd never runs in stage1

---

Documentation/subcommands/run.md

Also added rkt-run options present in rkt 1.27.0 but not present in the run.md markdown.  The entries in markdown have been sorted.
Fixes #3747.

docs: update CLI flags in run.md

---

CHANGELOG.md
Documentation/distributions.md
Documentation/proposals/oci.md
Documentation/running-fly-stage1.md
Documentation/running-kvm-stage1.md
Documentation/subcommands/prepare.md
Documentation/subcommands/version.md
Documentation/trying-out-rkt.md
configure.ac
scripts/install-rkt.sh
tests/empty-image/manifest
tests/image/manifest
tests/rkt-monitor/build-stresser.sh
tests/rkt_exec_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go

This is a minor bugfix release. It does not contain any changes to the rkt code, but it updates depencies and runtime versions for bugfixes:
- vendor: update go-systemd to v15 ([#3759](https://github.com/rkt/rkt/pull/3759)). rkt stopped working when running in a service with systemd v234. This update fixes it.
- scripts: update rkt-builder version to 1.3.0 ([#3754](https://github.com/rkt/rkt/pull/3754)). This updates the default Go runtime to 1.8, fixing https://github.com/rkt/rkt/issues/3738.

release 1.28.1

---

stage1/init/common/units.go

The previous version caused cryptic error messages. E.g. for `systemdVersion == 231 && flavor == "src"`:
> stage1 systemd ç does not support attachable I/O

stage1: fix systemd version fmt in error message

---

stage1/units/units-install.mk

This can cause the build to fail for some flavors, as the unit generation targets can delete the stage1/aci rootfs being built after some other make targets responsible for setting it up execute (e.g.: `stage1/aci` and `stage1/usr_from_src/stdlibdirs.mk`), effectively undoing everything other targets may have already done.
Here is an example `make V=2` output from one build with `--with-stage1-flavors=src`:
```
builder[5]:   RM RF        /opt/build-rkt/aci-for-src-flavor/rootfs
builder[5]:   MKDIR        /opt/build-rkt/aci-for-src-flavor/rootfs/lib/x86_64-linux-gnu
builder[5]:   RM RF        /opt/build-rkt/aci-for-src-flavor/rootfs/usr/lib/rkt/plugins/net
builder[5]:   RM RF        /opt/build-rkt/aci-for-src-flavor/rootfs
builder[5]:   STAMP …
```

build/stage1: make target installing units can not remove the ACI dir

---

configure.ac
stage1/usr_from_src/usr_from_src.mk

Local systemd source trees are useful here for packagers to build usr_from_src without requiring network access.  This differentiates between local and remote systemd sources by checking if the value from `./configure` contains "://".  If the string is found, the build will preserve existing behavior.  If not, the value is interpreted as a direct specification of the source directory path.

build/stage1: support local systemd source for offline builds

---

networking/networking.go
networking/podenv.go

Coming from Kubernetes issue [48427](https://github.com/kubernetes/kubernetes/issues/48427).
Initially I was thinking of doing it in the kubelet rkt code but as @squeed suggested, it's simpler and less hacky to do it in rkt codebase.
This PR ensure the `/run/netns` directory is always mounted once as tmpfs.
The `ip netns add <some-id>` command has this behavior by default. The kubelet calls this command for every new `hostNetwork: false` pods.
A mount of `/run/netns` over any existing netns files like `/run/netns/cni-30b37e42-157e-9796-dd74-ba4a3689bbde` cause issues with them.
Upgrading rkt with this fix needs a full drain of any running rkt-netns containers on the node.

networking: ensure the netns directory is mounted

---

pkg/keystore/keystore.go

Adding a Chmod after creating directories or files to ensure that they have the correct permission set.
Fixes: #3779

pkg/keystore: ensure correct permissions on path creation

---

common/cgroup/v1/cgroup.go

systemd introduced the hybrid cgroup hierarchy that mounts a cgroup v1
and v2 hierarchy in parallel. After systemd v233 the cgroup v2 hierarchy
is mounted in `/sys/fs/cgroup/unified`. This breaks rkt (specifically
flavor host) because we mount `/sys/fs/cgroup` ourselves and were not
creating the `unified` directory.
Let's create `/sys/fs/cgroup/unified` in `CreateCgroup()` to support the
hybrid cgroup hierarchy. If the host system (or the stage1) doesn't use
the hybrid hierarchy, having this directory created doesn't hurt.
Fixes #3741

stage1: support hybrid cgroup hierarchy

---

stage1/init/common/pod.go

Docker uses the UID as GID if you only specify the "user".
In that case, docker2aci sets the group name to the user name because
the appc spec requires both user and group to be set. This will fail
because that group name won't be found in /etc/group.
Let's detect if the image was converted from docker and set the GID to
the UID in that case.

stage1: handle docker group semantics

---

common/common.go
lib/app.go
pkg/pod/pods.go
rkt/status.go
stage0/run.go

Getting creation/start time and status of applications will fail for
pods using overlay if stage1 was unmounted (e.g. when rebooting).
This commit checks in the `upper/` directory if the pod uses overlay.

lib/app: check in upper/ if the pod uses overlay

---

rkt/image/resumablesession.go

The go [http/client](https://golang.org/doc/go1.8#net_http) changes its behavior for redirect and header's copy since the go 1.8:
> The Client now copies most request headers on redirect.
The ETag header is added and sent twice in the http header request as mentioned in #3678.
This behavior was tracked by ARCH users because they bumped to go1.8 earlier.
As the last release (github v1.28.1) bumped to go1.8, the problem is now present globally.

image: set the header instead of adding it

---

api/v1/json.go
lib/pod.go
tests/rkt_tests.go

It might happen that the pod is created but we can't get its start time
(e.g. we can't find the CNI network corresponding to `--net=NETWORK`).
This means StartedAt will not be set and the kubelet will error out and
ignore the pod, so it won't try to start it again.
Let's introduce CreatedAt to express the time when the pod was created
(even if it doesn't start) to handle this. This works because this time
is available after pod preparation.
We'll need to change rktlet to use CreatedAt instead of StartedAt when
getting a pod sandbox status.

api: add CreatedAt to v1.Pod

---

pkg/pod/sandbox.go
rkt/app_rm.go
stage0/app_add.go
stage0/app_rm.go

The kubelet tries to remove apps from pods that are stopped and there's
no reason to prevent the removal of apps from not running pods, actually
it was considered in some parts of stage0.RmApp().
Let's not require pods to be running to remove apps. If the pod is
running, we'll still stop the app units and so on. If not, we just
remove the app.

stage0,rkt: don't require the pod to be running to remove apps

---

rkt/gc.go

Before Linux 4.13, it used to be possible to perform double overlayfs
mounts in place. This now fails at mount() with EBUSY.
We were abusing this feature to unconditionally ensure that the stage1
image overlay mount was present before calling gc entrypoint.
This improves stage0 logic to perform the stage1 image overlay mount
only if it doesn't already exist.
Fixes https://github.com/rkt/rkt/issues/3805

stage0/gc: try to avoid double overlay mounts

---

stage1/init/common/units.go

It's needed to make systemd-journald write to /var/log/journal instead
of /run/log/journal. We added this unit in 7c7e833e9 but we didn't configure it so it starts.

stage1/init: activate systemd-journal-flush.service

---

Documentation/devel/update-coreos-stage1.md
scripts/sort-stage1-manifests.sh
stage1/usr_from_kvm/manifest-amd64-usr.d/sshd.manifest
stage1/usr_from_kvm/manifest-arm64-usr.d/ip.manifest

To ease maintenance let's keep the stage1 manifest files sorted.  Adds a script `sort-stage1-manifests.sh`, and sorts the usr_from_kvm files.  The usr_from_coreos files were sorted in https://github.com/rkt/rkt/commit/e70889eea122e73afd94cc2598f87b4919328b30 (stage1: upgrade to systemd-v233 from CoreOS 1478.0.0).
cc: @alban

Sort stage1 manifest files

---

common/apps/apps.go
rkt/app_sandbox.go
rkt/cli_apps.go
rkt/run.go
stage0/common.go
tests/rkt_app_sandbox_test.go

Before this change, "app add" CLI allowed only to define
user annotations. User annotations were designed mostly
to store annotations from Kubernetes API. At the same time,
we want to store some data related to rktlet which aren't
k8s annotations (i.e. log directories for CRI-compatible
logs).
Defining annotations is allowed here by --annotation
CLI option (i.e. --annotation=foo=bar).
Ref #3813
---
TODO:

app/add: Allow to define annotations for app from CLI

---

common/common.go
common/common_test.go
stage0/app_add.go
stage0/run.go
tests/rkt_app_sandbox_test.go

The help message in "app add" sucommand suggests that --name flag is optional, but it wasn't. This commit fixes the desired behaviour.
Fixes #3801

app/add: Use the image name as a default name for app

---

rkt/app_sandbox.go
tests/rkt_app_sandbox_test.go

Before this change, "app sandbox" CLI allowed only to define
user annotations. User annotations were designed mostly to
store annotations from Kubernetes API. At the same time, we
want to store some data related to rktlet which aren't k8s
annotations (i.e. log mode).
Defining annotations is allowed here by --annotation CLI
option (i.e. --annotation=foo=bar).
Ref #3813

app/sandbox: Allow to define annotations for sandbox from CLI

---

README.md

This removes the Jenkins build badge from the README. These builds were no longer maintained and the Jenkins instance has been decommissioned.

Remove Jenkins build-badge from README.md

---

stage1/init/common/units.go
stage1/init/init.go
stage1/iottymux/iottymux.go
tests/rkt_app_sandbox_test.go

This is the change made for rktlet. Kubelet expect the CRI-formatted
logs to be in specific directory and it provides that information with
CRI.
CRI-compatible logs are generated by iottymux. That specific directory
which kubelet is looking at, exists in the host filesystem. In order to
make it available for iottymux, we need to mount it into the stage1
container. That's why this commit introduces the new annotation called
coreos.com/rkt/experiment/kubernetes-log-dir. This annotation is read
by stage1 init and the directory by it is bind mounted to the stage1
nspawn container (the mountpoint inside container is /rkt/kubernetes/log).
Kubelet provides the name of a logfile of a container via CRI. Since the
container concept in Kubernetes refers to an app in rkt, we use the
annotation named …

iottymux: Store logs for kubelet in the appropriate location

---

tests/build-and-run-tests.sh

To aid in debugging build problems add a -v flag to build-and-run-tests that will add a `V=3` to the make commands.

tests: Add verbose flag to build-and-run-tests.sh

---

rkt/cli_apps.go
rkt/cli_apps_test.go

When any string in `[]args` is empty, `""`, then the `al.Count()` gets still incremented, even if there's nothing to parse. As a result, `rkt app add` fails with an error message like `must give only one app`, even when only one app name is given.
For example, rktlet runs the following command:
```
rkt app --insecure-options=image,ondisk add 58992c0a-540d-40a4-bf39-4bb193d74f94 \
docker://busybox:1.26 --name=2-seccomp-container-docker-default-d25eafce-ad02-11e7-a670-2eecc98c9398d25eaff2-ad02-11e7-a670-2eecc98c9398 \
--user-annotation=k8s.io/reserved/image-name=busybox:1.26  --exec=top
```
Then the last part, `"  --exec=top"` is parsed to a list of 2 separate strings: `" "` and `"--exec=top"`, That's why `al.Count()` becomes 2.
See also …

rkt: skip parsing in case of an empty string

---

stage1/init/init.go

So the annotation coreos.com/rkt/experiment/kubernetes-log-dir works
with the source and host flavors.

stage1: mount kubernetesLogDir for src and host flavors too

---

tests/install-deps.sh

When running on semaphore use thier install-package to
take advantage of package caching.

tests: Use semaphore install-package

---

rkt/run.go
tests/rkt_etc_hosts_test.go

This tweaks the '--hosts-entry' CLI flag parser to accept multiple
time the special value "host" when there are no other conflicting
settings.

stage0/run: relax '--hosts-entry' parser

---

Documentation/subcommands/run.md

Some users find confusing the fact that `--pod-manifest` overrides
everything specified in the image manifest.
Document that to avoid confusion.
Fixes #3000

Documentation: add --pod-manifest explanation

---

rkt/image_gc.go

We were using break when we found an image with a pod in running state
but that means we'll miss subsequent images for non-running pods.
Change the break to a continue to keep processing the rest.

rkt: prevent skipping some images in image gc

---

stage1_fly/run/main.go

changes stage1-fly to convert a command name into an absolute path so
that syscall.Exec is able to properly execute it.
solves #3662.
@jyouchan and I worked on this together.

stage1-fly/run: allow non absolute commands to be run

---

stage1/init/common/units.go
tests/rkt_run_test.go

Even if we run the container as an unprivileged user.
Usually, pre-start and post-stop are used to initialize or shut down a
service, and very often this needs privileges.

stage1: execute pre-start/post-stop hooks as privileged

---

Documentation/block-devices.md
Documentation/security.md
Documentation/subcommands/run.md

Document how to use block devices inside a rkt container.
Add examples for sshfs, CUDA, and formatting disks.
Fixes #3170

Documentation: add block device docs

---

Documentation/app-container.md
Documentation/proposals/oci.md
ROADMAP.md

The documentation about OCI and appc created uncertainty for users, as
shown by the issues #3777 and #3745.
This is an attempt to clarify that although not much development is
happening in appc, rkt will not drop the ACI support.
Once this PR is merged, I would like to delete the project
https://github.com/rkt/rkt/projects/5 as it does not contain anything
and we have https://github.com/rkt/rkt/projects/4 to track the progress
of OCI native support.
Fixes https://github.com/rkt/rkt/issues/3777
Fixes https://github.com/rkt/rkt/issues/3745

doc: OCI & appc/spec clarification

---

Documentation/subcommands/status.md
rkt/status.go
tests/build-and-run-tests.sh
tests/rkt_status_test.go

#3005 added --uuid-file to status command

status: added read from uuid-file

---

Documentation/using-rkt-with-systemd.md

Container Linux enabled lz4 support for journald[[1]], which means logs
started being written compressed with the lz4 format instead of xz.
Change the note about host's systemd compression support needed from xz
to lz4.
Also, clarify that this only applies to the coreos and kvm flavors.
Users of the host flavor will not be impacted since the systemd used in
stage1 will be the same as on the host.
[1]: https://github.com/coreos/coreos-overlay/pull/2593
Fixes #3839

Documentation: update compression note for journal files

---

Documentation/configuration.md

Issue: https://github.com/coreos/rkt/issues/3157
Example credit goes to @sjansen
It seems that a generic solution is already documented in [configuration](https://github.com/coreos/rkt/blob/master/Documentation/configuration.md#description-and-examples-1) options. That said, I had the same experience as @thattommyhall and concluded that Amazon's ECR was not working with rkt.
This PR purposes adding ECR as an example Docker registry to help others in the future find the solution.
cc @jonboulle

docs: add AWS ECR link to examples of Docker registries

---

pkg/pod/pods.go
rkt/api_service.go
rkt/status.go
tests/rkt_list_test.go

partial fix for #3550 
ip of the non running pod is added to the json output

list: add ip of non-running pods to status output

---

Documentation/pod-manifest.md
Documentation/subcommands/run.md

This guide explain how to generate a pod manifest and points to the
relevant resources in the appc spec repo.
Fixes #3108

Documentation: add pod manifest walkthrough

---

makelib/misc.mk

Use the current working directory and not MK_TOPLEVEL_ABS_SRCDIR when
processing 'go list' output in go-find-directories.
Our invocation of 'go list' in the go-find-directories function uses
paths relative to the current working directory and so the output of
that command will have file paths based on the current working
directory.  The make file variable MK_TOPLEVEL_ABS_SRCDIR is initialized
with make's abspath function.  The abspath function (GNU Make 4.1) will
resolve symlinks.  This difference in resolved and unresolved symlinks
causes problems in the go-find-directories function output when building
from a path that includes a symlink.
Fixes 'make unit-check' errors like these when building in a directory
that has a symlink in its path:
stat …

makelib: Fix go-find-directories symlink problem

---

scripts/install-deps-debian-sid.sh
scripts/install-deps-fedora-22.sh

libfdt-dev is needed when building kernels for architectures that
support a device tree.
Fixes build errors like these when building kvm+lkvm flavor for
ARM64:
make[1]: Entering directory 'build/tmp/usr_from_kvm/lkvm/src'
Makefile: No libfdt found. Please install libfdt-dev package. Stop.
Related to: https://github.com/rkt/rkt/pull/3829

scripts: Add libfdt to install deps

---

Documentation/integrations.md

Since that's the recommended way to run a k8s cluster.
Fixes #3867

 Documentation/integrations: update Kubernetes link to rktlet

---

Documentation/dependencies.md
Documentation/troubleshooting.md
README.md

It's useful to have common problems with their solutions or workarounds
in one document.
This starts a troubleshooting document.
Fixes #3865

Documentation: add initial troubleshooting doc

---

networking/networking.go

The value read from /proc contains LF, and shoud be trimmed

networking/portfwd: fix compare routeLocalnetValue

---

Documentation/devel/architecture.md
Documentation/devel/inspect-containers.md

This adds documentation on inspecting rkt's execution with strace, by
querying the proc filesystem, and finding out information about the
cgroups rkt sets up.
It's by no means comprehensive but can be a good starting point for
people learning about containers.
Closes #3868

Documentation: add rkt internals inspection

---

networking/kvm.go

When the kvm stage1 and the coreos stage1 are used on the same machine with a
flannel CNI configuration (and likely other configurations) without a specified
bridge name, different bridges will be constructed by each stage1 for the same
subnet -- cni0 and kvm-cni0 -- causing traffic intended for the
later-constructed bridge to be lost, as it is routed to the earlier-constructed
bridge.
The normal workaround is to specify a bridge name in the CNI configuration, but
this fix avoids the issue altogether by making sure that cni0 is used in all
cases.
I can't find any records of a specific motivation for using kvm-cni0 instead of cni0, so it's possible that I'm missing the original reason behind it, but it seems like an arbitrarily-made decision from the original development of CNI support in …

kvm: solve certain routing issues by using the same default bridge as CNI

---

scripts/pkg/build-pkgs.sh

Different RPM distributions use different packages to collect the
various tools from the 'shadow' package so we could use the path
from one of these tools in order to allow the rkt package to be used
in more RPM distributions.
Fixes: #3908

scripts/build-pkgs: use RPM file dependency for shadow tools

---

rkt/config/auth.go
rkt/config/config.go

This refactors awsAuthHeaderer to match oAuthBearerTokenHeaderer and modifies
the `config` command so awsAuthHeaderer can be marshaled to JSON (support for
this was previously missing).

rkt: add AWS auth headerer support to `rkt config`

---

Documentation/distributions.md

Using `nix-env` you have two options:
`nix-env -i rkt` or `nix-env -iA nixos.rkt`
Using `nix-env -iA rkt` will usually not work.
On NixOS however you also want general virtualization dependencies.
Therefore enabling the rkt virtualisation is the right way to
set up everything correctly.

Fix NixOS install instructions

---

Documentation/using-rkt-with-kubernetes.md

link 'rktnetes' is not valid currently. Latest I could find was v1.8.

docs: update rktnetes URL

---

stage1/usr_from_kvm/qemu.mk
stage1/usr_from_kvm/qemu/patches/000-memfd_fix_configure_test.patch

This is a backport of a qemu upstream patch to fix a memfd related
failure. It first adds infrastructure to apply the patch to qemu at
build time.
Ref: https://git.qemu.org/?p=qemu.git;a=commit;h=75e5b70e6b5dcc4f2219992d7cffa462aa406af0
Ref: https://github.com/rkt/rkt/pull/3921#issuecomment-380791171

stage1/kvm: fix qemu memfd build failure

---

CHANGELOG.md
Documentation/devel/inspect-containers.md
Documentation/distributions.md
Documentation/pod-manifest.md
Documentation/proposals/oci.md
Documentation/running-fly-stage1.md
Documentation/running-kvm-stage1.md
Documentation/subcommands/prepare.md
Documentation/subcommands/version.md
Documentation/trying-out-rkt.md
configure.ac
scripts/install-rkt.sh
tests/empty-image/manifest
tests/image/manifest
tests/rkt-monitor/build-stresser.sh
tests/rkt_exec_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go
tests/rkt_run_test.go

release 1.30.0

---

stage1/init/common/pod.go
stage1/init/common/pod_test.go

systemd substitutes both %-specifiers and $-variables starting from the
second command-line argument, and rkt should escape both of them.
Fixes #3925

stage1: escape '%' in command lines as well as '$'

---

tests/inspect/inspect.go
tests/rkt_exec_test.go

Fix some misspells in inspect.go

---

tests/rkt_tests.go

Remove patchImportAndRun, patchImportAndPrepare functions unused in rkt_test.go

Remove unused functions
