stage1/rootfs/Makefile
stage1/rootfs/aggregate/Makefile
stage1/rootfs/aggregate/aggregate.sh
stage1/rootfs/aggregate/install.d/99misc
stage1/rootfs/diagexec/Makefile
stage1/rootfs/diagexec/install
stage1/rootfs/shim/Makefile
stage1/rootfs/shim/install
stage1/rootfs/usr/Makefile
stage1/rootfs/usr/install

* usr/Makefile lacked dependency on manifest.d
* aggregate/Makefile lacked dependency on discrete components:
- Introduce aggregate/install.d registry of ordered component installers
- Add Makefile dependency on aggregate/install.d/*
- Amend discrete component's Makefiles to register their installation
as aggregate/install.d/$prio$component scripts sourced by aggregate.sh
These changes cause aggregate to occur when any discrete component is built
in an incremental rootfs build.  Otherwise discrete components would be built
without getting pulled into a (re)built rootfs.

stage1/rootfs: various small Makefile dependency fixups

---

Documentation/hacking.md

As the build process is going to build libraries and executables it requires:
* make
* gcc
* glibc development and static pieces.

doc: Add needed build programs and libraries.

---

Documentation/getting-started-guide.md

if either user or group is missing, the actool validation would remind that's required:
$ actool -debug validate manifest.json
manifest.json: invalid ImageManifest: User is required
manifest.json: invalid ImageManifest: Group is required
Signed-off-by: Derek Ch <crquan@gmail.com>

added user and group for the example app

---

version/version.go

coreos-stable-00 rocket-v0.1.1 # ./rkt version
rkt version 0.1.0
coreos-stable-00 rocket-v0.1.1 # ./rkt help
NAME:
rkt - rocket, the application container runner
USAGE: 
rkt [global options] <command> [command options] [arguments...]
VERSION:
0.1.0

rkt: version information is old/wrong

---

.gitignore
stage0/.gitignore
stage1/.gitignore

This wasn't catching some of the artefacts from the stage1 build process.
Also, .gitignore files can be more local to what they ipact so this creates
ones for the stage0/stage1 directories that should be updated inline with
changes to those packages.
/cc @vcaputo, seem OK to you?

*: update and split out gitignore

---

stage1/init/container.go
stage1/init/container_test.go
test

Note this only quotes the arguments, not the path.  There's a bug in
systemd which prevents quoting the path; it thinks the executable's path
is not absolute when quoted.  This prevents things like an executable path
containing spaces from working.
Fixes #321.

stage1/init: quote Exec* argument lists

---

rkt/help.go

The subcommand functions can't directly call printCommandUsage on their
own Command struct due to the circular initialization which emerges.
With this they can simply supply their subcommand name instead, we'll
probably revisit this later.

rkt/help: add function for printing command help by name

---

rkt/fetch.go
rkt/fetch_test.go
test

Unfortunately the recent fetch refactoring inverted the logic from what it
should be; we want to first check if the supplied image name is a valid URL,
and, if so, we should just pass it through. Otherwise, newDiscoveryApp will
return bogus results because discovery.NewAppFromString does not expect to get
URLs.
Also adds a few test cases for NewDiscoveryApp.

rkt: refactor fetch, add tests

---

rkt/status.go

Simple querying of container status by uuid is provided.
The pid of the container's stage1, an exited boolean, and per-imageid
exit status codes are printed when available.
Container exit synchronization occurs when --wait is specified.
Examples:
Already exited but not yet garbage collected container:
$ rkt status --uuid 32e5c3d4-c851-4c46-bddc-b52c46449523
pid=11219
exited=true
sha256-f9124faae79eb859b27581d9673a2d29a8e394a2685088753264dea276dd7571=0
$
Already exited and "marked" for garbage collection by rkt gc (same as above):
$ rkt status --uuid 32e5c3d4-c851-4c46-bddc-b52c46449523
pid=11219
exited=true
sha256-f9124faae79eb859b27581d9673a2d29a8e394a2685088753264dea276dd7571=0
$
Already exited and actively being discarded by rkt gc (treated as gone):
$ bin/rkt status --uuid …

rkt status: implement status

---

pkg/tar/tar.go
pkg/tar/tar_test.go
stage0/run.go

Last commit is the interesting one. 
The previous required commit was proposed in #347.
If this or #348 is merged the other one will need a rebase due to added arguments to ExtractTar.

pkg/tar: add PathWhitelistMap to whitelist files for tar extraction.

---

stage1/rootfs/diagexec/diagexec.c

In `rkt enter` usage, users are likely to specify a filename rather than a
path expecting $PATH lookup resolution to occur.

stage1/diagexec: use execvp() to facilitate `rkt enter`

---

pkg/lock/dir.go
pkg/lock/dir_test.go

In creating a more general interface to the container dirs a method for
unlocking a DirLock without closing it became necessary.
This should have been added when lock.NewLock() became public.

pkg/lock: add DirLock.Unlock()

---

stage1/init/init.go

Fixes issue reported by @crquan in https://github.com/coreos/rocket/pull/357

stage1/init: handle relative /etc/localtime symlinks

---

networking/net-plugin.go
stage0/run.go
stage1/init/init.go

Invoke the private networking from stage1. It's currently disabled -- the flag defaults to false and it's not plumbed through to stage0.

invoke net plugins from stage1 -- disabled for now

---

cas/remote.go
rkt/fetch.go

as Remote.Blob is used to store the related key on the diskv blob store rename it to BlobKey.
It should also be noted that it's not the same as an ImageID (as an ImageID can
be a sha512 with different key lenghts) and to deriver a
BlobKey from an imageID one should use cas.ResolveKey(ImageID).
In the last update round of the various acirenderer patches (for example #297, #356 etc...)
I decoupled key from ImageID and always use key in the various cas functions, and, when I 
have a types.Hash imageID, I first call cas.ResolveKey(ImageID) to get the key.

cas: remote: clarify the meaning of Blob and rename it to BlobKey.

---

rkt/fetch.go
rkt/rkt.go
rkt/run.go

The cas decides whether to retrieve the signature based on whether the 
supplied *keystore.Keystore is non-nil; however, we were not properly passing
a nil Keystore through in the case that InsecureSkipVerify is set, so it was
still attempting to retrieve a signature in this case.
/cc @kelseyhightower

fetch: do not build keystore if InsecureSkipVerify

---

stage1/init/container.go

commit dbcdb4a8 used unit.UnitOption composite literals causing go vet
complaining (at least on my system, dunno why tests on travis are working).
This was fixed in other places by 1af30a2d but dbcdb4a8 was older.

stage1: use newUnitOption for WorkingDirectory.

---

rkt/fetch.go

This patch, should be merged together with the appc/spec part (appc/spec#132). Tests will fail due to this requirement.

rkt: use new discovery.Endpoint struct from appc/spec.

---

cas/cas.go
cas/cas_test.go

ResolveKey would return full-length keys without actually looking
them up in the store.

cas: make ResolveKey() only return keys which exist

---

networking/ipam/ipam.go
networking/networking.go
networking/plugins/veth/veth.go
networking/util/link.go
networking/util/net.go
networking/util/route.go
networking/util/setns.go

The scheme of having a host veth not have an IP
and not be plugged into bridge does not work in
practice. This creates a true point-to-point link
between the container and the host.

net: Give the host end of veth an IP

---

metadatasvc/main.go
networking/ipam/ipam.go
networking/net-plugin.go
networking/net.go
networking/networking.go
networking/plugins/bridge/bridge.go
networking/plugins/veth/veth.go
networking/util/cidr.go
networking/util/link.go
networking/util/net.go
networking/util/route.go
networking/util/setns.go
rkt/gc.go

A small collection of `go vet`, `golint`, and other idiomatic/convention fixes, which I discovered while reading the code. Nothing that changes any behavior.

go vet, golint, and other small fixes

---

metadatasvc/main.go

see  issue https://github.com/coreos/rocket/issues/409
The specification says that queries to the metadata service must have an HTTP header:
Metadata-Flavor: AppContainer
The actual check in the metadatasvc main.go is for "AppContainer header"

metadatasvc: remove string "header" from http header match

---

build

build should be callable even if the user's env has no GOPATH in it

build: don't fail if GOPATH is unset

---

cas/remote.go

This is for symmetry with printing out the ACI URL; in future we can 
standardise this better as we tweak what exactly goes to stdout, but I think
this adds value for now.

cas: print URL when retrieving remote signature

---

stage0/run.go

Rather than coming up with a UUID and doing a Mkdirall, just rely on the 
atomicity of Mkdir instead, and keep generating UUIDs until we find a 
directory that doesn't exist or hit an arbitrary limit (100).

stage0: avoid collisions when generating UUID

---

cas/cas_test.go
cas/remote.go
cas/remote_test.go
networking/plugins/bridge/bridge.go
pkg/aci/aci.go
pkg/keystore/keystore.go
pkg/lock/dir.go
pkg/tar/tar.go
rkt/doc.go
rkt/fetch_test.go
stage1/init/registration.go

Also moves pkg/util/aci.go -> pkg/aci/aci.go for simplicity and consistency
with the other pkgs.

*: add missing godocs and copyright headers

---

stage0/run.go

Now that apps are an optional part of the ImageManifest, we need to check an
image contains one before accessing it.
At some point it would be nicer to check this higher up the stack, but that
will require reworking the interface between `rkt run` and stage0, so for now
just do it here.

stage0: do not panic on missing app

---

rkt/rkt.go
rkt/trust.go

Example output:
$ rkt trust --prefix foo.net/woot http://pengaru.com/~swivel/pubkeys.gpg
GPG key fingerprint is: BF65 1A65 AE01 DC62 C469  9CF5 E627 E9F1 4D8E F0A2
Subkey fingerprint: 0434 4CC9 525E 1348 7735  D4DF 8396 4F3D F63C F071
Kelsey Hightower (ACI signing key) <kelsey.hightower@coreos.com>
Are you sure you want to trust this key (yes/no)? no
Not trusting "http://pengaru.com/~swivel/pubkeys.gpg".
$
$ rkt trust --prefix foo.net/woot http://pengaru.com/~swivel/pubkeys.gpg
GPG key fingerprint is: BF65 1A65 AE01 DC62 C469  9CF5 E627 E9F1 4D8E F0A2
Subkey fingerprint: 0434 4CC9 525E 1348 7735  D4DF 8396 4F3D F63C F071
Kelsey Hightower (ACI signing key) <kelsey.hightower@coreos.com>
Are you sure you want to trust this key (yes/no)? yes
Trusting "http://pengaru.com/~swivel/pubkeys.gpg" …

rkt: implement `rkt trust` command

---

rkt/containers.go
rkt/status.go

Should have been renamed when container became the receiver

rkt: rename c.containerWaitExited() -> c.waitExited()

---

.travis.yml
Documentation/hacking.md
build
common/common.go
rkt/run.go
rkt/status.go
stage0/enter.go
stage0/entrypoint.go
stage0/run.go
stage1/.gitignore
stage1/init/path.go
stage1/rootfs/Makefile
stage1/rootfs/aggregate/Makefile
stage1/rootfs/aggregate/aci-manifest
stage1/rootfs/aggregate/aggregate.sh
stage1/rootfs/init/Makefile
stage1/rootfs/init/install
stage1/rootfs/usr/install

One may now specify an alternative stage1 in a style like run and fetch:
rkt run --stage1-image foo.com/rocket/stage1 app
--stage1-image currently defaults to "stage1.aci", which requires running
`rkt run` from the rocket source root to use the bundled stage1.

*: switch stage1 to aci image format

---

Documentation/getting-started-guide.md
Documentation/getting-started-ubuntu-trusty.md

Add instructions for static build on go1.4, update etcd 0.5.0 -> 2.0.0
/cc @kelseyhightower

docs: update getting started guides

---

rkt/version.go

`rkt version` should print not only its own version, but version information
for the spec against which it is built.

rkt: add appc spec version information

---

pkg/tar/tar.go
pkg/tar/tar_test.go

Restore the extracted entry uid and gid. This uses tar header Uid and Gid
values and ignores header's Uname and Gname.
As the tests are usually run as a unprivileged user the generated test tars'
entries are defaulted to the running user uid and gid. For this reason tests
are implictly verifing that the os.Chown/os.LChows calls works but it's
difficult to create a more comprehensive test using different uid and gid
values.

tar: restore entry's uid and gid.

---

stage1/init/container.go
stage1/init/path.go
stage1/rootfs/aggregate/install.d/99misc
stage1/rootfs/diagexec/diagexec.c
stage1/rootfs/enter/enter.c

This change places per-app environment files in stage1/rootfs/rkt/env/$id
The stage1 systemd service files no longer contain Environment directives,
instead they simply supply the env file path to diagexec.
`rkt enter` also uses diagexec and needs to enter the same enviroment of the
app being entered.  This commit also modifies the stage1 /enter to supply the
env file to its diagexec invocation, giving `rkt enter` an environment
consistent with the app's.

stage1: set app environment via diagexec instead of systemd

---

build

Without this, go throws an error about no source files available because
all of the source files for github.com/vishvananda/netlink/nl end in
"_linux.go".

build: build network plugins only on linux

---

rkt/containers.go
rkt/gc.go
rkt/uuid.go

rkt: don't build gc.go, containers.go, and uuid.go on non-linux

---

pkg/keystore/keystore.go

if the Reader for the *.sig is without an armored signature, then the
returned error is just EOF. Not helpful.
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

pkg/keystore: error for no sigs in *.sig

---

rkt/trust.go

rkt trust: strip common url schemes from --prefix argument

---

README.md
stage0/entrypoint.go
stage0/run.go
stage1/rootfs/aggregate/aci-manifest

Currently the annotation "coreos.com/rocket/stage1/init" represents the stage1
entrypoint used by `rkt run`.  Renaming to "coreos.com/rocket/stage1/run" is
more consistent and self-documenting, aligning with the `rkt enter` entrypoint
annotation "coreos.com/rocket/stage1/enter".

*: rename stage1 entrypoint annotation from init->run

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/docker2aci/lib/docker2aci.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/docker_functions.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/docker_types.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/types.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/util.go
Godeps/_workspace/src/github.com/appc/docker2aci/tarball/tarfile.go
Godeps/_workspace/src/github.com/appc/docker2aci/tarball/walk.go
cas/cas.go
cas/cas_test.go
cas/remote.go
rkt/fetch.go

This PR uses the [appc/docker2aci](https://github.com/appc/docker2aci) library to implement fetch and run support for docker registry URLs in rocket.
Addresses #145

rkt run: support docker images

---

build
rkt/run.go

As mentioned in https://github.com/coreos/rocket/issues/457#issuecomment-73944496, the path where the rkt binary looks for stage1 should be something you can specify when building rocket.
Looking at [the code](https://github.com/coreos/rocket/blob/68a0c0b6567a3e9b2feb4fbf476f1730f27b6fb5/rkt/run.go#L51-L56), this doesn't currently appear to be the case.
This is currently blocking a fix to the [Arch Linux AUR package](https://github.com/yuvadm/archlinux-packages/pull/5#issuecomment-73985648), and will probably be necessary for other distributions as well.

Default stage1 path should be configurable with a build option

---

rkt/fetch.go

Unfortunately since Docker images do not support signature verification, we
can't enable it for them. To make things explicit, require users to provide
the -insecure-skip-verify flag to work with Docker images.

fetch: require -insecure-skip-verify for Docker images

---

pkg/tar/tar.go

Fix the TODO introduced and discussed in #462 calling os.Chmod after the
os.LChown for all files except symlinks.

tar: call os.Chmod after os.LChown

---

rkt/trust.go

Instead of silently stripping and ignoring the URL scheme, print
an error and exit.
Fixes #472

rkt trust: disallow URL schemes in --prefix parameter

---

cas/cas.go
cas/cas_test.go

Last two commits are the interesting ones.
The previous required commits were proposed in other #342 (only needed for tests)
Add a new diskv store to save the ImageManifest of an ACI. As future functions
will need the image manifest this avoids the needs (and slowness) of extracting
it from the ACI.
As an ACI and its image manifest are tied together, on WriteACI the image
manifest is saved using the same key of the blob store.
GetImageManifest retrieves the ImageManifest with the specified key.

cas: Add Imagemanifeststore, save ImageManifest on WriteACI and ad GetImageManifest function.

---

cas/aciinfo.go
cas/aciinfo_test.go
cas/cas.go
cas/schema.go

Last commit is the interesting one. It needs the db implementation provided in #361 and is based over #392. IMHO this db based implementation is really cleaner and better that the hackish diskv based ones proposed in #352 and #353.
The ACIInfo table saves informations on the ACIs. The saved informations are:
* BlobKey is the key in the blob and imageManifest store of the related ACI file.
* AppName is the app name provided by the ACI.
* ImportTime is the time this ACI was imported in the store
* Latest defines if the ACI was imported using the latest pattern (no version
label provided on ACI discovery)
About the latest pattern please see (and comment) on appc/spec#73.

cas: add an ACIInfo table

---

.gitignore
Vagrantfile
scripts/install-go.sh
scripts/install-rocket.sh

This commit adds the necessary Vagrantfile and
associated provisioning scripts to stand-up a working
rocket installation using the Vagrant tooling.
see vagrantup.com for more details about Vagrant
Environment details:
* Ubuntu trusty 64bit (Official Image)
* golang version 1.4.1
* Rocket version 0.3.2
* APPC version 0.3.0
files directly copied from commit 03592ce of:
https://github.com/brookerj11211/vagrant-rocket

Add Vagrant support to Rocket

---

cas/cas.go
cas/cas_test.go

Using a very short key like "sha512-a", cas.blockTransform will panic
retrieving parts[1][0:2] as part[1] will be "a" and [0:2] is out of range. As
blockTransform cannot return an error this should be checked before calling
diskv functions.
Assuming that all cas functions using diskv should be called passing a full
key (if needed retrieving it with cas.ResolveKey), this patch just adds
additional validations to cas.ResolveKey for the right prefix and a minimal
length.
A more paranoid patch should verify this before any call to diskv functions.

cas: check key prefix and min size in ResolveKey.

---

networking/networking.go

Before this patch, when withNetNS() returns with an error, the current
net namespace is undefined. In order to make the API more readable,
withNetNS() should always at least attempt to return in a defined
namespace used before being called, even in case of errors.
In practice, the only caller of withNetNS will handle the error case
correctly by calling Teardown() so there should be no functional changes
with this patch.

net: withNetNS: attempt to revert net ns in case of error

---

Documentation/container-lifecycle.md
rkt/containers.go
rkt/containers_test.go
rkt/enter.go
rkt/gc.go
rkt/list.go
rkt/prepare.go
rkt/rkt.go
rkt/run-prepared.go
rkt/run.go
rkt/status.go
rkt/uuid.go
stage0/run.go

Introduces a new directory for all uuids in use:
containers/uuid/$uuid
Introduces new states for a container directory, now:
embryo:	containers/embryo/$uuid
preparing:	containers/prepared/$uuid & x-locked
prepared:	containers/prepared/$uuid
running:	containers/run/$uuid & x-locked
exited:	containers/run/$uuid
garbage:	containers/garbage/$uuid
deleting:	containers/garbage/$uuid + x-locked
gone:		absent
Some of these states overlap, garbage and deleting for example both imply
exited.
For a simple `rkt run` invocation, the container never enters the prepared
state, instead it directly transitions from preparing to running.
For the split `rkt prepare` and `rkt run-prepared` invocation the
container enters the prepared state between the two.
When a container is first created, it starts in the …

*: refactor container lifecycle to be more granular/comprehensive

---

rkt/fetch_test.go

The appc spec does not allow it anymore:
https://github.com/appc/spec/commit/14f48a22af6a013afe7848844a66f0ca6aac9af6

tests: don't use an AC name finishing with a slash

---

cas/cas.go

Consuming tar files 512 bytes at a time is silly, bump to 32KiB.

cas: increase reader iobuf size in WriteACI

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/spec/pkg/acirenderer/acirenderer.go
Godeps/_workspace/src/github.com/appc/spec/pkg/acirenderer/acirenderer_test.go
Godeps/_workspace/src/github.com/appc/spec/pkg/acirenderer/resolve.go
Godeps/_workspace/src/github.com/appc/spec/pkg/acirenderer/store_test.go
cas/cas.go
pkg/aci/render.go
stage0/run.go

Now that #464 and #465 are completely self contained (so they can be moved to another repo/project), this is the part that adds the starting acirendering functions to rocket.

rkt: add aci rendering.

---

Documentation/signing-and-verification-guide.md
README.md
rkt/fetch.go
rkt/fetch_test.go

Use the standard PGP file extension of .asc instead of .sig. This was
changed in the the 0.4.0 spec.

rkt: use .asc instead of .sig files

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/spec/schema/version.go

This is basically a no-op because the only changes since 
480f5812e40cb93dbc5270301092368952546bb1 don't touch the vendored code, but it
gets in sync with the actual release.

Godep: bump appc/spec to 0.4.0

---

Documentation/commands.md
rkt/prepare.go
rkt/run.go
stage0/run.go

Also renamed --inherit-environment to --inherit-env, the former is too
verbose for consistent use with --set-env considering --set-env is to be
used repeatedly for multiple variables, abbreviate both uniformly.
This incarnation of --set-env applies set variables globally to all apps,
it seems desirable to be able to specify target apps for the variables.
Limiting inheritance to specific apps may also be useful.

rkt: add --set-env to `rkt run` and `rkt prepare`

---

rkt/uuid.go

Though the uuid isn't returned until `rkt prepare` completes, it's still
discoverable via `rkt list`, and `rkt status --wait a01b` should work if
a01b is in the preparing phase.

rkt: include preparing containers when matching a uuid

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/spec/aci/file_test.go
Godeps/_workspace/src/github.com/appc/spec/schema/image_test.go
Godeps/_workspace/src/github.com/appc/spec/schema/types/isolator.go
Godeps/_workspace/src/github.com/appc/spec/schema/types/isolator_linux_specific.go
Godeps/_workspace/src/github.com/appc/spec/schema/types/isolator_resources.go
Godeps/_workspace/src/github.com/appc/spec/schema/types/isolator_test.go
Godeps/_workspace/src/github.com/appc/spec/schema/version.go
stage1/init/container.go

This is to capture the bugfix from https://github.com/appc/spec/pull/234
The real solution here is to fix https://github.com/appc/spec/pull/235, bump
the spec, and then vendor the new release, but rolling this in now so that
isolators are fixed on master.

Godeps: bump appc to latest master

---

pkg/keystore/keystore.go

Lets make everything under `/etc/rkt` be 0755. This makes install work perfectly with the following workflow.
```
groupadd rocket
usermod -a -G rocket philips
sudo rkt install
sudo rkt trust --prefix coreos.com/etcd
rkt fetch coreos.com/etcd:v2.0.4
sudo rkt run coreos.com/etcd:v2.0.4
```

Read only etc rkt

---

rkt/install.go
rkt/install_test.go

This new command sets rocket dirs' permissions so a member of the
"rocket" group can fetch and run images.
Note: Right now it's not possible to run an image because systemd-nspawn
requires root.
Addresses #43

rkt: add install command

---

Documentation/networking.md
networking/net.go

If a user supplies a net with name "default", rkt will not
instantiate its default net. Also warn and ignore duplicate
nets.

net: allow overriding default net

---

pkg/tar/tar.go

After fixing actool to include fifo file types, implements the functionality in rocket to extract same.

pkg/tar: implement tar.TypeFifo

---

cas/cas.go
cas/cas_test.go
cas/remote.go
rkt/fetch.go
rkt/run.go

The last commit is the interesting one. It's based on #393.
On fetching, if downloaded with the "latest" pattern (no version label
specified), the ACI is saved in the store with the "latest" flag.
In future, on "rkt fetch" or "rkt run", a way for the user to define if the
provided images (by local file or URL) should be saved in the store with the
lastest flag, should be provided. For doing this there's the need to find how
the user can request this for a specific file/URL as multiple files/URls can be
provided.
See appc/spec#73 for my thoughts about the need of the "latest" flag.

cas: Introduce latest pattern handling for image fetching.

---

networking/networking.go

Containers now migrate thru state directories so hard
coded path was broken

net: bug fix: don't use hard coded path to container dir

---

common/common.go
rkt/containers.go
rkt/run.go
rkt/run_prepared.go
stage0/run.go
stage1/init/container.go
stage1/init/init.go

By using systemd's StandardInput option we set /dev/console in stage1
as the tty for the app (see systemd.exec(5)). This makes interactive
executables like bash work with rkt run (or prepare+run-prepared).
This is only supported if the container has only one app.
Fixes #562

stage1: support interactive containers

---

cas/cas.go
cas/cas_test.go

GetACI returns the best ACI that matches the required app name and the
provided labels. If there are multiple matching ACIs choose the last one
imported in the store. If no version label is requested, ACIs marked as latest
in the ACIInfo are preferred.

cas: add a GetACI function.

---

pkg/tar/tar.go
pkg/tar/tar_test.go
pkg/tar/utimes_linux.go
pkg/tar/utimes_unsupported.go

This pull request depends on #275.
As the syscalls to restore a symlink modification times are not available (os.Chtime changes the linked file times) I used the github.com/docker/pkg/system that contains this functions and many other that can be very useful and tests (for example makeblockdev can be replaced with system.Mknod and used for various os).

Restore files and directories times (access and modification times).

---

stage1/rootfs/prepare-app/prepare-app.c

The bind mount on / was introduced by
https://github.com/coreos/rocket/pull/626 to fix the "Docker inside
Rocket" use case in https://github.com/coreos/rocket/issues/638
But this introduced a regression on volume mounted via "rkt run
-volume". This patch fixes the regression.
Regression discovered by @iaguis when testing Flannel from
https://github.com/coreos/rocket/issues/389

stage1: prepare-app: fix volumes during the root bind-mount

---

rkt/list.go

Introduces --full `rkt list` option to include full uuids.

rkt: abbreviate uuids in `rkt list` output

---

common/common.go
networking/net_plugin.go
pkg/lock/dir.go
pkg/sys/sys.go
stage0/run.go
stage1/init/init.go

When launching metadata service and net plugins,
set the close-on-exec flag so the child processes
don't end up holding the lock.

net: set FD_CLOEXEC on RktLock prior to fork/exec

---

stage1/rootfs/prepare-app/prepare-app.c

Interactive containers expect /dev/pts.
Also, make /dev/ptmx a symlink to /dev/pts/ptmx.
See https://www.kernel.org/doc/Documentation/filesystems/devpts.txt

stage1: prepare-app: prepare /dev/pts for apps

---

cas/cas.go
cas/cas_test.go
cas/tree.go
cas/tree_test.go
pkg/aci/aci.go

The last 4 commits are the relevant ones. The others are from #395 and #533.
As explained in #223 this PR adds a tree store.
The first patch provides the Write, Remove and GetRootFs functions
The second patch changes cas.WriteACI to call the tree store Write function (not sure if this should be done directly inside WriteACI or outside).
The third patch adds validity checking to the rendered ACI. As discussed in #223 using an archive/tar writer doesn't work as it doesn't create reproducible tars due to some maps in pax headers. This implementation uses a special writer the tries to keep a consistent fileinfo struct and write it (by now in json) and the file contents to an hash writer. There are some TODOs that needs some thoughts.
Thanks!

cas: add a tree store (#223)

---

pkg/keystore/keystore.go

Show the filename & fingerprint for the mismatching key to assist
troubleshooting.
Targeting https://github.com/coreos/rocket/issues/655

keystore: improve fingerprint mismatch error message

---

cas/cas.go

WriteStream isn't used and shouldn't be used as it just writes a stream of data
to the blob store. This work should be done using WriteACI that correctly
handles an ACI.

cas: remove WriteStream method.

---

rkt/fetch.go

Or it will panic calling fetchImageFromEndpoints.
By now appc/spec discovery.DiscoverEndpoints doesn't return an error if no endpoints are found. I'm not sure if this is a wanted behavior or should be fixed there.
In past I proposed PR #382 that will automatically avoid this as it iterates over all the endpoints.

rkt: check that at least one endpoint has been discovered.

---

common/common.go
rkt/containers.go
rkt/enter.go
rkt/prepare.go
rkt/run.go
rkt/run_prepared.go
stage0/enter.go
stage0/run.go

This mounts stage1 and the application images as an overlay filesystem
using each ACI's cached tree as the lower filesystem.
Also, the mounts are done in a separate mount namespace so they will be
unmounted when the container exits and they're not visible by the rest
of the system.
Systems that don't support overlay fall back to plain copying.
Addresses #387

rkt: support overlay filesystem

---

common/common.go
rkt/containers.go
rkt/status.go
stage0/run.go

When using overlay fs rkt status stopped working because it searched for
the status file in the stage1 rootfs, which is either in a different
mount namespace or unmounted.
If the container uses overlay fs, we now search in its upper layer,
which is accessible outside the mount namespace or when the filesystem
is not mounted.
Fixes #665

rkt: fix status with overlay

---

scripts/vagrant/install-rocket.sh

Last change introduced in issue where the
squashfs tools were no longer installed if missing.
This corrects that issue

Vagrant: Bug no squashfs-tools.

---

stage1/init/container.go
stage1/init/container_test.go

stage1: Override image manifest's readOnly field for volume mounts.

---

scripts/debug/stage1_install_busybox.sh

Add a script to copy busybox into stage1 for debugging purposes. It
takes a container UUID and outputs the nsenter command needed to enter
stage1's namespaces.
When using overlay filesystem, a new mount namespace will be created for
stage1. This script enters this namespace to copy busybox.

scripts: debug: add script to install busybox in stage1

---

common/common.go

This was breaking prepare/run-prepared because it expected the file to
be named "pod".  Rename it accordingly.

common: rename PodManifest: "container" -> "pod"

---

stage0/run.go

Having the permissions of overlay, upper and work dirs set to 0700 makes
"/" in the container have 0700 permissions, which breaks images that try
to execute files as different users.

stage0: fix overlay dir permissions 0700 -> 0755

---

common/common.go
rkt/metadata_service.go
stage0/run.go
stage1/init/registration.go

Using allows Unix socket allows for limiting who can
register/unregister containers by setting proper
permissions on the socket.
Fixes #437

mdsvc: use Unix socket for registration

---

stage0/run.go

When not using overlay fs, the tree cache was not getting populated.
Since we now take the enter binary from the tree cache, this was
breaking rkt enter.
We now populate stage1's tree cache in every case. We don't do it for
the app images because it can add a significant amount of time in the
first run if the image is big and it's not needed unless you use overlay
fs.
Fixes #683

rkt: fix enter when running without overlay fs

---

common/common.go
rkt/prepare.go
rkt/run.go
stage0/run.go

Adds an option to not disable overlay filesystem.
Since this option is listed in https://github.com/coreos/rocket/releases/tag/v0.5.1 I thought it'd be nice to actually have it :P. I called it `--no-overlay` because that's the official name of the filesystem.

rkt: add --no-overlay option

---

stage1/rootfs/aggregate/aci-manifest

This has little significance until we start keying off version numbers, but might as well keep it in sync for now.

stage1: bump acVersion

---

common/common.go
networking/net/net.go
networking/net/veth/veth.go
networking/net_plugin.go
networking/networking.go
rkt/metadata_service.go
stage1/init/init.go

Since the spec requires AC_METADATA_URL env var,
well known IP is no longer needed. This removes
the iptables manipulation. Instead the IP address of the
host is passed in the AC_METADATA_URL. This host IP
is the address of the host end of the default veth.

mdsvc: no more 169.254.169.255 address

---

rkt/metadata_service.go
rkt/metadata_service_test.go

There was a bug in that there was no mutex to protect
concurrent access to maps. This patch fixes that by
introducing a mutex protected store. It also updates
code for container->pod rename.

mdsvc: introduce podStore as synchronized data structure

---

rkt/containers.go

Add definitions for external states which are visible to users so
that other libraries and make use of them.
Fix #669

rkt: Export external states.

---

cas/cas.go
rkt/fetch.go
rkt/fetch_test.go

```
--- FAIL: TestDownloading (0.01s)
fetch_test.go:188: error downloading aci: error downloading the aci image: error downloading ACI: open /var/lib/rkt/tmp/691547836: permission denied
```
This was introduced in https://github.com/coreos/rocket/commit/835787be94ce668b788ed47e6c1e8c0358dcf932 , which introduced a new `tmpDir()` helper unassociated with the cas. Unfortunately that means that even though we initialise the cas with a [custom tmpdir in the test](https://github.com/coreos/rocket/blob/190ba4257d668c3a38b733c20d99d9cc909e51c3/rkt/fetch_test.go#L170), the download function [still relies on the global directory argument](https://github.com/coreos/rocket/blob/190ba4257d668c3a38b733c20d99d9cc909e51c3/rkt/fetch.go#L361).

fetch: download does not use correct tmpdir during tests

---

Documentation/networking.md
networking/networking.go
networking/portfwd.go
rkt/cli_apps_test.go
rkt/prepare.go
rkt/run.go
stage0/run.go
stage1/init/init.go

Ports that were defined in app manifest can be
exposed via --port=name:host-port option on cmd line.
For example, given app manifest with ports entry:
{
"name": "http",
"port": 80,
"protocol": "tcp"
}
rkt run --private-net --port=http:8888 myapp.aci
will forward traffic from host's tcp port 8888 to
container's port 80.
Fixes #624

net: add option to expose ports on hosts

---

networking/portfwd.go

If no ports are exposed, no corresponding iptables rules get installed.
Unfortunately, on the teardown path, there's no good way to test for
that or issue deletes that succeed if there's nothing to do. Therefore
it's better to just ignore these errors on the cleanup path.

net: bug fix: suppress errors printed out if no ports were exposed

---

rkt/enter.go
rkt/fetch.go
rkt/fetch_test.go
rkt/images.go
rkt/prepare.go
rkt/run.go
rkt/run_prepared.go
stage0/run.go
store/aciinfo.go
store/aciinfo_test.go
store/db.go
store/remote.go
store/remote_test.go
store/schema.go
store/store.go
store/store_test.go
store/tree.go
store/tree_test.go
store/utils.go
store/z_last_test.go
test

The cas package implements more than just a CAS, so this patch gives it
a suitably generic name.
Fixes #707
(Go newbie here, let me know if I missed anything!)

cas: rename to store

---

Documentation/app-container.md
Documentation/metadata-service.md
rkt/metadata_service.go
rkt/metadata_service_test.go
rkt/run.go
rkt/run_prepared.go
stage0/run.go

Also remove --no-idle from metadata-service since it
is no longer required. It was really only useful with
--spawn-metadata-svc but also racy.
Fixes #724

rkt: remove --spawn-metadata-svc option from run cmd

---

rkt/images.go
rkt/prepare.go
rkt/run.go

This patch adds a -local flag to use only local images (if available) from the
local store.
If the provided image name is a URL-like app name (like coreos.com/etcd:2.0.9)
then discovery is disabled and the image is searched in the store using
cas.GetACI.
If the provided image name has an "http", "https", "docker" scheme it will avoid
downloading if it's not in the store (not existing in the remote table).
This can be useful to use rkt in offline mode or to just simply avoid
downloading.

rkt: add -local flag to run/prepare.

---

store/db.go
store/migrate.go
store/migrate_test.go
store/schema.go
store/store.go

This patch adds migrate codes and tests. It simply updates the current db
version to 1 without changing the schema.
The migration needs an exclusive store lock to avoid concurrent old rkt versions
operating to an updated db and returning strange errors or giving bad behaviours.
As the store lock is removed when spawning the stage0, migration isn't blocked by
running containers but only by rkt processes doing store operations (like
downloading an image, rendering an aci etc...).
By now no reports are done to the user if waiting for a store global lock, this to avoid the store writing to stdout. If this is needed, probably the store functions should be changed to add a migrate bool to NewStore (or an additional CheckMigrate functions) to call so the various rkt commands can know and log …

store: add migrate code and tests.

---

Documentation/hacking.md

When rkt needs to switch to a new version of appc/spec, a developer needs to use `godep` to update the deps based on `Godeps/Godeps.json`.
It would be good to document how to do that in Documentation/hacking.md

Documentation/hacking.md: how to use godep

---

rkt/run.go

rkt complains with "run: interactive option only supports one image" when trying to execute an image in interactive mode with arguments

rkt: bug fix: -interactive doesnt work with args

---

pkg/lock/keylock.go

* the keylock FileLock wasn't closed on error in createAndLock
* fd for changed file detection wasn't closed.

lock: add missing closes in keylock.

---

rkt/enter.go
stage0/enter.go

d12615f hard-coded the enter binary to accomodate overlayfs, this goes
back to using the entrypoint annotation.
Fixes #772

rkt: use entrypoint annotation to resolve enter

---

rkt/install.go
store/db.go

Create all cas directories explicitly and create qldb files with the
right permissions.
If we don't create them and the first fetch is made by root, the
files/directories will be created with root permissions and following
fetches as a user belonging to the rkt group will fail.

install: fix rkt install again

---

rkt/gc.go
stage0/gc.go

When using overlay, the stage1 filesystem is mounted in a separate mount
namespace, rkt can't access the gc binary.
We now get the gc binary from the tree cache, using the stagee1 image
the user specified when preparing/running the container.

rkt: fix gc when using overlay

---

pkg/sys/sys_linux.go
pkg/sys/sys_linux_386.go
pkg/sys/sys_linux_amd64.go
pkg/sys/sys_linux_arm.go
rkt/pods.go
rkt/prepare.go
store/tree.go

This PR implement suggestions from https://github.com/coreos/rkt/issues/693#issuecomment-89003434.
`sys: add linux syncfs syscall.` adds a linux syncfs syscall. Perhaps someone should prefer the cgo way. Just let me know.
`store: use syncfs instead of syncing every file on TreeStore.Write().` converts the treestore to use the linux syncfs syscall.
`rkt: sync prepared pod file contents on disk` before returning a prepared pod uuid ensures that its contents are synced to
disk. This avoid problems running an inconsistent pod if the machine crashes
between preparing and running a pod.
This is done in two steps:
* Before calling p.xToPrepared sync all contents on disk. By now syncfs is
used as suggested in #693.
* After calling p.xToPrepared sync the PreparedDir (the parent dir of all
prepared …

rkt: sync prepared pod file contents on disk and use syncfs also in treestore

---

rkt/fetch.go
rkt/prepare.go
rkt/rkt.go
rkt/run.go

In the same way as we allow overriding rkt data directory. Can be
useful for some functional tests that need clean state. With those
parameters these tests could set their own data and configuration
directories.

rkt: Allow overriding configuration directory paths

---

tests/build
tests/test

It is now possible to run only one functional test, see the instructions
in tests/test.
The build script is also more reliable.

functional tests: improve scripts

---

Documentation/configuration.md
rkt/config/auth.go
rkt/config/config.go
rkt/config/config_test.go
rkt/fetch.go
rkt/images.go
rkt/prepare.go
rkt/run.go

Please see commit messages to see config format.

Add config for docker auth

---

Documentation/configuration.md
common/common.go
pkg/keystore/keystore.go
rkt/config/config.go
rkt/config/config_test.go
rkt/rkt.go
tests/rkt_auth_test.go

This is a continuation of #778. It reuses --vendor-config and --custom-config to set up keystore parameters.
This somewhat conflicts for now with #760 - that PR uses constants from rkt/config package which were moved to common package in this PR.

Allow setting keystore paths from cmdline

---

tests/install-deps.sh
tests/rkt_env_test.go

The new Semaphore platform has most packages already installed.
Use awk instead of gawk in functional tests: awk is more commonly installed than gawk.

Semaphore: reduce dependencies for faster functional tests

---

Documentation/getting-started-guide.md

- Be consistent with tabs/spaces in json
- Always put a newline between a code section and previous paragraph

Documentation: fixup formatting on getting-started

---

Documentation/configuration.md
Documentation/getting-started-ubuntu-trusty.md
Documentation/hacking.md

Add more paragraphs between code blocks and text. This fixes rendering
errors on jekyll.

Documentation: Fixup more missing paragraphs

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/mitchellh/ioprogress/reader.go

It fixes a bug that caused the progress bar never to reach the end.

Godeps: bump ioprogress dependency

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/ThomasRooney/gexpect/gexpect.go
Godeps/_workspace/src/github.com/ThomasRooney/gexpect/gexpect_test.go
stage1/init/pod.go
stage1/rootfs/diagexec/diagexec.c
stage1/rootfs/enter/enter.c
tests/inspect/inspect.go
tests/rkt_caps_test.go

Fix #539 by adding `setresuid` and `setresgid` in `diagexec`.
I preferred a solution based on RootDirectory (#679) but this was not ready yet.

run apps as non-root user (diagexec setresuid)

---

rkt/enter.go
rkt/pods.go
stage0/enter.go
stage1/rootfs/enter/enter.c

- Fixup pod.getPID() to cover race between xToRun() and stage1 getting
around to writing the pid file.
- Rework `rkt enter` to retrieve the pid in rkt/stage0 and supply it to
stage1 enter.
- Rework stage1 enter to consume pid from argv instead of opening it
itself, so as to not have to duplicate the same race coverage.
- Some stage1 enter code cleanups thrown in for good measure, particularly
around the argv forwarding copy which started simple had become unwieldy.

rkt/enter: use pod.getPID() to get container's pid race-free

---

rkt/fetch.go
rkt/images.go
rkt/prepare.go
rkt/run.go

After fetching an image also fetch recursively all its dependencies.
Dependencies needs to be resolved using discovery as the unique useful
informations (as per spec) are the app name and the labels.
Image fetching and dependencies fetching could be done in a single function but
they are left split in two functions as sometimes, for example when importing
images from disk, it'll be useful to disable dependencies fetching.
By now, findImage in rkt/run.go will call fetchImage with withDep = true.
For testing there'll be the need of faking discovery. By now its quite difficult
to fake the meta discovery mechanism. There'll be the need of something like
appc/spec#110
This will probably clash with #509.

rkt: fetch images dependencies.

---

rkt/pods.go

In order for `os.IsNotExist(err)` to work, need to change the returned error.
/cc @vcaputo

rkt/enter: Change the returned error type to fix getPID().

---

test
tests/rkt_auth_test.go
tests/rkt_caps_test.go
tests/rkt_env_test.go
tests/rkt_exit_test.go
tests/rkt_interactive_test.go
tests/rkt_tests.go
tests/rkt_volume_test.go
tests/test

It introduces rkt run context which uses `--dir`, '--local-config` and `--system-config` flags to avoid using default values. So functional tests can be ran on local computer without worrying about messed up or deleted /var/lib/rkt or configuration.

non destructive functional tests

---

test
tests/inspect/inspect.go
tests/rkt_auth_test.go
tests/test-auth-server/aci/server.go

Commits in this PR do:
1. Run `go vet` against packages mentioned in `FORMATTABLE` instead of `TESTABLE_AND_FORMATTABLE` and extend the list of packages in `FORMATTABLE`.
3. Fix issues in inspect and networking.
4. Replace the hardcoded list of packages with inexplicable magic.
5. Remove dead unit test file from networking - outdated, does not build, never executed.
cc @alban @eyakubovich for `go vet` fixes.

Check more packages with gofmt and go vet

---

tests/rkt_env_test.go
tests/rkt_tests.go

Avoid child.Close(), prefer child.Wait()
Depending on the kernel version, it's not allowed to delete a directory if it is a mount point, even in another mount namespace.
functional tests: better panic error messages
printing a string is more readable than printing a array of bytes

functional tests: environment: fix a race between child.Close() and ctx.reset()

---

rkt/imageslist.go
store/aciinfo.go
store/store.go

This adds a new command "rkt images" to display the images in the store.
The -fields option let the user provide a comma separated list of fields to display. Accepted values: "key", "appname", "importtime", "latest".
The -sort option permits to sort the output according to the provided comma separated list of fields. Accepted values: "appname", "importtime".
The ordering is ascending by default but can be configured with the -order=[asc|desc] option.
By default all the available fields ("key", "appname", "importtime", "latest") are displayed sorted by ascending "importtime".
If the image has a version label its written in the app name (with the ":$version" format).
In future additional options can be provided:
* show all the labels
* define displayed time format (for example human format …

rkt: add command to list images in the store.

---

rkt/rmimage.go
store/aciinfo.go
store/remote.go
store/store.go
store/store_test.go

This should go after #571 and the interesting commits are the last two.
This adds a new command `rkt rmimage` to remove one or more images from the
store providing a key uniquely resolvable.
The logic is to firstly remove transactional data (the rows in the aciinfo and
remote db tables for the given key) and then remove non transactional data (the
diskv blob and imageManifest stores).
The tree store is removed separately and only if an image hash related to the
tree store key isn't referenced by any preparing/prepared/running pod.
This means that an image can be removed (from the db and the blob/imageManifest
stores) but not from the treestore.
As removal of non transactional data can fail for multiple reasons some data
can remain stale, the same applies if the treestore can't be removed …

rkt: add command to remove one or more images from the store.

---

networking/net_plugin.go
networking/networking.go
networking/podenv.go

rktRoot is misleading as the directory is really the root of a specific pod.
Also add a TODO note that this is currently only ever set to cwd
(i.e. "."), and hence necessitates relative paths.

networking: podRoot -> rktRoot

---

networking/net_plugin.go

As discovered in #851 - some of the CNI plugins (for example, veth) relies on
the supplied `CNI_NETNS` as a source of uniqueness for things like entropy. In
theory this is reasonable because network namespace paths should be unique
per-pod. However, in rkt, the stage1 init (which executes the plugins) was
passing a relative path from its cwd, rather than an absolute path - for
example, "netns" rather than
"/var/lib/rkt/pods/foobarbaz/netns".
As a consequence of this, every network plugin was executed with the same
value for `CNI_NETNS`. This results in conflicts when e.g. every veth plugin
attempts to create an interface by the same name, since they do a
straightforward hash of `CNI_NETNS` to generate interface names.
This should be considered an interim solution until this is …

networking: make netns path absolute for CNI plugins

---

stage1/init/init.go

Instead of using image manifest to get forwarded ports, we should
use pod manifest.
@eyakubovich @jonboulle

stage1/init: Use pod manifest to get forwarded ports

---

scripts/vagrant/install-rkt.sh

Before this change, when I run `sudo rkt trust` it fails. I hope
we can also install rkt under usr/local/bin by default. So our
users can have a better experience when following our rkt basic
tutorial.
This issue was introduced by a recent script rewrote (#652)

script/vagrant: cp the build target to usr bin

---

Vagrantfile

I had to do this last Sunday to get `rkt trust --prefix quay.io` working.
See the thread at ServerFault for more info http://serverfault.com/a/595010

vagrantfile: fix slow VM DNS

---

README.md

For those completely new to rkt and the appc spec, we should clearly signal from the landing page (i.e. README) how they can get started building ACIs, and where they can go for more information.
We do touch on it in the getting started guide, but that isn't even referenced from the README at present.

docs: intro building ACIs in README

---

Documentation/hacking.md

The commit message of https://github.com/jonboulle/rkt/commit/10beb3920debb0be135ae6cecee2ca55fbc43169 contains useful information for developers and package maintainers, about how `RKT_STAGE1_IMAGE` will influence the build.
This information should be more obvious to someone who is getting started with rkt.
A good place to start would be to include it in the *hacking* docs:
* https://github.com/coreos/rkt/blob/master/Documentation/hacking.md#building-rkt

documentation: make RKT_STAGE1_IMAGE more obvious

---

tests/rkt_auth_test.go
tests/rkt_caps_test.go
tests/rkt_env_test.go
tests/rkt_exit_test.go
tests/rkt_interactive_test.go
tests/rkt_volume_test.go

This can help us to reason about the failures more easily.

rkt/tests: Print out the error info on failures.

---

tests/rkt_exit_test.go

Since systemd commit f2341e ("core,network: major per-object logging rework"),
systemd does not log "main process exited" but "Main process exited" (notice
the uppercase).
Improve the test to accept both strings.
Fixes #891.

functional tests: update string from systemd

---

Documentation/running-docker-images.md
Documentation/signing-and-verification-guide.md
rkt/images.go
rkt/rkt.go
rkt/trust.go

- insecure-skip-verify is used in image fetch and trust for skipping
verification, document this in the flags usage
- make the docs more explicit about what insecure-skip-verify does
We will split this sledgehammer flag into multiple flags via #912

rkt: make warning map to `insecure-skip-verify` usage

---

stage1/init/init.go

In systemd-209 libsystemd-login was merged into libsystemd and a
compatibility libsystemd-login library was created. Unfortunately,
distributions like Fedora don't ship the compatibility libraries so
runningFromUnitFile will always return false.
Fix it by dlopening libsystemd.so instead of libsystemd-login.so.

stage1: dlopen libsystemd instead of libsystemd-login

---

networking/podenv.go

All files found in UserNetPath that don't match the suffix '.conf' will be
ignored as a network configuration file.
Fixes #859.

networking: load only *.conf files

---

tests/install-deps.sh

Semaphore updated their platform on May 19th. The dependencies are
already installed.

functional tests: semaphore: update dependencies

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/cni/pkg/ip/link.go
Godeps/_workspace/src/github.com/appc/cni/pkg/plugin/ipam.go
Godeps/_workspace/src/github.com/appc/cni/pkg/plugin/types.go
Godeps/_workspace/src/github.com/appc/cni/pkg/skel/skel.go
Godeps/_workspace/src/github.com/appc/cni/plugins/ipam/host-local/main.go
Godeps/_workspace/src/github.com/appc/cni/plugins/main/bridge/bridge.go
Godeps/_workspace/src/github.com/appc/cni/plugins/main/ipvlan/ipvlan.go
Godeps/_workspace/src/github.com/appc/cni/plugins/main/veth/veth.go
stage1/dummy.go

This plugin is very similar to macvlan but let's the secondary interfaces use
the primary interface's MAC address instead of generating their own one.
Fixes #479

stage1: add ipvlan network plugin

---

stage0/run.go

When using overlayfs, we read the status directory from its upper layer
since the fs might be unmounted or in another mount namespace. If the
directory is not modified it won't be in the upper layer causing the
status command to fail.
We touch the directory to force the status directory to be in the upper
layer of the overlayfs.
Fixes #856

stage0: touch status directory when using overlay fs

---

rkt/rmimage.go
tests/rkt_image_rm_test.go

Also stage1 should be considered a referenced image. Stage1 gc will fail with an error if the stage1 image is removed before the gc (as the gc binary cannot be found in the tree store).
Functional tests are added for image removal.

rkt/rmimages: consider also stage1 as referenced image and add functional tests.

---

stage1/rootfs/usr_from_src/patches/v220/0001-nspawn-add-pid-file.patch

This fixes the compilation for:
RKT_STAGE1_USR_FROM=src RKT_STAGE1_SYSTEMD_VER=v220
By copying the patch from:
stage1/rootfs/usr_from_src/patches/master/0001-nspawn-add-pid-file.patch
to:
stage1/rootfs/usr_from_src/patches/v220/0001-nspawn-add-pid-file.patch
There is ongoing work to build stage1 without patches on systemd but
it's not ready yet.
The ./build script still use v219 by default.

stage1: fixes compilation on systemd-v220 (flavor=src)

---

pkg/aci/render.go
pkg/multicall/multicall.go
pkg/sys/capability.go
pkg/tar/chroot.go
pkg/tar/tar.go
pkg/tar/tar_test.go
rkt/rkt.go
store/store_test.go
store/tree.go
store/tree_test.go
tests/run-build.sh

this introduces tar extraction inside a chroot. This is done spawning a
new process. Instead of creating a new executable (difficult to find,
package etc...) it adds the concept of a multicall process (like busybox).
Now a new multicall command "extracttar" is added.
tar.ExtractTar executes this new command passing a pipe to send the
filesMap and the tar contents to stdin.
The incomplete "insecure link" checks are removed from the the tar
functions.  Additionally these functions are now not exported and the
extraction directory is always the root directory.

aci: extract tar in chroot

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/docker2aci/lib/backend/file/file.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/backend/repository/repository.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/common/common.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/docker2aci.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/util/util.go
rkt/images.go
stage1/init/init.go
stage1/init/pod.go

fetch: docker2aci: use the correct tmpDir
This requires a new version of docker2aci in Godeps. And the new version of docker2aci requires a new version of appc/spec. Update both accordingly.
Fixes: https://github.com/coreos/rkt/issues/839

update appc/spec and docker2aci for tmpdir #839

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/dbus.go
Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/dbus_test.go
Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/methods.go
Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/methods_test.go
Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/properties.go
Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/set.go
Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/set_test.go
Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/subscription.go
Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/subscription_set.go
Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/subscription_set_test.go
Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/subscription_test.go
Godeps/_workspace/src/github.com/coreos/go-systemd/unit/deserialize.go
Godeps/_workspace/src/github.com/coreos/go-systemd/unit/deserialize_test.go
Godeps/_workspace/src/github.com/coreos/go-systemd/unit/escape.go
Godeps/_workspace/src/github.com/coreos/go-systemd/unit/escape_test.go
Godeps/_workspace/src/github.com/coreos/go-systemd/unit/option_test.go
Godeps/_workspace/src/github.com/coreos/go-systemd/unit/serialize.go
Godeps/_workspace/src/github.com/coreos/go-systemd/unit/serialize_test.go
Godeps/_workspace/src/github.com/coreos/go-systemd/util/util.go
tests/inspect/inspect.go
tests/rkt_service_file_test.go
tests/rkt_tests.go

This test requires systemd on the host. It will be disabled when systemd is not running on the host.
You can start it manually with:
```
cd tests && ./test -run=TestServiceFile
```
It prints "HelloWorld" repetitively until the test stops it after 10 seconds.

functional tests: start rkt from a systemd service file

---

Documentation/devel/release.md

The build can be modified by several environment variables. Make sure releases are built with the default options.
```
RKT_STAGE1_USR_FROM=
RKT_STAGE1_SYSTEMD_SRC=
RKT_STAGE1_SYSTEMD_VER=
RKT_STAGE1_IMAGE=
```

documentation: release guide: compilation options

---

rkt/metadata_service.go
stage1/init/registration.go

When registering a pod to the metadata service, if individual app 
registrations failed then an error object was being instantiated but not 
actually returned. This fixes it to return the error and also to make a 
best-effort attempt to unregister the pod in this scenario.
Also tweaks the file operations to close manifests more immediately after
they've been used.
Also fixes minor typo in rkt/metadata_service error message.
/cc @eyakubovich

stage1: fix metadata service registration errors

---

tests/rkt_cat_manifest_test.go

This PR adds a functional test to run `rkt image cat-manifest` against a local image, a hash, and non-existed image/hash. I am also thinking about running this against a remote image, but not sure which one is an ideal target (maybe etcd ACI?)
Note that this PR have a dependency on https://github.com/coreos/rkt/pull/931

tests: Add rkt_cat_manifest_test to exercise 'rkt image cat-manifest'.

---

tests/rkt_exit_test.go

Since commit 76ed159 ("functional tests: TestFailure: don't rely on
systemd debug logs"), TestExitCode didn't test anything and always
passed.
Fortunately, there was no regression bugs introduced in rkt. So no harm
done. But let's fix the test to catch potential future regression bugs.

functional test: TestExitCode: fix test

---

pkg/tar/utimes_unsupported.go
test

Dumb test looking for either a Copyright header or sign that the file was
autogenerated (e.g. by `go generate`) in all non-Godep .go files.
Also moves the actual unit/functional tests after the pre-flight checks
(gofmt, go vet, this new check)

test: add check for license header

---

networking/net_plugin.go
networking/networking.go

This also undoes the temporary work around
of using absolute paths for pod directories.
Fixes #953

networking: fix gc cleaning up networks

---

networking/netinfo/netinfo.go
networking/networking.go
networking/podenv.go
stage1/init/init.go

This commit allows the mentioned environment var to be populated correctly.
On the way some error handling for involved code was added.
Fixes #962
Fixes #875

networking: populate AC_METADATA_URL correctly

---

Documentation/networking.md
common/common.go
networking/networking.go
networking/podenv.go
rkt/run.go
rkt/run_prepared.go
stage0/run.go
stage1/init/init.go
stage1/rootfs/net/99-default-restricted.conf
stage1/rootfs/net/Makefile

Alternative implementation of #954 that uses a common type for the argument handling in stage0 and stage1.
Fixes #874. Closes #954.

networking: allow network selection with private-net (2nd impl.)

---

tests/README.md

This is following-up the bump to v220: https://github.com/coreos/rkt/pull/952
I checked the other occurrences of v219 (`git grep "v219"`) and they don't require other changes.
@jonboulle : this requires some changes in the Semaphore configuration.
/cc @steveeJ

functional tests: test v220

---

README.md

The `vagrant up` command fails on OSX with the message `The box 'ubuntu/trusty64' could not be found.` Upgrading vagrant solves the     problem.

Clarify required version of vagrant

---

common/cgroup_util.go
common/cgroup_util_test.go
stage0/run.go
stage1/init/init.go
stage1/init/pod.go
stage1/rootfs/usr_from_src/patches/v219/0005-nspawn-only-mount-the-cgroup-root-if-it-s-not-alread.patch
stage1/rootfs/usr_from_src/patches/v219/0006-nspawn-skip-symlink-to-a-combined-cgroup-hierarchy-i.patch
tests/image/manifest

To allow systemd inside stage1 to set resource limits for apps we mount
the cgroup controllers hierarchy in rkt. We need this because
systemd-nspawn mounts cgroup controllers as read-only.
We mimic systemd-nspawn cgroup mounts with the difference that we
bind-mount the apps' subdirectories over themselves so they stay
read-write. We leave the mounting of systemd's cgroup hierarchy to
nspawn.
Addresses (partially) #811

stage1: support per-app memory and cpu isolators

---

stage1/init/init.go

It wasn't taking into account if the cgroup controller was enabled or
not.

stage1: fix parseCgroups function

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/goaci/proj2aci/asset.go
Godeps/_workspace/src/github.com/appc/goaci/proj2aci/binary.go
Godeps/_workspace/src/github.com/appc/goaci/proj2aci/builder.go
Godeps/_workspace/src/github.com/appc/goaci/proj2aci/cmake.go
Godeps/_workspace/src/github.com/appc/goaci/proj2aci/go.go
Godeps/_workspace/src/github.com/appc/goaci/proj2aci/run.go
Godeps/_workspace/src/github.com/appc/goaci/proj2aci/util.go
Godeps/_workspace/src/github.com/appc/goaci/proj2aci/vcs.go
Godeps/_workspace/src/golang.org/x/tools/go/vcs/discovery.go
Godeps/_workspace/src/golang.org/x/tools/go/vcs/env.go
Godeps/_workspace/src/golang.org/x/tools/go/vcs/http.go
Godeps/_workspace/src/golang.org/x/tools/go/vcs/vcs.go
Godeps/_workspace/src/golang.org/x/tools/go/vcs/vcs_test.go
build
stage1/dummy.go
stage1/init/init.go
stage1/init/pod.go
stage1/rootfs/Makefile
stage1/rootfs/aggregate/aggregate.sh
stage1/rootfs/usr_from_host/Makefile
tests/README.md
tests/test

As mentioned on https://github.com/coreos/rkt/issues/686#issuecomment-101305256, I would like to have a new build flavor:
```
RKT_STAGE1_USR_FROM=host ./build
```
to build `stage1.aci` without `systemd` or `systemd-nspawn`. `systemd` or `systemd-nspawn` would be taken from the host at run-time. It would just fail if the host does not have those. This would be useful for Linux distributions packagers who have policies restricting "convenience copies of code" and access to internet.
This is proof-of-concept code based on top of #910 to work on a non-patched systemd-v220. I have tested it on Debian-sid with systemd-v220.
My stage1.aci contains the following:
```
$ tar tvf  bin/stage1.aci
drwxr-xr-x 1000/1000         0 2015-06-02 16:16 rootfs
-rwxr-xr-x 1000/1000    750992 2015-06-02 16:16 …
```

Introduce new build flavor: usr-from-host

---

stage1/init/init.go

See:
http://www.freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge/
flavor usr-from-host was working on Debian and Ubuntu but not on Arch and Fedora.

stage1, flavor usr-from-host: look in /usr/lib first

---

stage1/init/init.go

--link-journal=host fails if the host system doesn't have persistent
journaling enabled. Fix that by using "try-host"; if the system has
persistent journaling enabled it links the journal, otherwise it skips
the linking without exiting with a failure.
In 969a57c6 (stage1: use --link-journal=host instead of try-host) we
switched from "try-host" to "host" to support journal linking in systemd
versions <219 but now we don't support it on them anymore.
Fixes #1000

stage1: use --link-journal=try-host in systemd-nspawn

---

stage1/rootfs/aggregate/install.d/99misc
stage1/rootfs/aggregate/units/halt.target

When systemd-nspawn receives a TERM signal it will send it to systemd in
stage1 which will try to run the halt.target. This target was not
present in the current stage1 so the container was not being shut down.
Fix this by adding halt.target which calls reaper.service to shut down
the container cleanly.
Fixes #1008

stage1: add halt.target

---

build

$OSTYPE is "linux" on OpenSUSE 13.2.
uname should be more reliable.
Fixes: https://github.com/coreos/rkt/issues/1005

build: fix on OpenSUSE

---

pkg/fileutil/fileutil.go
pkg/fileutil/utimes_linux.go
pkg/fileutil/utimes_unsupported.go
pkg/tar/tar.go
stage0/run.go

Since we render the stage1 image anyway, if we don't use overlay fs, we
copy its rootfs from the tree cache instead of extracting it every
single time.
Addresses #693

stage0: copy stage1 image from tree cache instead of extracting it

---

stage1/init/cgroup.go
tests/inspect/inspect.go
tests/rkt_app_isolator_test.go

This test checks that the cpu isolator is applied by reading the values
cpu.cfs_period_us and cpu.cfs_quota_us of the process cgroup knob and
converting them to milli-cores.

functional tests: cpu isolator test

---

test
tests/README.md

The functional tests are already guarded by $CI, no need to restrict to
SemaphoreCI and CircleCI. I will need this change for Jenkins.

Functional tests: do not restrict to Semaphore

---

Documentation/app-container.md
Documentation/commands.md
Documentation/devel/pod-lifecycle.md
Documentation/getting-started-guide.md
Documentation/getting-started-ubuntu-trusty.md
Documentation/networking.md
Documentation/running-docker-images.md

Rewriting these links to be absolute instead of relative. Doesn't change anything when browsing on Github but makes it easier to manipulate via regex for display on coreos.com

Docs: Remove relative links

---

stage1/rootfs/usr_from_src/Makefile

When a test fails because of systemd, it is useful to know which version
of systemd was used exactly. But this information is not always known:
when stage1 is build with systemd from git-master, we don't know exactly
which commit was used for the build because git-master moves often.
Write the git version both in the build logs (useful for continuous
integration) and in stage1.aci.
Unfortunately, git-describe does not always work well on repository
cloned with --depth so I am removing the --depth optimization.
I am thinking of "systemd-nspawn: double free" [errors](https://github.com/coreos/rkt/pull/980#issuecomment-110189255).

stage1: flavor src: print systemd version with git-describe

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/coreos/go-systemd/unit/option.go
common/cgroup/cgroup.go
common/cgroup/cgroup_test.go
stage1/init/init.go
stage1/init/pod.go
tests/build
tests/image/manifest
tests/inspect/inspect.go
tests/rkt_app_isolator_test.go

This allows sharing functions between stage1 and the functional tests.
Depends on coreos/go-systemd#91 and #1036

common: move cgroup.go from stage1/init to common/cgroup

---

tests/test

When the host does not have systemd >= v220, we cannot use stage1 built
with flavor=usr-from-host.

Functional tests: disabled on flavor=usr-from-host & host systemd < v220

---

stage1/rootfs/usr_from_coreos/cache.sh

wget has the benefits of retrying automatically, which can reduce
the chance that downloading the pxe image fails.
Also it will fails on some fatal errors (where `curl --output` seems to always return 0)
Any consideration on not using wget at the first place? For portability? @vcaputo

stage1/rootfs/usr_from_coreos/cache.sh: Replace curl with wget.

---

stage1/rootfs/usr_from_src/Makefile

When compiling the src flavor, systemd will be cloned from the URL given
in $RKT_STAGE1_SYSTEMD_SRC. The Makefile assumed that
$RKT_STAGE1_SYSTEMD_SRC ends with "systemd" but that might not be the
case. Fix the Makefile.

stage1: flavor=src: fix git clone directory

---

stage1/init/init.go

86ad903 bumped the image version for RKT_STAGE1_FROM=coreos and in
doing so removed the LD_LIBRARY_PATH and interpreter overrides. However
we still need those to ensure the stage1 is truly self-contained and
does not have dependencies on host libraries.

stage1: revert interpreter changes in coreos build

---

CHANGELOG.md
Documentation/devel/release.md

We've previously use git tags for change logs, but let's move to a
dedicated file which is a bit more robust and easier to introspect.
Also update release documentation to reflect this.

*: introduce CHANGELOG

---

tests/rkt_service_file_test.go

After moving to the Cobra CLI framework, flags need to start with "--".
This was not exposed by Semaphore becase we skip this functional test there.

functional tests: fix rkt flags in TestService

---

rkt/image.go
rkt/image_list.go
rkt/image_rm.go
tests/rkt_image_rm_test.go

This patch moves `rkt images` to `rkt image list` and `rkt rmimage` to
`rkt image rm`.
This fixes #933,
I thought about adding some doc but perhaps it would be better first updating #649?

rkt: move image-related commands as rkt image's subcommands

---

.travis.yml
Documentation/hacking.md

We needed 1.3 until static linking to resolved in 1.4.
However upcoming PR needs to vendor modules that don't
work with 1.3 so we can stop testing 1.3 in the CI.

Remove Go 1.3 support

---

Documentation/devel/release.md
stage1/rootfs/aggregate/aci-manifest

The version was still 0.0.1... It should follow rkt versioning.
```
$ sudo bin/rkt image list
KEY																		APPNAME
sha512-f910f96f18ef781e8fabfb6f8e37ba07c33d3dfc21e8f7b5be5f88a96d2da775	coreos.com/rkt/stage1:0.0.1
sha512-fa1cb92dc276b0f9bedf87981e61ecde93cc16432d2441f23aa006a42bb873df	coreos.com/etcd:v2.0.0
```

stage1: fix version in manifest

---

stage1/init/init.go

This patch does not introduce any functional change. But it should
change the message from:
```
Disabling per-app isolators: error getting own cgroup path:
controller "name=systemd" not found
```
to:
```
Continuing with per-app isolators disabled: could not get own cgroup
path: controller "name=systemd" not found
```
This should make the warning message on #1076 less confusing

stage1: init: rephrase errors as warnings

---

common/common.go
rkt/metadata_service.go
stage1/init/init.go
stage1/init/registration.go

Per https://github.com/appc/spec/pull/327, use bearer token
instead of IP to authenticate containers.

metadata-svc: implement token based container auth

---

pkg/keystore/keystore.go

When a supplied signature file (e.g. .asc) contains no valid signature,
the current error message is a bit misleading; tweak it to try make it
clearer.

keystore: improve missing signature error message

---

common/common.go
rkt/run.go
rkt/run_prepared.go

starting from spf13/pflag#20 it accepts also `--flag value` while
before `--flag=value` was needed. Additionally it supports default values
for flags specified without an explicit value (`--flag`) (which is
different from the default value for flags not passed as arguments).
In that case, the `--flag=value` is needed for flags that can have a
default value because the parser won't know if the argument after
`--flag` is the flag's value or another argument.
That fix also changed the way flags are handled and removed the use of
the boolFlag interface as now default values can be provided for every
type (not just bool) by setting the NoOptDefVal variable.
This patch fixes rkt to use the new behavior.

rkt: fix --private-net without arguments

---

stage1/init/init.go

systemd-shutdown currently ignores --log-target=null so it was printing
the messages
Sending SIGTERM to remaining processes...
Sending SIGKILL to remaining processes...
Halting system.
This is fixed in systemd master but for now setting --log-level=warning
mutes these messages.

stage1: limit systemd log output

---

stage1/init/pod.go

It was causing systemd in stage1 to block on shutdown.
When systemd starts the shutdown process it will broadcast SIGTERM to
every process. That will make exit-watcher.service and the app service
stop.
exit-watcher.service has the property
ExecStopPost=/usr/bin/systemctl isolate reaper.service
and the app service has the property
OnFailureJobMode=isolate
That means both will try to run in isolate mode and sometimes that was
getting systemd to a state where it's not executing any job:
-bash-4.3# systemctl --no-pager list-jobs
JOB UNIT                        TYPE  STATE
30 halt.target                 stop  waiting
18 exit-watcher.service        stop  waiting
17 default.target              stop  waiting
19 systemd-journald.service    stop  waiting
16 system-prepare\x2dapp.slice stop  waiting …

stage1: remove OnFailureJobMode=isolate

---

Documentation/commands.md
rkt/image.go
rkt/image_cat_manifest.go
rkt/image_export.go
rkt/image_extract.go
rkt/image_render.go
tests/build
tests/empty-image/manifest
tests/rkt_image_export_test.go
tests/rkt_image_extract_test.go
tests/rkt_image_render_test.go
tests/rkt_tests.go

rkt image export exports an image from the internal rkt store to an ACI
file.
rkt image extract renders an image from the internal rkt store to a
directory.
Fixes #645
It was inspired by #649 but I didn't implement image render since I'm not sure what it means. Does it mean we render stage1+stage2 to a directory?
Also, it needs to run as root so it generates output artifacts owned by root. That's good for `rkt image extract` but maybe not so good for `rkt image export`.

rkt: add image export and image extract subcommands

---

Documentation/running-docker-images.md

The information about converting Docker images to ACI is there.
Fixes #787
Depends on appc/docker2aci#72

Documentation: link to docker2aci docs

---

rkt/fetch_test.go
rkt/images.go

This is an optimization to avoid having to download the image twice when
the user forgets to use "rkt trust".
Note that this optimization does not help when downloading the signature
returns the HTTP error 202 (such as quay.io on the first conversion).
Fixes: https://github.com/coreos/rkt/issues/573#issuecomment-78361925
Fixes partially, but not completely: https://github.com/coreos/rkt/issues/776

fetch: check signature identity before downloading

---

tests/rkt_service_file_test.go

Missing --mds-register=false flag, not caught before, because this
test is not run on semaphore.

functional tests: Fix ServiceFileTest

---

rkt/gc.go
rkt/pods.go
stage0/run.go
stage1/init/init.go

NOT READY FOR MERGE! This is WIP PR to explore how to best handle https://github.com/coreos/rkt/issues/1054
This allows the networking setup to still run in the host ns.
The overlay mount also happens in host ns and gets cleaned by
by the gc process. The cgroups get mounted in the child ns.

Move mnt ns unshare into stage1

---

Documentation/devel/release.md

There are neither `build` nor `test` scripts anymore.

documentation: Update roadmap to recent build system changes

---

makelib/variables.mk.in

When calling "make BUILDDIR=some/dir" the BUILDDIR variable's origin
becomes "command line". Further modifications of variable of such
origin are ignored unless they are done with "override" directive.

build: Fix overriding BUILDDIR variable

---

tests/README.md
tests/install-deps.sh

Functional tests never worked with CircleCI so let's remove it from the
documentation and the install-deps script to avoid confusions.

functional tests: remove CircleCI

---

tests/rkt_volume_test.go

Sometimes this expect fails after the 10 minutes timeout without
printing the log. Use an explicit timeout in order to get the logs.

TestVolumes: use expectTimeoutWithOutput

---

Documentation/commands.md
stage1/init/init.go

Now that we mount the overlay fs on the host mount namespace, we can
access the container's log directory from the host and hence we can
start systemd-nspawn with --link-journal=try-guest. This has two
benefits:
* The logs get removed with a garbage collector pass. Before (with
try-host), they were stored in the host's /var/log/journal directory
and they were ignored by the GC. Since systemd doesn't have a way to
limit the contents of /var/log/journal, only the contents of a
specific machine directory, it kept growing and growing.
* journalctl -M rkt-machine works now.
Fixes #947

stage1: use --link-journal=try-guest in systemd-nspawn

---

stage0/gc.go
stage0/registration.go

If pod was started with --mds-register=true, it will create
an empty file, $POD_DIR/mds-registered, and "rkt gc" will not
try to unregister the pod if the file is missing.
Fixes #1120

Keep a record of whether pods was mds registered or not

---

stage1/net-plugins/net-plugins.mk

Assuming it has been forgotten since migrating to the new build system.
Fixes #1146.

stage1: include ipvlan netplugin in build system

---

stage1/units/units.mk
stage1/units/units/poweroff.target
stage1/units/units/reboot.target
stage1/units/units/systemd-reboot.service

These targets are called by machinectl reboot and poweroff respectively.
In ctrl-alt-del we just reboot the system without saving the exit
statuses of the apps and the poweroff target is just the same as the
halt.target: it calls the reaper to save the exit statuses of the apps
and shuts down the container.

stage1: add ctrl-alt-del and poweroff targets

---

rkt/images.go
tests/rkt_fetch_test.go

If the aciURL is a file path, it will fetch from the file path instead of the on-disk store.
If the `--local` flag is provided, then it will only fetch from the on-disk store.
Otherwise, it will fetch from the internet.
Fix #1086 
Will add some functional tests.

rkt/images.go: fix fetchImageFrom().

---

Documentation/commands.md
Documentation/configuration.md
README.md
rkt/images.go
rkt/trust.go

Just explain it a little bit and put links to main document about
configuration, which currently describes only authentication.
I decided against cooking another document only for authentication - the `configuration.md` describes the format quite extensively and has lots of examples.
Fixes #866.

docs: Improve authentication docs a bit

---

Vagrantfile
scripts/vagrant/install-go.sh
scripts/vagrant/install-rkt.sh

Now that the build system changed, the vagrant scripts were not
working.

scripts/vagrant: use new build system

---

Documentation/networking.md
common/common.go
rkt/run.go

This commit changes the behavior of --private-net. "--private-net=all" and
"--private-net" will enable all private networks. Otherwise there are no special
values. Like this, passing "true" or "false" will just attempt to load the
correspondingly named networks.
Partially fixes #1169.

rkt: remove boolean properties of --private-net

---

Documentation/devel/stage1-implementors-guide.md
networking/networking.go
networking/podenv.go
rkt/run.go
stage0/run.go
stage1/init/init.go

If the local-config argument is provided to `rkt` it will be passed down all the
way to the network loading function. The network config dir will be the
local-config path joined with *net.d*.
Fixes #1172.

networking: respect local-config flag

---

rkt/gc.go

Doing it after results in stage1 disappearing and
GC can't find networking plugins to call.

rkt: call stage1 GC prior to overlayfs unmounts

---

dist/init/systemd/rkt-gc.service
dist/init/systemd/rkt-gc.timer

Use less aggressive values for the garbage collection and make it easy
for a user to modify the grace period via a drop-in.

dist: update GC-related units

---

pkg/selinux/selinux.go

When rkt is compiled with selinux support (selinux tag) but selinux is disabled
the selinux mount point doesn't exists. Actually it's not checked so rkt thinks
selinux is enabled. It will then fail mounting overlayfs with selinux labels.
This patch checks for the existence of /sys/fs/selinux. 
Note: This is different than the check done in https://github.com/opencontainers/runc/blob/master/libcontainer/selinux/selinux.go#L55 that needs an additional package.

selinux: check if selinuxPath exists.

---

tests/rkt_fetch_test.go

Probably run and prepare should use both app names.

tests: fix app names in TestImplicitFetch

---

rkt/fetch_test.go
rkt/images.go
store/migrate.go
store/migrate_test.go
store/remote.go
store/schema.go
tests/rkt_fetch_test.go

This should replace #319. Thanks @hectorj2f  !
this patch handles ETag and Cache-Control: max-age server headers.
It saves the Etag, the max-age and the current download time in the store's
remote data.
Before downloading it checks if the current time is before the download time
plus maxage, if so it uses the current store image.
During an ACI download it also sends the saved ETag, if the server answers with
a 304 Not Modified status then the store image is used.
The signature will be downloaded anyway because it's not cached in the store
and it's usually downloaded before the ACI.
This patch also provides db migration code (to version 2) and related tests as
the store's remote struct changed.
Signed-off-by: Simone Gotti <simone.gotti@gmail.com>
Co-Authored-By: Hector Fernandez …

rkt: handle http caching (ETag and Cache-Control max-age)

---

stage1/usr_from_coreos/manifest.d/systemd

stage1: coreos: add missing libip4tc

---

Documentation/commands.md
rkt/trust.go

Using `trust` with `--root` needs a local key file (#500).
Changed doc, help, and error msg accordingly.
Removed note on line 83 in `commands.md` as it seems not relevant to #500
Does not solve this part of original post: 
> Oddly, this outputs nothing at all:
> ./rkt trust --prefix coreos.com

fix #500 rkt trust --root

---

configure.ac
depsgentool.mk
makelib/variables.mk.in

When generating tools to use during the build they should be built for the build
machine, and not the target.
Add a section to configure.ac that sets up the make variable GOARCH_FOR_BUILD
which holds the value that GOARCH should be set to when building go language
build tools.  Also change depsgentool.mk to use GOARCH_FOR_BUILD.
Fixes errors like these when cross building:
/bin/bash: tools/depsgen.tmp: No such file or directory
Fixes issue https://github.com/coreos/rkt/issues/1184.

rkt: Add GOARCH_FOR_BUILD

---

store/store_test.go
tests/tests.mk

`go vet` does not track types across packages and so assumes
types.Labels is a struct rather than a container; consequently, it
complains about unkeyed fields in store_test.go
To work around this, use a []types.Label and have go automatically
convert the type instead.
Re-enables go vet checking on Semaphore.
https://github.com/golang/go/issues/6820

store: trick go vet into not complaining

---

store/backup.go
store/backup_test.go
store/store.go

This feature is a clearly developer-oriented one. We do not restore
backups - migrations happen inside transactions, so on failure all the
changes will be rolled back.
Here we create "db-backups" directory inside "cas" directory and store
at most 5 backups.
Fixes #748.

store: Backup a database when migrating.

---

rkt/fetch_test.go
rkt/image.go
rkt/image_cat_manifest.go
rkt/image_export.go
rkt/image_extract.go
rkt/image_render.go
rkt/images.go

Some images imported in the store will not contain os/arch labels.
This will happen with os/arch independent images.
In this case fetchImageFromStore will fail because it retrieves the image name and
labels from the image name string calling newDiscoveryApp that by default
adds the os and arch label for the current os and arch.
Adding the current os and arch labels is correct for the discovery phase and
should be used only there.
Instead `rkt image cat-manifest/export/extract/renders` works as their logic
doesn't add a default os and arch label.
This patch unifies and uses the same logic also for fetchImageFromStore.

rkt: fix fetchImageFromStore with missing os/arch labels.

---

stage1/init/pod.go

adhere to appc spec in AC_APP_NAME by using full name found
in manifest instead of image name, as required by spec:
`"AC_APP_NAME name of the application, as defined in the image manifest"`
fixes ace-validator fail:
```
[ 3464.555222] ace-validator[10]: ==> AC_APP_NAME not set appropriately (need "ace-validator-main", got "coreos.com/ace-validator-main")
```
when run like this:
```
sudo rkt --insecure-skip-verify --debug run --mds-register=false --volume=database,kind=host,source=database --private-net ace-validator-main.aci ace-validator-sidekick.aci
```
@yifan-gu PTAL, maybe your ["TODO comment"](https://github.com/coreos/rkt/blob/master/stage1%2Finit%2Fpod.go#L174) is invalid now and should be deleted ? (AFAIK there is no such thing as AC_IMAGE_NAME in spec)

fix AC_APP_NAME by using name from manifest

---

rkt/images.go

This will speed up fetching on big images as it avoids a double aci archive
walk.

rkt: remove redundant double manifest retrieval.

---

store/store.go
store/utils.go

This removes duplicated code in store and uses appc/spec functions to
decompress an aci.
When appc/spec#461 will be merged and the vendored appc/spec in rkt updated, the code will need an additional `defer dr.Close()`
this becomes also useful for the future fixes in appc/spec#462 for #1224.

store: use appc/spec aci.NewCompressedReader

---

pkg/keystore/keystore.go
pkg/keystore/keystoretest/opengpg.go
rkt/images.go

Previously, rkt only accepted armored signatures. There is no good
reasons not to accept binary signatures as well.
It will help with older versions of the ACE validator before
https://github.com/appc/spec/pull/460

keystore: accept binary signatures

---

store/store.go
store/utils.go
store/utils_test.go

Report provided name and labels in GetACI instead of a generic "aci not found"
error if it doesn't find an ACI matching them.
To get an ordered labels list, a new function labelsToString is added. It sorts
by label name giving precedence to the "version", "os" and "arch" (in this
order) labels.
Perhaps this function, if deemed useful, should be ported to appc/spec.

store: print error reporting name and labels in GetACI.

---

common/cgroup/cgroup.go
stage1/init/pod.go
tests/image/manifest

This enables things like `"resource/cpu":{"limit","100m"}`,
or `"resource/cpu":{"limit":"0.01"}`, which is the Kubernetes's style.
Previously, we will try to parse "100m" as an integer, and fail.

stage1/cgroup: replace string with resource.Quantity.

---

networking/podenv.go
rkt/run_prepared.go
stage1/net/conf/99-default-restricted.conf

If --private-net=foo,bar and either foo or bar is not found,
error out with the appropriate error message.
Also fixes --private-net to imply --private-net=all
in run-prepared cmd.
Fixes #1216

networking: fail to run if specified nets were not found

---

stage1/usr_from_kvm/lkvm.mk
stage1/usr_from_kvm/lkvm/patches/quiet-booting.patch

includes:
- patch for quiet kernel booting (lkvm earlyprink option is only
appended when lkvm run with --debug flag)
- fix for refreshing sources of lkvm (optional git fetch)
- possibility to add another patches for lkvm
- fixes lkvm version freeze (git-refresh removed)

kvm: lkvm patches (includes quiet patch)

---

stage1/init/init.go
stage1/init/kvm/doc.go
stage1/init/kvm/mount.go
stage1/init/kvm/mount_test.go
stage1/init/pod.go
stage1/usr_from_coreos/manifest.d/systemd

because kvm flavor doesn't use systemd-nspwan, we cannot utilize
its feature to bind mount demanded volumes (both kinds), so this
commit moves that responsibility to systemd (idea thx to xnox)
how it works - check the [mount.go "package" docs](https://github.com/intelsdi-x/rkt/commit/c3b08193f17b7b7c093c84986f0d6bebe2495739#diff-5e4f009487e0dd19a243aaca7de5862bR18) for idea or commit message 
**TODOs**:
`  closing because not related to kvm ( iaguis's https://github.com/coreos/rkt/pull/1176#issuecomment-127546032 )
`[    0.263976] ace-validator[84]: ==> AC_APP_NAME not set appropriately (need "ace-validator-main", got "coreos.com/ace-validator-main")` (#1199)

kvm: volumes support

---

tests/README.md
tests/rkt_exec_test.go

We switched to steveeJ's fork but there was one test still using
ThomasRooney's which broke the build

tests: forgot to change one ThomasRooney gexpect import

---

tests/functional.mk

Effectively ignores errors in succeeding builds where the symlink already
exists.
Fixes  #1251.

force symlink creaton for inspect-link

---

makelib/misc.mk

make 3.81 does not like unescaped stuff. It is not a problem for make
4.0 I have installed.
In this case, equal function always return empty value, which is then
interpreted as values not being equal, which in case of dependency
checking results in useless rebuilds.

build: Fix equal make function for make 3.81

---

rkt/images.go

We were writing the output file of docker2aci.Convert to the same temp
directory. Since the file name for a converted image is always the same
this was causing file corruption when fetching the same  docker image
with rkt several times in parallel.
We fixed that issue upstream in
https://github.com/appc/docker2aci/pull/76
In addition to the upstream fix, this patch makes the temporary
directory where rkt saves the converted docker image different in each
execution.
cc @yifan-gu @sgotti

rkt: create a real temp dir for docker2aci images

---

common/fetch_keys.go
pkg/keystore/keystore.go
rkt/fetch_keys.go
rkt/images.go
rkt/trust.go

Code for trust moved to common/fetch_keys.go for sharing between
commands 'rkt trust' and other fetch commands.
The keys are only trusted automatically if they are fetched via https
and the images are fetched via the discovery protocol.
Partially fixes #481.

fetch: automatically trust keys

---

rkt/status.go
tests/rkt_exit_test.go

This helps to parse the exit code without ambiguity. (e.g. an app can be named "exited" or "pid"...)

rkt/status.go: add 'app-' prefix to exit codes.

---

Documentation/commands.md
rkt/enter.go
rkt/gc.go
rkt/pods.go
rkt/rm.go
rkt/run.go
rkt/run_prepared.go
rkt/status.go
rkt/uuid.go

Cleans up specified pod without waiting for
the GC to run. Pod UUID can by specified as an
argument or via file that contains the UUID.
Also adds --uuid-file-save to run command to
save the pod UUID for cleanup command to consume.
Fixes #1171

rkt: add cleanup command

---

rkt/images.go
rkt/rkt.go

The default is true, so by default keys will be fetched automatically
when it is possible to do so through https.
The user can add --trust-key-from-https=false to disable it.
This is part of https://github.com/coreos/rkt/issues/481

fetch: introduce new option --trust-key-from-https

---

stage0/run.go

When using overlayfs, there is one overlayfs mount per app. If the pod
has two apps from the same image, they should use a different upper &
work directory to avoid data corruption.
The overlayfs documentation states:
> Changes to the underlying filesystems while part of a mounted overlay
filesystem are not allowed.  If the underlying filesystem is changed,
the behavior of the overlay is undefined, though it will not result in a
crash or deadlock."
https://www.kernel.org/doc/Documentation/filesystems/overlayfs.txt
This was first reported on https://github.com/coreos/rkt/pull/1194
/cc @iaguis @steveeJ @yifan-gu

overlayfs: use different upperdir/workdir for each mount

---

networking/kvm.go
networking/netinfo/netinfo.go
networking/networking.go
networking/podenv.go
networking/tuntap/tuntap.go
stage1/gc/gc.go
stage1/init/init.go
stage1/init/kvm/network.go

Includes support for ptp mode (used in default and default restricted example modes).
Not tested:
- port forwarding (uses existing rkt code)
- ip masquerade (uses existing rkt code)
Not working:
- no support to additional routes in network configuration
Co-authored-by: Pawel Palucki <pawel.palucki@gmail.com>

kvm: basic networking support

---

common/common.go
pkg/aci/render.go
pkg/fileutil/fileutil.go
pkg/tar/chroot.go
pkg/tar/tar.go
pkg/tar/tar_test.go
pkg/uid/uid.go
rkt/image_extract.go
rkt/image_render.go
rkt/prepare.go
rkt/run.go
stage0/run.go
stage1/init/init.go
stage1/init/pod.go
store/backup.go
store/tree.go

The last patch "stage1:userns: add a workaround to make env file world writable" is just a work around. Will fix it later.
Alban and others asked to this PR so we can have a first review especially from @sgotti 
This is part of https://github.com/coreos/rkt/issues/986 and it is an update of https://github.com/coreos/rkt/pull/1027 
I will close PR https://github.com/coreos/rkt/pull/1027

rkt: user namespace support through chown at extract time

---

Documentation/running-lkvm-stage1.md

Networking has been merged so we can remove this caveat.

Documentation: running-lkvm-stage1

---

rkt/prepare.go
rkt/run.go

This fixes #1276, print an error message if user namespace was requested
but the kernel was compiled with CONFIG_USER_NS=n
Reported-by: Iago López Galeiras <iago@endocode.com>
Signed-off-by: Djalal Harouni <djalal@endocode.com>

rkt:userns: print an error if user namespace is not supported #1276

---

tests/rkt_run_pod_manifest_test.go

This is based on #1269 + Stefan's suggestion to use `expectRegexWithOutput`.

tests: print the stdout and stderr when command execution fails (based on #1269)

---

stage1/init/kvm/network.go

Fixes [1290](https://github.com/coreos/rkt/issues/1290).

[kvm] Fix network parameters generation.

---

tests/rkt_run_pod_manifest_test.go

Instead of deleting them in the end of tests, this helps
us to run out of space less likely on Semaphore CI.

tests: remove intermediate images during tests.

---

tests/rkt_caps_test.go
tests/rkt_fetch_test.go
tests/rkt_run_pod_manifest_test.go
tests/rkt_socket_activation_test.go
tests/rkt_tests.go

Some tests weren't removing the results of `patchTestACI` properly, that is - by deferring `os.Remove` right after the call to `patchTestACI`.
Caught that when working on make clean.

functional tests: Properly remove patched ACIs

---

networking/kvm.go
networking/tuntap/tuntap.go

I tried to give the tap device a name so it's obvious it was created by rkt and that there would be a way for NetworkManager to ignore it. But the current patch does not work.
See also https://github.com/coreos/rkt/issues/1302
/cc @ppalucki @jellonek

kvm: tun: give the network interface a name

---

tests/install-deps.sh

An update to Semaphore's platform caused the default version to be 4.6,
which broke the systemd build.

functional tests: set gcc version to 4.8

---

tests/rkt_run_pod_manifest_test.go
tests/rkt_tests.go

Remove images from the CAS after each iteration of the test run to avoid
running out of space.
We also do a garbage collector run so can remove the images and to save
even more space.

functional tests: TestPodManifest: remove images from cas

---

stage1/find-so-deps.mk
stage1/stage1.mk

This file will get a bit more code later which handles the removing of
copied libraries, so split it out to avoid cluttering the already
messy stage1.mk.

build: Split out make part doing the copying of libraries from host

---

tools/common/filelist/filelist.go
tools/common/util.go
tools/filelistgen/main.go
tools/filelistgentool.mk
tools/tools.mk

The filelist generator tool is currently not used by anything. But in
following commits it will be used by depsgen and by other new tool.
filelistgen is expected to be called like:
filelistgen <OPTIONS> >filelist
filelistgen has three modes of operation:
1. Generate empty filelist (zero directories, files and symlinks):
filelistgen --empty >empty.filelist
2. Generate shallow filelist of a directory with given suffix:
In this mode, the generator does not descend into subdirectories. The
generated filelist will contain only items that does not begin with a
dot and have a matching suffix.
filelist --directory=some/dir --suffix=.patch >patches.filelist
3. Generate deep filelist:
In this mode, the generator just gathers all files, directories and
symlinks from given directory and its …

build: Add a filelist generator tool

---

stage1/gc/gc.go
stage1/init/init.go
stage1/init/pod.go

If we use overlayfs and we unmount the directories before
running rkt gc we won't have access to the stage1 directory but we need
the pod's flavor to do the correct GC (regular or LKVM).
We need to store the pod's flavor in the pod's root directory, trying
first in stage1 to keep backwards compatibility. This means it will
garbage collect old pods that weren't unmounted but if they did get
unmounted it will still fail.
Fixes #1322

stage1: fix garbage collection after unmount

---

common/common.go

The previous port number was registered and reserved. Use a random high
port number in the non-dynamic range.

common: change the port number

---

stage0/run.go

This was creating the apps' /tmp directory with the wrong permissions
We're already creating it in prepare-app with the right ones.
Fixes #1321

stage0: don't create app/tmp directory

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/coreos/go-iptables/iptables/iptables.go

Revendor go-iptables to pick up addition
of --wait flag so that multiple containers
starting won't cause failure.

net: revendor go-iptables for --wait

---

networking/kvm.go
stage1/init/init.go
stage1/init/kvm/network.go
stage1/init/kvm/network_test.go

**PR note**: this is just a refactoring it doesn't fix any issues or add any user features (other than maintainability and neatness :smile: ) + includes unit tests
It's effect of discussion from [here #1219] (https://github.com/coreos/rkt/pull/1219#discussion_r36347022)
Below some rationale from commit message:
> NetParams was used as carrier for dynamic/static network configuration
> provided by CNI plugin to virtual machine then used by lkvm tool (through
> kernel parameters).
>
> netDescriber is just an interface required by function that prepares
> arguments to kernel for kvm flavor and is implicitly implemented by
> activeNet.
/cc @eyakubovich

kvm: network code refactoring: replace s/NetParams/netDescriber/

---

Documentation/hacking.md

New build system is not using ./build script any more, after @krnowak changes - docs mentioned above should be updated.
https://github.com/coreos/rkt/blob/master/Documentation/hacking.md#managing-dependencies

Docs/hacking mentioning about build script.

---

.gitignore
autogen.sh

autogen.sh script supports the file .config.args where I put the
following:
--with-stage1=src
--with-stage1-systemd-src=/home/tixxdz/code/github-work/systemd/systemd
--with-stage1-systemd-version=master
So it prints at the end these arguments especially for us who build from
source, this way we don't have to remember them each time.
Signed-off-by: Djalal Harouni <djalal@endocode.com>

autogen: more fixes for autogen script

---

common/cgroup/cgroup.go

If someone calls MaybeAddIsolator with a recognised isolator type but a
nil *resource.Limit, a kernel panic results when we try to call Value()
on the nil Limit. Rather than reaching this stage, just skip trying to
create an isolator when the supplied limit is nil.
Fixes #1377

common/cgroup: don't add isolators with nil limits

---

stage0/registration.go

In go1.5 syscall errors in OpError.Err changed from syscall.Errno to
os.SyscallError. This broke the error handling in httpRequest.

stage0: fix error handling in go1.5

---

rkt/metadata_service.go

When requesting the metadata service to verify a signature from another pod,
the uuid of the pod needs to be passed as an HTTP-POST option. According to
the spec, the name of the option is "uuid" and not "uid".
Note: the same typo was done in the ACE validator: https://github.com/appc/spec/pull/485

metadata svc: fix typo in the HTTP-POST options

---

Documentation/hacking.md

Simple change to make the stage1 kvm image description consistent with the rest of the docs.

Docs: Make stage1 kvm description full sentence

---

stage1/usr_from_kvm/lkvm.mk
stage1/usr_from_kvm/lkvm/patches/terminal_late_fix.patch

There is a problem during console device initialization.
In case of some buffered stdio events, backend thread (host level) is
started before threadpool workers (threads that pass value to
frontend driver) while condition variable is no initialized properly yet.
This causes deadlock or segfault.
This temporary solution just delays initialization of mentioned backend thread to
firmware initialization phase.
Additionally this commit updates lkvm to the newest upstreamed version.
ps. I'm going to upstream this patch after refactoring and then we just updated lkvm to fixed version.

lkvm: fix stdio events pending race in interactive mode & lkvm update

---

rkt/prepare.go
rkt/run.go

Before this, 'rkt help prepare' will show default stage1image="",
(although it doesn't affect the real prepare work).

rkt/prepare: find default stage1 image in init().

---

configure.ac

Configure script should check if libc exists on the system,
for both dynamic and static library.
If any of them doesn't exist, print out appropriate error message.
Fixes: https://github.com/coreos/rkt/issues/1371

build: make configure check if libc exists

---

Documentation/subcommands/image.md

Fixes small typo in Documenation/subcommand/image.md where the article 'a' was doubled up.

Docs: subcommand image: Fix small typo

---

makelib/file-ops-epilog.mk

Make function responsible for returning the proper -m flag for install
program was being undefined before it was called inside recipe.

build: Fix setting file mode when copying files

---

Documentation/networking.md

Seems it was intended to put an example after this comment. Not there yet so removing and referencing the followup ticket: https://github.com/appc/cni/issues/56.

Docs: networking: Remove reference to missing example

---

configure.ac

Go 1.5 deprecated the "-X variable value" format in favor of " -X
variable=value" one. Unfortunately Go 1.4 does not accept the latter
format.
This commit introduces a shell function RKT_XF which outputs the old
format for Go 1.4 or older and a new one for Go 1.5 or newer. My
initial idea was to specify a separator variable which would hold a
space for old Go and = for new Go, so it would be used like "-X
variable${X_SEPARATOR}value". I dropped the idea, because of quoting
issues - we want to be safe against spaces in a value part. That's
why, for old Go, we have "-X variable 'value'" and for new Go - "-X
'variable=value'". Using "-X variable='value'" ended up with version
string enclosed with literal single quotes.
When the support for Go 1.4 is dropped, the code can be then
simplified.

build: Prepare for different ldflags syntax in newer go

---

tools/depsgen/mkfile.go

Just a typo - used wrong variable.

build: Fix key-value depsgen reporting about invalidating build

---

configure.ac

An embarrassing mistake from my side - GO_MINOR and GO_MAJOR try to
read the GO_VERSION variable, while the actual version was stored in
VERSION variable instead.

build: Fix go version detection

---

Documentation/using-rkt-with-systemd.md

Running the lkvm flavor of rkt in systemd does not currently work if
$HOME is not defined: see https://github.com/coreos/rkt/issues/1393
It should be fixed in lkvm upstream, but meanwhile, mention the
workaround in the documentation.

doc: rkt with systemd: lkvm: workaround for missing $HOME

---

rkt/images.go

Right now the progress bar for downloading an image will be send to
stderr for docker images, and stdout for aci images. This should send it
to stderr in both cases.

Send human consumable messages to stderr

---

Documentation/getting-started-guide.md

Looks like the page describing the metadata service was moved to the
subcommands folder. This commit moves the link on the getting started
page to point to it.

docs: fixed bad link to metadata service in getting started

---

Documentation/running-lkvm-stage1.md

More documentation in addition to https://github.com/coreos/rkt/pull/1401
Running the lkvm flavor of rkt in systemd does not currently work if
$HOME is not defined: see https://github.com/coreos/rkt/issues/1393
It should be fixed in lkvm upstream, but meanwhile, mention the
workaround in the documentation.

doc: lkvm: troubleshooting for missing $HOME

---

Documentation/subcommands/run.md

Same as the last docs fix I did, but in a different place. Metadata
service link returned a 404, updated to point to the new place.

docs: fixed bad link to metadata service in run subcommand

---

rkt/prepare.go
tests/rkt_exec_test.go
tests/rkt_run_pod_manifest_test.go
tests/rkt_tests.go

When preparing a container, the exec flag can be used to override the
default binary run inside the container. Behaves the same way as on the
run command.

stage0: added exec flag to prepare statement

---

tests/rkt_exec_test.go

It wasn't using the right image :$

functional tests: fix noapp exec test

---

makelib/misc.mk
stage1/usr_from_coreos/usr_from_coreos.mk
stage1/usr_from_kvm/kernel.mk
stage1/usr_from_kvm/lkvm.mk
stage1/usr_from_src/usr_from_src.mk
tools/depsgen/globcmd.go

This moves the dependency generation to their own rules instead of being a part of other rules. Anytime depsgen changes the dep.mk are regenerated, but other binaries do not need to be rebuilt anymore.

build: Generate dependencies from filelists

---

Documentation/running-lkvm-stage1.md
Documentation/using-rkt-with-systemd.md
stage1/init/init.go

kvmtool currently does not work when $HOME is not defined. When started
by a systemd unit file (or by systemd-run), $HOME is typically
undefined, unless "User=" (or resp. "--uid=") is given.
Instead of asking users to work around the issue with "User=" or
"--uid=", just define that variable in rkt before calling lkvm.
This could be removed when this gets fixed in lkvm upstream.
Issue described in https://github.com/coreos/rkt/issues/1393
/cc @jellonek

lkvm: make sure $HOME is defined before running lkvm

---

stage1/init/init.go
stage1/init/pod.go
stage1/reaper/reaper.sh
stage1/units/units.mk
stage1/units/units/default-rkt.target
stage1/units/units/exit-watcher.service
stage1/units/units/halt.target
stage1/units/units/poweroff.target
stage1/units/units/reaper.service
stage1/units/units/shutdown.service

This changes the way rkt starts apps in a pod.
The default.target has a Wants and After dependency on each app, making
sure they all start. Each app has a Wants dependency on an associated
reaper service that deals with writing the app's status exit. Each
reaper service has a Wants and After dependency with a shutdown service
that simply shuts down the pod.
The reaper services and the shutdown service all start at the beginning
but do nothing and remain after exit (with the RemainAfterExit flag). By
using the StopWhenUnneeded flag, whenever they stop being referenced,
they'll do the actual work via the ExecStop command.
This means that when an app service is stopped, its associated reaper
will run and will write its exit status to /rkt/status/${app} without
having to wait until the pod …

stage1: rework systemd service structure

---

rkt/images.go

ioprogress was updated, this change makes rkt use a function that was
added to prevent drawing the download bar when not drawing to a
terminal.
Fixes https://github.com/coreos/rkt/issues/1282

stage0: Switch to use updated ioprogress and docker2aci

---

rkt/run_prepared.go
stage0/registration.go

When a user has no metadata service running and runs rkt run-prepared
without specifying mds-register=false, the pod is left in the run state
and the user needs to reprepare the pod again to rerun.
To avoid this scenario, this commit does an early check to see if the
metadata service is available before the pod is moved to the run state.
fixes https://github.com/coreos/rkt/issues/1434

rkt: Make run-prepared rerunnable when mds is missing

---

store/store.go

The interface for aci.NewCompressedReader changed in the upstream appc
code (https://github.com/appc/spec/pull/462) to return a ReadCloser
instead of a Reader. Hence it's now our responsibility to close the
returned ACI.
Fixes #1224
/cc @sgotti

store: close aci.NewCompressedReader

---

common/cgroup/cgroup.go
stage1/init/init.go

To avoid problems on environments without a properly mounted cgroup
hierarchy and/or without the systemd hierarchy we also deal with
mounting the host cgroup hierarchy.
Since we're in a different mount namespace the host is not affected.
Fixes https://github.com/coreos/rkt/issues/1320
Fixes https://github.com/coreos/rkt/issues/1076
Fixes https://github.com/coreos/rkt/issues/1042

stage1: common: mount also the host cgroup hierarchy

---

tests/install-deps.sh
tests/run-build.sh

We don't need to set gcc via alternatives to version 4.8 - it is
already fixed. Also, instead of installing go and gofmt with apt-get,
just use what semaphore provides with change-go-version script.
Maybe makes the builds a bit faster.

semaphore: Update install-deps

---

configure.ac
rkt/prepare.go
rkt/run.go
rkt/stage1hash.go
stage1/stage1.mk

This PR makes some small changes in rkt's behavior. Hopefully commit messages are quite clear about the changes.
In short - we do not default to `stage1.aci` in the same directory as rkt if default stage1 image path was not set; we always set the path. But the code tries to load the stage1 image from the same directory as rkt if loading stage1 image from default path fails.
This PR fixes #1292.

Give different names to different flavors of stage1 images

---

rkt/fetch.go
rkt/fetch_test.go
rkt/images.go
rkt/prepare.go
rkt/run.go
rkt/stage1hash.go
store/store.go
tests/rkt_fetch_test.go

Implement fetching behavior as explained in the below table (see also https://github.com/coreos/rkt/issues/1196#issuecomment-127983674 for previous discussion).                  
For `fetch/run/prepare`.
--store-only | --no-store |  behavior          | description
----------- | ---------- | ------------------ | -------------------------------------------------------------------------------
1            | 0          | store              | Just check the store
0            | 1          | remote             | Do remote download (handling caching logic for http(s):// and docker://)
0            | 0          | store then remote  | Default Behavior. Does `store` and if it doesn't return an image calls `remote`
behavior details related to provided image:
behavior     | image              | …

rkt: implement new image fetching behavior.

---

tests/functional.mk

It was making "make clean" fail.

functional tests: add missing files to CLEAN_FILES

---

Documentation/devel/stage1-implementors-guide.md
Documentation/getting-started-guide.md
Documentation/subcommands/image.md
pkg/aci/aci.go
rkt/fetch_test.go
rkt/images.go
stage0/arch.go
stage0/run.go
stage1/aci/aci-manifest.in
store/store_test.go
store/tree_test.go
tests/empty-image/manifest
tests/image/manifest
tests/rkt_cat_manifest_test.go
tests/rkt_exec_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go
tests/rkt_tests.go
tests/test-auth-server/aci/aci.go

We also check during findImages so we don't start downloading an image
we know is not supported.

rkt,stage0: validate OS/arch during run

---

tests/rkt_exit_test.go

Factorize the code that runs "rkt list" and "rkt status" in
checkStatus() and use it both in the existing test TestExitCodeSimple
and in the new test TestExitCodeWithSeveralApps.
This new functional test will help when implementing https://github.com/coreos/rkt/pull/1396
/cc @yifan-gu @iaguis @sgotti

tests: check exit status on a 3-app pod

---

common/common.go
pkg/fileutil/fileutil.go
rkt/enter.go
rkt/gc.go
rkt/image_render.go
rkt/image_rm.go
rkt/pods.go
rkt/run_prepared.go
stage0/run.go
store/store.go
store/store_test.go
store/tree.go
store/tree_test.go
tests/rkt_image_list_test.go
tests/rkt_image_rm_test.go

NOTE:
This is going to change the on disk format for pods, see #1132. This means that actually, after applying it, `rkt run-prepared`, `rkt gc` and other commands working on pods will fail to find the stage1 path for exitstent pods and possibly other problems.
If an image has dependencies, and they have changed, for the same imageID we
can have multiple different rendered images (#1198).
Until now this wasn't handled and rkt and the treestore used the imageID to
reference the rendered image.
This patch, does multiple things:
* the treestore now returns a treeStoreID on store.RenderTreeStore. The
treeStoreID is computed as an hash of the flattened dependency tree image keys.
In this way if some dependencies have changed a new ID will be generated and a
new image rendering will be done.
* …

rkt: handle multiple rendered images for the same imageID

---

Documentation/devel/stage1-implementors-guide.md
Documentation/getting-started-guide.md
Documentation/subcommands/image.md
pkg/aci/aci.go
rkt/fetch_test.go
rkt/images.go
stage0/arch.go
stage0/run.go
stage1/aci/aci-manifest.in
store/store_test.go
store/tree_test.go
tests/empty-image/manifest
tests/image/manifest
tests/rkt_cat_manifest_test.go
tests/rkt_exec_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go
tests/rkt_tests.go
tests/test-auth-server/aci/aci.go

We also check during fetchSingleImage so we don't start downloading an image
we know is not supported.
Fixes #271 
Take two. First take was #1472

rkt,stage0: validate OS/arch during run (take 2)

---

Documentation/subcommands/image.md
common/common.go
rkt/image_gc.go
rkt/install.go
rkt/pods.go
rkt/prepare.go
rkt/rkt.go
rkt/run.go
store/store.go
tests/rkt_image_gc_test.go
tests/rkt_tests.go

This is on top of #1240. The last patch is the interesting one.
rkt: implement initial image gc for the tree store.
This patch adds an initial image gc command.
Image gc can be thought in multiple ways:
* Remove treeStores not referenced by any non GCed pod
* Remove images not used for some time (#1205)
* ~~Cleanup the store from other garbage:~~
* ~~Entries removed from the aciinfo tables but failed to remove for any reason from the diskv stores during `rkt image rm`~~
* ~~Cleanup store's treestorelocks directory~~
* ~~Cleanup store's tmpdir directory~~
This patch implements the removal of treeStores not referenced by any non GCed pod.
A "preparelock" is added to avoid races between getting the list of referenced treeStoreIDs and new pods/treeStores being created/referenced in the …

rkt: implement initial image gc for the tree store.

---

rkt/help.go
rkt/image_list.go
rkt/list.go
rkt/rkt.go
store/store.go

Text below copied from #1266.
Example output of `rkt list`:
```
Unable to load manifest of pod 1ad35d47-34a4-4800-ac34-088f7a8f75ee: ACName must contain only lower case alphanumeric characters plus "-"
Invalid pod manifest - version: 0.7.0+git
App: "!redis" from image "redis" (sha512-afe588bd39c1e5b6e85743d0fbfde921cc895eeee9e64dac8c31b4647a12577c)
Unable to load manifest of pod 22fc87d3-9c53-4b35-b83d-d3d19a865f9c: ACName must contain only lower case alphanumeric characters plus "-"
Invalid pod manifest - version: 0.7.0+git
App: "busybox~" from image "busybox" (sha512-bf885104dc06468d8458c43d3f7f66774da77c62c09574de22d1bce17fd14df4)
UUID		APP	ACI		STATE	NETWORKS
2f969bfd	redis	redis		exited	
70020f80	busybox	busybox		exited	
7b6c7615	busybox	busybox		exited	
85390bde	redis	redis		exited …
```

Use last-ditch manifest parser for error reporting

---

Documentation/commands.md
Documentation/subcommands/prepare.md
Documentation/subcommands/run-prepared.md

Documentation: add prepare and run-prepared

---

rkt/image_rm.go
tests/rkt_run_pod_manifest_test.go

When `rkt image rm` cannot remove one or more of the images that it is passed, it should return an exit status of 1. Up to now an exit status of 0 has been returned whether all, some or no images could be removed.
Closes #1483

rkt: exit with status 1 on image rm failure

---

stage1/stage1.mk

Without this, the generated stage1 will have the uid and gid of the user
building it.
Fixes #1453

stage1: make root own files/dirs in stage1.aci

---

stage1/init/pod.go
tests/inspect/inspect.go
tests/rkt_supplementary_gids_test.go

stage1: pass supplementary Gids to diagexec

---

common/group.go
common/group_test.go
rkt/image_gc.go
rkt/install.go
rkt/pods.go
rkt/run.go
rkt/run_prepared.go
stage0/run.go
store/store.go
tests/rkt_exit_test.go
tests/rkt_non_root_test.go
tests/rkt_tests.go

Changes made:
Add `set-group-ID` bit to the directorys installed by `rkt install`
so that later the files created in those directory can be read by
users in the `rkt` group if the group exits. All the directories are
read-only by `rkt` group except for the `cas` which enables `rkt`
group to fetch images.
Change the permission bits of ppid, pod manifest, image manifest,
dropped the execution bit.
Change the gid of `stage1/rootfs` to the gid of `rkt` group if the
group exits.
Change the gid of `stage1/rootfs/rkt` directory and all its sub-directories
(`rootfs/rkt/status`, `rootfs/rkt/env` currently) to the gid of `rkt`
group if the group exits. Also add `set-group-ID` bit to them so that
files created by the pod in these directories later can be read by
process in `rkt` group. (e.g. exit …

DOT NOT MERGE: install/stage0: change file mode bits to several fils/dirs.

---

stage1/init/pod.go

Some pre-start jobs take a long time, set the timeout to 0 so they can
complete. If it takes too long, the user can just kill rkt.
Fixes #1515

stage1: set TimeoutStartSec to 0

---

tests/rkt_privatenet_test.go

The rktRunCtx.reset() function is useful for loops - call it at the
end of loop iteration for the next iteration to have a fresh data and
config directories, like:
```go
ctx := newRktRunCtx()
defer ctx.cleanup()
for _, tt := range testcases {
...
rkt.reset()
}
```
In these cases there are no loops, so these calls are superfluous.

functional tests: Remove unnecessary calls to reset()

---

rkt/image_list.go
rkt/image_rm.go
rkt/images.go
rkt/list.go
store/store.go
store/store_test.go
tests/rkt_image_export_test.go
tests/rkt_image_list_test.go
tests/rkt_image_rm_test.go

The `rkt list` command currently shows an inadequate amount of information to determine which image an app is associated with. For example, one could have fetched multiple versions of an image and it's possible for images to have the same name but different hashes. However, these details are not shown in the output.
This change adds the version information to the default `rkt list` output and adds the 12-char ID of the image to the output when the '--full' flag is used.
It also changes the 'ACI' field header to 'IMAGE NAME'.
Lastly, this PR change tries to make the term used for the image's hash value more consistent by changing the user-facing reference to "Image ID" instead of "key". "Key" is already used more adequately  in the trust context.
Closes #1492

provide more info in rkt list

---

rkt/fetch.go
store/store.go
tests/rkt_caps_test.go
tests/rkt_non_root_test.go
tests/rkt_tests.go

Evidently the LockOSThread approach is a disaster in go. However, the
os/exec.Command struct does expose some ability to control the execution
parameters via the SysProcAttr - and in particular the Credentials
struct which (in principle) allows us to safely set the uid/gid for the
execed rkt process.

tests: switch to using SysProcAttr for non-root

---

Documentation/subcommands/image.md
Documentation/subcommands/list.md

Also updates the docs to use the term "image ID" instead of "key" where
appropriate.

Docs: Update docs with new rkt list --full flag

---

rkt/image_list.go

We should treat options as case-insensitive

rkt: make image list order flag case-insensitive

---

tests/rkt_ace_validator_test.go
tests/rkt_app_isolator_test.go
tests/rkt_auth_test.go
tests/rkt_caps_test.go
tests/rkt_cat_manifest_test.go
tests/rkt_env_test.go
tests/rkt_exit_test.go
tests/rkt_fetch_test.go
tests/rkt_image_export_test.go
tests/rkt_image_extract_test.go
tests/rkt_image_list_test.go
tests/rkt_image_render_test.go
tests/rkt_image_rm_test.go
tests/rkt_interactive_test.go
tests/rkt_net_test.go
tests/rkt_pid_file_test.go
tests/rkt_run_pod_manifest_test.go
tests/rkt_tests.go
tests/rkt_trust_test.go
tests/rkt_volume_test.go

Much of the code in the functional tests was copy and pasted around. This commit tries to reduce that a bit by providing functions for the common tasks of spawning, waiting, checking expected values, etc.
There is much more room for improvement, but this is a start.

tests: functional test refactoring

---

tests/functional.mk
tests/inspect/inspect.go
tests/rkt_userns_test.go

Check if "/" in the container belongs to root as it should.
Fixes #1531
-----
WIP: the test does not work yet: first, mkdir /proc failed. I added the patch from #1454 to have `/proc` in stage1.aci for testing, and then systemd-nspawn fails to mount it:
```
mount("proc", "/proc", "proc", MS_NOSUID|MS_NODEV|MS_NOEXEC, NULL) = -1 EPERM (Operation not permitted)
```
I need to check whether the regression comes from #1452 or if it is something else...

tests: new test for user namespaces

---

tests/install-deps.sh

The src flavor with systemd from git master requires the last version of
libmount.
Symptoms:
> configure: error: *** libmount support required but libraries not found
Semaphore does not have the correct version. This patch installs the
last version as explained on https://github.com/systemd/systemd/pull/986
-----
Let's see how long it takes to run this on Semaphore.

semaphore: install the last libmount

---

tests/install-deps.sh

This new version is required by systemd from master, but for now we
stopped building it in semaphore.

functional tests: Stop installing new libmount

---

Documentation/configuration.md
Documentation/devel/stage1-implementors-guide.md
Documentation/getting-started-guide.md
Documentation/signing-and-verification-guide.md
Documentation/subcommands/run.md
Documentation/subcommands/trust.md
Documentation/using-rkt-with-systemd.md

Just added some syntax highlighting hints to make the docs a bit shinier.

docs: add syntax hints to code blocks

---

configure.ac
rkt/help.go
rkt/image_list.go
rkt/prepare.go
rkt/rkt.go

While help output for the commands is nicely formatted with a gutter between the command name and the description, the options were not formatted so nicely. This change formats the options nicely as well.
This should close issue #1113.

stage0: make options output nicer

---

Documentation/getting-started-ubuntu.md

No need for this to be named so specifically; this way we don't need to
rename it every time we change the ubuntu release.
/cc @robszumski

docs: rename gsg-ubuntu-vivid -> gsg-ubuntu

---

rkt/prepare.go
rkt/rkt.go
rkt/run.go
rkt/run_prepared.go

The parameters --dir=, --system-config= and --local-config= used to only
accept absolute paths. This patch changes the type of the parameters
from string to absDir. When the flag is parsed, the potentially relative
path is converted to an absolute path automatically.
The parameters still have the same defaults. It is no longer allowed to
pass an empty string (e.g. --dir="" is not allowed).
Fixes https://github.com/coreos/rkt/issues/1605

directory parameters: allow relative paths

---

tests/README.md
tests/install-deps.sh
tests/run-build.sh

Just add "[skip ci]" somewhere in the commit message to skip the build in CI.

ci: allow skipping ci runs via keyword in commit msg

---

tests/install-deps.sh

The regexp for checking the keyword in the commit msg was bogus.

ci: don't skip all ci runs

---

rkt/rm.go

p.isExitedGarbage and p.isExited can both be true at the same time. Fix
the tests order in the switch, so we don't move a pod to garbage if it
is already in garbage.
Fixes https://github.com/coreos/rkt/issues/1620
-----
/cc @vcaputo

rkt: removePod: fix switch order

---

common/apps/apps.go
networking/netinfo/netinfo.go
networking/networking.go
networking/podenv.go
pkg/tar/tar.go
rkt/help.go
rkt/image_list.go
rkt/list.go
rkt/pods.go
stage1/init/init.go
stage1/init/kvm/mount.go
stage1/init/kvm/network.go
stage1/init/pod.go
store/aciinfo.go
store/aciinfo_test.go
store/migrate_test.go
store/store.go
store/store_test.go
store/utils.go
tests/rkt_os_arch_test.go
tools/cleangen/main.go
tools/depsgen/globcmd.go
tools/depsgen/gocmd.go

In order to avoid unnecessarily allocating memory in the case where the
empty slice is never appended to, it's better to use the "var name
[]type" form than the "name := []type{}" form.
See:
https://github.com/golang/go/wiki/CodeReviewComments#declaring-empty-slices

Avoid allocating space for empty slice initialization

---

Documentation/devel/stage1-implementors-guide.md

Stage1's diagexec was renamed to appexec in https://github.com/coreos/rkt/pull/1627
Update the documentation accordingly.

doc: rename diagexec -> appexec

---

Documentation/subcommands/metadata-service.md

Possibly typo? If I am wrong, please feel free to drop this.
And added missing punctuation.
Thanks!

Documentation: typo in metadata-service.md

---

stage1/init/pod.go
stage1/init/pod_test.go

Now that we use systemd v222 in stage1 we can quote the executable path.
This allows it to contain spaces.
Fixes #1466

stage1: quote exec[0]

---

rkt/gc.go

Prints warning message when a pod is in the garbage, but is not removed
due to still being within the grace period.
Fixes #1629

rkt: Add warning message during gc for pod within grace period

---

tests/install-deps.sh

We're having some problems with building coreos/rkt after Semaphore's platform update today. Here's [an example](https://semaphoreci.com/coreos/rkt/branches/pull-request-1582/builds/10)
```
go tool: no such tool "vet"; to install:
go get golang.org/x/tools/cmd/vet
```
I opened an ssh session and it seems that not all the go executables are installed for go1.4.3. For example, "vet" and "cover" should be in "/usr/local/golang/1.4.3/go/pkg/tool/linux_amd64" but they're not. In the go1.5.1 installation they are there.
I checked the go1.4.3 release and they're not included there either while they are in go1.4.2. ~~It seems they did that unintendedly since go1.4.3 is supposed to be a bugfix release.~~
Here's an upstream issue: https://github.com/golang/go/issues/12883
I guess we can `go get` …

functional tests: Semaphore is broken

---

Documentation/packaging.md

When packagers prepare a `rkt` package for a new distribution, it would be nice to have a checklist.
There are some information in [configure.ac](https://github.com/coreos/rkt/blob/master/configure.ac) and [Documentation/hacking.md](https://github.com/coreos/rkt/blob/master/Documentation/hacking.md) but not everything and it is not oriented towards packagers.

RFC: doc: packaging

---

common/apps/apps.go
rkt/cli_apps.go
rkt/prepare.go
rkt/run.go
stage0/run.go
stage1/init/pod.go
stage1/init/pod_test.go
tests/rkt_volume_test.go

Based on #770
--mount flags preceding any apps apply globally to all apps,
--mount flags succeeding any apps apply only to the nearest preceding app.
This flag allows injecting volumes into apps using source and target
paths.
Example:
```
rkt run app.aci --inject-volume /data:/var/lib/data
```
Fixes #1467
Fixes #761

stage1: implement PodManifest.Mounts and --inject-volumes

---

rkt/list.go
stage0/run.go

Since we are now able to remove an image without removing the pod, use
of the ImageManifest in the rkt list creates a dependency on an image
that may not be around, causing rkt list to fail.
This change removes that dependency and instead relies on the
PodManifest which will be available and should supply the needed
information.
Also found an issue in the PodManifest generation.
Fixes #1628

rkt list fails to list pods whose image is removed

---

stage0/run.go
stage1/rootfs.mk
stage1/usr_from_coreos/usr_from_coreos.mk
stage1/usr_from_src/usr_from_src.mk
tests/rkt_userns_test.go

Setting the group of the rootfs to 'rkt' causes problems with user
namespaces when the group is not mapped in the user namespace. It
prevents the container from doing a 'mkdir' or a 'lstat' on /proc. See
https://github.com/systemd/systemd/issues/1585
Setting the group ownership of the rootfs to 'rkt' was done in
https://github.com/coreos/rkt/pull/1452 so that the command 'rkt status'
could work as non-root. However, if the rootfs is r-x for others, setting
the group should not be necessary. r-x for others was removed by
https://github.com/coreos/rkt/pull/1607 but I am adding it back.
This patch reverts a part of https://github.com/coreos/rkt/issues/1602,
therefore fixing the regression with user namespaces. 'rkt status' as
non-root still works.
Fixes …

stage0: don't change the group ownership of rootfs

---

stage0/run.go

This way we don't need to re-marshal the manifest into a []byte, just
trust the manifest coming from the store.  If the manifests need
validating we should do that before putting them in the store.  This is
in the hot path of starting pods since we write manifests for the app
and stage1 acis.

stage0/run: use store.GetImageManifestJSON() instead

---

Documentation/app-container.md
Documentation/networking.md
common/common.go
networking/podenv.go
rkt/run.go
rkt/run_prepared.go
stage1/init/init.go
stage1/init/pod.go
tests/inspect/inspect.go
tests/rkt_ace_validator_test.go
tests/rkt_net_test.go
tests/testutils/iputils.go

* default to mds-register=false
* net=none will only load loopback interface
Fixes #1574.
Fixes #1566.

Allow loopback only networking

---

stage1/usr_from_coreos/build-usr.mk
stage1/usr_from_coreos/usr_from_coreos.mk
stage1/usr_from_kvm/usr_from_kvm.mk

All the rules for preparing the initial contents of ACI rootfs from
CoreOS image are placed in build-usr.mk. Both usr_from_kvm and
usr_from_coreos use this file to get their rootfs prepared.
This commit includes also a bunch of tweaks and fixes.
- properly customizable flavor symlink creation (so kvm flavor does
not need a hack replacing the flavor symlink with its own)
- proper creation and dependencies on symlinks directly in ACI rootfs
directory (symlinks are created via INSTALL_SYMLINKS variable and
adding a new one to both CBU_ACIROOTFS_SYMLINKS and INSTALL_SYMLINKS
will recreate the ACI rootfs)
- proper dependencies for file manifests (not ACI manifest; modifying
a manifest or removing one or adding a new one will recreate the ACI
rootfs)
- documented it a bit
- the ACI rootfs …

build: Split the building of CoreOS ACI rootfs into separate file

---

rkt/list.go

Commit 65398a didn't take into consideration that the Name field in the
Image section of the PodManifest is options. Thus, in the case that it's
not there rkt list crashed. This is a temporary fix for this issue.
A more thorough fix is being tracked in ticket #1659.
Closes #1628

stage0: check for valid name in PodManifest

---

Documentation/subcommands/run.md

There was an incorrect flag in the docs for the `run` subcommand, as reported in https://github.com/coreos/rkt/issues/1665. This commit fixes the flag.

docs: replaced reference to --register-mds with --mds-register

---

common/common.go
rkt/api_service.go
rkt/api_service_test.go
store/store.go

This PR implements basic interfaces for reading pod/image information:
ListPods(), InspectPod(), ListImages(), InspectImage(). And GetInfo()
to get rkt/appc/api version info.

rkt/api_service: add implementation for basic api service interfaces.

---

Documentation/app-container.md
Documentation/devel/stage1-implementors-guide.md
pkg/aci/aci.go
rkt/fetch_test.go
stage1/aci/aci-manifest.in
store/store_test.go
store/tree_test.go
tests/empty-image/manifest
tests/image/manifest
tests/rkt_cat_manifest_test.go
tests/rkt_exec_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go
tests/test-auth-server/aci/aci.go

rkt uses appc/spec 0.7.1 since https://github.com/coreos/rkt/pull/1543

appc/spec: use version 0.7.1

---

Documentation/subcommands/run.md
rkt/cli_apps.go
rkt/prepare.go
rkt/run.go
tests/rkt_volume_test.go

The syntax of `--inject-volume` has been somewhat contentious [1][1] and
it seems pretty clear we do not want the flag to remain as-is.
Furthermore, there's actually no immediate need for it since the same
functionality can be achieved through a combination of the `--volume`
and `--mount` flags (which landed in the same PR as `--inject-volume`).
Hence, remove it for now, guide people towards the alternative, and we
can put further thought into re-adding something similar in future
(which would essentially just be a convenience).
[1]: https://github.com/coreos/rkt/issues/1656
[2]: https://github.com/coreos/rkt/pull/1582

run: remove `--inject-volume`

---

stage1/makelib/aci_install_bin.mk
stage1/makelib/aci_simple_go_bin.mk

stage1 ACI image had an indirect dependency on a tool (init or gc)
inside the ACI rootfs directory, but it didn't have any dependency on
the stamp which, besides making sure that the binary was built, is
making sure that the deps file are generated. Those deps file are
adding dependencies to built binary on its source files.
Make the binary in the ACI rootfs directory to depend on the stamp
too, so the missing files are generated.

build: Fix ACI Go tools not being rebuilt on the source file changes

---

pkg/fileutil/fileutil.go
pkg/fileutil/fileutil_test.go

Otherwise you could end up with truncated file paths.
cc @dgonyeo

pkg/fileutil: clean src dir in CopyTree

---

stage1/common/mount.go
stage1/init/kvm/mount.go
stage1/init/pod.go

In https://github.com/coreos/rkt/pull/1582 we added support for
PodManifest.Mounts but we didn't consider the kvm flavor.
This commit adds support for the kvm flavor and refactors the code a
bit.
Fixes #1663

stage1: use PodManifest.Mounts in the kvm flavor

---

stage1/makelib/aci_simple_go_bin.mk

The stamp was not created at all, and that forced copying built go
tools into the ACI rootfs directory on every run, which in turn forced
rerunning actool to build the final stage1 image.

build: Fix useless rebuilds of stage1 images

---

pkg/tar/chroot.go
pkg/tar/tar.go

It would be useful in acbuild to be able to untar ACIs without
chrooting, so this commit makes the function that does the extracting of
the tar file exposed. With this change the tar package exposes an
ExtractTar function for extracting an ACI inside of a chroot, and an
ExtractTarInsecure function for extracting an ACI without any chroot
happening.

pkg/tar: rename extractTar to ExtractTarInsecure

---

rkt/enter.go
rkt/pods.go

Instead of returning the PID of the process that's PID 1 inside the
container, we return the pid of the rkt process that started the pod.
Users can, for example, terminate the pod by sending SIGTERM to that PID
if the container was started with systemd-nspawn.

rkt: return the pid of stage1 in "rkt status"

---

Documentation/using-rkt-with-systemd.md

After https://github.com/coreos/rkt/pull/1694, rkt needs to be the group
leader in a systemd unit file to make unit file detection work.
Add some documentation on the topic.

Documentation: systemd: executing commands before rkt

---

common/common.go
rkt/list.go
rkt/pods.go
store/tree.go
tests/rkt_list_test.go

Currently we are relying on an optional field in the PodManifest to get
the images name and version when running `rkt list` because, since one
has been able to remove referenced images, there was no guarantee that
the ImageManifest in the cas would be available.
However, little did we know, there is a copy of the ImageManifest of the
pod in the pod's appinfo directory. This commit makes use of that.
Should close #1659.

rkt: get name from ImageManifest

---

pkg/aci/aci.go
rkt/enter.go
rkt/images.go
rkt/pods.go
rkt/prepare.go
rkt/run.go

We were directly returning err so messages were confusing.
Fixes partially #1700

rkt: improve manifests unmarshaling errors

---

scripts/vagrant/install-rkt.sh

The `scripts/vagrant/install-rkt.sh` script erroneously tests for the
existence of a `unsquash` command. It should be `unsquashfs` instead.

build: Correct erroneous test for squashfs-tools

---

stage1/init/init.go

With https://github.com/systemd/systemd/pull/1817, systemd-nspawn can
receive the name of the container service that's calling it.
This commit passes "rkt", which allows the container to be registered to
machined with the "rkt" name.
Note that this will start working when we update stage1's systemd to
v228, but doing it now doesn't hurt and we'll be ready.

stage1: pass SYSTEMD_NSPAWN_CONTAINER_SERVICE env var

---

rkt/images.go
store/store.go
tests/rkt_fetch_test.go

Downloads for a given url are now saved to a file named after a sha512
hash of the url. If the file already exists for a requested download, a
check will be made to see if the server supports HTTP range requests. If
such requests are supported then only the missing part of the file will
be downloaded, otherwise the entire file will be downloaded as before.

stage0: added ability to resume interrupted downloads

---

Documentation/subcommands/image.md
rkt/image_gc.go
rkt/image_list.go
rkt/image_rm.go
store/aciinfo.go
store/migrate.go
store/schema.go
store/store.go

This commit makes rkt image gc remove images from the store apart from
unreferenced treestores.
By default, images not used in the last 24h will be removed. This can be
configured with the `--grace-period`.
Fixes #1205

rkt: image gc: garbage-collect images from the store

---

pkg/uid/uid.go

Since integer constants on 32-bit platforms are signed 4-byte integers, some of
them overflow. They therefore need explicit casting.

pkg/uid: fix integer overflow on 32-bit systems

---

tests/rkt_tests.go

The [previous error](https://semaphoreci.com/coreos/rkt/branches/pull-request-1696/builds/12) on #1696 was:
```
--- FAIL: TestAPIServiceGetInfo (0.10s)
rkt_api_service_test.go:37: Running rkt install
rkt_api_service_test.go:42: Running rkt api service
rkt_tests.go:125: rkt didn't terminate correctly: exit status 2
```
This patch should add more output.
/cc @yifan-gu

tests: add output when the test fails

---

tests/run-build.sh

Unnecessarily quoting sections was causing it to be double-quoted when
bash was invoking the grep.

tests: fix regex for doc check

---

tests/run-build.sh

:facepalm: running these commands in a sub-shell (to ensure failures
don't propagate) means that the variables are never appropriately
replaced in the parent.

docs: perhaps maybe really fix doc-skip check

---

Documentation/commands.md
Documentation/subcommands/cat-manifest.md
rkt/cat_manifest.go
rkt/enter.go
rkt/pods.go
rkt/run_prepared.go
rkt/status.go
tests/rkt_cat_manifest_test.go
tests/rkt_image_cat_manifest_test.go

We've had a cat-manifest for the ImageManifest but not for the PodManifest. This adds that missing functionality.
There is also a bit of related refactoring included.
Should close issue #1730

cat-manifest cmd for pods

---

rkt/api_service.go
rkt/images.go
rkt/metadata_service.go
tests/rkt_api_service_test.go
tests/rkt_tests.go

Add tests for GetInfo(), ListPods(), InspectPod()
ListImages() and InspectImage().
Fix #1668
This follows #1696 as semaphore refuses to test that branch :(

tests: add functional tests for rkt api service.

---

README.md

The signing procedure guide was incorrectly linked to old vivid docs. Now links
to signing and verification guide.

docs: fix broken reference to signing process

---

pkg/label/label_selinux.go
pkg/selinux/selinux.go
rkt/run.go

In the absence of a long-running daemon, the current code that ensures that
SELinux contexts aren't reused makes no sense - it's simply keeping a map
of used contexts, which means independent instances of rkt aren't sharing
this list. Keep the contexts in the filesystem instead in order to avoid
this.

Store used MCS contexts on the filesystem

---

tests/run-build.sh

This is the case on PR merges.
Fixes #1778

tests: always run tests when the current HEAD is master

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/docker2aci/lib/common/common.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/conversion_store.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/docker2aci.go
Godeps/_workspace/src/github.com/golang/protobuf/proto/testdata/test.pb.go

The last docker2aci should help with the following issues:
- https://github.com/coreos/rkt/issues/1653 (whiteout-ed hard links)
- https://github.com/coreos/rkt/issues/1617 (/dev/stdout)

Godeps: update to the last docker2aci

---

Documentation/subcommands/run.md
stage1/init/common/mount.go
stage1/init/kvm/mount.go
stage1/init/pod.go
tests/rkt_fetch_test.go
tests/rkt_volume_test.go

If there is a mount point in the Image Manifest but the user didn't
provide a matching volume, we create an implicity empty volume.
We warn the user because the empty volume will be deleted when the pod
gets garbage-collected.
Fixes #1480 
Closes #1772

stage1: generate empty vol if a required one is not provided

---

CHANGELOG.md

Updating the changelog at each release takes time because we need to go
over all the changes since the previous release. I would like to add a
"vUNRELEASED" entry to update as long as we implement something worthy
of writing in the changelog. Then, we would just rename the
"vUNRELEASED" entry during the release process.
-----
/cc @blixtra @jonboulle

CHANGELOG.md: add an entry for unreleased changes

---

tests/rkt_ace_validator_test.go

The test failed, because it expected ACE validator to print several OK messages in strict order (prestart, main, sidekick and poststop). But main and sidekick run in parallel, so the order of OK messages was sometimes prestart, sidekick, main and poststop.
Fixes #1781.

functional tests: fix ACE validator race

---

CHANGELOG.md
Documentation/commands.md
rkt/rkt.go
rkt/run.go
stage0/run.go

Disable checking the treestore when using `--insecure-options=ondisk`
which is implemented in this change.
This reduces the start-up time of big images dramatically.
For example, with docker://jenkins.
docker://jenkins
real	0m7.200s
user	0m6.740s
sys	0m0.550s
docker://jenkins --insecure-skip-verify
real	0m0.384s
user	0m0.100s
sys	0m0.030ss
Closes #1350

Insecure options ondisk

---

networking/kvm.go

This PR adds macvlan network type CNI interface in kvm flavor with use of macvtap interfaces.

[kvm] Macvlan network type

---

stage1/init/common/mount.go
tests/rkt_volume_test.go

We added the mandatory Mode, UID and GID flags to empty volumes but we
weren't setting them when we generated implicit empty volumes.
This wasn't caught in the tests because they were wrong: we were using a test ACI that didn't include a mount point so we were not really testing implicit empty volume generation.

stage1: set permissions for implicit empty volumes

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/docker2aci/lib/backend/file/file.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/backend/repository/repository.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/backend/repository/repository1.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/backend/repository/repository2.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/common/common.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/common/docker_functions.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/docker2aci.go
rkt/images.go

docker2aci recently gained support for the v2 docker HTTP API. Bumping
the version used by rkt to pull that into here.

godeps: bump docker2aci

---

makelib/file-ops-epilog.mk

Otherwise build system will complain about generating two exactly the
same rules for the target.

build: Deduplicate CREATE_DIRS variable

---

Documentation/hacking.md

These were the required packages when building on Fedora 22

Documentation: add more build-time requirments

---

rkt/images.go
tests/rkt_fetch_test.go

The insecure parameter forces docker2aci to connect to the registry
using `http://`.
Make it false while docker2aci doesn't have logic to try `https://` and
fall back to `http://` if that didn't work.
Fixes #1829

rkt: always use https:// when fetching docker images

---

Documentation/running-lkvm-stage1.md
stage1/init/init.go
stage1/init/kvm/resources.go
stage1/init/kvm/resources_test.go

KVM Added: new functionality to read cpus and mem from resource isolators. Currently kvm uses hard-coded values.
Notes-cpus: By default containers start working on all cpus if at least one app does not have specfied cpus. In the other case, container will be working on aggregate amount of cpus. 
Notes-memory: Container memory is a sum of memory required by each app in pod and additional 128MB required by system. If memory of some app is not specified, app memory will be set on default value (128MB).

kvm: resource isolators

---

rkt/rkt.go

Make change to combine the 2 functions together.

<rkt>: rkt.go has 2 functions with the same name - init()

---

stage1/aci/aci-install.mk

The rules for generating deps file for variables used in manifest
generation and for installed files were there, but nothing depended on
those. Fix that, so now main stamp depends on them.

build: Add missing deps generation

---

stage1/init/pod.go

We were assuming that if "exec" is present, it won't be empty. This is
incorrect because the spec lists exec as optional.
Fixes #1841

stage1: return an error if an app has empty exec

---

CHANGELOG.md
Documentation/configuration.md
Documentation/devel/on-disk-format.md
rkt/api_service.go
rkt/config/config.go
rkt/config/config_test.go
rkt/config/paths.go
rkt/enter.go
rkt/fetch.go
rkt/gc.go
rkt/image_cat_manifest.go
rkt/image_export.go
rkt/image_extract.go
rkt/image_gc.go
rkt/image_list.go
rkt/image_render.go
rkt/image_rm.go
rkt/install.go
rkt/pods_test.go
rkt/prepare.go
rkt/rkt.go
rkt/run.go
rkt/run_prepared.go

Adds a new category of config called "paths" which is intended to
allow the user to configure various paths. At the moment, it supports
one - the data directory. By setting this, you can control where image
files are stored without having to give a CLI argument.
This is based on #1192.
I will need it for configuring default stage1 directory.

config: Make the data directory configurable

---

.gitignore
CHANGELOG.md
rkt/gc.go
stage0/gc.go
stage0/gc_test.go

When a pod directory is in an unexpected state, it may happen that the
standard garbage collection fails. When this happens mounts can be left
around, requiring manual removal.
This change forces a GC of the pod mount points when the pod GC
otherwise fails. To do this, the /proc/self/mountinfo file is parsed,
the pod mount points are extracted, ordered, then unmounted.
fixes #1572

stage0: brute-force GC on GC failure

---

pkg/tar/tar.go
pkg/tar/tar_test.go

If the extraction is not running in a chroot, the file to hard link
against must be prefaced by the target for the extraction, otherwise the
file that's being linked to will not exist and the link will fail.
Fixes appc/acbuild#139.
Replaces https://github.com/coreos/rkt/pull/1827.

tar: prefix hard link destination with extraction target

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/coreos/go-tspi/LICENSE
Godeps/_workspace/src/github.com/coreos/go-tspi/attestation/attestation.go
Godeps/_workspace/src/github.com/coreos/go-tspi/tpmclient/tpmclient.go
Godeps/_workspace/src/github.com/coreos/go-tspi/tspi/context.go
Godeps/_workspace/src/github.com/coreos/go-tspi/tspi/hash.go
Godeps/_workspace/src/github.com/coreos/go-tspi/tspi/key.go
Godeps/_workspace/src/github.com/coreos/go-tspi/tspi/nv.go
Godeps/_workspace/src/github.com/coreos/go-tspi/tspi/pcrs.go
Godeps/_workspace/src/github.com/coreos/go-tspi/tspi/policy.go
Godeps/_workspace/src/github.com/coreos/go-tspi/tspi/tpm.go
Godeps/_workspace/src/github.com/coreos/go-tspi/tspi/tspi.go

This is a no-op, really just to test godep v33, capture the license
file, and fix one gofmt issue in go-tspi.

Godeps: bump go-tspi to get license file

---

tools/quickrm/main.go

Might provide a clue why make clean is failing.
cc @steveeJ

build: Print contents of the directory we failed to remove

---

Documentation/packaging.md
configure.ac

We use patch to patch the kernel and kvmtool. bc is used somewhere
during kernel build.

build: Check for patch and bc for kvm flavor

---

api/v1alpha/api.pb.go
api/v1alpha/api.proto
rkt/api_service.go
tests/README.md
tests/rkt_api_service_bench_test.go
tests/rkt_api_service_test.go

This enables the API service to return detailed pod/image infos
if required. So for some use case where the users want to get N
pods' detailed info, this saves N grpc round trips.
cc @jonboulle @alban 
cc @dgonyeo you might take advantage of this to not to inspect each pod later.

api: Add 'detail' field in ListPods and ListImages request.

---

stage1/init/init.go

libsystemd.so is not part of some default installations. For example,
Fedora includes that file as a part of systemd-devel.
Use libsystemd.so.0 and treat failures to open it as errors instead of
assuming we're not running systemd. Use util.IsRunningSystemd() to check
if we're actually running systemd.
Fixes #1867

stage1: fix unit file detection

---

CHANGELOG.md
Documentation/subcommands/run.md

The new rkt parameters --memory and --cpu were added without
documentation via https://github.com/coreos/rkt/pull/1851.
Add the documentation.

doc: --memory, --cpu

---

rkt/image/fetcher.go
tests/rkt_auth_test.go
tests/rkt_image_dependencies_test.go
tests/rkt_tests.go
tests/test-auth-server/aci/server.go

fetch: allow duplicate dependencies in the dependency tree
Fixes https://github.com/coreos/rkt/issues/1752
Includes a new test TestImageDependencies that could reproduce the bug. The test run an image discovery on a local https server (port 443) with the appropriate insecure option.
I cannot run the test on http because httptest waits forever when using
httptest.Start() on a non-random port, see:
https://golang.org/src/net/http/httptest/server.go?s=2768:2792#L112
And I have to use the non-random port 443: I need standard https port because
of https://github.com/coreos/rkt/pull/375#issuecomment-160901072

fetcher: fix dependency issue, new test TestImageDependencies + disco

---

api/v1alpha/api.pb.go
api/v1alpha/api.proto
pkg/set/string.go
pkg/set/string_test.go
rkt/api_service.go
rkt/api_service_test.go

This is a break change for API service:
1, replaces the single filter field with multiple filters in `ListPods` and `ListImages`.
2, filters are combined with `OR`, and conditions within a filter are combined with `AND`, which provides a better flexibility.
cc @dgonyeo

replace single filter with multiple filters

---

rkt/gc.go
stage0/gc.go
stage0/gc_test.go

This covers unmounting of recursive bind-mounts, as well as the overlay mounts.
It also has the advantage of not attempting to unmount something that is
not there, e.g. if a reboot happened and the mounts are gone anyway.

GC: always detect and unmount leftovers

---

api/v1alpha/api.pb.go
api/v1alpha/api.proto
rkt/api_service.go
rkt/api_service_test.go

api_service: Minor refactoring on what to return for different pod state.
If a pod is in Embryo, Preparing, AbortedPrepare state,
only id and state will be returned.
If a pod is in other states, the pod manifest and
apps will be returned when 'detailed' is true in the request.
Valid pid and networks are only returned when a pod is in Running.

api_service: Minor refactoring on what to return for different pod state.

---

MAINTAINERS

Eugene is sadly no longer with CoreOS, so remove his handle from
the list of maintainers. He will be gladly welcomed back if he
decides to continue contributing to the project.
In happier news, Derek has joined us as an active and effective
contributor, so add him to the maintainers.

MAINTAINERS: remove eyakubovich, add dgonyeo

---

.travis.yml
Documentation/hacking.md
configure.ac
scripts/install-go.sh
tests/install-deps.sh
tests/run-build.sh

~~At this point we drop support for go 1.4.~~
We still support go 1.4, but it is only used in travis. Semaphore builds with go 1.5 only now.

*: Move to go 1.5.

---

api/v1alpha/api.pb.go
api/v1alpha/api.proto
rkt/api_service.go
tests/rkt_api_service_test.go
tests/rkt_tests.go

Partially implements #1872. This patch adds "Size" to the API response. It does not add annotations, I was planning on adding that in another PR but can fold it into this one if that's preferred.

Add size to api response

---

Documentation/trying-out-rkt.md
Documentation/using-rkt-with-kubernetes.md
Documentation/using-rkt-with-nomad.md
README.md

This breaks apart much of the README into a new "basics" document. The
goal is to make the README a little more approachable and do better at
highlighting the different options for people to reach out.
Also adds initial documents describing integration with Nomand and
Kubernetes and links to them appropriately.

docs: rework README + add initial docs for nomad/k8s

---

README.md

This replaces the Travis CI Badge in README.md with SVG, makes the badges much nicer on hi-dpi devices.

Change Travis CI Badge from PNG to SVG

---

CHANGELOG.md
Documentation/packaging.md
Documentation/subcommands/enter.md
Documentation/using-rkt-with-kubernetes.md

For unknown and mildly baffling reasons, kubernetes.io is only available over http

*: fix various broken links

---

networking/kvm.go

Call RemovePersistentIface func to cleanup tap interface when error occurs.
Please give any feedback!

added a line that cleanup tap interface

---

Documentation/subcommands/image.md
rkt/image_rm.go
store/store.go
tests/rkt_image_rm_test.go

Images can be deleted by both ID and name. Should there be multiple
images with the same name, all of them will be removed.
Resolves #1779

rkt,store,tests: delete images by name

---

rkt/list.go
rkt/pods.go

Because we already had the app names, it's better to get a specific app's
image manifest rather than getting the image manifests from all the
apps and forcing the caller to sort through those.
This was requested by @yifan-gu here:  https://github.com/coreos/rkt/pull/1701#discussion-diff-48934836

rkt: change getAppsImageManifests to getAppImageManifest

---

.travis.yml
tests/rkt_api_service_test.go

Go 1.4.3 tarball by mistake does not provide some tools we require, so
we were go-getting them. Unfortunately go vet recently became broken
for go 1.4, so we revert to go 1.4.2, which had those tools.

travis: Work around problems with go vet on go 1.4

---

.travis.yml
Documentation/hacking.md
Documentation/using-rkt-with-systemd.md
Godeps/Godeps.json
Godeps/_workspace/src/github.com/naegelejd/go-acl/.gitignore
Godeps/_workspace/src/github.com/naegelejd/go-acl/README.md
Godeps/_workspace/src/github.com/naegelejd/go-acl/acl.go
Godeps/_workspace/src/github.com/naegelejd/go-acl/acl_darwin.go
Godeps/_workspace/src/github.com/naegelejd/go-acl/acl_linux.go
Godeps/_workspace/src/github.com/naegelejd/go-acl/entry.go
Godeps/_workspace/src/github.com/naegelejd/go-acl/example/.gitignore
Godeps/_workspace/src/github.com/naegelejd/go-acl/example/unix.go
Godeps/_workspace/src/github.com/naegelejd/go-acl/getfacl/.gitignore
Godeps/_workspace/src/github.com/naegelejd/go-acl/getfacl/getfacl.go
Godeps/_workspace/src/github.com/naegelejd/go-acl/os/group/group.go
Godeps/_workspace/src/github.com/naegelejd/go-acl/os/group/lookup.go
Godeps/_workspace/src/github.com/naegelejd/go-acl/os/group/lookup_stubs.go
Godeps/_workspace/src/github.com/naegelejd/go-acl/os/group/lookup_unix.go
Godeps/_workspace/src/github.com/naegelejd/go-acl/os/owner.go
Godeps/_workspace/src/github.com/naegelejd/go-acl/perms.go
Godeps/_workspace/src/github.com/naegelejd/go-acl/setfacl/.gitignore
Godeps/_workspace/src/github.com/naegelejd/go-acl/setfacl/setfacl.go
configure.ac
stage1/init/common/pod.go
stage1/init/init.go
tests/install-deps.sh

Mimicking my host's `/var/log/journal` permissions, set pod's
`/var/log/journal` to:
```
user::rwx
group::r-x
group:rkt:r-x
mask::r-x
other::r-x
default:user::rwx
default:group::r-x
default:group:rkt:r-x
default:mask::r-x
default:other::r-x
```
Fixes #1755

stage0: set journal permissions/ACLs to allow access to rkt group

---

Documentation/rkt-build-rkt.md
scripts/install-deps-debian-sid.sh
scripts/install-deps-fedora-22.sh

We depend on libacl development headers but we forgot to update the
scripts to build rkt in rkt.

build: add libacl dev dependencies to build rkt-in-rkt scripts

---

common/common.go
rkt/pods.go

Noticed in #1701 that it appeared to have gained a superfluous modifier
and the docstring was out of sync with the function name

common: fix function name AppImageManifestPath

---

stage1/usr_from_kvm/lkvm.mk
stage1/usr_from_kvm/lkvm/patches/terminal_late_fix.patch

stage1: Upgrade lkvm to current master branch to fix a 9pfs bug.
Fixes: https://github.com/coreos/rkt/issues/1917
Signed-off-by: Arthur Chunqi Li <chunqi.li.pku@gmail.com>

Upgrade lkvm to fix a 9pfs bug

---

CHANGELOG.md
Documentation/commands.md
rkt/flag/rktflag_test.go
rkt/flag/secflags.go
rkt/image/namefetcher.go

This adds code, tests, and documentation for a new "http" `--insecure-options` flag.
fixes https://github.com/coreos/rkt/issues/1836

Add insecure option http

---

tests/aws.sh
tests/cloudinit/centos.cloudinit
tests/cloudinit/debian.cloudinit
tests/cloudinit/fedora.cloudinit
tests/cloudinit/ubuntu.cloudinit
tests/test-on-several-distro.md

Support Fedora, Ubuntu, Debian, CentOS.
rkt does not have a Continuous Integration system that can run the tests
on all Linux distributions yet. But this script helps with manual
testing.
-----
See also https://github.com/coreos/rkt/issues/847
/cc @iaguis @steveeJ

tests: new script to run test on AWS

---

Documentation/devel/release.md

Small updates explaining how to do a release:
- include the "fly" stage1
- nicer "sed" command to get the authors
- use more recent version as example
- suggest to add a vUNRELEASED section in CHANGELOG.md

Documentation/devel/release.md: small updates

---

tests/rkt_non_root_test.go
tests/rkt_tests.go
tests/rkt_userns_test.go

CentOS 7 pretends to support user namespaces but does not. See
https://bugzilla.redhat.com/show_bug.cgi?id=1168776#c5
Skip rkt tests with user namespaces when the host cannot do user
namespaces.
https://github.com/coreos/rkt/issues/1927

tests: skip userns tests when userns does not work

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/coreos/gexpect/README.md
Godeps/_workspace/src/github.com/coreos/gexpect/gexpect.go

It includes fixes for regexp expects, which will be used later in functional tests (in #1977).

godeps: Bump coreos/gexpect

---

store/store.go

store: Keep the error message if it causes GetACIInfoWithBlobKey fail.

---

rkt/image_rm.go
tests/rkt_image_rm_test.go

Resolve and deduplicate all images before removing them to prevent
unnecessary error messages.
Fixes #1779

rkt: deduplicate images on image removal

---

tests/rkt_image_rm_test.go

There were no conflicts when I was merging the PR, but some other
function had its name changed in the shortcut-capitalization commit.

functional tests: Fix the broken tests

---

CHANGELOG.md
rkt/image/fetcher.go

If we don't do this, we could use the asc object from a previous image,
resulting on the incorrect signature being fetched.
Fixes https://github.com/coreos/rkt/issues/1982
cc @krnowak

rkt/image: clean asc object before every fetch

---

CHANGELOG.md
rkt/fetch.go
tests/rkt_fetch_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_image_dependencies_test.go
tests/rkt_image_export_test.go
tests/rkt_image_extract_test.go
tests/rkt_image_render_test.go
tests/rkt_non_root_test.go
tests/rkt_os_arch_test.go
tests/rkt_tests.go

It prints the full image hash instead of a truncated one.
Fixes #1967

rkt: add --full flag to fetch

---

tests/aws.sh
tests/cloudinit/fedora-22.cloudinit
tests/cloudinit/fedora-23.cloudinit
tests/cloudinit/fedora-rawhide.cloudinit
tests/cloudinit/fedora.cloudinit
tests/test-on-several-distro.md

The test can now run on Fedora-23, Fedora-22 and Fedora-rawhide.

AWS tests: update to the latest Fedora AMI

---

rkt/version.go

Example of ouput:
$ rkt version
rkt Version: 0.15.0+git7bb295b-dirty
appc Version: 0.7.4
Go Version: go1.5.2
Go OS/Arch: linux/amd64
This does not give the full "Git SHA" but at least it is closer to the
standardised output described on
https://github.com/coreos/docs/issues/637
-----
It was first submitted via #1971 but there was still discussion about the test and I would like to get the first patch in.

version: print the version of the golang compiler

---

tests/rkt_exit_test.go

Only check the return status after the pod terminates. The test was
racy.
Users don't have a good way yet to control when the pod terminate after
an app exits. This test could be revisited if this gets implemented. See
discussion about --nuclear-exit (https://github.com/coreos/rkt/issues/1461).
Fixes https://github.com/coreos/rkt/issues/1999

test: fix race in TestExitCodeWithSeveralApps

---

api/v1alpha/api.pb.go
api/v1alpha/api.proto
rkt/api_service.go
rkt/api_service_test.go

Fix https://github.com/coreos/rkt/issues/1939
First two commits if from https://github.com/coreos/rkt/pull/1983
cc @jonboulle @derekparker

api: Add 'full_names' in the image filter to filter images with names.

---

.travis.yml
configure.ac

./configure already prints the go version, but unfortunately only the
major.minor numbers without the micro:
>        go version:                             '1.5'
This patch prints the full version instead:
>        go version:                             '1.5.3'
Additionally, it checks that the go version is not 1.5.0, 1.5.1 or 1.5.2
to be absolutely sure it is not vulnerable to CVE-2015-8618.

configure: print full go version and check against CVE-2015-8618

---

stage1_fly/run/main.go

Insert environment value by checking related value in Manifest.
Please give any feedback.

rkt fly: add logic to insert environment value

---

Documentation/devel/release.md

When testing the produced binary on a distribution with minimal packages
installed, we could have the following:
```
$ sudo ./rkt
./rkt: error while loading shared libraries: libtspi.so.1: cannot open
shared object file: No such file or directory
```
To make sure it does not happen, the release procedure should check
that.

doc: release: check deps with ldd

---

Documentation/signing-and-verification-guide.md

Make the example use --with-fingerprint option to gpg. Equivalent
to --fingerprint but with filter-intended output.
[I think, interpreting from the "I wish" input, this] Fixes #1858.

Doc/signing-guide: Change --fingerprint to --with-fingerprint

---

rkt/image/dockerfetcher.go

So we can fetch images from non-TLS docker registries.

rkt/image: pass insecure-options=http to docker2aci

---

Documentation/running-fly-stage1.md

This is a convenient quick change to test Docs download script
on the coreos-pages side.

Documentation/running-fly: Monospace kubelet

---

rkt/image/resumablesession.go

As ToDo message indicates, http cache-control arguments are separated by comma and whitespace. Please give any feedback, thanks!

image : modify http cache-control split

---

stage0/arch.go
tests/rkt_os_arch_test.go

Rkt stage0 should support all Linux architectures specified by appc.
TestMissingOrInvalidOSArchFetchRun needs to skip the test case involving
the invalid arch, due to rkt failing it before reaching stage0.

stage0,tests: support more Linux architectures

---

CHANGELOG.md
Documentation/subcommands/list.md
Documentation/subcommands/status.md
rkt/list.go
rkt/pods.go
rkt/status.go
tests/rkt_list_test.go

To get the pod creation time we use the modification time in
`/var/lib/rkt/pods/*/<UUID>/pod`. It's written when the pod is prepared
and doesn't change afterwards.
To get the pod start time we use the modification time in
`/var/lib/rkt/pods/*/<UUID>/ppid`. It's written when the pod actually
starts and doesn't change afterwards.
Partially addresses #1789

rkt: show created/started times in rkt list/status

---

rkt/metadata_service.go
tests/inspect/inspect.go
tests/rkt_metadata_service_test.go

Metadata-service: Handle annotation names that contain slash.

---

networking/networking.go
stage1/gc/gc.go
stage1/init/init.go

This fixes a NullPointerException that happened because stderr was not
initiliazed in Teardown(), but only in Setup().
Fixes #2051 
/cc @blixtra

networking: initialize stderr in Teardown

---

configure.ac

The current 'go version' in fedora rawhide is '1.6rc1'. This version
string doesn't get correctly parsed by the configure script and it
terminates saying, "configure: error: *** go is too old (go version
go1.6rc1 linux/amd64".
This fixes the parsing to accept several version format. Tested with:
- go version go1.5.3
- go version go1.5
- go version go1.6rc1
Based on a patch from: Lokesh Mandvekar <lsm5@fedoraproject.org>
Closes https://github.com/coreos/rkt/pull/2056
-----
/cc @lsm5
I didn't change the preferred version 1.5.

go version: parse 1.6rc1

---

Documentation/getting-started-guide.md

Pretty sure this is necessary for `curl 127.0.0.1:5000` to work.

docs: add --net=host to getting started guide

---

networking/networking.go
networking/portfwd.go
tests/rkt_net_test.go
tests/testutils/iputils.go

This implementation is not ideal because it uses heuristics to find interface names.
The host's veth interface has to be found with the only thing that's known, it's IP address. The names are randomly generated by CNI and are not returned in the CNI result. Further, due to the way the PTP plugin works, multiple veth interfaces have the same address, so they are all candidates for needing *route_localnet* enabled.
Fixes #1256.
Follow-Up:

masquerade and route forwarded packets from host's loopback to the pod

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/coreos/go-tspi/tpmclient/tpmclient.go
pkg/tpm/tpm.go

It allows defining a timeout for requests to the TPM server.
Fixes #1816

Godeps: bump go-tspi

---

pkg/keystore/keystore.go
rkt/image/namefetcher.go
rkt/image/validator.go
rkt/pubkey/pubkey.go
rkt/rkt.go
rkt/trust.go

This commit changes rkt's behavior such that when fetching an image
through meta discovery, rkt will only download and trust the gpg public
key for the image if rkt doesn't have any local keys with a matching
prefix. If the key for an image has changed, the user must manually
trust the new key with `rkt trust --prefix`.
In addition, `--trust-keys-from-https` now defaults to false, so the
user is prompted to approve new keys (unless rkt isn't running in a tty,
in which case an error is printed).
New default behavior when fetching an image in a tty:
```
[nix-shell:~/go/src/github.com/coreos/rkt]$ sudo ./build-rkt-0.15.0/bin/rkt fetch quay.io/coreos/alpine-sh
image: searching for app image quay.io/coreos/alpine-sh
image: remote fetching from URL …
```

trust: only trust pubkeys on first use, prompt for https trust

---

CHANGELOG.md
Documentation/commands.md
Documentation/subcommands/api-service.md
Documentation/subcommands/cat-manifest.md
Documentation/subcommands/enter.md
Documentation/subcommands/fetch.md
Documentation/subcommands/gc.md
Documentation/subcommands/image.md
Documentation/subcommands/install.md
Documentation/subcommands/list.md
Documentation/subcommands/metadata-service.md
Documentation/subcommands/prepare.md
Documentation/subcommands/rm.md
Documentation/subcommands/run-prepared.md
Documentation/subcommands/run.md
Documentation/subcommands/status.md
Documentation/subcommands/trust.md

Follow-up for https://github.com/coreos/rkt/pull/2033:
- update documentation on `--trust-keys-from-https`
- add an entry in the changelog
-----
/cc @dgonyeo @iaguis

Follow up for #2033: documentation

---

Documentation/using-rkt-with-systemd.md

Revision of #2066. In attempt at company-wide consistency, I broke
the rkt repo's internal consistency with use of # for root shell
prompt. This restores the # for command lines requiring privs.
/cc @jonboulle

Documentation/with-systemd: Reconsider shell prompt # v $

---

Documentation/subcommands/api-service.md

Fix a spelling error in the first sentence by dramatically shortening the phrase.

Docs/subcmd/api-svc: Fix first sentence

---

Documentation/build-configure.md
Documentation/devel/tpm.md

Supersedes #2083. 
Add a TPM doc under `devel/`. Link to file from build-configure document,
where the `./configure` option to enable it is covered.
Questions/Requests for particular review:
1. In build-configure, is it true that `--enable-tpm=yes` by default?
2. In build-configure, is the TrouSers requirement still true? Is it true for building only, or for building and running?
3. In tpm.md, are all three items stored in the PCR *hashes* of things (as I recall from earlier work), or are numbers 2 and 3 in fact the actual manifest and the actual argv?

Doc/devel: Describe rkt TPM event log use

---

tests/aws.sh
tests/cloudinit/ubuntu-1510.cloudinit
tests/cloudinit/ubuntu-1604.cloudinit

The current status of the tests is:
- Fedora
- Fedora-Rawhide: currently broken: `Error: nothing provides libpsl.so.0()(64bit) needed by wget-1.17.1-1.fc24.x86_64`
- Fedora-23: PASS
- Fedora-22: kernel panic https://github.com/coreos/rkt/issues/2097
- Ubuntu: needs https://github.com/coreos/rkt/pull/2093
- Ubuntu-1510: PASS
- Ubuntu-1604: TestStage1LoadingFromFlags fails: https://github.com/coreos/rkt/issues/2095
- Debian 8.1: PASS
- CentOS 7: PASS

tests/aws.sh: update with the last images

---

Documentation/build-configure.md
configure.ac
tests/run-build.sh

Ubuntu does not have golang 1.5.3 yet, so the check was completely
blocking the build on Ubuntu. Replace it with a warning.
Related to https://github.com/coreos/rkt/pull/2006
-----
/cc @krnowak

build: print a warning on go version 1.5.{1,2}

---

scripts/install-common.sh

rkt build breaks in configure with
'TPM is enabled, but could not find required development files'
without it

scripts: install libtspi-dev dependency

---

api/v1alpha/README.md
api/v1alpha/api.proto
rkt/api_service.go

I kept "experimental" but removed the "do not use it" warnings.
Is it time to remove it?
/cc @joshix @yifan-gu

api-service: remove "do not use it" warnings

---

Documentation/hacking.md
Documentation/packaging.md

Just make a somewhat completish list in one place and point to it in
packaging docs.
This is rather a temporary solution, I'd prefer the separate document
for listing all the dependencies in a nicer way, but no time for that
currently.
Fixes #2102.

Docs: update the build-time and run-time dependencies

---

CHANGELOG.md
pkg/log/log.go
stage1/enter_kvm/enter_kvm.go
stage1/init/common/kvm_mount.go
stage1/init/common/log.go
stage1/init/init.go
stage1_fly/gc/main.go
stage1_fly/run/main.go
tests/rkt_error_output_test.go

Closes https://github.com/coreos/rkt/issues/2038

stage1: don't suppress error output

---

dist/scripts/setup-data-dir.sh

Most of the script is spaces, in three places tabs were used. Be
consistent and use spaces.

dist: scripts: use spaces everywhere

---

Documentation/getting-started-guide.md

The prior link just ended up pointing at the main Github page for rkt.

documentation: fix link to Vagrant instructions

---

app-container/README.md
app-container/SPEC.md

Winter cleaning time. appc has long, long had its own identity
and home, and it is extraordinarily unlikely anything is still
linking to this location.

*: remove old app-container directory

---

stage1/common/types/pod.go
stage1/init/common/pod.go
stage1_fly/run/main.go

If the fly stage1 was passed an image that had an empty exec, it could
panic. This adds the same check that we use for the non-fly stage1, and
refactors the code slightly to share it between them.
Also renames a couple of old vestigial variables: appmanifest rather
than imagemanifest, etc.
Fixes #2131

stage1/fly: fix error with unset exec statement

---

networking/networking.go
stage1/gc/gc.go

When running 'rkt run --net=mynetwork', it looks for the network plugin
in three different places [1][1]:
- /etc/rkt/net.d/ (or something else with --local-config)
- /usr/lib/rkt/plugins/net
- ${STAGE1_ROOTFS}/usr/lib/rkt/plugins/net
This code works fine for 'rkt run' but does not work for 'rkt gc' or
'rkt rm' because there is a bug in the way --local-config is handled.
When stage1's 'run' entrypoint [2][2] is called, the --local-config flag
is passed. But this --local-config flag was not passed to stage1's 'gc'
entrypoint [3][3].
It might be unfortunate that plugin binaries can be stored in a
configuration directory but this is part of the stable rkt 1.0 interface
now. And plugins like calico rely on it.
Adding this --local-config flag would change the API between stage0 and
stage1, so …

rkt gc: look up for plugins in default local config

---

networking/net_plugin.go
networking/netinfo/netinfo.go
networking/networking.go
stage1/gc/gc.go

The NetInfo struct is created and serialised during "rkt run" into
/var/lib/rkt/pods/run/$UUID/net-info.json. Then, "rkt gc" deserialize
it.
Example of net-info.json, created with the command
"rkt --local-config=/etc/rkt2 run --net=mynetwork ..."
```
> [
>    {
>       "netName" : "mynetwork",
>       "netConf" : "net/mynetwork.conf",
>       "pluginPath" : "/etc/rkt2/net.d/myplugin",
>       "ifName" : "eth0",
>       "ip" : "172.16.28.3",
>       "args" : "",
>       "mask" : ""
>    }
> ]
```
This patch adds the new field "pluginPath". In this way, "rkt gc" knows
where to find the CNI plugin without having to use a --local-config
flag. In the case of network plugins in stage1, "pluginPath" can have a
local path relative to the pod directory, such as …

networking: store the network plugin path in NetInfo

---

CHANGELOG.md
Documentation/using-rkt-with-systemd.md
stage1/init/common/pod.go
stage1/init/init.go
tests/rkt_socket_activation_test.go

We were using the port of the image manifest to set up the socket unit
file inside the pod. This means it only worked if the port in the image
manifest and the pod in the pod manifest (set by rkt at runtime) were
the same.
The reason is that systemd inside the host matches based on the socket
port number, and since the socket is created on the host, it will have
the host port number. If this number is different from the one in the
image manifest, systemd will not assign the socket to the correct app in
the pod because it will expect a socket with the image manifest port
number.
The solution is using the host port number for the socket unit file.
Fixes https://github.com/coreos/rkt/issues/2135

stage1: fix socket activation port matching

---

rkt/metadata_service.go

This was removed from the spec by appc/spec#370, and isn't documented
anywhere.

Delete the "Metadata-Flavor:" header requirement.

---

configure.ac

This fixes detection of development version of go, fixes a warning about expecting integer expression and replaces uses of echo with something portable.
Fixes #2156

build: fix devel go version detection

---

CHANGELOG.md
pkg/group/group.go
pkg/group/group_test.go
pkg/passwd/passwd.go
pkg/passwd/passwd_test.go
pkg/uid/uid.go
stage1/init/common/pod.go
tests/functional.mk
tests/rkt_run_pod_manifest_test.go

Support for non-numerical uid/gid added, as specified by appc.
Resolves #1919

stage1,tests: add support for non-numerical uid/gid

---

store/store.go

The current error message reads for example: "current store db version: 5 greater than the current rkt expected version: 3"
This is misleading and could also mean that it is "5 greater than the rkt expected version: 3". (Hence: 8).
I suggest using brackets around the error message to improve the readability.

Improve readability of error message

---

Documentation/configuration.md

* domains -> registries
Reference: https://github.com/coreos/rkt/blob/9ddb77f0fbc8d5cabbd5a70b7873882341d87ce7/rkt/config/auth.go#L47

documentation: Fix typo in dockerAuth example

---

tests/aws.sh
tests/cloudinit/centos.cloudinit
tests/cloudinit/debian.cloudinit
tests/cloudinit/fedora.cloudinit
tests/cloudinit/ubuntu.cloudinit
tests/test-on-several-distro.md

Previously, tests/aws.sh could only test the default 'coreos' stage1. Add a parameter to the script to select the stage1 flavor to use for the tests.
Also, install nspawn on Debian/Ubuntu. It is not installed by default on Debian and Ubuntu. In order to test the 'host' flavor, I need to install it.

tests: aws: test the 'host' stage1

---

.travis.yml

Travis does not see Makefile in the toplevel directory anymore (it is
now Makefile.in), so it is running `go get -t -v ./..` in install
phase. This is documented in
https://docs.travis-ci.com/user/languages/go#Dependency-Management.
Fix it by explicitly overriding the install phase, as documented in
https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step.

travis: Fix the build after build system changes

---

Documentation/running-lkvm-stage1.md

Explain why rkt LKVM stage1 has the "experimental" label.
Fixes #2163. Fixes coreos/docs#746.

Documentation: Add explanation of experimental label to running-lkvm doc

---

stage1/init/common/kvm_mount.go
stage1/init/common/mount.go
stage1/init/common/pod.go

Add support for pre-defined volumes modes, UIDs and GIDs for apps
inside rkt-kvm pod.
By default, rkt with kvm flavor ignores additional volumes isolators.

kvm: Add custom permissions into mounted volumes

---

Documentation/dependencies.md
Documentation/hacking.md
Documentation/packaging.md
configure.ac

Both coreos and kvm flavors take their userspace from CoreOS PXE
image, so they need the same tools to actually get it.

build: Fix checking for utilities for kvm and coreos flavors

---

stage1/init/init.go

This patch provides setting pod hostname for kvm flavor.
By default, there is one hostname for each pod, instead of unique name (like in coreos flavor)
This patch prepares /etc/hostname file for pod on stage1.
Closes #2189

kvm: Set hostname inside kvm container. Closes #2189

---

CHANGELOG.md
Documentation/devel/architecture.md
common/common.go
stage1/init/common/pod.go
stage1/init/init.go
stage1/reaper/reaper.sh
stage1/units/units/exit.target
stage1/units/units/shutdown.service
tests/rkt_ace_validator_test.go
tests/rkt_api_service_bench_test.go
tests/rkt_api_service_test.go
tests/rkt_caps_test.go
tests/rkt_env_test.go
tests/rkt_exit_test.go
tests/rkt_fetch_test.go
tests/rkt_image_dependencies_test.go
tests/rkt_image_export_test.go
tests/rkt_image_extract_test.go
tests/rkt_image_list_test.go
tests/rkt_image_render_test.go
tests/rkt_image_rm_test.go
tests/rkt_list_test.go
tests/rkt_net_test.go
tests/rkt_pid_file_test.go
tests/rkt_stage1_loading_test.go
tests/rkt_tests.go
tests/rkt_volume_test.go

If the version of the systemd running in stage1 is >=v227, the command
"systemctl exit STATUS" will set the exit status of the container. See
https://lists.freedesktop.org/archives/systemd-devel/2015-October/034509.html:
* The "systemctl exit" command now optionally takes an
additional parameter that sets the exit code to return from
the systemd manager when exiting. This is only relevant when
running the systemd user instance, or when running the
system instance in a container.
If not, we will continue with the previous logic, so we can merge this now
and benefit from it when we actually update to v229.
Closes https://github.com/coreos/rkt/pull/1783

stage1: propagate app exit code to rkt exit code

---

rkt/rkt.go

An obsolete CoreOS test was erroneously passing:
Error: unknown command "install" for "rkt"
Run 'rkt --help' for usage.
2016-02-08T00:57:26Z kola: --- PASS: coreos.rkt.install

rkt: use exit status 2 to report usage errors

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/cni/pkg/ip/ipmasq.go
Godeps/_workspace/src/github.com/appc/cni/pkg/types/types.go
Godeps/_workspace/src/github.com/appc/cni/plugins/ipam/host-local/config.go
Godeps/_workspace/src/github.com/appc/cni/plugins/main/bridge/bridge.go
Godeps/_workspace/src/github.com/appc/cni/plugins/main/ipvlan/ipvlan.go
Godeps/_workspace/src/github.com/appc/cni/plugins/main/macvlan/macvlan.go
Godeps/_workspace/src/github.com/appc/cni/plugins/main/ptp/ptp.go
Godeps/_workspace/src/github.com/appc/cni/plugins/meta/tuning/tuning.go
networking/net_plugin.go
stage1/net-plugins/net-plugins.mk
vendoredApps

Allow users to tune net network parameters such as somaxconn.
With this patch, users can add a new network configuration:
```
> # cat /etc/rkt/net.d/mytuning.conf
> {
>       "name": "mytuning",
>       "type": "tuning",
>       "sysctl": {
>               "net.core.somaxconn": "500"
>       }
> }
```
Then, start rkt with that configuration file:
```
> # rkt run --net=default,mytuning /tmp/mycontainer.aci
```
The value /proc/sys/net/core/somaxconn will be set to 500 in the pod but
will remain unchanged on the host.
Only sysctl parameters that belong to the network subsystem can be
modified.
-----
/cc @slallema: In addition to `net.core.somaxconn`, is there any other settings that would be useful to let users configure?
/cc @steveeJ 
Fixes https://github.com/coreos/rkt/issues/2075

network: add network tuning plugin from CNI

---

stage1/usr_from_kvm/lkvm/patches/dead_lock_fix.patch

This patch is fixing dead lock issue in lkvm. When VM is sending
reboot signal to lkvm then lkvm is sending SIGKVMEXIT to all cpu threads.
When first cpu became closed, pci-devices are checking which cpus are still
alive and send to them SIGKVMPAUSE signal(for detaching, pci-devices require
threads in pause or exited  state). After this signal, devices are waiting
for response from threads.
Main problem in this bug is situation when cpu thread becames exited and
SIGKVMPAUSE signal was sent. In this situation Pci-device is still waiting
for notification from closed thread.
To fix this bug I am waiting for exit status from all cpus before, turning
down devices.

kvm: Fix for dead lock while rebooting VM

---

common/cgroup/cgroup.go
common/common.go
stage0/run.go
stage1/init/init.go

systemd-nspawn should be setting the mount point labels of tmpfs.  Need to add
-L$(MOUNT_CONTEXT) to the options to clean up this problem.
Also need to pass in the mount_context to create the tmpfs to be used with
cgroups to the proper context.
Signed-off-by: Dan Walsh <dwalsh@redhat.com>

This patch make rkt work better with SELinux

---

rkt/image_gc.go

If we can't get some treestoreIDs from the pods, those pods are in a
broken state and we can remove the treestore (if not referenced by some
other healthy pods).
This avoids cases where treestores can't be removed because of damaged
pods.
Fixes https://github.com/coreos/rkt/issues/2180

rkt/image_gc: don't fail hard when unable to get some treestore IDs

---

scripts/install-common.sh

I just tried setting up a development environment from scratch with `vagrant up`, but building failed during the provision step. Looks like it fails because `bc` isn't installed inside the Vagrant box:
```
$ cat rkt-build.log
----------------------------------------------------------------
Initialized build system. For a common configuration please run:
----------------------------------------------------------------
./configure 
checking for bash... /bin/bash
checking for git... git
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for cat... cat
checking for cpio... cpio
checking for gzip... gzip
checking for md5sum... md5sum
checking for mktemp... mktemp
checking for sort... sort
checking for touch... touch
checking …
```

scripts: Add bc to common dependencies

---

stage1/init/common/kvm_mount.go
stage1/init/common/kvm_mount_test.go

P9 file system has limitation, that the tag name needs to be less
than 31 bytes long. Using the md5 hash in stage1 from `volume.name`
(16 bytes long) instead `volume.name` directly doesn't exceed this.

limit from p9 tag to 31 bytes, hash name of the volume
