Documentation/hacking.md

doc: Add appc/spec to dependencies and docker build command.

---

pkg/keystore/keystore_test.go

removeKeyStore removes only the files known in Config.
Drop it and just defer the removal of the whole temp dir.

keystore: tests: remove the whole temporary directory.

---

rkt/fetch.go

- fetchURL expects a url string, not the img name
- When creating a discovery.App from the supplied string, fill in
default values for the "os" and "arch" labels if they're unset
/cc @kelseyhightower

rkt: fix fetch discovery logic

---

rkt/fetch.go

It looks like it is not used anymore.

rkt: remove unused images directory

---

pkg/tar/tar.go

So it can be reused by reused by different tar extraction functions.

pkg/tar: create a function for single tar file extraction

---

pkg/tar/tar.go
pkg/tar/tar_test.go
stage0/run.go

Last commit is the interesting one. 
The previous required commit was proposed in #347.

pkg/tar: add overwrite option to ExtractTar.

---

rkt/fetch.go

Some of the output bothered me, so I changed it.

rkt: tweak wording

---

build
metadata/metadatasvc.go
networking/net-plugin.go
networking/net.go
networking/networking.go
networking/plugins/veth/veth.go
rkt/metadatasvc.go
rkt/rkt.go
rkt/run.go
stage0/run.go
stage1/init/container.go
stage1/init/init.go
stage1/init/registration.go
test

- Move metadatasvc into rkt as a subcommand
- Add option to spawn metadatasvc from rkt run
- Register container with metadatasvc

Integrate metadata service

---

Documentation/getting-started-ubuntu-trusty.md
README.md

added trust instructions for CoreOS signing key
updated links

updated ubuntu getting started for 0.2.0

---

rkt/metadatasvc.go

metadatasvc really belongs in its own package.

metadatsvc: rename container struct to mdsContainer

---

rkt/metadatasvc.go

The spec now says that content to sign/that was signed
is now passed as a form argument.

metadatasvc: content is passed in separately to verify

---

rkt/list.go

This is an initial implementation of the rkt list command.
````
$ ./rkt list
CONTAINER ID                            ACI             STATUS
68d92e43-1dca-45b1-8b07-6c3ce54ac25d    coreos.com/etcd active
df7b479d-3f73-4feb-b992-af2fd615648d    coreos.com/etcd inactive
````
The features of the commands are discussed in #162. I based this on the previous work from @alban in #343 without moving the subcommands (like `GetContainers()`, etc.) in a separate file. 
This code will probably need to be rewritten once #371 is merged, as it's way cleaner to get all the info from an API instead of generating it each time over and over again.

list containers: add new subcommand

---

rkt/enter.go
rkt/status.go
rkt/uuid.go

Last commit is the interesting one

Support short container uuids on the rkt cli

---

README.md
rkt/fetch.go
rkt/fetch_test.go
rkt/run.go

rkt: disable discovery in stage1 image fetching

---

stage0/run.go
stage1/init/init.go

--spawn-metadata-svc is just a helper to launch another
program. It's not stage1 specific and stage0 feels like
a better place for it.

metadatasvc: process --spawn-metadata-svc in stage0

---

networking/ipam/ipam.go
networking/ipam/static/backend/disk/backend.go
networking/net/bridge/bridge.go
networking/net/veth/veth.go
networking/networking.go

- Fixes bugs in ipam/static release path
- veth and bridge plugins invoke ipam plugin during DEL cmd

net: call ipam plugin on container shutdown

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/coreos/go-iptables/iptables/iptables.go
Godeps/_workspace/src/github.com/coreos/go-iptables/iptables/iptables_test.go

IP masquerading will use this package

net: vendor go-iptables

---

networking/ipam/ipam.go
networking/net/bridge/bridge.go

net: ignore dup route errors; better handling of gw in bridge

---

rkt/run.go

rkt/run: clarify location of default stage1

---

cas/remote.go

Minor cleanup which fell out of local+remote unification effort

cas/remote: consolidate signature/ACI HTTP gets

---

README.md

This updates the recommended rocket install to the latest release.  Thanks!

readme: bump rocket version to 0.3.1

---

Documentation/commands.md

docs: expand run and gc commands

---

rkt/trust.go

Fixes https://github.com/coreos/rocket/issues/474

rkt trust: disable http by default, enable via --insecure-allow-http

---

Documentation/stage1-implementors-guide.md

doc: stage1 implementor's guide

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/docker2aci/lib/docker2aci.go

It fixes some non-working images by including environment and workdir,
handling Entrypoint and Cmd correctly and fixing a couple of minor bugs.

Bump docker2aci dependency

---

networking/networking.go

The user might modify or delete the net config
files while the container is running. This will
mess up the plugins on the teardown path. Copying
them into a the container directory and using them
from there should guard against that. It also lays
the foundation for GC to process unremoved files.

net: copy netconf files into container dir

---

networking/ipam/static/main.go
networking/net/bridge/bridge.go
networking/net/veth/veth.go
networking/util/skel.go

main function of plugins is very boilerplate with
all the env var extraction and error checking.
Factor it out into util.

net: factor out plugin main

---

networking/ipam/static/config.go
networking/net/bridge/bridge.go

Be more consistent across config files.

net: fix names of JSON config keys

---

Documentation/networking.md

I think what I wrote is not completely clear. Feedback would be much appreciated.

docs: added networking docs

---

rkt/prepare.go

Also fix an error message output.

Fix return value for 'rkt prepare'.

---

rkt/gc.go

`rkt gc` will now reap expired prepared containers, the default period is
somewhat arbitrary right now at 24 hours.
Invoking `rkt gc --expire-prepared=0` removes all prepared containers.

rkt: add --expire-prepared flag to `rkt gc`

---

rkt/run.go

Add the missing error for the output message.

Fix rkt/run.go

---

cas/remote.go

It is annoying to sit through an entire download of an ACI only to find
out the author didn't publish a signature. Download the ASC first.
Fixes #573

cas: remote: download the sig before the ACI

---

rkt/prepare.go
rkt/run.go

The example in the help text is wrong and conflicts with the docs, fix
this.

rkt: fix volume example in run/prepare

---

Documentation/commands.md

Open question: I want to describe how ports work. Is it accurate to say that any port can be communicated without conflict since the container/pod has its own IP? Or is that wrong?
cc: @eyakubovich

docs: include short networking example

---

stage0/run.go

Last commit is the interesting one. The other commits are the needed ones from #297.
This makes rocket stage0 use the acirenderer library (the tar hash checks are done by the acirenderer). This will fully render ACIs with dependencies (a dependency fetching mechanism is needed)
Probably the future will be something like #223 but in the meantime it does its job.

stage0: Use ACI Renderer library.

---

stage0/run.go

stage0: simplify image rendering invocation

---

stage1/rootfs/prepare-app/prepare-app.c

https://github.com/coreos/rocket/issues/606

stage1: prepare-app: prepare /, /sys, /dev/shm for apps

---

networking/netinfo/netinfo.go
networking/networking.go
rkt/containers.go
rkt/list.go
rkt/status.go

net: rkt list supports displaying container's IP addrs

---

stage0/run.go
stage1/rootfs/prepare-app/prepare-app.c

Also clear umask in prepare-app so modes are used verbatim.

stage1: create /tmp in prepare-app instead of stage0

---

cas/cas.go

cas: remove TODO referencing the need of a database.

---

stage0/run.go

stage0: change default perms to 0755

---

dist/init/systemd/rkt-gc.service
dist/init/systemd/rkt-gc.timer

Add some initial service files for rkt gc

dist: init: systemd: initial commit

---

Documentation/commands.md

Links to doc written based on https://github.com/coreos/rocket/issues/622

docs: link to metadata service document

---

cas/cas.go
cas/db.go
networking/ipam/static/backend/disk/backend.go
pkg/lock/dir.go
pkg/lock/dir_test.go
pkg/lock/keylock.go
pkg/lock/keylock_test.go
rkt/containers.go
rkt/containers_test.go

This patch adds image locking like explained in #460.

cas: add image locking.

---

stage1/init/container.go

These are currently being set to static root values, will revisit once
the spec matures in this area.
Fixes #687

stage1/init: set minimum appc-required environment defaults

---

rkt/install.go

We added some new directories and files to the cas so we need to update
rkt install to handle them.

rkt: update install with new directories/files

---

README.md

readme: Update section about Vagrant.

---

stage1/init/container.go

stage1: set systemd-nspawn machine to pod UUID

---

rkt/rkt.go
stage0/run.go
stage1/init/init.go

stage1: discard logger output if no --debug is present

---

scripts/debug/stage1_install_busybox.sh

Pods live in /var/lib/rkt/pods now.

scripts: debug: containers -> pods

---

Documentation/getting-started-guide.md
Documentation/getting-started-ubuntu-trusty.md

Use rkt trust instead of manual trust process; update to latest etcd; tweak
some terminology/output
Fixes #779

docs: update getting started guides

---

Documentation/metadata-service.md

docs: no more iptables NAT and mention systemd units

---

Documentation/networking.md

Fix a few formatting issues when moving docs over to jekyll.

docs: fix formatting

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/syndtr/gocapability/capability/capability.go
Godeps/_workspace/src/github.com/syndtr/gocapability/capability/capability_linux.go
Godeps/_workspace/src/github.com/syndtr/gocapability/capability/capability_noop.go
Godeps/_workspace/src/github.com/syndtr/gocapability/capability/capability_test.go
Godeps/_workspace/src/github.com/syndtr/gocapability/capability/enum.go
Godeps/_workspace/src/github.com/syndtr/gocapability/capability/syscall_linux.go
tests/inspect/inspect.go
tests/rkt_caps_test.go
tests/rkt_env_test.go

I am not sure whether to re-implement tools like captest, pscap etc. in
rkt-inspect.aci (fast to execute, no need to download extra containers
from Internet) or to re-use existing tools with docker://debian and
apt-get install (fast to implement new tests).
This patch contains a bit of both approaches.

functional tests: new test for capabilities

---

tests/inspect/inspect.go
tests/rkt_interactive_test.go

It contains a regression test for
https://github.com/coreos/rkt/issues/758
/cc @iaguis

functional tests: new test for rkt run -interactive

---

rkt/enter.go
rkt/fetch.go
rkt/fetch_test.go
rkt/gc.go
rkt/images.go
rkt/prepare.go
rkt/run.go
rkt/run_prepared.go
store/aciinfo_test.go
store/remote_test.go
store/store.go
store/store_test.go
store/tree.go
store/tree_test.go

ds was a legacy name reflecting the store was once DownloadStore

store: rename ds -> s

---

rkt/prepare.go
rkt/run.go
stage0/run.go

Fix #294.
This assumes the image is already on the machine when `rkt run --pod-manifest $manifest.json`

rkt: add --pod-manifest to support user specified pod manifest.

---

stage1/rootfs/enter/enter.c

Also the capitalized error messages.

stage1/enter: use pexit_if() for errno-valid conditions

---

Documentation/metadata-service.md

I'm not sure this link ever worked...

docs: fix broken link to dist

---

Documentation/using-rkt-with-systemd.md
README.md

/cc @rimusz, this is extremely basic so far. What else would you like to see here?

docs: add basic systemd doc

---

rkt/images.go

rkt: support deferring of the signature download

---

stage1/init/init.go

If we're running from a unit file, we pass --keep-unit to systemd-nspawn
to avoid being moved to a different cgroup.
Fixes #848

stage1: use systemd-nspawn's --keep-unit

---

Documentation/commands.md

docs: fix host volume example

---

Documentation/using-rkt-with-systemd.md

Adding in a more advanced unit that shows off some cooler systemd integration.

docs: expand systemd examples

---

stage1/rootfs/usr_from_src/Makefile

- remove --disable-readahead
- remove --disable-multi-seat-x
- add --disable-selinux

stage1: systemd: update build option

---

rkt/images.go

Before:
```
rkt: searching for app image coreos.com/etcd:v2.0.4
rkt: fetching image from https://github.com/coreos/etcd/releases/download/v2.0.4/etcd-v2.0.4-linux-amd64.aci
sha512-1eba37d9b344b33d272181e176da111e
```
After:
```
rkt: searching for app image coreos.com/etcd:v2.0.4
rkt: found image from local store, skip fetching from https://github.com/coreos/etcd/releases/download/v2.0.4/etcd-v2.0.4-linux-amd64.aci:wq
```

rkt: better logging around fetch

---

rkt/help.go
rkt/image.go
rkt/image_cat_manifest.go
rkt/rkt.go

Also add some facilities to print usage for sub-commands.
Not sure about the UX on this.
Previous proposal: #649

rkt/image: Add cat-manifest to print the image manifest to stdout.

---

Documentation/devel/pod-lifecycle.md

I am pretty sure this is a typo.

Fix small typo

---

Documentation/getting-started-guide.md

A few things noticed while verifying #895

docs: fix a few things in getting started guide

---

rkt/images.go

If discovery fails for any reason (no domain, not meta tags but also
network errors) fallback to local store app fetch.
The fallback isn't done if discovery returns valid endpoints but the
the image fetching from the returned endpoints fails for any reason
(network errors, wrong signature, etc...).

rkt: fallback to local store fetch if discovery fails.

---

stage1/rootfs/usr_from_src/patches/master/0001-nspawn-add-pid-file.patch

Last systemd master breaks our build.

stage1: rebase add-pid patch to latest systemd master

---

rkt/enter.go
rkt/fetch.go
rkt/gc.go
rkt/images.go
rkt/install.go
rkt/rmimage.go
rkt/trust.go

Also need https://github.com/appc/docker2aci/pull/60 to get a clean stdout. (but what if we include other packages not controllable by us...)

rkt/*: Replace stdout with stderr for human consumable messages.

---

Documentation/networking.md

Describe macvlan in more detail since ipvlan is derived from macvlan,
and can be nicely explained by pointing out the differences between
the two.
Additionally the ipvlan example shows a more complex way to configure
the host-local ipam plugin with IPv6.
Fixes #922.

documentation: add ipvlan and rewrite macvlan

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/spec/aci/file_test.go
Godeps/_workspace/src/github.com/appc/spec/pkg/acirenderer/acirenderer.go
Godeps/_workspace/src/github.com/appc/spec/pkg/acirenderer/acirenderer_test.go
Godeps/_workspace/src/github.com/appc/spec/pkg/device/device_posix.go
Godeps/_workspace/src/github.com/appc/spec/pkg/tarheader/pop_linux.go
Godeps/_workspace/src/github.com/appc/spec/pkg/tarheader/pop_posix.go
Godeps/_workspace/src/github.com/appc/spec/pkg/tarheader/pop_posix_test.go
Godeps/_workspace/src/github.com/appc/spec/schema/image_test.go
Godeps/_workspace/src/github.com/appc/spec/schema/types/isolator_linux_specific.go
Godeps/_workspace/src/github.com/appc/spec/schema/types/isolator_test.go
Godeps/_workspace/src/github.com/appc/spec/schema/types/labels.go
Godeps/_workspace/src/github.com/appc/spec/schema/types/labels_test.go
Godeps/_workspace/src/github.com/appc/spec/schema/types/mountpoint_test.go
Godeps/_workspace/src/github.com/appc/spec/schema/types/port.go
Godeps/_workspace/src/github.com/appc/spec/schema/types/port_test.go
Godeps/_workspace/src/github.com/appc/spec/schema/version.go

Godeps: bump appc/spec to v0.5.2

---

rkt/rmimage.go
tests/rkt_image_rm_test.go

This is based on #936 so only the last patch is the interesting one.
By now only the treestore isn't removed if an image is referenced by
some pod.
This brings the need of a store gc to remove the rendered images in
the treestore when they aren't referenced anymore. This is difficult to
coordinate and is an extra work that can be avoided simply not removing
also the image from the store (store.RemoveACI) if the image is
referenced. IMHO it's also more consistent as the image doesn't
disappear from the `rkt images` output.

rkt/rmimage: Apply reference check to the whole image.

---

rkt/image.go
rkt/image_cat_manifest.go

I am adding tests for the command.

rkt/image-cat-manifest: Rendering only images in the store.

---

Documentation/hacking.md

Fixes #918 
--- 
I am not sure if it is the correct place to add that documentation.
Do you want to add anything else? Other source of information:
* [systemd requirements](https://github.com/systemd/systemd/blob/master/README#L38)
* [Docker requirements](https://docs.docker.com/installation/binaries/)

documentation: kernel requirements

---

Documentation/getting-started-ubuntu-trusty.md
README.md
ROADMAP.md
pkg/aci/aci.go
rkt/fetch_test.go
stage1/rootfs/aggregate/aci-manifest
store/store_test.go
store/tree_test.go
version/version.go

release v0.5.6

---

networking/net_plugin.go

When plugins exit with non-zero code, they now
print a JSON with the error info to stdout. This
will parse this output and report that error.
Partly fixes #953

networking: handle error json from plugin

---

build

stage1: bump systemd source version to v220

---

tests/rkt_pid_file_test.go

This test should catch any regression in the fix https://github.com/coreos/rkt/pull/826
/cc @vcaputo @yifan-gu

Functional test: new test to check the pid file race

---

tests/rkt_pid_file_test.go

This test should catch more regression in the fix
https://github.com/coreos/rkt/pull/826

Functional test: TestPidFileAbortedStart (pid file race)

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/docker2aci/lib/common/common.go

Godeps: bump docker2aci

---

stage1/init/init.go

Instead of bind-mounting the whole controller subcgroup directory RW we
only bind-mount the files we need to set isolators. This reduces the
cgroup attack surface.
Addresses #983

stage1: bind-mount cgroup controller files RW

---

tests/README.md

Load balance the tests on the two VMs to have faster tests.

Functional tests, semaphore: reorder the tests

---

build

systemd has now moved to GitHub
http://lists.freedesktop.org/archives/systemd-devel/2015-June/032738.html
https://github.com/systemd/systemd/commit/eb0914fc85812570538c37287dd3cfa377289418#diff-c47c7c7383225ab55ff591cb59c41e6bR11

build: update default systemd source location

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/ThomasRooney/gexpect/README.md
Godeps/_workspace/src/github.com/ThomasRooney/gexpect/examples/ftp.go
Godeps/_workspace/src/github.com/ThomasRooney/gexpect/examples/ping.go
Godeps/_workspace/src/github.com/ThomasRooney/gexpect/gexpect.go
Godeps/_workspace/src/github.com/ThomasRooney/gexpect/gexpect_test.go
tests/rkt_auth_test.go
tests/rkt_caps_test.go
tests/rkt_cat_manifest_test.go
tests/rkt_env_test.go
tests/rkt_exit_test.go
tests/rkt_image_rm_test.go
tests/rkt_interactive_test.go
tests/rkt_pid_file_test.go
tests/rkt_tests.go
tests/rkt_volume_test.go

functional tests: capture output and print it on error

---

stage1/init/init.go

When using `--private-net`, init.go uses `exec.Cmd` to start nspawn, so setting ppid to `os.Getpid()` is incorrect.
This grabs the correct pid out of `cmd.Process.Pid` when using `--private-net`

stage1:init fix wrong ppid when using --private-net

---

stage1/rootfs/Makefile
stage1/rootfs/shim/Makefile
stage1/rootfs/shim/install
stage1/rootfs/usr_from_coreos/install

stage1: only include shim.so in the coreos flavor

---

stage1/init/cgroup.go
stage1/init/init.go

Previously we were assuming that machined registration was enabled when
we mounted the cgroups RW to allow per-app isolators.
We now get the right cgroup path if machined registration is disabled.

stage1: get correct cgroup path when machined registration is disabled

---

stage1/init/cgroup.go
tests/image/manifest
tests/inspect/inspect.go
tests/rkt_app_isolator_test.go

This test checks that the memory isolator is applied by ~~allocating
more memory than what's set on the isolator and checking the usage is
within the isolator's limit.~~ reading the value of the process memory.limit_in_bytes cgroup knob

functional tests: add memory isolator test

---

stage1/init/pod.go
stage1/init/pod_test.go

stage1:init Fix forwardedPorts nil pointer dereference

---

stage1/rootfs/usr_from_coreos/install
stage1/rootfs/usr_from_host/Makefile

I thought I could simplify it, but it did not always work when switching flavors.
Fix #997

stage1: flavor=usr-from-host: restore install target in Makefile

---

stage0/run.go

Allow nil app in image.manifest when run with pod manifest.

---

tests/inspect/inspect.go
tests/rkt_cat_manifest_test.go
tests/rkt_run_pod_manifest_test.go

Found a bug during tests: https://github.com/coreos/rkt/pull/978

tests: Add basic functional tests for rkt run/prepare --pod-manifest.

---

stage1/init/init.go

systemd v221 will be released soon:
http://lists.freedesktop.org/archives/systemd-devel/2015-June/033008.html
Make sure stage1 can use systemd v221

stage1: flavor=usr-from-host: supports systemd v221

---

CHANGELOG.md
Documentation/getting-started-ubuntu-trusty.md
README.md
ROADMAP.md
version/version.go

release v0.6.1

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/spf13/cobra/README.md
Godeps/_workspace/src/github.com/spf13/cobra/bash_completions.go
Godeps/_workspace/src/github.com/spf13/cobra/bash_completions.md
Godeps/_workspace/src/github.com/spf13/cobra/bash_completions_test.go
Godeps/_workspace/src/github.com/spf13/cobra/cobra_test.go
Godeps/_workspace/src/github.com/spf13/cobra/command.go
Godeps/_workspace/src/github.com/spf13/pflag/README.md
Godeps/_workspace/src/github.com/spf13/pflag/bool.go
Godeps/_workspace/src/github.com/spf13/pflag/bool_test.go
Godeps/_workspace/src/github.com/spf13/pflag/duration.go
Godeps/_workspace/src/github.com/spf13/pflag/flag.go
Godeps/_workspace/src/github.com/spf13/pflag/flag_test.go
Godeps/_workspace/src/github.com/spf13/pflag/float32.go
Godeps/_workspace/src/github.com/spf13/pflag/float64.go
Godeps/_workspace/src/github.com/spf13/pflag/int.go
Godeps/_workspace/src/github.com/spf13/pflag/int32.go
Godeps/_workspace/src/github.com/spf13/pflag/int64.go
Godeps/_workspace/src/github.com/spf13/pflag/int8.go
Godeps/_workspace/src/github.com/spf13/pflag/ip.go
Godeps/_workspace/src/github.com/spf13/pflag/ipmask.go
Godeps/_workspace/src/github.com/spf13/pflag/string.go
Godeps/_workspace/src/github.com/spf13/pflag/uint.go
Godeps/_workspace/src/github.com/spf13/pflag/uint16.go
Godeps/_workspace/src/github.com/spf13/pflag/uint32.go
Godeps/_workspace/src/github.com/spf13/pflag/uint64.go
Godeps/_workspace/src/github.com/spf13/pflag/uint8.go

Godep: bump spf13/cobra and spf13/pflag.

---

Documentation/selinux.md
build
pkg/fileutil/xattrs_linux.go
pkg/fileutil/xattrs_unsupported.go
pkg/label/label.go
pkg/label/label_selinux.go
pkg/label/label_selinux_test.go
pkg/selinux/selinux.go
pkg/selinux/selinux_test.go
rkt/run.go
stage0/run.go
test

Add support for using svirt to confine individual container instances in
separate selinux contexts.

Add selinux support

---

stage1/init/init.go

stage1: silence nspawn warning messages

---

README.md

README: change IRC to #rkt-dev

---

tests/rkt_run_pod_manifest_test.go

functests: use expectWithOutput

---

stage0/registration.go

stage0: fix wrong variable assignment

---

tests/rkt_tests.go

Now that the overlay fs is not mounted in a separate mount namespace
mounts will stay in host's mount namespace and to unmount them we need
to run the GC. Tests were failing because we tried to remove the
temp directory with a mounted filesystem inside.
This commit runs the GC before removing the temp directory.

functional tests: Run GC on cleanup and reset

---

Documentation/devel/release.md

There were some remnants of the old build system.

Documentation: update release documentation

---

tools/libdepsgen.pm

Some leftover from debugging session I supppose.

build: Fix deps generation

---

Documentation/getting-started-guide.md
Documentation/metadata-service.md
Documentation/networking.md
stage0/registration.go

- Fix the error msg when rkt is unable to reach metadata service
- Update documentation and a guide
Fixes #1111

Fix docs related to --mds-register=true being default

---

Documentation/app-container.md
Documentation/commands.md
Documentation/devel/architecture.md
Documentation/getting-started-guide.md
Documentation/getting-started-ubuntu-trusty.md
Documentation/hacking.md
Documentation/networking.md
Documentation/running-docker-images.md
Documentation/signing-and-verification-guide.md

* Fix consistency issues
* Add some missing commands

Documentation: improve and extend docs

---

stage1/usr_from_coreos/usr_from_coreos.mk

stage1: bump coreos flavor to systemd v222

---

ROADMAP.md

We can discuss what are the priorities for the next release.

Roadmap: update and add links

---

tests/inspect/inspect.go
tests/rkt_app_isolator_test.go

Inside the container the cgroups tree should be mounted read-only except
some well-known files.
This test tries to write in /sys/fs/cgroup and a couple of controllers
and checks we get EROFS.
Fixes #981

functional tests: add TestCgroups

---

tests/inspect/inspect.go
tests/rkt_run_pod_manifest_test.go

Add tests for CPU/memory usage.
Add tests for multiple apps within a pod.
Add tests for capability.
I also intent to add some tests for port forwarding, but since it's not obvious to do it on single host(as we don't have user proxy), I think we can skip that for now.
Should address #806

tests: add more test cases to TestPodManifest.

---

Documentation/using-rkt-with-systemd.md

Mention machinectl, systemd-cgls.
This improves #764 a bit. But I'd like to hear suggestions what else can be added here.

documentation: Update docs about integration with systemd a bit

---

Documentation/commands.md
Documentation/devel/architecture.md
Documentation/devel/stage1-implementors-guide.md
Documentation/using-rkt-with-systemd.md
common/cgroup/cgroup.go
common/common.go
rkt/enter.go
rkt/gc.go
rkt/list.go
rkt/run.go
rkt/run_prepared.go
stage0/enter.go
stage0/registration.go
stage0/run.go
stage1/enter/enter.c
stage1/init/init.go
stage1/init/path.go
stage1/init/pod.go
tests/rkt_exit_test.go
tests/test-auth-server/README.md

Follows #1068 's discussion.
In this PR, I use appName to name those on-disk files/dirs. 
/cc @iaguis @jonboulle @vcaputo @alban

*.*: replace image id with app name for identifying apps within pod.

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/hydrogen18/stoppableListener/LICENSE
Godeps/_workspace/src/github.com/hydrogen18/stoppableListener/README.md
Godeps/_workspace/src/github.com/hydrogen18/stoppableListener/example/example.go
Godeps/_workspace/src/github.com/hydrogen18/stoppableListener/listener.go
tests/inspect/inspect.go
tests/rkt_privatenet_test.go
tests/test_netutils/httputils.go
tests/test_netutils/iputils.go

Tests:
- host networking (without `--private-net`)
- default private-net (`--private-net=default`)
- restricted default private-net (`--private-net=default-restricted`)
Working on #1010.

functional tests for private-net for host+default

---

Documentation/using-rkt-with-systemd.md

Documentation: add socket-activation example

---

tests/rkt_privatenet_test.go

Search all interfaces for IPv4 addresses that could for connections by the
client. Skip the test if no address is found.

testing: fix TestPrivateNetDefaultConnectivity

---

stage1/prepare-app/prepare-app.c

We want to set some flags and options when mounting points, like the
MS_REC for procfs and sysfs.
Later we may convert all the other mount points to the same mount_table.
Signed-off-by: Djalal Harouni <djalal@endocode.com>

stage1:prepare-app: add support for mount points options

---

tests/rkt_run_pod_manifest_test.go

functional test: TestPodManifest: skip a test if cgroups unsupported

---

Documentation/running-lkvm-stage1.md

Documentation: add initial LKVM stage1 docs

---

rkt/images.go

fetch: add user-agent

---

store/store.go

Store.NewStore is created providing a "base" dir.
The "base" directory used by all rkt commands for creating the store is the
rkt data directory (by default `--dir="/var/lib/rkt"`). Then the store will
create its own directory inside it (`/var/lib/rkt/cas`).
Store, for some reasons, was saving this "base" directory in its struct. This
added some confusion since all functions needing a path under the store dir
needed to add a `/cas` path to `Store.base` every time.
This also caused store.TmpDir() to create a tmp directory outside the cas
directory (under `/var/lib/rkt/tmp` instead of `/var/lib/rkt/cas/tmp`)
With this patch, the store struct will now contain the store directory
(`/var/lib/rkt/cas/` by default) instead of the base directory so all functions
can refer to it without the need …

store: remove confusion on store.base dir

---

networking/portfwd.go

- Insert port forwarding rules in the beginning of the tables
- Only add if the rule is unique. This must always be the case cause old IPs
can only be reused after GC has run (correctly)
Fixes #1163.

port forwards: insert rules in the beginning

---

Documentation/networking.md

docs: improve private-net section

---

stage0/run.go
tests/rkt_exit_test.go

regression introduced by https://github.com/coreos/rkt/pull/1264

status: fix overlayfs upper directory

---

tests/rkt_privatenet_test.go
tests/testutils/httputils.go
tests/testutils/iputils.go

functional tests networking: various NAT tests and bridged grouping

---

Documentation/devel/on-disk-format.md

Fix part of https://github.com/coreos/rkt/issues/1132

doc: stable on-disk format

---

Documentation/devel/stage1-implementors-guide.md
stage0/enter.go
stage1/enter/enter.c

stage1: enter: make parameters more readable

---

Documentation/devel/user-namespaces.md

This is a first draft, it should be explained better.

doc: user namespaces

---

Documentation/devel/release.md

Update release.md to bundle kvm-based stage1.

---

rkt/fetch_keys.go

rkt trust: accept --trust-keys-from-https

---

rkt/fetch_keys.go
rkt/trust.go

trust: check for --insecure-skip-verify

---

stage1/init/kvm/mount_test.go

kvm/mounting/testing: fix test error message

---

stage0/run.go

stage0: improve the readability of the logging message.

---

rkt/rm.go

When a pod is successfully removed its UUID is echoed to stdout.
If a UUID cannot be resolved no pod will be removed.
Pods that cannot be removed will not interfere with the removal of
others.
Resolves https://github.com/coreos/rkt/issues/1297

Allow rkt rm to take multiple containers

---

stage1/init/init.go

stage1: error out when using --private-users with lkvm

---

common/cgroup/cgroup.go

cgroup: workaround: configure cpuset on system.slice

---

rkt/fetch_test.go
rkt/images.go

by default golang's http.Client doesn't copy the original request headers on a
http redirect.
This currently breaks ETag handling and authentication (additionally the
default user agent is sent on redirect instead of the rkt one)
This patch defines a checkRedirect function to populate the headers also on
redirect.
The ETag header is sent for every request.
The authentication headers are sent only if there's a related configuration for
the current request's host. For example if authentication is configured for
example.com but not for anotherdomain.com and a request to example.com
redirects to anotherdomain.com, no authentication headers will be provided to
it.

rkt: send headers on redirect

---

tools/depsgen/globcmd.go
tools/depsgen/gocmd.go
tools/depsgen/kvcmd.go
tools/depsgen/main.go
tools/depsgen/mkfile.go
tools/depsgen/util.go

First commits are doing some small cleanups and fixes.
The last but one adds a glob-mode (whether to take only normal files, hidden files or all of them).
Last commit teaches depsgen to use filelists.

Cleanups in depsgen, glob mode and filelist support.

---

Documentation/using-rkt-with-systemd.md

Documentation: systemd: add systemd-run example

---

.gitignore

- Extend build-rkt directory so it catches build-dir
- Add .vagrant
fixes #1332

*: update .gitignore

---

Documentation/devel/architecture.md

The description for stages 1 and 2 in the architecture document was
rather confusing. Part of the confusion was in the wording, part in the
description itself.
I still have questions as to what exactly the execution group is, though.

Docs: Clarify description of stages 1 and 2

---

Documentation/networking.md
Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/cni/pkg/plugin/args.go
Godeps/_workspace/src/github.com/appc/cni/pkg/plugin/ipam.go
Godeps/_workspace/src/github.com/appc/cni/plugins/ipam/dhcp/lease.go
Godeps/_workspace/src/github.com/appc/cni/plugins/ipam/host-local/allocator.go
Godeps/_workspace/src/github.com/appc/cni/plugins/ipam/host-local/config.go
Godeps/_workspace/src/github.com/appc/cni/plugins/ipam/host-local/main.go
Godeps/_workspace/src/github.com/appc/cni/plugins/main/ptp/ptp.go
common/common.go
networking/podenv.go
tests/rkt_privatenet_test.go

Alternative to #1369.
Fixes #944.

Privatenet override args2

---

common/common.go
stage0/run.go
stage1/init/init.go
stage1/usr_from_coreos/manifest.d/systemd
stage1/usr_from_coreos/usr_from_coreos.mk

Make SELinux support work more reasonably and update the build so we have the appropriate dependencies in stage1.

SELinux updates

---

rkt/config/config_test.go

tests: Remove temporary config files

---

rkt/prepare.go

The image parameter for rkt prepare had the wrong case.

rkt: The parameter should be IMAGE, not Image

---

stage0/run.go
tests/rkt_exec_test.go

When an image doesn't have an App section and we override exec with the
--exec flag we should create a minimal App section instead of failing.
This would fail with a missing app section error:
rkt run image-without-app-section.aci
But this would succeed and exec the specified command if it exists in
the image:
rkt run image-without-app-section.aci --exec /bin/sh
Fixes #1421

stage0: create app section if we override exec

---

makelib/misc.mk
makelib/variables.mk.in
stage1/find-so-deps.mk
stage1/usr_from_coreos/usr_from_coreos.mk
stage1/usr_from_kvm/kernel.mk
stage1/usr_from_kvm/lkvm.mk
stage1/usr_from_src/usr_from_src.mk

This batch of commits add filelist generation. Filelist will be later used to generate dep.mk and clean.mk files.

build: Generate filelists

---

stage1/init/init.go

stage1: host flavor: copy systemd-journald units

---

tests/install-deps.sh

semaphore: make sure go and gofmt are installed

---

tests/rkt_auth_test.go

/cc @krnowak 
Before automatically trusting a key that comes from https with TLS verified (https://github.com/coreos/rkt/issues/481#issuecomment-73382560), I would like to add more functional tests on the way it currently work.
This is a work in progress.
At the moment, the taas server only gives a new ACI at each request. I would like if it also gave:
- the gpg public keys
- the signature of the aci
But for that, it would need to persist the ACIs. And possibly use the discovery protocol.

functional tests: check signatures

---

Documentation/subcommands/fetch.md

Just fixing the link to configuration docs.

docs: fix link to configuration doc

---

Documentation/selinux.md

docs: update selinux.md

---

Godeps/Godeps.json

Not sure how this got missed earlier.

godeps: remove old GoogleCloudPlatform/kubernetes reference

---

api/v1_alpha/api.pb.go
api/v1_alpha/api.proto

api: change version from v1 to v1_alpha

---

common/common.go
stage1/init/pod.go
tests/rkt_ace_validator_test.go

Add support for empty volume types

---

Documentation/hacking.md

Documentation: add autoconf to build time requirements

---

rkt/stage1hash.go

rkt: fix `--stage1-image` handling

---

rkt/enter.go
rkt/gc.go
rkt/image_rm.go
rkt/prepare.go

rkt: fix missing error prints

---

Documentation/devel/pod-lifecycle.md
Documentation/networking.md
Documentation/subcommands/image.md
Documentation/subcommands/run.md

I found some typos. Please let me know if you have any feedback.
Thanks for the great project and documentation!

Documentation: fix typos

---

Documentation/image-fetching-behavior.md
Documentation/subcommands/fetch.md
Documentation/subcommands/run.md

Documentation: add image fetching behavior docs

---

stage1/init/pod.go

This removes the setgid bit on the shared volumes directory.

stage1: explicitly set permissions on shared volumes

---

CHANGELOG.md
Documentation/getting-started-ubuntu-vivid.md
Documentation/running-lkvm-stage1.md
Documentation/subcommands/prepare.md
README.md
configure.ac
scripts/bump-release

gotta work on the changelog a bit, right now it's largely a braindump

rkt v0.9.0

---

Documentation/networking.md

Actually not 100% sure if it should be "pod networks" or "pods' networks".

Docs: couple small fixes to networking.md

---

Documentation/image-fetching-behavior.md

After Rob Szumski's feedback on #1560.

Documentation: improve image fetching docs

---

Documentation/getting-started-ubuntu-vivid.md
Documentation/running-lkvm-stage1.md
Documentation/subcommands/prepare.md
rkt/prepare.go
rkt/run.go
rkt/run_prepared.go
stage0/run.go
tests/rkt_image_list_test.go

stage0: print log messages only when debug is enabled

---

CONTRIBUTING.md

Updating from coreos/template-project

CONTRIBUTING.md: add reference to golang style

---

stage1/usr_from_kvm/files.mk
stage1/usr_from_kvm/usr_from_kvm.mk

We have to remove both /var and /var/run directories.

build: Fix make clean for kvm flavor

---

tests/rkt_auth_test.go
tests/rkt_net_test.go
tests/rkt_tests.go
tests/testutils/goroutineassistant.go
tests/testutils/httputils.go
tests/testutils/logger/logger.go

 testutils: fix GoroutineAssistant and httputils

---

Documentation/getting-started-guide.md

Changes: I've added information to the tutorial that would help me avoid the problems I had following it.
Context: I spent several hours getting the tutorial to work, solving one problem after another, and these hints would have helped me a lot.
I'm not sure about some of the wording, but I think this information should be in the tutorial.

Documentation: add more info to Getting Started Guide

---

stage0/enter.go
stage0/gc.go
stage0/run.go

Also normalize all stage1 entrypoint error messages.

stage0: fix run entrypoint error message: s/init/run/

---

common/common.go
stage0/run.go
stage1/init/init.go

Make consistent with the RKT_LOCK_FD environment variable symbolic name.

common: s/SELinuxContext/EnvSELinuxContext/

---

tests/README.md

The Semaphore configuration UI changed. Update the documentation
accordingly.
-----
/cc @steveeJ

tests: update semaphore documentation

---

Documentation/subcommands/run.md
rkt/cli_apps.go

Removed misleading warning.
Added documentation.

rkt: fixes for PodManifest.Mounts

---

Documentation/getting-started-guide.md

docs: change name in getting started guide

---

CHANGELOG.md
Documentation/getting-started-ubuntu.md
Documentation/running-lkvm-stage1.md
Documentation/subcommands/prepare.md
README.md
configure.ac

rkt v0.10.0

---

stage1/usr_from_coreos/cache.sh

Variables in functions should be marked as local. Also looks like the
form "local var=foo" should not be used, because of a strange order of
processing this line - first var is marked as global variable and a
value is assigned to it, then the variable is made local.
Also, make it run with "set -e", so it will bail out if downloading or
verification failed.

coreos: Small fixes in cache.sh

---

makelib/misc.mk
stage1/find-so-deps.mk
stage1/stage1.mk

This tries to cleanup the mess in stage1 into something less messy.

build: Cleanup of  stage1.mk 

---

tests/functional.mk
tests/tests.mk

This should be a part of a pull request that added nicer output to the
whole project, but I must have removed that commit by accident.

build: Print nicer output in tests

---

stage1/init/init.go

This augments the heuristics used to err on the side of non-unit-file,
but will still consider as run from a unit file when executed directly
via systemd.service Exec* directives.
With this change, interactive invocations of rkt on CoreOS cease passing
--keep-unit to nspawn.
Fixes https://github.com/coreos/rkt/issues/1664

stage1/init: only consider running from unit file when session leader

---

rkt/api_service.go

This PR makes that the image manifest only returned by InspectImage()
and pod manifest only returned by InspectPod().

rkt/api_service: do not return manifest in ListPods() and ListImages().

---

tests/rkt_ace_validator_test.go
tests/rkt_app_isolator_test.go
tests/rkt_auth_test.go
tests/rkt_caps_test.go
tests/rkt_cat_manifest_test.go
tests/rkt_env_test.go
tests/rkt_etc_hosts_test.go
tests/rkt_exec_test.go
tests/rkt_exit_test.go
tests/rkt_fetch_test.go
tests/rkt_image_export_test.go
tests/rkt_image_extract_test.go
tests/rkt_image_gc_test.go
tests/rkt_image_list_test.go
tests/rkt_image_render_test.go
tests/rkt_image_rm_test.go
tests/rkt_interactive_test.go
tests/rkt_net_test.go
tests/rkt_non_root_test.go
tests/rkt_os_arch_test.go
tests/rkt_pid_file_test.go
tests/rkt_run_pod_manifest_test.go
tests/rkt_service_file_test.go
tests/rkt_socket_activation_test.go
tests/rkt_tests.go
tests/rkt_trust_test.go
tests/rkt_userns_test.go
tests/rkt_volume_test.go
tests/testutils/ctx.go
tests/testutils/utils.go

tests: move rktRunCtx to testutils.

---

rkt/gc.go
store/store.go
store/store_test.go

Fixes https://github.com/coreos/rkt/issues/1713

Close Store opened during `rkt gc`

---

tests/run-build.sh

tests: only run functional tests when source has changed

---

stage1/init/pod.go
stage1/init/pod_test.go
tests/rkt_run_pod_manifest_test.go

tests: more exec escaping unit tests and their fixes

---

tests/rkt_net_test.go

Closes #1662.
Helping with #1651.

functional net tests: likely prevent local collisions

---

tests/README.md

This also fixes some style issues.
Fixes #1422

functional tests: Document make functional-check target

---

tests/rkt_socket_activation_test.go

Fixes https://github.com/coreos/rkt/issues/1739

test: fix TestSocketActivation on systemd-v219

---

rkt/gc.go

It will help to understand https://github.com/coreos/rkt/issues/1762

gc: better panic message

---

Documentation/packaging.md

Fixes https://github.com/coreos/rkt/issues/1743
-----
@krnowak is it correct?

packaging: add glibc-static in the build-time deps

---

CHANGELOG.md
rkt/config/config.go
rkt/images.go
rkt/pubkey/pubkey.go

rkt: use authentication for discovery and trust

---

CHANGELOG.md
stage1/init/pod.go
tests/rkt_run_pod_manifest_test.go

stage1: set empty volumes permissions

---

networking/kvm.go

Based on #1530 
Provides flannel networking support in kvm flavor.

kvm: flannel networking

---

rkt/image_rm.go

rkt: rKt -> rkt

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/goaci/proj2aci/asset.go
stage1/init/init.go
stage1/usr_from_host/usr_from_host.mk

Fixes https://github.com/coreos/rkt/issues/1809
-----
This makes the host flavor work on Debian for me. Tested with `systemd-228-2`.
/cc @onlyjob

host flavor: fix copying for Debian

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/cni/pkg/invoke/args.go
Godeps/_workspace/src/github.com/appc/cni/pkg/invoke/exec.go
Godeps/_workspace/src/github.com/appc/cni/pkg/invoke/find.go
Godeps/_workspace/src/github.com/appc/cni/pkg/ip/cidr.go
Godeps/_workspace/src/github.com/appc/cni/pkg/ip/ipforward.go
Godeps/_workspace/src/github.com/appc/cni/pkg/ip/ipmasq.go
Godeps/_workspace/src/github.com/appc/cni/pkg/ip/link.go
Godeps/_workspace/src/github.com/appc/cni/pkg/ip/route.go
Godeps/_workspace/src/github.com/appc/cni/pkg/ipam/ipam.go
Godeps/_workspace/src/github.com/appc/cni/pkg/ns/ns.go
Godeps/_workspace/src/github.com/appc/cni/pkg/skel/skel.go
Godeps/_workspace/src/github.com/appc/cni/pkg/types/args.go
Godeps/_workspace/src/github.com/appc/cni/pkg/types/types.go
Godeps/_workspace/src/github.com/appc/cni/plugins/ipam/dhcp/daemon.go
Godeps/_workspace/src/github.com/appc/cni/plugins/ipam/dhcp/lease.go
Godeps/_workspace/src/github.com/appc/cni/plugins/ipam/dhcp/main.go
Godeps/_workspace/src/github.com/appc/cni/plugins/ipam/dhcp/options.go
Godeps/_workspace/src/github.com/appc/cni/plugins/ipam/host-local/allocator.go
Godeps/_workspace/src/github.com/appc/cni/plugins/ipam/host-local/backend/disk/backend.go
Godeps/_workspace/src/github.com/appc/cni/plugins/ipam/host-local/backend/disk/lock.go
Godeps/_workspace/src/github.com/appc/cni/plugins/ipam/host-local/backend/store.go
Godeps/_workspace/src/github.com/appc/cni/plugins/ipam/host-local/config.go
Godeps/_workspace/src/github.com/appc/cni/plugins/ipam/host-local/main.go
Godeps/_workspace/src/github.com/appc/cni/plugins/main/bridge/bridge.go
Godeps/_workspace/src/github.com/appc/cni/plugins/main/ipvlan/ipvlan.go
Godeps/_workspace/src/github.com/appc/cni/plugins/main/macvlan/macvlan.go
Godeps/_workspace/src/github.com/appc/cni/plugins/main/ptp/ptp.go
Godeps/_workspace/src/github.com/appc/cni/plugins/meta/flannel/flannel.go

Fixes https://github.com/coreos/rkt/issues/1707
-----
/cc @steveeJ

godeps: bump CNI

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/coreos/go-tspi/attestation/attestation.go
Godeps/_workspace/src/github.com/coreos/go-tspi/tpmclient/tpmclient.go
Godeps/_workspace/src/github.com/coreos/go-tspi/tspi/context.go
Godeps/_workspace/src/github.com/coreos/go-tspi/tspi/hash.go
Godeps/_workspace/src/github.com/coreos/go-tspi/tspi/key.go
Godeps/_workspace/src/github.com/coreos/go-tspi/tspi/nv.go
Godeps/_workspace/src/github.com/coreos/go-tspi/tspi/pcrs.go
Godeps/_workspace/src/github.com/coreos/go-tspi/tspi/policy.go
Godeps/_workspace/src/github.com/coreos/go-tspi/tspi/tpm.go
Godeps/_workspace/src/github.com/coreos/go-tspi/tspi/tspi.go
configure.ac
makelib/variables.mk.in
pkg/tpm/tpm.go
pkg/tpm/tpm_stub.go
rkt/image_render.go
rkt/prepare.go
rkt/run.go
rkt/run_prepared.go
stage0/run.go
store/store.go
store/store_test.go
store/tree.go
store/tree_test.go

Hash container data into the TPM if tpmd is running

stage0: add container hash data into TPM 

---

CHANGELOG.md
Documentation/getting-started-ubuntu.md
Documentation/running-lkvm-stage1.md
Documentation/subcommands/prepare.md
README.md
ROADMAP.md
configure.ac

The primary motivation for this release is to add support for fetching images on the Docker Registry 2.0.

release v0.13.0

---

stage1/init/init.go

Fixes https://github.com/coreos/rkt/issues/1840

stage1: fix cgroup slices when machined is not used

---

Documentation/configuration.md

docs: Add paths to config examples

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/spec/ace/image_manifest_main.json
Godeps/_workspace/src/github.com/appc/spec/ace/image_manifest_sidekick.json
Godeps/_workspace/src/github.com/appc/spec/actool/discover.go
Godeps/_workspace/src/github.com/appc/spec/discovery/discovery.go
Godeps/_workspace/src/github.com/appc/spec/discovery/http.go
Godeps/_workspace/src/github.com/appc/spec/schema/types/isolator_resources.go
Godeps/_workspace/src/github.com/appc/spec/schema/version.go
rkt/image/namefetcher.go
rkt/pubkey/pubkey.go

Closes https://github.com/coreos/rkt/pull/1859
It will help for
- https://github.com/coreos/rkt/pull/1851 https://github.com/coreos/rkt/issues/1735 (aka `--memory --cpu`)
- https://github.com/coreos/rkt/pull/1822 https://github.com/coreos/rkt/issues/1752 (aka dependencies, disco with insecure options)

bump appc to v0.7.4 and fix rkt code

---

Documentation/devel/cgroups.md

Fixes https://github.com/coreos/rkt/issues/1868

Documentation: cgroup doc for developers

---

common/apps/apps.go
rkt/cli_apps.go
rkt/run.go
stage0/run.go
tests/rkt_app_isolator_test.go

Fixes https://github.com/coreos/rkt/issues/1735
-----
Depends on https://github.com/appc/spec/issues/552 / https://github.com/appc/spec/pull/553

rkt: add --memory and --cpu to override isolators

---

CHANGELOG.md

CHANGELOG.md: better phrasing with focus on the impact

---

CHANGELOG.md
Documentation/build-configure.md
Documentation/running-fly-stage1.md
Documentation/subcommands/fly.md
Makefile
configure.ac
stage1/common/run.go
stage1/common/types/pod.go
stage1/init/common/kvm_mount.go
stage1/init/common/kvm_mount_test.go
stage1/init/common/path.go
stage1/init/common/pod.go
stage1/init/common/pod_test.go
stage1/init/init.go
stage1/init/kvm.go
stage1/stage1.mk
stage1_fly/aci/aci-manifest.in
stage1_fly/aci/aci.mk
stage1_fly/enter/enter.mk
stage1_fly/enter/main.go
stage1_fly/gc/gc.mk
stage1_fly/gc/main.go
stage1_fly/makelib/aci_binary.mk
stage1_fly/run/main.go
stage1_fly/run/run.mk
stage1_fly/stage1_fly.mk

Alternative proposal for #1825

initial implementation of rkt fly as stage1

---

Documentation/commands.md
Documentation/subcommands/api-service.md
api/v1alpha/README.md
api/v1alpha/client_example.go
common/common.go
rkt/api_service.go

Also add a small example program shows how to using the api service.
And fixed a flag bug.

Document the api service

---

store/db.go
store/db_test.go

store: Make db thread-safe.

---

api/v1alpha/api.pb.go
api/v1alpha/api.proto
rkt/api_service.go
tests/image/manifest
tests/rkt_api_service_test.go

Partially fixes #1872, still need to address `ImageFilter` comment, unless we want to break that out into another issue.

Add annotations to api response

---

Documentation/build-configure.md

An infinitessimal nit, but a while-I'm-at-it during 0.15.0 sync.

Docs/build-configure: Title Case for Titles

---

Documentation/devel/release.md
dist/bash_completion/rkt.bash
rkt/rkt.go

Based on an initial implementation from Iago.
Fixes https://github.com/coreos/rkt/issues/1419

bash completion

---

Documentation/devel/stage1-implementors-guide.md

cc @steveeJ @jonboulle @alban @iaguis

stage1-implementors-guide.md: Add filesystem layout assumptions.

---

Vagrantfile
scripts/install-common.sh

Fix vagrant rkt build

---

rkt/api_service.go
rkt/fetch.go
rkt/flag/rktflag_test.go
rkt/flag/secflags.go
rkt/image/common.go
rkt/image/fetcher.go
rkt/image/httpfetcher.go
rkt/image/namefetcher.go
rkt/image_gc.go
rkt/prepare.go
rkt/pubkey/pubkey.go
rkt/rkt.go
rkt/run.go
rkt/stage1hash.go
rkt/trust.go
stage0/gc.go
stage1/init/init.go
tests/inspect/inspect.go
tests/rkt_cat_manifest_test.go
tests/rkt_image_export_test.go
tests/rkt_image_list_test.go
tests/rkt_image_rm_test.go
tests/rkt_list_test.go
tests/rkt_net_test.go
tests/rkt_non_root_test.go
tests/testutils/httputils.go

See https://github.com/golang/go/wiki/CodeReviewComments#initialisms
Following up on discussion from here: https://github.com/coreos/rkt/pull/1945#discussion_r49264529

Make initialisms all caps

---

rkt/api_service.go
tests/rkt_api_service_test.go

This commit changes the way how List/Inspect pod fetches image manifest
for apps. Previously, the manifest is read from store, which will be empty
if the image is removed. Now the manifest is read from the image manifest
inside the pod directory, so it won't be affected by image removal.
However, some information like importtime, image size are not available
for List/Inspect pod after this change.
Should fix https://github.com/coreos/rkt/pull/1924#issuecomment-169183858
cc @derekparker @jonboulle @krnowak

api_service: Use image manifest in the pod directory for List/Inspect pod

---

CHANGELOG.md

CHANGELOG.md: updates

---

Documentation/devel/stage1-implementors-guide.md

Documentation: document --private-users in stage1 implementors guide

---

store/main_test.go

Go 1.4 landed a new testing.M type [1][1] which allows for start-up and
shutdown hooks when running tests. The standard library now uses this
for checking for leaked goroutines in net/http [2][2].
This patch re-ports the updated code from the net/http test. For a
previous example, see https://github.com/coreos/etcd/pull/4026
[1]: https://golang.org/pkg/testing/#M
[2]: https://github.com/golang/go/blob/release-branch.go1.4/src/net/http/main_test.go#L18

store: update leaked goroutines check to TestMain

---

Documentation/subcommands/trust.md

Fixes https://github.com/coreos/rkt/issues/1984

doc: trust: fix example

---

Documentation/devel/cgroups.md
Documentation/using-rkt-with-systemd.md

Fixes https://github.com/coreos/rkt/issues/1883

documentation: systemd: use Delegate and Slice properties

---

networking/net_plugin.go

Add /etc/rkt/net.d to the search path for net plugins
Also see #1992 and #1950

Use the existing configurable local config dir

---

scripts/install-go.sh

scripts: bump go to 1.5.2

---

Documentation/commands.md
Documentation/subcommands/api-service.md
Documentation/subcommands/cat-manifest.md
Documentation/subcommands/enter.md
Documentation/subcommands/fetch.md
Documentation/subcommands/gc.md
Documentation/subcommands/image.md
Documentation/subcommands/install.md
Documentation/subcommands/list.md
Documentation/subcommands/metadata-service.md
Documentation/subcommands/prepare.md
Documentation/subcommands/rm.md
Documentation/subcommands/run-prepared.md
Documentation/subcommands/run.md
Documentation/subcommands/status.md
Documentation/subcommands/trust.md
Documentation/subcommands/version.md
rkt/api_service.go
rkt/prepare.go
rkt/run.go
rkt/run_prepared.go

Documentation: document subcommand flags

---

CHANGELOG.md

CHANGELOG: Add entry for error and output changes

---

.travis.yml
pkg/log/log.go

This adds a SetOutput to the log package and builds the with the default ./configure on travis.

Add SetOutput method to our pkg/log

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/docker2aci/lib/backend/repository/repository.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/backend/repository/repository1.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/backend/repository/repository2.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/common/common.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/docker2aci.go

Fixes https://github.com/coreos/rkt/issues/2036

godeps: update docker2aci

---

Documentation/subcommands/prepare.md
Documentation/subcommands/run.md
rkt/prepare.go
rkt/run.go
rkt/run_prepared.go

Also, make `--port` description consistent between `run` and `prepare`.

rkt, docs: explain --port syntax

---

Documentation/using-rkt-with-systemd.md

Remove the WIP label, delete discussion of machined stuff that
isn't yet supported by any stage1 (like machinectl login), clean
up prose, formatting, style issues and make reference links so
this doc can be prominently linked in 1.0 release things.

Documentation/using-rkt-with-systemd: Polish for 1.0

---

Documentation/subcommands/fetch.md
Documentation/subcommands/trust.md

docs: fix appc-discovery links in trust/fetch

---

rkt/enter.go
rkt/gc.go
rkt/install.go
rkt/prepare.go
rkt/rkt.go
rkt/rm.go
rkt/run.go
rkt/run_prepared.go
tests/rkt_root_commands_test.go
tests/rkt_tests.go

Possible alternative to #2074
/cc @alban @crawford

stage0: check root EUID for certain subcommands

---

CHANGELOG.md
Documentation/packaging.md
dist/init/systemd/tmpfiles.d/rkt.conf
rkt/install.go

dist: add rkt tmpfiles

---

CHANGELOG.md
rkt/api_service.go
rkt/enter.go
rkt/fetch.go
rkt/gc.go
rkt/image_export.go
rkt/image_extract.go
rkt/image_gc.go
rkt/image_list.go
rkt/image_render.go
rkt/image_rm.go
rkt/list.go
rkt/metadata_service.go
rkt/prepare.go
rkt/rkt.go
rkt/rm.go
rkt/run.go
rkt/run_prepared.go
rkt/status.go
rkt/trust.go
rkt/version.go

Most of these changes were inspired by the rkt subcommand documentation.
Closes https://github.com/coreos/rkt/issues/2080

rkt: add long command descriptions

---

README.md
ROADMAP.md

README, ROADMAP: Update to reflect rkt v1

---

Documentation/devel/tpm.md

For a little more context for those who've never heard of TPM.

docs/devel: add external TPM link

---

Documentation/trying-out-rkt.md

- Show users how to setup privilege separation.
- Call for help for distro packaging.
- De-emphasize the vagrant instructions.

Documentation: expand the trying out rkt guide

---

Documentation/devel/cgroups.md

Unfortunately I think we're just going to be chasing this one as the
unification plays out, but oh well.

docs: fix cgroup link

---

Documentation/networking.md

More text based on @steveeJ 's work.
It is a start for https://github.com/coreos/rkt/issues/1522

doc: network: more examples

---

CHANGELOG.md
Documentation/getting-started-ubuntu.md
Documentation/running-fly-stage1.md
Documentation/running-lkvm-stage1.md
Documentation/subcommands/prepare.md
Documentation/subcommands/version.md
Documentation/trying-out-rkt.md
configure.ac
scripts/acbuild-rkt-builder.sh
scripts/build-rir.sh

release v1.0.0

---

stage1_fly/run/main.go

stage1/fly: add workingDirectory support

---

Documentation/commands.md
Documentation/subcommands/api-service.md
Documentation/subcommands/cat-manifest.md
Documentation/subcommands/enter.md
Documentation/subcommands/fetch.md
Documentation/subcommands/gc.md
Documentation/subcommands/image.md
Documentation/subcommands/list.md
Documentation/subcommands/metadata-service.md
Documentation/subcommands/prepare.md
Documentation/subcommands/rm.md
Documentation/subcommands/run-prepared.md
Documentation/subcommands/run.md
Documentation/subcommands/status.md
Documentation/subcommands/trust.md

Fixes https://github.com/coreos-inc/coreos-pages/issues/511. I tested this locally as well:

docs: fix table formatting

---

Documentation/trying-out-rkt.md
Vagrantfile

Handle the memory setting for vagrant-libvirt plugin and document the process of runing that kind of VM.

Add vagrant-libvirt support

---

LICENSE
README.md
pkg/acl/LICENSE.MIT
pkg/acl/acl.go
store/LICENSE.BSD
store/main_test.go

LICENSE: add reference to Go license

---

Documentation/distributions.md

Addresses a part of @erickj's comment on https://github.com/coreos/rkt/issues/1727#issuecomment-180554752.
Todo: link this document from the other docs.
/cc @erickj @joshix

documentation: add distro-specific instructions

---

Documentation/trying-out-rkt.md

Update instructions to enable rkt group

---

CHANGELOG.md
Documentation/subcommands/image.md
Documentation/subcommands/list.md
Documentation/subcommands/prepare.md
Documentation/trying-out-rkt.md
rkt/run.go
scripts/acbuild-rkt-builder.sh
stage1/init/common/pod.go
stage1/init/kvm/network.go

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

*: fix typos

---

Documentation/running-fly-stage1.md

Incidentally update etcd version listed.

Doc/running-fly-stage1: Update path to stage1-fly.aci to /usr/share/rkt

---

stage1/init/common/pod.go

If we can't parse a string of the form v229, assume the version in the
"systemd-version" file is a branch name and indicate callers the version
couldn't be guessed.
In that case, assume it's new enough for "systemd exit" to work.

stage1: handle parsing errors in systemd version

---

Documentation/using-rkt-with-systemd.md

Since https://github.com/coreos/rkt/pull/1886, we started to advise users to use Slice=machine.slice in .service files. Update documentation to follow that advice.
- Use Slice=machine.slice in .service file
- systemd-run and systemd-cgls shows the processes in the machine.slice
- Also, use new version of etcd in examples
Fixes https://github.com/coreos/rkt/issues/2212
-----
/cc @joshix

doc: using-rkt-with-systemd: fix examples

---

CHANGELOG.md
Documentation/getting-started-ubuntu.md
Documentation/running-fly-stage1.md
Documentation/running-lkvm-stage1.md
Documentation/subcommands/prepare.md
Documentation/subcommands/version.md
Documentation/trying-out-rkt.md
ROADMAP.md
configure.ac
scripts/acbuild-rkt-builder.sh
scripts/build-rir.sh
tests/empty-image/manifest
tests/image/manifest
tests/rkt_exec_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go

release v1.1.0

---

Documentation/devel/release.md
scripts/bump-release

Documentation: update release instructions

---

rkt/pubkey/pubkey.go

It seems that we can handle multiple locations and keys from the code now. So update the comment accordingly.

pubkey: update comments

---

README.md

README: add note on security disclosures

---

stage1/gc/gc.go

In the nspawn flavors, we use the "--try-guest" option. This means a
symlink is created from `/var/log/journal/${machine-id}` to pod's
`/var/log/journal/{machine-id}` when the pod is started.
If that symlink exists when doing GC, remove it.
If systemd on the host is configured to use `/run/log/journal/`, we
don't care about that because it will be deleted on a reboot.
Fixes #2281

stage1/gc: remove journal link

---

stage1/init/common/pod.go
tests/rkt_mount_test.go

This follows-up #2290 with issues raised on a review.

stage1: follow-up to the symlink mount issue

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/methods.go
Godeps/_workspace/src/github.com/coreos/go-systemd/util/util.go

Godeps: bump go-systemd to v5

---

tools/depsgen/gocmd.go

The way depsgen works is that it recursively gets all the dependencies
of a given module (say, github.com/coreos/rkt/rkt), filters the
dependencies to eliminate packages outside the repository (basically
packages from Go standard library), and then gets the files of all
those filtered deps and the module. Filtering was done by simply
checking if an import path of a dependency had a specific prefix,
namely a name of the repository (in our case the repo name is
github.com/coreos/rkt). This worked fine until we stopped rewriting
our imports. It is because rewritten imports always had the prefix we
wanted (github.com/coreos/rkt/Godeps/_workspace/etc/etc) and now they
do not. In effect, we were getting the files of all the dependencies
that are a part of the repository (like …

build: Fix dependency generation for go binaries

---

tests/rkt_api_service_test.go

Follow up to https://github.com/coreos/rkt/pull/2331
-----
/cc @yifan-gu @iaguis

api_service: fix typos

---

Godeps/Godeps.json

godeps: update goaci to v0.1.0

---

rkt/pubkey/pubkey.go

Just assume that DefaultTransport _is_ an *http.Transport behind the
RoundTripper interface. If this is not true in future, we can adapt.
cc @jonboulle

pubkey: simplify the code

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/cni/pkg/invoke/delegate.go
Godeps/_workspace/src/github.com/appc/cni/pkg/invoke/exec.go
Godeps/_workspace/src/github.com/appc/cni/pkg/invoke/find.go
Godeps/_workspace/src/github.com/appc/cni/pkg/ip/ipmasq.go
Godeps/_workspace/src/github.com/appc/cni/pkg/ipam/ipam.go
Godeps/_workspace/src/github.com/appc/cni/pkg/ns/ns.go
Godeps/_workspace/src/github.com/appc/cni/pkg/types/args.go
Godeps/_workspace/src/github.com/appc/cni/pkg/utils/utils.go
Godeps/_workspace/src/github.com/appc/cni/plugins/ipam/host-local/allocator.go
Godeps/_workspace/src/github.com/appc/cni/plugins/ipam/host-local/config.go
Godeps/_workspace/src/github.com/appc/cni/plugins/ipam/host-local/main.go
Godeps/_workspace/src/github.com/appc/cni/plugins/main/bridge/bridge.go
Godeps/_workspace/src/github.com/appc/cni/plugins/main/ptp/ptp.go
Godeps/_workspace/src/github.com/appc/cni/plugins/meta/flannel/flannel.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/internal/backend/repository/repository.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/internal/backend/repository/repository2.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/internal/util/util.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/version.go
networking/kvm.go

Godeps: bump docker2aci to v0.9.3 and cni to v0.2.0-rc0

---

CHANGELOG.md
Documentation/getting-started-ubuntu.md
Documentation/running-fly-stage1.md
Documentation/running-lkvm-stage1.md
Documentation/subcommands/prepare.md
Documentation/subcommands/version.md
Documentation/trying-out-rkt.md
ROADMAP.md
configure.ac
scripts/acbuild-rkt-builder.sh
scripts/build-rir.sh
tests/empty-image/manifest
tests/image/manifest
tests/rkt_exec_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go

release v1.3.0

---

tests/rkt_list_test.go

Also fix the error messages
Fix https://github.com/coreos/rkt/issues/2220
-----
/cc @krnowak

tests: TestRktListCreatedStarted: fix timing issue

---

tests/rkt_volume_test.go

I tried to reproduce the issue mentioned in:
https://github.com/coreos/rkt/pull/2290#issuecomment-206003364
However, the tests pass fine for me. Nevertheless, this test is worth
adding.
-----
TestDockerVolumeSemantics was added in https://github.com/coreos/rkt/pull/2315
/cc @iaguis @sjpotter

tests: TestDockerVolumeSemantics: more tests with symlinks

---

networking/kvm.go

With @mstachowski help - this PR provides resolution to bug reported in #2023 
We are still working on our testsuite (this work should turn into mergable PR due this or next week), which also covers this area.

kvm: Fix macvtap naming issue. Closes #2023

---

stage1/common/run.go
stage1/init/init.go
stage1_fly/run/main.go
tests/stub-stage1/run/main.go

kvm: fix pid vs ppid usage

---

Documentation/subcommands/run.md

found while wandering through the docs

documentation: remove superfluous dash

---

stage1/init/common/pod.go

By default kvm flavor has got enabled every capability inside pod.
This is normal systemd behavior, when its running as a init process
inside VM. Coreos pod is started by systemd-nspawn, which apply some
initial capabilities by default.
This patch add support for restricted set of capabilities inside rkt-kvm
pod

kvm: Add support for capabilities limitation

---

rkt/rkt.go

If dataDir or some of its parents are symlinks all seems to work correctly
except the gc.
That's because stage0.MountGC determines which mountpoints should be
unmounted filtering the mountpoints returned from /proc/self/mountinfo
with the dataDir value. These mountpoints are the real path so, if the
dataDir or its parents are symlinks, no mountpoint will match.
This patch evaluates the dataDir real path.
If some functional tests are needed I'm not sure under what file under `./tests/` I should put them.

rkt: calculate real dataDir path

---

tests/rkt_socket_proxyd_test.go

skip TestSocketProxyd when systemd-socket-proxyd is not installed

---

tests/rkt_run_user_group_test.go

tests/TestAppUserGroup: cleanup ctx after each test

---

rkt/image/resumablesession.go

We shouldn't pass the "Authorization" header if the redirect goes to a
different host, it can leak sensitive information to unexpected third
parties.
This fixes an issue where rkt gets redirected to Amazon S3 when
downloading an ACI from quay and S3 returns a 400 (Bad Request) with
this error message:
"Only one auth mechanism allowed; only the X-Amz-Algorithm query
parameter, Signature query string parameter or the Authorization header
should be specified"
The problem happens because we're sending "Authorization" and the URL on
the redirect already includes a "Signature" query string parameter.
Fixes #2266

rkt/image: strip "Authorization" on redirects to a different host

---

tests/build-and-run-tests.sh

Creates a function to find the lowest common ancestor between two commits.
Fixes #2423

Find LCA to detect commit differences

---

.github/ISSUE_TEMPLATE.md
CONTRIBUTING.md
Documentation/devel/release.md
scripts/changelog.sh

This specifies the process after pull request submission and also the content of pull requests (title and description) as well as new issues.
Also this introduces a small helper script to generate changelog entries.

Extend contributing guidelines regarding pull requests and issues.

---

Documentation/running-lkvm-stage1.md
configure.ac

The kvm flavor was initially introduced in rkt v0.8.0.
-----
@jellonek PTAL

kvm: not experimental anymore

---

Documentation/subcommands/gc.md
Documentation/using-rkt-with-systemd.md
tests/rkt_api_service_test.go
tests/rkt_gc_test.go

Fix https://github.com/coreos/rkt/issues/2425
Fix https://github.com/coreos/rkt/issues/2420
Fix https://github.com/coreos/rkt/pull/2400#discussion_r59181630
cc @alban @iaguis  @jonboulle

*.*: Updated docs/tests for 'rkt gc --mark-only'

---

stage1/init/init.go

We're using it in stage1 so we need to copy it from the host in the host
flaver.

stage1/init: copy systemd-sysusers on flavor host

---

stage1/init/init.go

Improves documentation and fixes a typo

Improve stage1/init documentation

---

tests/rkt_net_test.go

Checks the discarded error value.
Related to #2390

Check the returned err value

---

CHANGELOG.md
Documentation/getting-started-ubuntu.md
Documentation/running-fly-stage1.md
Documentation/running-lkvm-stage1.md
Documentation/subcommands/prepare.md
Documentation/subcommands/version.md
Documentation/trying-out-rkt.md
ROADMAP.md
configure.ac
scripts/acbuild-rkt-builder.sh
scripts/build-rir.sh
tests/empty-image/manifest
tests/image/manifest
tests/rkt_exec_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go

release v1.5.0

---

stage1/init/common/pod.go

stage1/init: remove redundant slice

---

stage1/init/common/mount.go
stage1/init/common/pod.go
stage1/init/kvm.go
tests/rkt_volume_test.go

Closes #2534
Closes #2547 
Reverts #2535

kvm: fix docker volume semantics

---

pkg/fileutil/fileutil_test.go

Adds tests for fileutil.IsExecutable function.
Fixes #2509

Test fileutil.IsExecutable utility function

---

CHANGELOG.md
Documentation/getting-started-ubuntu.md
Documentation/running-fly-stage1.md
Documentation/running-lkvm-stage1.md
Documentation/subcommands/prepare.md
Documentation/subcommands/version.md
Documentation/trying-out-rkt.md
configure.ac
scripts/acbuild-rkt-builder.sh
scripts/build-rir.sh
tests/empty-image/manifest
tests/image/manifest
tests/rkt_exec_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go

release v1.5.1

---

Documentation/distributions.md

Documentation: update Arch Linux documentation

---

Documentation/subcommands/run.md

A example was missing how to run multiple apps in one pod
Fixes #2583 
@jonboulle Please take a look. I hope you thought about something like that.

docs: Add example to run multiple apps in one pod

---

tests/rkt-monitor/main.go
tests/tests.mk

Enables code simplification checks of gofmt.
Related to #2462
cc @jonboulle @s-urbaniak

Invoke gofmt with simplify-code flag

---

Documentation/distributions.md

Adds instructions for installing rkt on NixOS.
Related to #2202

docs: add instructions for nixos

---

rkt/api_service.go
tests/rkt_api_service_test.go
tests/rkt_tests.go

Fix #2502 
cc @euank @alban @iaguis @jonboulle

api: Return the pods even when we failed to get every information of it.

---

rkt/rkt.go

Refactors the if-else chains for readability
Fixes #2421

Simplify if-else chains and spacing

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/cni/plugins/main/bridge/bridge.go
Godeps/_workspace/src/github.com/appc/cni/plugins/main/ptp/ptp.go

godeps: update cni to v0.2.3

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/spec/ace/image_manifest_main.json.in
Godeps/_workspace/src/github.com/appc/spec/ace/image_manifest_sidekick.json.in
Godeps/_workspace/src/github.com/appc/spec/schema/pod.go
Godeps/_workspace/src/github.com/appc/spec/schema/version.go

Note: #2611 is missing the version 0.8.1

godep: update appc/spec to v0.8.1

---

networking/kvm.go

kvm: fix flannel network info

---

CONTRIBUTING.md
tests/README.md

I think some links were outdated in the docs. I hope you agree these changes, otherwise i would be happy to add changes after a review.
@jonboulle can you please take a look? Thanks a lot!

docs: improve CONTRIBUTING and test docs

---

stage1/init/common/pod.go

There's a race[1][1] on systemd that causes the systemd unit name not
getting written to the journal for short-lived non-root services.
To provide a way to identify an app within a pod in the logs, we set
`SyslogIdentifierp` to the app name as a workaround.
This causes processes forked by the app and pre/post start hooks to be
identified as the app, but it was already happening before we removed
appexec[2][2] with the binary exec'd by the app instead of the app name.
In theory we could remove that and we'll get the binary name of each
process executed in the pod as the syslog identifier, but then this
workaround would not *work*.
Setting the app name as the identifier is already an improvement over
the previous situation.
[1]: https://github.com/systemd/systemd/issues/2913
[2]: …

stage1/init: work around cgroup/SCM_CREDENTIALS race

---

networking/kvm.go

This is minor issue but could be irritating.

kvm: fix logging network plugin type

---

.travis.yml

Validate commit messages for PRs
Fixes #2412

*: validate git commit messages

---

.travis.yml

cc @jonboulle @iaguis @alban  
For reference see:

git-validation: disable until the bugs are fixed

---

dist/init/systemd/tmpfiles.d/rkt.conf

dist: fix "other" permissions so rkt list can work without root/rkt-admin

---

tests/rkt_api_service_test.go
tests/rkt_auth_test.go
tests/rkt_config_test.go
tests/rkt_tests.go
tests/testutils/ctx.go

tests/config: implement functional tests

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/appc/docker2aci/lib/internal/backend/repository/repository2.go
Godeps/_workspace/src/github.com/appc/docker2aci/lib/version.go
Godeps/_workspace/src/github.com/coreos/pkg/progressutil/iocopy.go
Godeps/_workspace/src/github.com/coreos/pkg/progressutil/progressbar.go

Fixes https://github.com/coreos/rkt/issues/2716

Godeps: update appc/docker2aci (0.11.1) and coreos/pkg (v2)

---

MAINTAINERS

Vito is not currently actively working on the project so remove him for
now. He'll be gladly welcomed back as a maintainer at any time if he
wishes to resume involvement.

MAINTAINERS: remove @vcaputo for now

---

rkt/api_service.go
tests/rkt_api_service_test.go

This changes the api_service to only fill in partial information from the image manifest if it was actually retrieved. Prior to this change, a panic was possible (see #2738).
I verified that if I revert the fix commit, the functional test I edited does fail.
Fixes #2738
cc @yifan-gu

api: fix service panic on incomplete pods

---

networking/kvm.go

Connected with https://github.com/containernetworking/cni/pull/149
Fixes #1765 in kvm flavor macvlan support.

kvm: add proxy arp support to macvtap

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/coreos/go-systemd/dbus/methods.go
Godeps/_workspace/src/github.com/coreos/go-systemd/sdjournal/journal.go
Godeps/_workspace/src/github.com/coreos/go-systemd/sdjournal/read.go

Fixes a panic on the api-service when calling GetLogs().

Godeps: bump go-systemd

---

stage1/init/init.go

Prepare rkt for systemd-v230 in stage1.
rkt was previously only writing /etc/machine-id in the stage1 rootfs if
systemd was running on the host. However, new versions of systemd always
require /etc/machine-id, see:
https://github.com/systemd/systemd/commit/e01ff70a77e781734e1e73a2238af2e9bf7967a8
This patch will be in systemd-v230.
This is currently not a problem because stage1 does not use systemd-v230
(and systemd-v230 is not released yet), but we want rkt to be ready.
Fixes https://github.com/coreos/rkt/issues/2416

stage1: always write /etc/machine-id

---

Documentation/devel/release.md

This commit updates the release guide with detailed steps for
signing tags and release artifacts in a consistent way.
Fixes #2734

docs: update release guide with signing details

---

Documentation/subcommands/cat-manifest.md
Documentation/subcommands/image.md
rkt/cat_manifest.go
rkt/config.go
rkt/image_cat_manifest.go
tests/rkt_cat_manifest_test.go
tests/rkt_config_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_tests.go

Also change some docs accordingly

CLI: default to pretty printing for all json

---

Documentation/devel/quickstart-dev.md

My write up about first steps in preparing development environment
Hey!
We talked about additional document in #2587
This is my proposal.

Docs: New file in documentation - instruction for new developers in rkt

---

rkt/api_service.go
tests/rkt_api_service_test.go
tests/rkt_tests.go

If we return before we're registered with machined, we could return a
wrong cgroup because the pod is not yet moved to its final cgroup.
Wait until we're registered with machined for 500ms before returning
pod's information.
Fixes #2778

api_service: wait until a pod regs with machined

---

store/store.go

This PR is just to investigate #2287

store: print more information on rm as non-root

---

Documentation/running-fly-stage1.md

docs: fix list formatting

---

README.md

https://jenkins-rkt-public.prod.coreos.systems/
This still need improving, but the basics are here.
Fixes #847

docs: add Jenkins CI Badge

---

Documentation/distributions.md

Closes #1308 
Signed-off-by: Thomas Hipp <thipp@suse.de>

Documentation: add openSUSE to distributions

---

Documentation/app-environment.md

docs: fix broken link to DNS document

---

.travis.yml
rkt/rkt.mk
tests/build-and-run-tests.sh

dist: fix manpage/bash-completion generation

---

glide.lock
glide.yaml
rkt/image/namefetcher.go
rkt/pubkey/pubkey.go
stage0/run.go
stage1/aci/aci-manifest.in
vendor/github.com/appc/spec/ace/image_manifest_main.json.in
vendor/github.com/appc/spec/ace/image_manifest_sidekick.json.in
vendor/github.com/appc/spec/actool/discover.go
vendor/github.com/appc/spec/actool/manifest.go
vendor/github.com/appc/spec/discovery/discovery.go
vendor/github.com/appc/spec/discovery/http.go
vendor/github.com/appc/spec/schema/types/app.go
vendor/github.com/appc/spec/schema/types/isolator.go
vendor/github.com/appc/spec/schema/types/isolator_linux_specific.go
vendor/github.com/appc/spec/schema/types/isolator_resources.go
vendor/github.com/appc/spec/schema/version.go

This `appc/spec` update introduces seccomp isolators and stricter
isolators validation.

vendor: update appc/spec to 0.8.5

---

CONTRIBUTING.md

contributing: describe PRs consisting of multiple commits

---

networking/kvm.go
networking/networking.go
tests/rkt_net_kvm_test.go
tests/rkt_net_nspawn_test.go
tests/rkt_net_test.go
tests/rkt_socket_proxyd_test.go
tests/testutils/iputils.go

networking/kvm: add flannel default gateway parsing

---

CHANGELOG.md
Documentation/running-fly-stage1.md
Documentation/running-lkvm-stage1.md
Documentation/subcommands/prepare.md
Documentation/subcommands/version.md
Documentation/trying-out-rkt.md
configure.ac
rkt/run.go
scripts/acbuild-rkt-builder.sh
scripts/build-rir.sh
scripts/install-rkt.sh
stage1/enterexec/enterexec.c
tests/empty-image/manifest
tests/env_file_test.conf
tests/image/manifest
tests/rkt_exec_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go

v1.10.1 bug fix release

---

stage1/gc/gc.go

It's not a good idea to clean up our own cgroup, it will lead to
errors.
If we're doing this it means we're running in the same unit file as the
rkt pod. We don't have to do anything, systemd will do the cleanup for
us.
Fixes https://github.com/coreos/rkt/issues/2894

stage1/gc: skip cleaning our own cgroup

---

stage1/enterexec/enterexec.mk

Added entry to ASSCB_EXTRA_HEADERS for a better changes tracking.
Related to https://github.com/coreos/rkt/pull/2872

stage1/enterexec: Add entry to ASSCB_EXTRA_HEADERS

---

tests/rkt_volume_test.go

functional tests: add some more volume/mount tests

---

rkt/api_service.go
rkt/api_service_test.go

Fixes #2794. This allows rkt to run as a systemd socket-based unit.
When this looks good, I'll include the recommended unit files in #2272.

rkt/api: add --socket option to run as a systemd.socket(5) service

---

rkt/rkt.mk
scripts/genproto.sh

protobuf: fix protoc-gen-go build with vendoring

---

CHANGELOG.md
Documentation/running-fly-stage1.md
Documentation/running-lkvm-stage1.md
Documentation/subcommands/prepare.md
Documentation/subcommands/version.md
Documentation/trying-out-rkt.md
ROADMAP.md
configure.ac
scripts/bump-release
scripts/install-rkt.sh
tests/empty-image/manifest
tests/image/manifest
tests/rkt_exec_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go

release v1.11.0

---

Documentation/capabilities-guide.md

This commit introduces a new section in the capabilities guide,
showing how to override capabilities (both on-the-fly at runtime
and by patching images).

docs: document capabilities overriding

---

glide.lock
glide.yaml
vendor/github.com/coreos/go-systemd/sdjournal/journal.go
vendor/github.com/coreos/go-systemd/sdjournal/read.go

This fixes a buggy corner-case in journal seeking (implicit seek to head).
Closes #2776

glide: update go-systemd to v11

---

scripts/bump-release
tests/rkt-monitor/build-stresser.sh

The line parsing the actual version of rkt, so if the version will be change then this line give us right number of it. Before this rkt has in files encrypted line with version number.

rkt-monitor additional fix 

---

store/imagestore/store.go
tests/rkt_non_root_test.go

This makes sense when we think of the cas as a cache. Users in the rkt
group should be able to manage images.
cc @sgotti 
Fixes #2477

store: allow users in the rkt group to delete images

---

Documentation/capabilities-guide.md

docs: clarify run-time override semantics of capabilities

---

makelib/build_go_bin.mk

Tell go to be verbose when we want it to be verbose, which is when we
pass V=3 to make.

build: Quiet down go builds

---

README.md

Now that test pass on the periodic master build, let's use that for the
Jenkins badge.

README: fix Jenkins badge

---

pkg/label/label.go
pkg/label/label_selinux.go
pkg/label/label_selinux_test.go
rkt/run.go

Fixes https://github.com/coreos/rkt/issues/3043

pkg/label: supply mcsdir as function argument to InitLabels()

---

dist/init/systemd/rkt-api.service

dist: remove quotes from rkt-api.service ExecStart

---

Documentation/proposals/app-level-api.md

Bunch o' changes collected over a read through. Various formatting
tweaks/consistency fixes. Some minor re-ordering in an attempt to
enhance reading flow. Purged small parts that didn't make sense to me
or that already seemed to be captured elsewhere.
@tmrts would appreciate if you could review and ensure this still captures all of your intentions, I don't _think_ I've changed anything substantive but I might be missing something..

docs: update app-level API proposal

---

rkt/pubkey/pubkey.go

Currently public keys are being loaded using the http#DefaultClient. While
this specifies some timeouts, it does not specify a total client
timeout.
This can cause rkt to hang forever when reading from a faulty remote
server.
Also, currently the http#DefaultClient struct is being shallow-copied to
optionally set the InsecureSkipVerify flag. This causes `go vet` to
complain starting from Go 1.7 because this copies the the internal mutex
lock value.
This fixes both of the above by using a custom http client
configuration, and setting a client timeout.
See
https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/#clienttimeouts
Supersedes #3062

rkt/pubkey: use custom http client including timeout

---

Documentation/devel/architecture.md

docs: minor typo

---

Documentation/devel/stage1-implementors-guide.md

Docs: fix broken hyperlink

---

rkt/pods.go

Fixes #3109 
See the comment there for more details about this

rkt: Avoid possible panic

---

rkt/run.go
tests/env_file_test.conf

Meant to address https://github.com/coreos/rkt/issues/3116
rel: Feature addition: https://github.com/coreos/rkt/pull/2816, regression introduction: https://github.com/coreos/rkt/pull/2901

rkt/run: Allow --set-env-file files with comments

---

glide.lock
glide.yaml
vendor/github.com/coreos/go-systemd/activation/listeners.go
vendor/github.com/coreos/go-systemd/dbus/methods.go
vendor/github.com/coreos/go-systemd/dbus/properties.go
vendor/github.com/coreos/go-systemd/sdjournal/functions.go
vendor/github.com/coreos/go-systemd/sdjournal/journal.go
vendor/github.com/coreos/go-systemd/util/util.go
vendor/github.com/coreos/go-systemd/util/util_cgo.go
vendor/github.com/coreos/go-systemd/util/util_stub.go

This go-systemd update fixes several memory leaks and races in journal
module.

vendor: update go-systemd to v12

---

Documentation/using-rkt-with-systemd.md

Documentation: document required journal compression

---

Documentation/commands.md

Documentation changes to cover some logging caveats.
Closes #2640
Closes #2417

Documentation: description of known logging issues

---

Documentation/packaging.md
common/group.go

Documentation/packaging: document rkt-admin group

---

configure.ac

powerpc was added to spec in https://github.com/appc/spec/pull/639.

build: Add powerpc to configure

---

CHANGELOG.md
Documentation/running-fly-stage1.md
Documentation/running-lkvm-stage1.md
Documentation/subcommands/prepare.md
Documentation/subcommands/version.md
Documentation/trying-out-rkt.md
ROADMAP.md
configure.ac
scripts/install-rkt.sh
tests/empty-image/manifest
tests/image/manifest
tests/rkt-monitor/build-stresser.sh
tests/rkt_exec_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go

Closes https://github.com/coreos/rkt/issues/3140

Release v1.14.0

---

lib/app.go
lib/doc.go
pkg/pod/doc.go
pkg/pod/pods.go
pkg/pod/pods_test.go
pkg/pod/uuid.go
rkt/api_service.go
rkt/api_service_sdjournal.go
rkt/app.go
rkt/app_list.go
rkt/app_status.go
rkt/cat_manifest.go
rkt/enter.go
rkt/export.go
rkt/gc.go
rkt/help.go
rkt/image_gc.go
rkt/image_list.go
rkt/list.go
rkt/prepare.go
rkt/rm.go
rkt/run.go
rkt/run_prepared.go
rkt/status.go
rkt/stop.go
tests/rkt_api_service_test.go

Supersedes #3160, #3149, #3162

Add 'rkt app list/status', 'lib', and 'pkg' package

---

Documentation/using-rkt-with-kubernetes.md

Fix small typo in docs - as well as an extra space.

docs: fix small typo

---

stage1/init/init.go

Fixes https://github.com/coreos/rkt/issues/3215.

stage1/host: fix systemd-nspawn args ordering

---

networking/kvm.go
networking/podenv.go
pkg/user/resolver.go
rkt/api_service.go
rkt/rkt_test.go
stage0/run.go
tests/rkt_run_pod_manifest_test.go
tests/rkt_run_user_group_test.go

Correct typos listed by the tool misspell.
As seen on https://goreportcard.com/report/github.com/coreos/rkt#misspell

rkt: Correct typos listed by the tool misspell

---

rkt/status.go

This removes the unnecessary errors when a 'rkt status' happens right
after 'rkt app podsandbox'.
cc @lucab @s-urbaniak @iaguis

CRI: Wait at most 1 second for the pid file to exist.

---

Documentation/subcommands/prepare.md
rkt/prepare.go
rkt/run.go
stage0/run.go

This is in preparation to https://github.com/coreos/rkt/pull/3205
/cc @yifan-gu @s-urbaniak @krnowak

rkt: refactor app-level flags handling

---

glide.lock
glide.yaml
tests/rkt_volume_mount_test.go
tests/rkt_volume_test.go
vendor/github.com/appc/spec/schema/pod.go
vendor/github.com/appc/spec/schema/types/app.go
vendor/github.com/appc/spec/schema/types/cri_annotations.go
vendor/github.com/appc/spec/schema/types/cri_labels.go
vendor/github.com/appc/spec/schema/types/mountpoint.go
vendor/github.com/appc/spec/schema/types/port.go

 Temporarily depend on the CRI branch of appc

---

lib/app.go
lib/pod.go
lib/types.go
rkt/list.go
rkt/status.go

Also add annotations, startedAt in the json definition of the pod.
cc @lucab @s-urbaniak

rkt status: Add '--format=json' flag to print json format for pods.

---

stage1/app-start/app-start.go

#3207 added new cgroup bind mounts without checking for cgroup2. Meanwhile #3032 added support for cgroup2.
This patch skips the new cgroup bind mounts if we are using cgroup2.
Thanks @s-urbaniak for finding out.

cri: don't remount cgroup knobs RW with cgroup2

---

lib/pod.go
lib/types.go
rkt/app_sandbox.go
rkt/run.go
stage0/run.go

This enables injecting user-defined pod level labels and annotations.

CRI: Add '--annotation' and '--label' flag for 'rkt app sandbox'.

---

common/apps/apps.go
lib/app.go
lib/types.go
rkt/app_add.go
rkt/app_status.go
rkt/cli_apps.go
rkt/run.go
stage0/app.go

Add ability to patch the app during `rkt app add`.
Ref https://github.com/coreos/rkt/issues/3136 
https://github.com/coreos/rkt/issues/3010

CRI: Add '--name', '--annotation', '--label', '--environment' for 'rkt app add'.

---

common/apps/apps.go
rkt/cli_apps.go
rkt/run.go
stage0/app.go
stage0/run.go

Add these flags for 'rkt app add', 'rkt run', 'rkt prepare'.

CRI: Add '--working-dir', '--supplementary-gids', '--readonly-rootfs' flags

---

common/apps/apps.go
glide.lock
rkt/cli_apps.go
rkt/run.go
stage0/run.go
stage1/init/common/units.go
tests/rkt_oom_score_adj_test.go
vendor/github.com/appc/spec/actool/manifest.go
vendor/github.com/appc/spec/schema/types/isolator_linux_specific.go

Needed for #3203.
Depends on appc/spec#658 - will rebase with upstream changes when those are approved.
@lucab please review?

CRI: add oom_score_adj isolator

---

CONTRIBUTING.md

You can't follow the (docs) style guide if you don't know it exists!

Docs: Mention style guide in CONTRIBUTING.md

---

Documentation/devel/pod-lifecycle.md
common/common.go
rkt/app_rm.go
stage0/app.go
stage0/run.go

cri: synchronize app add/rm operations

---

dist/init/systemd/rkt-api-tcp.socket
dist/init/systemd/rkt-api.service

dist/: Add systemd rkt-api service and socket

---

scripts/pkg/build-pkgs.sh

Adds the rkt-api unit files to the packages.

dist: package rkt-api unit files

---

Documentation/using-rkt-with-systemd.md

Documentation: configure resource restrictions for systemd

---

Documentation/distributions.md
scripts/pkg/build-pkgs.sh

Documentation / pkg: update per-distro instructions, add iptables dependency

---

glide.lock
lib/app.go
lib/pod.go
rkt/app_sandbox.go
stage0/app.go
stage0/run.go
vendor/github.com/appc/spec/discovery/http.go
vendor/github.com/appc/spec/schema/pod.go
vendor/github.com/appc/spec/schema/types/app.go
vendor/github.com/appc/spec/schema/types/user_annotations.go
vendor/github.com/appc/spec/schema/types/user_labels.go

CRI: rename CRIAnnotations to UserAnnotations

---

common/apps/apps.go
rkt/cli_apps.go
rkt/run.go
stage0/run.go
stage1/init/common/units.go
tests/inspect/inspect.go
tests/rkt_app_isolator_test.go

CRI: add cpu-shares isolator

---

scripts/install-rkt.sh

scripts/install-rkt: add iptables dependency

---

pkg/tar/tar.go
pkg/tar/tar_test.go

Currently the xattr field is ignored, when untarring files. This fixes
it.
Fixes #3179

stage0/cas: apply xattr attributes

---

stage1/init/kvm.go
tests/rkt_volume_mount_fly_test.go
tests/rkt_volume_mount_generic_test.go
tests/rkt_volume_mount_test.go

stage1/kvm: correctly bind-mount read-only volumes

---

glide.lock
glide.yaml
vendor/github.com/appc/docker2aci/lib/common/common.go
vendor/github.com/appc/docker2aci/lib/internal/backend/file/file.go
vendor/github.com/appc/docker2aci/lib/internal/backend/repository/repository.go
vendor/github.com/appc/docker2aci/lib/internal/backend/repository/repository1.go
vendor/github.com/appc/docker2aci/lib/internal/backend/repository/repository2.go
vendor/github.com/appc/docker2aci/lib/internal/docker/docker_functions.go
vendor/github.com/appc/docker2aci/lib/internal/internal.go
vendor/github.com/appc/docker2aci/lib/internal/typesV2/docker_types.go
vendor/github.com/appc/docker2aci/lib/internal/util/util.go
vendor/github.com/opencontainers/image-spec/LICENSE
vendor/github.com/opencontainers/image-spec/specs-go/descriptor.go
vendor/github.com/opencontainers/image-spec/specs-go/version.go
vendor/github.com/opencontainers/image-spec/specs-go/versioned.go

This fixes multiple fetching and conversion bug, including two security issues.
Reference https://github.com/appc/docker2aci/releases/tag/v0.13.0
Fixes partially https://github.com/coreos/rkt/issues/2313#issuecomment-245453639

vendor: update docker2aci to 0.13.0

---

Documentation/rkt-build-rkt.md

Documentation: remove rkt-builder instructions.

---

glide.lock
glide.yaml
vendor/github.com/coreos/go-systemd/daemon/sdnotify.go
vendor/github.com/coreos/go-systemd/dbus/properties.go
vendor/github.com/coreos/go-systemd/sdjournal/journal.go
vendor/github.com/coreos/go-systemd/sdjournal/read.go
vendor/github.com/kr/pretty/License
vendor/github.com/kr/pretty/diff.go
vendor/github.com/kr/pretty/formatter.go
vendor/github.com/kr/pretty/pretty.go
vendor/github.com/kr/pretty/zero.go

This is a cumulative vendor bump which:
* introduces kr/pretty
* bumps go-systemd
* introduces the daemon package from go-systemd
/cc @s-urbaniak @squeed as the kr/pretty commit is taken from https://github.com/coreos/rkt/pull/3318 to speed up merging.

vendor: introduce kr/pretty and bump go-systemd

---

Documentation/hacking.md

It took me a while to figure out how to build rkt without manually installing a bunch of dependencies. I think these are the right directions?

docs: explain how to use rkt-builder to build rkt

---

stage1/usr_from_kvm/qemu.mk

Update of QEMU to latest stable version. I didn't saw any regressions in my tests.

kvm: update QEMU version to 2.7.0

---

rkt/image_list.go

@lucab PTAL
List images in the json format:
```
ubuntu@ubuntu-xenial:/rkt/build-rir$ sudo target/bin/rkt image list --format=json
[{"id":"sha512-bd4c342830c8","name":"coreos.com/rkt/stage1-coreos:1.17.0","import_time":"2 days ago","last_used":"2 days ago","size":"179MiB"},{"id":"sha512-7b1e1a77f0b6","name":"coreos.com/rkt/builder:1.1.0","import_time":"2 days ago","last_used":"2 days ago","size":"1.6GiB"}]
```
And json-pretty:
```
ubuntu@ubuntu-xenial:/rkt/build-rir$ sudo target/bin/rkt image list --format=json-pretty
[
{
"id": "sha512-bd4c342830c8",
"name": "coreos.com/rkt/stage1-coreos:1.17.0",
"import_time": "2 days ago",
"last_used": "2 days ago",
"size": "179MiB"
},
{
"id": "sha512-7b1e1a77f0b6",
"name": "coreos.com/rkt/builder:1.1.0",
"import_time": "2 days ago",
"last_used": "2 days …
```

stage0/image: list images output in JSON format

---

rkt/image/namefetcher.go

Makes fetchVerifiedURL() in namefetcher ETag aware to prevent needlessly
re-fetching images.
Fixes #3355

namefetcher: Use ETag in fetchVerifiedURL()

---

stage1_fly/enter/main.go

Adds a working `rkt enter` implementation for the fly stage1.  It just
chroots into the pod's rootfs and execs its arguments.
Fixes #2957

stage1/fly: Add a working enter implementation

---

common/environment.go
pkg/log/log.go
stage0/app.go
stage0/common.go
stage1/aci/aci-install.mk
stage1/app-add/app-add.go
stage1/app-rm/app-rm.go
stage1/app-start/app-start.go
stage1/app-stop/app-stop.go

This is a cumulative PR containing multiple fixes for `rkt app` that surfaced while writing tests at https://github.com/coreos/rkt/pull/3371. Tests are not yet green, but these fixes should be ready to get in.

rkt/app: multiple bugfixes

---

README.md

Addresses #2158#issuecomment-261922975

README: fix regarding overlay-over-overlay for newer kernels

---

Documentation/devel/architecture.md
Documentation/devel/pod-lifecycle.md

Chasing #3406, and, wreaking, havoc, with, commas.

docs: minor grammar/formatting cleanup

---

rkt/app_sandbox.go

rkt: remove empty TODO

---

common/cgroup/v1/cgroup.go
pkg/fs/mount.go
pkg/fs/mount_linux.go
stage1/init/common/dns_config.go
stage1/init/common/mount.go
stage1/init/init.go
tests/rkt_fetch_test.go
tests/rkt_tests.go

This adds r/w support for /proc/sys, and /sys
Fixes #3245

R/W support for /proc/sys, and /sys

---

tests/rkt_net_test.go

tests: clean up TestNetDefaultRestrictedConnectivity

---

rkt/app_sandbox.go

These were missing.
Fixes #3428

sandbox add missing flagDNSDomain and flagHostsEntries parameters

---

stage1/init/common/mount.go

os.Exit results in no defers running which meant garbage was left
behind in the form of tempdirs and potentially mounts.
This will merge conflict with #3451, I'll be happy to rebase after that merges, and feel free to push the rebase to it yourself if you'd like.
cc @squeed

stage1: properly run defer'd umounts in app add

---

tests/rkt_app_sandbox_test.go
tests/rkt_tests.go

This is currently used only by `TestAppSandboxSmoke` but it will be later needed for attach tests (and possibly more).

tests: add a waitPodReady helper

---

vendor/github.com/shirou/gopsutil/cpu/cpu_fallback.go
vendor/github.com/shirou/gopsutil/host/host_fallback.go
vendor/github.com/shirou/gopsutil/load/load_fallback.go
vendor/github.com/shirou/gopsutil/mem/mem_fallback.go
vendor/github.com/shirou/gopsutil/net/net_fallback.go
vendor/github.com/shirou/gopsutil/process/process_fallback.go

Some files were missing from a bad update.

vendor: add missing files from a bad glide update

---

glide.lock
glide.yaml
tests/rkt_caps_test.go
vendor/github.com/syndtr/gocapability/capability/capability.go
vendor/github.com/syndtr/gocapability/capability/capability_linux.go
vendor/github.com/syndtr/gocapability/capability/enum.go
vendor/github.com/syndtr/gocapability/capability/enum_gen.go
vendor/github.com/syndtr/gocapability/capability/syscall_linux.go

This change renames "sys_psacct" to "sys_pacct", so update rkt_caps_test
accordingly.

vendor: bump gocapability

---

.gitignore
tests/aws.sh
tests/cloudinit/debian-testing.cloudinit
tests/cloudinit/fedora-22.cloudinit
tests/cloudinit/fedora-23.cloudinit
tests/cloudinit/fedora-24.cloudinit
tests/cloudinit/fedora-25.cloudinit

Update to reflect current testing setup.

tests: update AWS CI setup

---

scripts/build-rir.sh

This updates the building script to rkt-builder 1.2.0.

scripts: update rkt-builder version

---

Documentation/running-kvm-stage1.md

Ideally I could have just linked to this instead of writing my comment
on HN here: https://news.ycombinator.com/item?id=13864159
- Use docker images
- Include debug to assist user
- Move build instructions to the bottom

Documentation: cleanup stage1 stuff

---

Documentation/app-container.md

this is mostly just an excuse to test semaphore again

docs: add appc deprecation note

---

store/treestore/tree.go

(the couple of changes to non-exported varialbes/functions were because
they were not found to be used anywhere.)
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

treestore: changes for golint

---

CHANGELOG.md
Documentation/distributions.md
Documentation/proposals/oci.md
Documentation/running-fly-stage1.md
Documentation/running-kvm-stage1.md
Documentation/subcommands/prepare.md
Documentation/subcommands/version.md
Documentation/trying-out-rkt.md
configure.ac
scripts/install-rkt.sh
tests/empty-image/manifest
tests/image/manifest
tests/rkt-monitor/build-stresser.sh
tests/rkt_exec_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go

Here is my PR for the 1.26.0 release. I hope my summary of the changes since the last release is good.
Closes https://github.com/rkt/rkt/issues/3676

Release 1.26.0

---

lib/app.go

When it is nil, the Volume info at the Pod level (with the same name)
should be used. Without this patch `rkt list --format=json` panics on a
nil pointer when Apps reference Volumes from the Pod level.
Signed-off-by: Fabio Kung <fabio.kung@gmail.com>

stage0: list|status --format=json panics: RuntimeApp.Mounts.AppVolume is optional

---

stage1/common/types/pod.go
stage1/init/common/app.go
stage1/init/common/pod.go
stage1_fly/enter/main.go
stage1_fly/process-credentials.go
stage1_fly/run/main.go

Refactored common functionality out of run.
Fixes #3392, fixes #3716.

stage1/fly: make run/enter honour uid/gid/suppGids

---

Documentation/devel/architecture.md

This was discussed on:
https://github.com/rkt/rkt/pull/3645#issuecomment-296865635
/cc @lucab @euank @sstabellini @n0rad @iaguis @schu
-----
Not sure it is the correct place to list the stage1s. Should it be a new file on the same model as https://github.com/rkt/rkt/blob/master/Documentation/production-users.md?

doc: mention external stage1s

---

stage1/usr_from_coreos/manifest-arm64-usr.d/systemd.manifest

Fixes issue https://github.com/rkt/rkt/issues/3714 (rkt run --user fails on arm64).

Fix --user --group on arm64

---

common/environment.go
common/environment_test.go
stage0/app_add.go
stage1/init/common/units.go
stage1_fly/enter/main.go
stage1_fly/run/main.go
tests/rkt_env_test.go

Fly run now writes the app env file, and fly enter reads it.
Fixes #3393.

stage1/fly: preserve environment between run and enter

---

CHANGELOG.md
Documentation/distributions.md
Documentation/proposals/oci.md
Documentation/running-fly-stage1.md
Documentation/running-kvm-stage1.md
Documentation/subcommands/prepare.md
Documentation/subcommands/version.md
Documentation/trying-out-rkt.md
configure.ac
scripts/install-rkt.sh
tests/empty-image/manifest
tests/image/manifest
tests/rkt-monitor/build-stresser.sh
tests/rkt_exec_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go

@lucab PTAL. Let me know how you want to coordinate signing and publishing the release. I can take care of posting release notes to the mailing list(s) if you want.
Cheers!
Closes #3721 
~~(I'm having some trouble running `build-rir.sh`, but it seems to be something on my local dev env. I will keep looking, but let me know if you have similar issues)~~ -> #3683

1.28.0 release

---

scripts/build-rir.sh

Builder script update to use latest rkt-builder.
Related to https://github.com/rkt/rkt/issues/3738

scripts: update rkt-builder version to 1.3.0

---

glide.lock
glide.yaml
vendor/github.com/coreos/go-systemd/sdjournal/journal.go
vendor/github.com/coreos/go-systemd/sdjournal/read.go
vendor/github.com/coreos/go-systemd/util/util_cgo.go
vendor/golang.org/x/text/gen.go
vendor/golang.org/x/text/transform/transform.go
vendor/golang.org/x/text/unicode/norm/forminfo.go
vendor/golang.org/x/text/unicode/norm/normalize.go
vendor/golang.org/x/text/unicode/norm/readwriter.go
vendor/golang.org/x/text/width/transform.go
vendor/golang.org/x/text/width/width.go

rkt stopped working when running in a service with systemd v234. This
bump includes a fix.

glide: bump go-systemd to v15

---

scripts/pkg/build-pkgs.sh

Fixes #3762.
Tested resulting RPM on CentOS 7, all is fine.  (Unable to test deb.)

RPM/deb package can upgrade even if running pods.

---

lib/app.go

This can happen if the pod dies but we don't have time to register
the app exit code.
Let's be more flexible here and continue even then.

lib: don't error out if we can't get the app exit code

---

tests/rkt_seccomp_test.go

The -stat-file option of rkt's inspect program uses the standard go
os.Stat() routine, which uses the syscall.Stat() routine for its
operation.  For amd64 syscall.Stat() uses the SYS_STAT system call,
and so setting actool's --seccomp-set option to 'stat' works with
inspect's -stat-file option.
The arm64 linux kernel does not implement a SYS_STAT syscall, so for
arm64 syscall.Stat() is implemented as a wrapper around the
syscall.Fstatat() routine.  Because of this actool's --seccomp-set
option needs to be set to 'newfstatat' for the '-stat-file' option
to work correctly on arm64 machines.
I put a small program that tests for valid seccomp syscall names here:
https://gist.github.com/glevand/4625adcef2c5d25c457eb308f76e5148 (seccomp-name-test.c)
See: …

rkt_seccomp_test: Fix arm64 stat tests

---

CHANGELOG.md
Documentation/distributions.md
Documentation/proposals/oci.md
Documentation/running-fly-stage1.md
Documentation/running-kvm-stage1.md
Documentation/subcommands/prepare.md
Documentation/subcommands/version.md
Documentation/trying-out-rkt.md
configure.ac
scripts/install-rkt.sh
tests/empty-image/manifest
tests/image/manifest
tests/rkt-monitor/build-stresser.sh
tests/rkt_exec_test.go
tests/rkt_image_cat_manifest_test.go
tests/rkt_image_export_test.go
tests/rkt_image_render_test.go
tests/rkt_os_arch_test.go

release 1.29.0

---

glide.lock
glide.yaml
vendor/github.com/appc/docker2aci/lib/common/common.go
vendor/github.com/appc/docker2aci/lib/version.go

It fixes an image pulling bug for some images in GCR.

vendor: bump docker2aci to v0.17.1

---

MAINTAINERS

Fixes #3836 
---
I have no more time to maintain rkt for the time being.
Thanks for having had me!

MAINTAINERS: remove Stefan Junker

---

Documentation/security.md

Documentation: first stab at security best practices

---

Documentation/dependencies.md

Fixes https://github.com/rkt/rkt/issues/2155

Documentation: link to configure flags doc for TPM dep

---

Documentation/subcommands/image.md

Documentation: document the size shown in image list

---

Documentation/capabilities-guide.md

Reorder capabilities docs to focus on how to configure them at runtime.
Fixes #3289

Documentation: capabilities: focus on runtime configuration

---

Documentation/subcommands/run.md

 Documentation: run: document recursive option for volumes 

---

Documentation/upgrading.md

Documentation: add upgrading doc

---

Documentation/build-container-examples/README.md
Documentation/build-container-examples/play-example/build-play-example.sh
Documentation/build-container-examples/play-example/custom.sql
Documentation/build-container-examples/play-example/wait-for-postgres.sh
Documentation/build-container-examples/postgres/build-postgres.sh
Documentation/build-container-examples/postgres/postgres-prestart.sh
Documentation/getting-started-guide.md

Fixes #2781
Fixes #906
~~Depends on #3844~~

examples: add complex ACI image building examples

---

pkg/distribution/docker.go
pkg/pod/wait.go
rkt/prepare.go
rkt/run.go
stage1/init/common/app.go
stage1/init/common/seccomp.go
stage1/init/common/units.go
tests/rkt_tests.go

This PR fixes all the misspell in this repo, which results in improving the go report card result. Also it helps to improve the code readability.

Fixes all the misspell.

---

Documentation/networking/examples-bridge.md
Documentation/networking/overriding-defaults.md
Documentation/networking/overview.md
README.md

This PR provides changed urls after s/appc/containernetworking/
and after extracting plugins into separate project.

Small update in docs

---

Documentation/networking/overview.md

Fixes https://github.com/rkt/rkt/issues/1522

Documentation: custom CNI plugin example

---

README.md

Added go report card badge

---

Documentation/hacking.md

Documentation: point to how to run tests in hacking doc

---

Documentation/getting-started-guide.md

Documentation: document Go version and gccgo in getting started

---

Documentation/aci-hosting.md

Fixes https://github.com/rkt/rkt/issues/3866

Documentation: add ACI hosting doc

---

Documentation/security.md

We cover file descriptor passing and runtime mount injection.
Fixes #2644

Documentation: security: unexpected host-pod communication channels

---

scripts/install-deps-debian-sid.sh

scripts: adding missing dependecies to debian dependency installer

---

Documentation/devel/debugging.md
Documentation/hacking.md

It includes explanations of how to debug images and rkt's stage1.
Loosely based on the presentation "Debugging in a Containerized
World"[[1]]
[1]: https://docs.google.com/presentation/d/1jUxja67wDgbGdc1kur11viLP5QXreyOnBu0inpoFfqs/edit#slide=id.gaf2bae832_0_28uu
Fixes #988

Documentation: add debugging guide

---

Documentation/capabilities-guide.md

Fixes https://github.com/rkt/rkt/issues/3672.

Documentation: explain non-root capabilities

---

api/v1alpha/README.md
api/v1alpha/docs/docs.md
api/v1alpha/docs/index.html
scripts/genproto.sh

It's generated in `scripts/genproto.sh` using pseudomuto/protoc-gen-doc.
Fixes #2434

api: add HTML and Markdown documentation

---

Documentation/selinux.md

Give an example on constraints you can apply to a context and link to
documentation.
Fixes #2606

Documentation: improve selinux docs

---

Documentation/subcommands/run.md

updated '--dns' option related to issue #3901

Documentation : Update run.md

---

Documentation/devel/distribution-point.md

fix documentation typo

---

MAINTAINERS

maintainers: update euank email

---

MAINTAINERS

This updates the maintainers list to current reality.

maintainers: update

---

Documentation/running-fly-stage1.md
Documentation/running-kvm-stage1.md
Documentation/troubleshooting.md

Although it is spelling mistakes, it might make an affects while reading.
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>

docs: fix some typos

---

stage0/app_start.go
stage1/init/common/path.go
store/imagestore/migrate_test.go

Although it is spelling mistakes, it might make an affects while reading.
Co-Authored-By: Nguyen Phuong An <AnNP@vn.fujitsu.com>
Signed-off-by: Kim Bao Long <longkb@vn.fujitsu.com>

Remove the duplicated words in code comments

---

CONTRIBUTING.md

Although it is spelling mistakes, it might make an affects while reading.
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>

Trivial fix typo

---

CONTRIBUTING.md

Correct hyperlink in documentation in order to visit link
properly.
Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>

Update deprecated link
